### ISSUE TITLE
报Invalid config keys错误

### ISSUE THREAD

**Issue by wenzhizhong** [umijs/umi#10027]
## What happens?
 yarn  start  ( or npm start) 报config keys 无效

## How To Reproduce

```
root@qing-PC:/data# yarn start 
yarn run v1.22.15
$ cross-env ANALYZE=1 umi build
fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: antd, dva, locale, dynamicImport
    at Function.validateConfig (/data/node_modules/_@umijs_core@4.0.36@@umijs/core/dist/config/config.js:182:31)
    at Config.getConfig (/data/node_modules/_@umijs_core@4.0.36@@umijs/core/dist/config/config.js:60:12)
    at Service.resolveConfig (/data/node_modules/_@umijs_core@4.0.36@@umijs/core/dist/service/service.js:286:97)
    at Service.run (/data/node_modules/_@umijs_core@4.0.36@@umijs/core/dist/service/service.js:235:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Service.run2 (/data/node_modules/_umi@4.0.36@umi/dist/service/service.js:58:12)
    at async Object.run (/data/node_modules/_umi@4.0.36@umi/dist/cli/cli.js:55:7) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
fatal - A complete log of this run can be found in:
fatal - /data/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Context
    "umi": "^4.0.36"
    "nodejs":"v10.21.0"
   "Platform":"Linux"

**Comment by fz6m** [comment]
`antd`, `dva`, `locale` 在 max 项目里自带了，如果用 umi ，需要单独装：

```bash
  pnpm add -D @umijs/plugins
```

```ts
export default {
  plugins: ['@umijs/plugins/dist/antd'],
  antd: {}
}
```

`dynamicImport` 在 umi4 没了，umi4 默认按页拆包（等同于 `dynamicImport`），详见：https://umijs.org/docs/introduce/faq#%E6%B2%A1%E6%9C%89-dynamicimport-%E6%80%8E%E4%B9%88%E9%85%8D%E7%BD%AE%E5%AE%83%E7%9A%84-loading-
