### ISSUE TITLE
[Bug] TypeError: Cannot destructure property 'winPath' of 'import_umi.utils' as it is undefined

### ISSUE THREAD

**Issue by theDoinb** [umijs/umi#10087]
## What happens?

从v3升级到v4报错，但我在升级文档好像没看到相关的内容？

## Mini Showcase Repository(REQUIRED)

 [https://umijs.org/docs/api/config#cssloader](https://umijs.org/docs/api/config#cssloader)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
v3升级v4

**Expected behavior** 1. 2.
升级成功

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
搜一下 winPath ，从 import {utils:{winPath}} from 'umi' 改成 
import { winPath } from '@umijs/utils'
或者
import { winPath } from 'umi/plugin-utils'

**Comment by theDoinb** [comment]
@xiaohuoni 
还有个，dva的hmr是不在v4中了吗？
withPath改了引入，现在又抛了dva的错误
所有用到connect的地方都抛错了

```
[ERROR] Unexpected "@"
@connect(() => ({}))
```

**Comment by theDoinb** [comment]
```
warn  - transpile code with esbuild got  123 errors, 0 warnings
fatal - Error: ENOENT: no such file or directory, open 'F:\wingo\wingo-nms-web\node_modules\.cache\mfsu\mfsu_v4\defaultSettings.js'
    at Object.openSync (fs.js:476:3)
    at readFileSync (fs.js:377:35)
    at LazySourceCodeCache.filesLoader (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\libs\folderCache\LazySourceCodeCache.js:147:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async LazySourceCodeCache.loadFiles (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\libs\folderCache\LazySourceCodeCache.js:63:20)
    at async LazySourceCodeCache.init (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\libs\folderCache\LazySourceCodeCache.js:60:5)
    at async Command.fn (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\commands\dev\dev.js:227:9)
    at async Service.run (F:\wingo\wingo-nms-web\node_modules\@umijs\core\dist\service\service.js:269:15)
    at async Service.run2 (F:\wingo\wingo-nms-web\node_modules\umi\dist\service\service.js:58:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'F:\\wingo\\wingo-nms-web\\node_modules\\.cache\\mfsu\\mfsu_v4\\defaultSettings.js'
}
fatal - A complete log of this run can be found in:
fatal - F:\wingo\wingo-nms-web\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
```

**Comment by fz6m** [comment]
看一下你的 `defaultSettings.js` 文件是不是有语法错误，给一个最小复现看看。

**Comment by theDoinb** [comment]
@f2elab 我把mfsu关闭就能启动了，我在该.cache路径下找不到mfsu目录，所以尝试了关闭mfsu

**Comment by theDoinb** [comment]
config把locale关了又不报了..

**Comment by fz6m** [comment]
你的 Umi 依赖版本是？

是否在 `app.ts` 里使用了 `defineApp` ？

**Comment by theDoinb** [comment]
@f2elab 
"@umijs/max": "^4.0.0"

我这个是从antd pro v2升上来的，没有app.ts
config/config.js 里面是 defineConfig
还有就是
```
  targets: {
    chrome: 58,
    firefox: 45,
    ie: 13,
    safari: 10,
    edge: 13,
    ios: 10
  },
```
targets 设置成这样打包不了，我又频掉了，就能正常打包
现在把 路由v6的调整了，已经跑起来了

**Comment by theDoinb** [comment]
尝试打开了 mfsu，
那个报 '@'，我把 export default 放到后边就好了，
然后持续的修复了一些代码，
然后报没有puppeteer，又装了个，
然后又报错...
```
error - Can not resolve dependence : 'F:/wingo/wingo-nms-web/node_modules/react/jsx-dev-runtime', please install it
error - [MFSU][eager] build failed AssertionError [ERR_ASSERTION]: dependence not found: F:/wingo/wingo-nms-web/node_modules/react/jsx-dev-runtime
    at Dep.buildExposeContent (F:\wingo\wingo-nms-web\node_modules\@umijs\mfsu\dist\dep\dep.js:63:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DepBuilderInWorker.writeMFFiles (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\commands\dev\depBuildWorker\depBuilder.js:135:23)
    at async DepBuilderInWorker.build (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\commands\dev\depBuildWorker\depBuilder.js:106:7)
error - AssertionError [ERR_ASSERTION]: dependence not found: F:/wingo/wingo-nms-web/node_modules/react/jsx-dev-runtime
    at Dep.buildExposeContent (F:\wingo\wingo-nms-web\node_modules\@umijs\mfsu\dist\dep\dep.js:63:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DepBuilderInWorker.writeMFFiles (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\commands\dev\depBuildWorker\depBuilder.js:135:23)
    at async DepBuilderInWorker.build (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\commands\dev\depBuildWorker\depBuilder.js:106:7)
error - [MFSU][eager] build worker failed AssertionError [ERR_ASSERTION]: dependence not found: F:/wingo/wingo-nms-web/node_modules/react/jsx-dev-runtime
    at Dep.buildExposeContent (F:\wingo\wingo-nms-web\node_modules\@umijs\mfsu\dist\dep\dep.js:63:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DepBuilderInWorker.writeMFFiles (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\commands\dev\depBuildWorker\depBuilder.js:135:23)
    at async DepBuilderInWorker.build (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\commands\dev\depBuildWorker\depBuilder.js:106:7) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
```
只要关闭mfusu就没问题.......

**Comment by theDoinb** [comment]
还有就是开启 vite 会报错
```
fatal - Error: Parse error @:11:9
    at parse (F:\wingo\wingo-nms-web\node_modules\@umijs\bundler-utils\compiled\es-module-lexer\index.js:1:511)
    at scanContent (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\libs\scan.js:41:54)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async scan (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\libs\scan.js:93:22)
    at async Hook.fn (F:\wingo\wingo-nms-web\node_modules\@umijs\preset-umi\dist\features\appData\appData.js:123:26)
    at async F:\wingo\wingo-nms-web\node_modules\umi\node_modules\@umijs\core\dist\service\service.js:152:13 {
  idx: 460
}
fatal - A complete log of this run can be found in:
fatal - F:\wingo\wingo-nms-web\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
```

**Comment by theDoinb** [comment]
还有就是404页面，./src/pages/404.js 确认有该文件，
但是当访问的路由地址不存在时，会进入空白页，控制台倒是没什么抛错....

**Comment by fz6m** [comment]
> 那个报 '@'，我把 export default 放到后边就好了，

这个是啥问题，能辛苦提供下更多的上下文信息帮助定位问题吗？谢谢

> targets 设置成这样打包不了，我又频掉了，就能正常打包

目前 targets 只支持 chrome 、safari 、firefox 、edge 这四个 key 设定版本

> 还有就是开启 vite 会报错

已知问题，见 #9869

> 还有就是404页面，./src/pages/404.js 确认有该文件，

是否使用了配置式路由 `routes` ？如果是约定式路由，应该不会有问题的，如果有问题，可以提供更多信息和最小复现帮助排查问题。

> Can not resolve dependence : 'F:/wingo/wingo-nms-web/node_modules/react/jsx-dev-runtime', please install it

确认一下你项目的 react 版本是？

**Comment by theDoinb** [comment]
@f2elab 
'@'之个，我之前是这样写的：
```
export default
@connect(() => ({}))
class credentialModal extends React.Component{}
```
现在我放到下边去了
```
@connect(() => ({}))
class credentialModal extends React.Component{}
export default credentialModal ;
```
404那个是使用了配置式路由 `routes`，之前v3匹配不到，`routers` 如果下边有配置 404的话，匹配不到是会返回的404页面的，
现在情况是，匹配不到他没进 `path: '/'`，没进 `BasicLayout.js`，看了眼 `root` 节点下是空的

React版本：`16.11.0`

**Comment by fz6m** [comment]
1. 你 at 错人了。。。

2. 现在不支持 @ + export default 连用了，改成下面的写法是正确的。

3. 配置式路由需要自己在最后写一个通配路由兜底 404 页面，只有约定式路由才会自动 404 ，你得自己配一下。

**Comment by theDoinb** [comment]
还真@错人了 - -，

404这个，我有在 `routers` 最后和 path: '/' 的 `routes` 最后都尝试加入
```
{
    path: '/',
    component: '404',
},
{
    component: '404',
}
```
但不知道为什么，似乎无效，难道不是这样配 ?....

还有上面 msfu 这个 `jsx-dev-runtime`，大概知道什么问题吗？

**Comment by fz6m** [comment]
umi 4 内置的是 react 18 ，使用 react 16 需要明确在 `package.json` 声明安装：

```ts
// package.json

 "dependencies": {
    "react": "^16.14.0",
    "react-dom": "^16.14.0"
  },
  "devDependencies": {
    "@types/react": "^16.14.34",
    "@types/react-dom": "^16.9.17",
  }
```

**Comment by theDoinb** [comment]
升级版本后，开启 `msfu` 能跑起来了

`404` 这个我参考ant pro v5配置，path加上 `*`

```
{
    path: '*',
    layout: false,
    component: './404',
}
```
现在可以了，感谢
