### ISSUE TITLE
Module not found: Error: Can't resolve 'worker_threads' in '\node_modules\thread-stream'

### ISSUE THREAD

**Issue by beeant0512** [umijs/umi#10275]
Uncaught TypeError: The "original" argument must be of type Function
    at promisify (umi.js:132878:11)
    at ./node_modules/readdirp/index.js (umi.js:123563:17)
    at options.factory (umi.js:140329:31)
    at __webpack_require__ (umi.js:139698:33)
    at fn (umi.js:139986:21)
    at ./node_modules/chokidar/index.js (umi.js:37445:18)
    at options.factory (umi.js:140329:31)
    at __webpack_require__ (umi.js:139698:33)
    at fn (umi.js:139986:21)
    at ./node_modules/@umijs/utils/dist/index.js (umi.js:16116:24)
    at options.factory (umi.js:140329:31)
    at __webpack_require__ (umi.js:139698:33)
    at fn (umi.js:139986:21)
    at ./src/utils/utils.tsx (umi.js:11278:70)
    at options.factory (umi.js:140329:31)
    at __webpack_require__ (umi.js:139698:33)
    at fn (umi.js:139986:21)
    at ./src/requestConfig.ts (umi.js:10931:70)
    at options.factory (umi.js:140329:31)
    at __webpack_require__ (umi.js:139698:33)
    at fn (umi.js:139986:21)
    at ./src/app.tsx (umi.js:9393:72)
    at options.factory (umi.js:140329:31)
    at __webpack_require__ (umi.js:139698:33)
    at fn (umi.js:139986:21)
    at ./src/.umi/core/plugin.ts (umi.js:5249:95)
    at options.factory (umi.js:140329:31)
    at __webpack_require__ (umi.js:139698:33)
    at fn (umi.js:139986:21)
    at ./src/.umi/testBrowser.tsx (umi.js:8965:70)
    at options.factory (umi.js:140329:31)
    at __webpack_require__ (umi.js:139698:33)
    at fn (umi.js:139986:21)
    at ./src/.umi/exports.ts (umi.js:6258:71)
    at options.factory (umi.js:140329:31)
    at __webpack_require__ (umi.js:139698:33)
    at fn (umi.js:139986:21)
    at ./src/global.tsx (umi.js:10077:68)
    at options.factory (umi.js:140329:31)
    at __webpack_require__ (umi.js:139698:33)
    at fn (umi.js:139986:21)
    at ./src/.umi/umi.ts (umi.js:9170:98)
    at options.factory (umi.js:140329:31)
    at __webpack_require__ (umi.js:139698:33)
    at umi.js:141074:37
    at umi.js:141076:12

**Comment by xiaohuoni** [comment]
注意看浏览器控制台上的报错。可能与 worker_threads 无关
![image](https://github.com/umijs/umi/assets/11746742/0fd4e76b-c029-4c87-8442-56c328523897)
