### ISSUE TITLE
运行@example/mpa报错

### ISSUE THREAD

**Issue by bingq6** [umijs/umi#10381]
> pnpm --filter @example/mpa run start
@example/mpa@ start E:\gitwork\umi\examples\mpa
> npm run dev

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> dev
> umi dev

info  - @local
X [ERROR] Syntax error "m"

    entry:E:\gitwork\umi\examples\mpa\pages\bar\index.tsx:2:32:
      2 │ import * as x from "E:\gitwork\umi\examples\mpa\pages\bar\index.tsx";
        ╵                                 ^

fatal - Error: Build failed with 1 error:
entry:E:\gitwork\umi\examples\mpa\pages\bar\index.tsx:2:32: ERROR: Syntax error "m"
    at failureErrorWithLog (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1604:15)
    at E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1056:28
    at runOnEndCallbacks (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1476:61)
    at buildResponseToResult (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1054:7)
    at E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1166:14
    at responseCallbacks.<computed> (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:701:9)
    at handleIncomingPacket (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:756:9)
    at Socket.readFromStdout (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:677:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Syntax error "m"'
    }
  ],
  warnings: []
}
fatal - A complete log of this run can be found in:
fatal - E:\gitwork\umi\examples\mpa\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

**Comment by fz6m** [comment]
是最新版本的 umi master 分支代码吗，我记得在 #10364 修复了这个问题。

**Comment by bingq6** [comment]
最新版本还是报错
(base) PS E:\gitwork\umi> pnpm --filter @example/mpa start

> @example/mpa@ start E:\gitwork\umi\examples\mpa
> npm run dev

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> dev
> umi dev

info  - @local
X [ERROR] Could not resolve "E:/gitwork/umi/examples/mpa/pages/bar/index.tsx"

    entry:E:\gitwork\umi\examples\mpa\pages\bar\index.tsx:2:19:
      2 │ import * as x from "E:/gitwork/umi/examples/mpa/pages/bar/index.tsx";
        ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The plugin "virtual-entry" didn't set a resolve directory for the file
  "entry:E:\\gitwork\\umi\\examples\\mpa\\pages\\bar\\index.tsx", so esbuild did not search for
  "E:/gitwork/umi/examples/mpa/pages/bar/index.tsx" on the file system.

fatal - Error: Build failed with 1 error:
entry:E:\gitwork\umi\examples\mpa\pages\bar\index.tsx:2:19: ERROR: Could not resolve "E:/gitwork/umi/examples/mpa/pages/bar/index.tsx"
    at failureErrorWithLog (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1604:15)
    at E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1056:28
    at runOnEndCallbacks (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1476:61)
    at buildResponseToResult (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1054:7)
    at E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1166:14
    at responseCallbacks.<computed> (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:701:9)
    at handleIncomingPacket (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:756:9)
    at Socket.readFromStdout (E:\gitwork\umi\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:677:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "E:/gitwork/umi/examples/mpa/pages/bar/index.tsx"'
    }
  ],
  warnings: []
}
fatal - A complete log of this run can be found in:
fatal - E:\gitwork\umi\examples\mpa\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

**Comment by fz6m** [comment]
在这个 pr #10382 合入后修复。

**Comment by bingq6** [comment]
> 在这个 pr #10382 合入后修复。

thanks

**Comment by fz6m** [comment]
通过 #10382 修复，本周四发版后即可更新使用。
