### ISSUE TITLE
[Bug]   Error: https://registry.npmmirror.com/@umijs/utils/-/utils-4.0.49.tgz: Request failed "404 Not Found"

### ISSUE THREAD

**Issue by wanshenghao** [umijs/umi#10404]
无法下载完整资源

环境
node  16.15.0
mac M1 

报错步骤：
执行  yarn create umi 
选择最新版本  4.0.48
直接报错 

下面是日志

Arguments: 
  /usr/local/bin/node /usr/local/bin/yarn

Yarn version: 
  1.22.18

Node version: 
  16.15.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.npmmirror.com/@umijs/utils/-/utils-4.0.49.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:696:66)
      at new ResponseError (/usr/local/lib/node_modules/yarn/lib/cli.js:802:124)
      at Request.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:66208:16)
      at Request.emit (node:events:527:28)
      at Request.module.exports.Request.onRequestResponse (/usr/local/lib/node_modules/yarn/lib/cli.js:141760:10)
      at ClientRequest.emit (node:events:527:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
      at HTTPParser.execute (<anonymous>)
      at TLSSocket.socketOnData (node:_http_client:494:22)

npm manifest: 
  {
    "private": true,
    "scripts": {
      "dev": "max dev",
      "build": "max build",
      "format": "prettier --cache --write .",
      "prepare": "husky install",
      "postinstall": "max setup",
      "setup": "max setup",
      "start": "npm run dev"
    },
    "dependencies": {
      "@ant-design/icons": "^4.7.0",
      "@ant-design/pro-components": "^2.0.1",
      "@umijs/max": "^4.0.49",
      "antd": "^5.0.0"
    },
    "devDependencies": {
      "@types/react": "^18.0.0",
      "@types/react-dom": "^18.0.0",
      "husky": "^8.0.1",
      "lint-staged": "^13.0.3",
      "prettier": "^2.7.1",
      "prettier-plugin-organize-imports": "^2",
      "prettier-plugin-packagejson": "^2",
      "typescript": "^4.1.2"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by fz6m** [comment]
npmmirror 有时候会抽风，从上游同步慢，哪个报错了可以到 npmmirror.com 手动点 sync ，或者 `cnpm sync some-pkg`
