### ISSUE TITLE
[Bug]   Centos 路由路径无法识别 同样的配置 本地环境macOs可以 

### ISSUE THREAD

**Issue by lei14370** [umijs/umi#10432]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.
root@nc-test-six:/root/web-log-collection-front# npm run setup

> setup
> max setup

fatal - Error: Cannot find module './home' from '/root/web-log-collection-front/src/pages'
    at Function.resolveSync [as sync] (/root/web-log-collection-front/node_modules/@umijs/utils/compiled/resolve/index.js:1:12304)
    at Object.onResolveComponent (/root/web-log-collection-front/node_modules/@umijs/preset-umi/dist/features/tmpFiles/routes.js:71:32)
    at transformRoute (/root/web-log-collection-front/node_modules/@umijs/core/dist/route/routesConfig.js:68:44)
    at /root/web-log-collection-front/node_modules/@umijs/core/dist/route/routesConfig.js:44:5
    at Array.forEach (<anonymous>)
    at transformRoutes (/root/web-log-collection-front/node_modules/@umijs/core/dist/route/routesConfig.js:43:15)
    at getConfigRoutes (/root/web-log-collection-front/node_modules/@umijs/core/dist/route/routesConfig.js:34:3)
    at getRoutes (/root/web-log-collection-front/node_modules/@umijs/preset-umi/dist/features/tmpFiles/routes.js:61:46)
    at Hook.fn (/root/web-log-collection-front/node_modules/@umijs/preset-umi/dist/features/appData/appData.js:42:53)
    at /root/web-log-collection-front/node_modules/@umijs/core/dist/service/service.js:129:38 {
  code: 'MODULE_NOT_FOUND'
}
fatal - A complete log of this run can be found in:
fatal - /root/web-log-collection-front/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

## Code
```
export default [
  {
    path: '/',
    redirect: '/home',
  },
  {
    name: '首页',
    path: '/home',
    component: 'home',
  },
  {
    name: '用户管理',
    path: '/user',
    component: 'user',
  },
  {
    name: '用户新增',
    path: '/user/detail',
    component: 'user/detail',
    hideInMenu: true,
  },
  {
    name: '应用管理',
    path: '/application',
    component: 'application',
  },
  {
    name: '应用管理新增',
    path: '/application/detail',
    component: 'application/detail',
    hideInMenu: true,
  },
  {
    name: '监控日志',
    path: '/logs',
    component: 'logs',
  },
  {
    name: '监控日志详情',
    path: '/logs/detail',
    component: 'logs/detail',
    hideInMenu: true,
  },
  {
    name: '登录',
    path: '/login',
    hideInMenu: true,
    layout: false,
    exact: true,
    component: 'login',
  },
];

```
- **Umi Version**:
-  "@umijs/max": "^4.0.47",
- v16.18.0
- **Platform**:
Linux version 3.10.0-1160.42.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Sep 7 14:49:57 UTC 2021

**Comment by fz6m** [comment]
依赖没找到，感觉应该：

1. 文件路径大小写问题，在 macos 和 linux 敏感度不一样。

2. node 包是不是缺了，确定是完整的 v16.18

3. 依赖一致性，依赖安装工具是不是不一样，保持本地和云工具一致，版本一致，比如都是 pnpm `v7.24.2` 

往这几个方向查

**Comment by lei14370** [comment]
文件路径 没得问题  确认了很多次了 
node 包也重新安装过 16.18
 本地 和 服务器都是依赖的 yarn v1.22.19

**Comment by fz6m** [comment]
```bash
fatal - Error: Cannot find module './home' from '/root/web-log-collection-front/src/pages'
```

注意这里，查一下路由配置是不是写了 `./home` ，找不到这个。
