### ISSUE TITLE
Plugin umi-plugin-react:pwa initialize failed

### ISSUE THREAD

**Issue by Superman-wc** [umijs/umi#1062]
启用PWA 失败了
```
Plugin umi-plugin-react:pwa initialize failed, You need to have package.json and the name in it when using pwa.
{ AssertionError [ERR_ASSERTION]: You need to have package.json and the name in it when using pwa.
    at _default (/Users/a/c/b/node_modules/umi-plugin-react/lib/plugins/pwa/index.js:23:23)
    at Service.initPlugin (/Users/a/c/b/node_modules/umi-build-dev/lib/Service.js:122:7)
    at extraPlugins.forEach.plugin (/Users/a/c/b/node_modules/umi-build-dev/lib/Service.js:145:14)
    at Array.forEach (<anonymous>)
    at Service.initPlugins (/Users/a/c/b/node_modules/umi-build-dev/lib/Service.js:144:20)
    at Service.init (/Users/a/c/b/node_modules/umi-build-dev/lib/Service.js:252:10)
    at Service.run (/Users/a/c/b/node_modules/umi-build-dev/lib/Service.js:283:10)
    at Object.<anonymous> (/Users/a/c/b/node_modules/umi/lib/scripts/realDev.js:28:47)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '==' }
```

.umirc.js
```
export default {
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      antd: true,
      dva: true,
      dynamicImport: true,
      title: 'timetabling',
      polyfills: ['ie9'],
      dll: true,
      pwa: true,
      routes: {
        exclude: [],
      },
      hardSource: true,
    }],
  ]
}
```

**Comment by xiaohuoni** [comment]
You need to have package.json and the name in it when using pwa.
在 package.json里面增加name字段就好了。

https://github.com/umijs/create-umi/pull/4
这个bug已修复
