### ISSUE TITLE
[Bug] Umi 4 + @umijs/plugins 手动配置 initialState 时出现 Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by lanvige** [umijs/umi#10839]
## What happens?

在升级 Umi 4 时遇到错误，没有使用 Max，而是直接使用 Umi4 + @umijs/plugins。

### 错误概要：

在生成 `src/.umi` 目录时，经测试，只有 `initialState: {},` 插件会遇到这个错误，其它插件正常。

```
info  - Umi v4.0.63
fatal - Error: ENOENT: no such file or directory, open '/Volumes/Estate/repos/uniscrm/uniscrm-console-web-v3/src/.umi/plugin-initialState/@@initialState.ts'
```

### 环境：

- **Umi Version**: ^4.0.63
- **Node Version**: v18.15.0
- **Platform**: macOS 13

### 版本依赖如下：

``` js
"dependencies": {
    "@umijs/route-utils": "^4.0.1",
    "antd": "^5.3.2",
    "axios": "^1.3.4",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
},
"devDependencies": {
    "@umijs/plugins": "^4.0.63",
    "umi": "^4.0.63"
},
```
  

### 配置 config.ts 加入 plugins

``` ts
/**
* @name 启用插件
* @@doc https://umijs.org/docs/guides/use-plugins
*/
plugins: [
    '@umijs/plugins/dist/locale',
    '@umijs/plugins/dist/antd',
    '@umijs/plugins/dist/layout',
    '@umijs/plugins/dist/model',
    '@umijs/plugins/dist/initial-state',
    '@umijs/plugins/dist/access',
    '@umijs/plugins/dist/request',
],

/**
* @name 数据流插件
* @@doc https://umijs.org/docs/max/data-flow
*/
model: {},

/**
* 一个全局的初始数据流，可以用它在插件之间共享数据
* @description 可以用来存放一些全局的数据，比如用户信息，或者一些全局的状态，全局初始状态在整个 Umi 项目的最开始创建。
* @doc https://umijs.org/docs/max/data-flow#全局初始状态
*/
initialState: {},
```

### 错误详情

```
> cross-env UMI_ENV=dev REACT_APP_ENV=dev MOCK=none umi dev

info  - Umi v4.0.63
fatal - Error: ENOENT: no such file or directory, open '/Volumes/Estate/repos/uniscrm/uniscrm-console-web-v3/src/.umi/plugin-initialState/@@initialState.ts'
    at Object.openSync (node:fs:601:3)
    at readFileSync (node:fs:469:35)
    at Model.findDeps (/Volumes/Estate/repos/uniscrm/uniscrm-console-web-v3/node_modules/.pnpm/@umijs+plugins@4.0.63_n2y4uzsci4s2fnz6gz7cj4pcuu/node_modules/@umijs/plugins/dist/utils/modelUtils.js:77:48)
    at new Model (/Volumes/Estate/repos/uniscrm/uniscrm-console-web-v3/node_modules/.pnpm/@umijs+plugins@4.0.63_n2y4uzsci4s2fnz6gz7cj4pcuu/node_modules/@umijs/plugins/dist/utils/modelUtils.js:74:29)
    at /Volumes/Estate/repos/uniscrm/uniscrm-console-web-v3/node_modules/.pnpm/@umijs+plugins@4.0.63_n2y4uzsci4s2fnz6gz7cj4pcuu/node_modules/@umijs/plugins/dist/utils/modelUtils.js:125:14
    at Array.map (<anonymous>)
    at _ModelUtils.getAllModels (/Volumes/Estate/repos/uniscrm/uniscrm-console-web-v3/node_modules/.pnpm/@umijs+plugins@4.0.63_n2y4uzsci4s2fnz6gz7cj4pcuu/node_modules/@umijs/plugins/dist/utils/modelUtils.js:124:7)
    at getAllModels (/Volumes/Estate/repos/uniscrm/uniscrm-console-web-v3/node_modules/.pnpm/@umijs+plugins@4.0.63_n2y4uzsci4s2fnz6gz7cj4pcuu/node_modules/@umijs/plugins/dist/model.js:106:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Hook.fn (/Volumes/Estate/repos/uniscrm/uniscrm-console-web-v3/node_modules/.pnpm/@umijs+plugins@4.0.63_n2y4uzsci4s2fnz6gz7cj4pcuu/node_modules/@umijs/plugins/dist/model.js:53:20)
    at async /Volumes/Estate/repos/uniscrm/uniscrm-console-web-v3/node_modules/.pnpm/@umijs+core@4.0.63/node_modules/@umijs/core/dist/service/service.js:184:15 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Volumes/Estate/repos/uniscrm/uniscrm-console-web-v3/src/.umi/plugin-initialState/@@initialState.ts'
}
fatal - A complete log of this run can be found in:
fatal - /Volumes/Estate/repos/uniscrm/uniscrm-console-web-v3/node_modules/.cache/logger/umi.log
```

**Comment by fz6m** [comment]
`initial-state` 顺序要在前面，后面插件依赖他。
