### ISSUE TITLE
name too long

### ISSUE THREAD

**Issue by xuguanqun** [umijs/umi#10868]
pnpm start 启动项目时报错

```log
error - Error: ENAMETOOLONG: name too long, open '.../node_modules/.cache/mfsu/mf-va__Users_lostdeer_Documents_xuguanqun_隐力科技_aismile-web-old_aismile-compatible_node_modules_.pnpm_registry.npmmirror.com+umi@4.0.63_@babel+core@7.21.3_@types+react@18.0.30_eslint@8.35.0_postc_c5ojm44bj3muyn6bfgjii3d3vy_node_modules_umi_client_client_plugin.js.js'
    at Object.openSync (node:fs:584:3)
    at writeFileSync (node:fs:2201:35)
    at DepBuilderInWorker.writeMFFiles (.../node_modules/.pnpm/registry.npmmirror.com+@umijs+preset-umi@4.0.63_@types+react@18.0.30_postcss@8.4.21_styled-co_wflebyz5isptna5vytv4hoplee/node_modules/@umijs/preset-umi/dist/commands/dev/depBuildWorker/depBuilder.js:145:35)
    at async DepBuilderInWorker.build (.../node_modules/.pnpm/registry.npmmirror.com+@umijs+preset-umi@4.0.63_@types+react@18.0.30_postcss@8.4.21_styled-co_wflebyz5isptna5vytv4hoplee/node_modules/@umijs/preset-umi/dist/commands/dev/depBuildWorker/depBuilder.js:118:7)
event - [Webpack] Compiled in 30394 ms (1437 modules)
wait  - [Webpack] Compiling...
```

**Comment by fz6m** [comment]
提供一下当前电脑的 node 版本吧，可以试试升级 node 版本看看还有没有这个问题。
