### ISSUE TITLE
[Bug] 在`umi4`实现动态路由后打开使用`@ant-design/charts`库的页面报错

### ISSUE THREAD

**Issue by tangbzai** [umijs/umi#10891]
## What happens?

在`umi4`实现动态路由后打开使用`@ant-design/charts`库的页面报错
报错内容: `Cannot read properties of null (reading 'useRef')`和`The above error occurred in the <ForwardRef> component`

如果将页面配置到`routes.ts`里就不会出现报错，但破坏了动态路由的设计。
## Mini Showcase Repository(REQUIRED)

[最小重现](https://github.com/tangbzai/ant-design-charts-demo)
## How To Reproduce

**Steps to reproduce the behavior:**
1. 安装依赖并运行
```bash
# 安装依赖
yarn
# 带mock数据运行
yarn start
```
2. 运行后打开网站，填写任意账号密码登录进入，点击菜单上的'首页'即可看到报错

**Expected behavior** 
1. 可正常打开页面并展示出图表数据

**错误日志**：
```
TypeError: Cannot read properties of null (reading 'useRef')
    at useRef (react.development.js:1630:1)
    at useInit (useChart.js:28:1)
    at index.js:22:1
    at renderWithHooks (mf-dep____vendor.daf1dd8d.js:290481:18)
    at updateForwardRef (mf-dep____vendor.daf1dd8d.js:293397:20)
    at beginWork (mf-dep____vendor.daf1dd8d.js:295807:16)
    at beginWork$1 (mf-dep____vendor.daf1dd8d.js:301597:14)
    at performUnitOfWork (mf-dep____vendor.daf1dd8d.js:300728:12)
    at workLoopSync (mf-dep____vendor.daf1dd8d.js:300637:5)
    at renderRootSync (mf-dep____vendor.daf1dd8d.js:300605:7)
    at recoverFromConcurrentError (mf-dep____vendor.daf1dd8d.js:300021:20)
    at performConcurrentWorkOnRoot (mf-dep____vendor.daf1dd8d.js:299921:22)
    at workLoop (mf-dep____vendor.daf1dd8d.js:315446:34)
    at flushWork (mf-dep____vendor.daf1dd8d.js:315419:14)
    at MessagePort.performWorkUntilDeadline (mf-dep____vendor.daf1dd8d.js:315713:21) 
```
```
The above error occurred in the <ForwardRef> component:
    at http://192.168.1.35:8001/webTemplates/vendors-node_modules_ant-design_plots_es_components_area_index_js.async.js:36:26
    at div
    at div
    at http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:134037:62
    at Analysis (http://192.168.1.35:8001/webTemplates/src_pages_Dashboard_Analysis_tsx.async.js:34:107)
    at Suspense
    at Outlet (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:305769:26)
    at Exception (http://192.168.1.35:8001/webTemplates/umi__plugin-layout__Layout.async.js:34:12)
    at main
    at http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:141443:25
    at http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:141426:66
    at ErrorBoundary (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:88849:90)
    at WrapContent (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:69594:70)
    at div
    at section
    at http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:141457:63
    at http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:141426:66
    at div
    at BaseProLayout (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:69239:13)
    at ProviderChildren (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:135586:24)
    at LocaleReceiver (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:141954:36)
    at ConfigProvider (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:135689:13)
    at SWRConfig (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:319721:13)
    at ConfigProviderContainer (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:79029:24)
    at FormProvider (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:233538:31)
    at LocaleProvider (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:142043:29)
    at ProviderChildren (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:135586:24)
    at LocaleReceiver (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:141954:36)
    at ConfigProvider (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:135689:13)
    at ProConfigProvider (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:79134:24)
    at ProviderChildren (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:135586:24)
    at LocaleReceiver (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:141954:36)
    at ConfigProvider (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:135689:13)
    at ProLayout (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:69537:28)
    at http://192.168.1.35:8001/webTemplates/umi__plugin-layout__Layout.async.js:208:66
    at Suspense
    at RemoteComponent (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:127584:25)
    at Routes (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:127120:76)
    at Router (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:305792:15)
    at BrowserRoutes (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:127082:23)
    at r (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:304293:7350)
    at Provider (http://192.168.1.35:8001/webTemplates/src_umi_umi_ts.async.js:2262:74)
    at InitialStateProvider (http://192.168.1.35:8001/webTemplates/src_umi_umi_ts.async.js:2603:105)
    at Provider (http://192.168.1.35:8001/webTemplates/src_umi_umi_ts.async.js:2999:34)
    at ProviderWrapper (http://192.168.1.35:8001/webTemplates/src_umi_umi_ts.async.js:3201:102)
    at Browser (http://192.168.1.35:8001/webTemplates/mf-dep____vendor.daf1dd8d.js:127185:68)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```
## Context

- **Umi Version**: 4.0.63
- **Node Version**: 14.18.3
- **Yarn Version**: 1.22.5
- **Platform**: windows

**Comment by fz6m** [comment]
太复杂了，看不明白你要做什么。提供下你需求路由的场景和预期，再看看有什么解决方案。

**Comment by tangbzai** [comment]
> 太复杂了，看不明白你要做什么。提供下你需求路由的场景和预期，再看看有什么解决方案。

**场景：**
主要就是用户登录后根据由后端返回的数据决定前端展示的菜单与生成路由（动态路由部分）。

**说明**
动态路由部分我基本实现了，别的页面也没有问题，但是在实际项目使用的过程中发现只要页面有用到 `@ant-design/charts` 图表库的页面都报错误了。
经过我的排查发现如果 未使用图表库的页面 或 **使用图表库的页面配置在`routes.ts`文件里** 就不会报错。

**预期**
希望使用了图表库的页面可以正常展示出来 并且不破坏 动态路由 的功能（即`React.lazy(() =>import('@/pages/xxx))` 的页面里可以使用图表库）

**Comment by fz6m** [comment]
不是这个组件库的问题，你要维护一个映射，把所有的组件都写明确类型导入进来，然后根据下发的 key 去添加 element， 写 `import('@/pages/')` 不知道要打包什么。

**Comment by tangbzai** [comment]
> 不是这个组件库的问题，你要维护一个映射，把所有的组件都写明确类型导入进来，然后根据下发的 key 去添加 element， 写 import('@/pages/') 不知道要打包什么。

有没有办法可以不用维护一个映射也做到这个效果？（类似约定式路由？）

我在尝试约定式路由时不知道怎么单独把登录页将其排除在ProLayout的全局布局之外。（文档说的是在`routes`里设置`layout=false`但配置了`routes`就不是约定式路由了）

我尝试像umi3的[扩展路由属性](https://v3.umijs.org/zh-CN/docs/convention-routing#%E6%89%A9%E5%B1%95%E8%B7%AF%E7%94%B1%E5%B1%9E%E6%80%A7)一样配置，但貌似umi4不支持

**Comment by fz6m** [comment]
动态路由必须维护所有路由表，否则 webpack 不知道打包哪些内容。

**Comment by tjj727** [comment]
同样碰到类似的问题，开发环境我是取巧解决的，打包后应该是没问题，你可以试一下
![image](https://user-images.githubusercontent.com/129740535/233890900-e926237b-b2bb-4df4-b692-68f7986074d0.png)

**Comment by tangbzai** [comment]
感谢你们的帮助，我目前的解决方案是改为约定式路由并编写一个umi 插件实现 “将登录页排除在ProLayout的全局布局之外”的功能。

**具体步骤：**
创建插件文件：`{rootPath}/plugins/noLayoutPath.ts`
![image](https://user-images.githubusercontent.com/47456577/233893361-6dcceb5d-623c-493d-92e2-6cc19e40dcb0.png)
然后在配置文件(`config/config.ts`)里使用该插件
![image](https://user-images.githubusercontent.com/47456577/233893442-c18d5bc2-6465-4f0b-916a-a5bc6b22686a.png)
