### ISSUE TITLE
umi@2.13.17 引入worker-loader@3.0.2 打包提示 ERROR  Failed to compile with 0 errors

### ISSUE THREAD

**Issue by DearGaz** [umijs/umi#10900]
### Discussed in https://github.com/umijs/umi/discussions/10899

<div type='discussions-op-text'>

<sup>Originally posted by **DearGaz** April  5, 2023</sup>
如题

1. yarn add worker-loader@3.0.2 --dev
2. 配置
...
chainWebpack(config, { webpack }) {
        config.module
            .rule("worker")
            .test(/\\.worker\\.js$/)
            .use("worker-loader")
            .loader("worker-loader");
        console.log(config.toString(), "webpack config");
    },
..

3. 使用
import Worker from "../a/b/link.worker.js";

const worker = new Worker();

移除掉第2步里的配置就正常了，可能是什么原因？没有任何提示，毫无头绪

【ps】worker-loader@3.0.2的peerDependency有Webpack"^4.0.0 || ^5.0.0"，我的项目yarn.lock文件里Webpack是4.41.1，应该是跟Webpack兼容的。。。https://www.npmjs.com/package/worker-loader/v/3.0.2?activeTab=code

求大佬指导</div>

**Comment by DearGaz** [comment]
升级到umi3.0之后，报错:..

...\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:64297
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:64297:11)
    at \node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:67099:7
    at processTicksAndRejections (internal/process/task_queues.js:77:11)



有啥建议 @fz6m

**Comment by fz6m** [comment]
升级到 umi4
