### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by haobarry** [umijs/umi#10943]
## What happens?

umi3 升级到UMI4 处理完插件问题  运行start ，报错 内容如下

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce
```
> ant-design-pro@5.2.0 start
> cross-env UMI_ENV=dev max dev

info  - [你知道吗？] 如果你需要使用 Jest 来测试 Umi 项目, max g jest 就可以一键完成配置，详见 https://umijs.org/生成器
info  - Umi v4.0.64
fatal - TypeError: Cannot read properties of undefined (reading 'includes')
    at D:\CodeProject\qwn-react-typescript\node_modules\@umijs\preset-umi\dist\features\exportStatic\exportStatic.js:49:31
    at Array.forEach (<anonymous>)
    at getExportHtmlData (D:\CodeProject\qwn-react-typescript\node_modules\@umijs\preset-umi\dist\features\exportStatic\exportStatic.js:44:25)
    at Hook.fn (D:\CodeProject\qwn-react-typescript\node_modules\@umijs\preset-umi\dist\features\exportStatic\exportStatic.js:179:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D:\CodeProject\qwn-react-typescript\node_modules\@umijs\core\dist\service\service.js:184:15
```

## Context

- **Umi Version**:4
- **Node Version**:14
- **Platform**:win11

**Comment by fz6m** [comment]
需要给最小复现

**Comment by lynzz** [comment]
现在也遇到这个问题

**Comment by haobarry** [comment]
找到原因了   'exportStatic', 配置要关掉

**Comment by haobarry** [comment]
> > 找到原因了 'exportStatic', 配置要关掉
> > 我需要静态页面，该如何做，这个配置关掉了，就打包就变成按需加载了

早就不用了   你最好是全新使用  不要升级
