### ISSUE TITLE
Umi3.5开启mfsu，然后报错

### ISSUE THREAD

**Issue by tianyazjq** [umijs/umi#10992]
1. umi3.5
2.swiper  8.4.7 "name": "swiper",
  "version": "8.4.7",
  
 umi.js config.js中开启了
 mfsu:{ 
    production:{
      }
 }
 然后报错。具体请看截图
 
![image](https://user-images.githubusercontent.com/5754329/232650727-2e1be249-5c0e-4056-995b-777b884fa010.png)

![image](https://user-images.githubusercontent.com/5754329/232650651-7596d419-ea90-4ee7-a983-4f753534c072.png)

[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
[MFSU] Build virtual application failed since ENOENT: no such file or directory, stat 'D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\swiper\css\scrollbar'.
Error: ENOENT: no such file or directory, stat 'D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\swiper\css\scrollbar'
    at statSync (node:fs:1526:3)
    at getPathWithPkgJSON (D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\getFilePath.js:87:26)
    at getFilePath (D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\getFilePath.js:140:27)
    at D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:104:51
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:64:103)
    at _next (D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:194)
    at D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:364
    at new Promise (<anonymous>)
    at D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:97
    at figureOutExport (D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:115:17)
    at D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:162:201
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:82:103)
    at _next (D:\wwwroot\thinker-cloud\thinkerCloud\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:84:194)
    at runMicrotasks (<anonymous>)
error Command failed with exit code 1.

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
