### ISSUE TITLE
umi2.9版本下，本地服务启动成功，但是浏览器访问时就报错，即使重启多少次都没用，只有在重启电脑后重启服务才不会报错。

### ISSUE THREAD

**Issue by vioi** [umijs/umi#11059]
报错如下:
Uncaught ReferenceError: umi is not defined
    at dll-reference umi (external "umi":1:1)
    at __webpack_require__ (bootstrap:774:1)
    at fn (bootstrap:129:1)
    at ./node_modules/node-libs-browser/node_modules/punycode/punycode.js (punycode.js" from dll-reference umi:1:1)
    at __webpack_require__ (bootstrap:774:1)
    at fn (bootstrap:129:1)
    at ./node_modules/url/url.js (url.js:24:1)
    at __webpack_require__ (bootstrap:774:1)
    at fn (bootstrap:129:1)
    at ./node_modules/af-webpack/lib/webpackHotDevClient.js (webpackHotDevClient.js:19:1)
d

**Comment by fz6m** [comment]
建议升级到 umi 4 ，可以初始化一个 umi 4 项目一点点迁移代码。
