### ISSUE TITLE
[Bug]  umi4 with electron template project cannot run up, get error: Uncaught Exception: Error: Cannot find module 'clear-module'

### ISSUE THREAD

**Issue by liaodalin19903** [umijs/umi#11104]
## What happens?

我参考[官方文档创建 umi4 + electron 项目](https://umijs.org/docs/tutorials/getting-started#从模板创建项目)：
```
# 从 @umijs/electron-template 创建一个 electron 模板
  pnpm create umi --template electron
```

然后在运行的时候报错：
```
npm run start
```
控制台报错：
```
$ npm run start
Debugger attached.

> @umijs/electron-template@1.0.1 start
> npm run dev

Debugger attached.

> @umijs/electron-template@1.0.1 dev
> umi dev

Debugger attached.
Debugger attached.
info  - [你知道吗？] umi g tsconfig 可一键完成项目的 TypeScript 配置。
info  - Umi v4.0.67
info  - Preparing...
info  - MFSU eager strategy enabled
info  - [MFSU][eager] restored cache
event - [MFSU][eager] start build deps
info  - [MFSU] skip buildDeps
        ╔════════════════════════════════════════════════════╗
        ║ App listening at:                                  ║
        ║  >   Local: http://localhost:8001                  ║
ready - ║  > Network: http://30.178.80.50:8001               ║
        ║                                                    ║
        ║ Now you can open browser with the above addresses↑ ║
        ╚════════════════════════════════════════════════════╝
event - [Webpack] Compiled in 895 ms (314 modules)
[dev] src: /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main, output: /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/.electron/dist
wait  - [Webpack] Compiling...
event - [MFSU][eager] start build deps
info  - [MFSU] skip buildDeps
[init] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/index.ts
[init] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/preload.ts
[init] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/tsconfig.json
[ignore] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/tsconfig.json
[init] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/typing.d.ts
[ignore] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/typing.d.ts
info  - [MFSU][eager] worker init, takes 985ms
event - [Webpack] Compiled in 600 ms (314 modules)
[init] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/ipc/platform.ts
Debugger attached.
App threw an error during load
Error: Cannot find module 'clear-module'
Require stack:
- /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/.electron/entry.js
- /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/node_modules/.store/electron@21.4.4/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/.electron/entry.js:5:15)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)

```

Electron 报错：
![image](https://user-images.githubusercontent.com/12727582/236621719-2aa736a3-b29b-4748-863a-ef4b09ea725c.png)

```
Uncaught Exception:
Error: Cannot find module 'clear-module'
Require stack:
- /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/.electron/entry.js
- /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/node_modules/.store/electron@21.4.4/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
at Module._load (node:internal/modules/cjs/loader:785:27)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/.electron/entry.js:5:15)
at Module._compile (node:internal/modules/cjs/loader:1120:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
```

## Mini Showcase Repository(REQUIRED)

示例项目如下：
https://codesandbox.io/s/pc5crz

github repo：
https://github.com/liaodalin19903/umi4-electron-bug

## How To Reproduce

```
npm run start
```

## Context

- **Umi Version**:
```
 "dependencies": {
    "umi": "^4.0.42"
  },
```

- **Node Version**:
v16.18.0

- **Platform**:
macOS Monterey 12.6

**Comment by fz6m** [comment]
来这边反馈一下吧，这个模板属于社区维护的：https://github.com/xiefengnian/umijs-electron-template
