### ISSUE TITLE
[Bug] build err ,can i get any help?

### ISSUE THREAD

**Issue by hhstu** [umijs/umi#11130]
## What happens?
``` sh
Step 1/7 : FROM node:16.15.0 AS builder
 ---> 9d200cd667d5
Step 2/7 : COPY web/package.json .
 ---> Using cache
 ---> 486288fa21f9
Step 3/7 : RUN yarn install
 ---> Using cache
 ---> 38562bd0bd17
Step 4/7 : COPY web .
 ---> fa06ef9c9b63
Step 5/7 : RUN yarn build
 ---> Running in 97e191f76a22
yarn run v1.22.18
$ max build
info  - [你知道吗？] 全局样式、全局脚本写在哪里？创建 src/global.(ts|css) 轻松解决，详见 https://umijs.org/docs/guides/directory-structure#globaljtsx
info  - Umi v4.0.67
info  - Preparing...
RangeError: Maximum call stack size exceeded
fatal - Error: Compiling RuleSet failed: Evaluation of condition function threw error (at ruleSet[1].rules[2].include[0][0]: (path) => {
        try {
          if (path.includes("client/client/client"))
            return true;
          return (0, import_depMatch.isMatch)({ path, pkgs: depPkgs });
        } catch (e) {
          console.error(import_utils.chalk.red(e));
          throw e;
        }
      })
    at RuleSetCompiler.error (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143878:10)
    at RuleSetCompiler.compileCondition (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143743:16)
    at /node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143758:10
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileCondition (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143757:28)
    at /node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143758:10
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileCondition (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143757:28)
    at /node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143424:40
    at Hook.eval [as call] (eval at create (/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7460), <anonymous>:15:1)
    at RuleSetCompiler.compileRule (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143682:19)
    at /node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143659:9
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143658:16)
    at RuleSetCompiler.compileRule (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143689:30)
    at /node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143659:9
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143658:16)
    at RuleSetCompiler.compile (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:143573:22)
    at new NormalModuleFactory (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:84276:34)
    at Compiler.createNormalModuleFactory (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62624:31)
    at Compiler.newCompilationParams (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62645:30)
    at Compiler.compile (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62656:23)
    at /node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62020:12
    at Compiler.readRecords (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62482:5)
    at /node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62017:11
    at Hook.eval [as callAsync] (eval at create (/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4851)
    at /node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62014:20
    at Hook.eval [as callAsync] (eval at create (/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:23:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4851)
    at run (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62011:25)
    at Compiler.run (/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62034:4)
    at /node_modules/@umijs/bundler-webpack/dist/build.js:108:16
    at new Promise (<anonymous>)
    at Proxy.build (/node_modules/@umijs/bundler-webpack/dist/build.js:73:10)
    at async Command.fn (/node_modules/@umijs/preset-umi/dist/commands/build.js:139:17)
    at async Service.run (/node_modules/@umijs/core/dist/service/service.js:328:15)
    at async Service.run2 (/node_modules/umi/dist/service/service.js:65:12)
    at async run (/node_modules/umi/dist/cli/cli.js:57:7)
fatal - A complete log of this run can be found in:
fatal - /node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
error Command failed with exit code 1.

```

## Context

- **Umi Version**:
@umijs/max": "^4.0.49
- **Node Version**:
   16.15.0
- **Platform**:

**Comment by fz6m** [comment]
需要给一个会报错的最小复现。

可以本地构建看下有啥报错，如果本地不报错，排查下云构建的环境问题。

**Comment by hhstu** [comment]
> 需要给一个会报错的最小复现。
> 
> 
> 
> 可以本地构建看下有啥报错，如果本地不报错，排查下云构建的环境问题。

谢谢，已经解决了，dockerfile写的有问题

**Comment by aak1247** [comment]
@hhstu 方便问下是啥问题吗

**Comment by hhstu** [comment]
@aak1247 看看 dockerfile 和日志
