### ISSUE TITLE
umi dev 运行报错。 Error: Cannot find module 'is-glob'

### ISSUE THREAD

**Issue by xgj1988** [umijs/umi#1116]
module.js:549
    throw err;
    ^

Error: Cannot find module 'is-glob'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\gitlab\manager-xyzy-antd\node_modules\_glob-parent@3.1.0@glob-parent\index.js:4:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xyzy@2.0.0 start: `cross-env PORT=7070 APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xyzy@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-09-21T16_38_18_299Z-debug.log

**Comment by xgj1988** [comment]
我运行 npm install --save is-glob 之后，然后又报错glob没有。。安装glob之后又报错body-parser没有。安装body-parser 之后又报address 没有。但是我在公司的电脑就没有这些问题啊。

**Comment by xgj1988** [comment]
用yarn 多安装几次就可以了
