### ISSUE TITLE
[Bug] 使用 vue 时，在开启 legacy 配置，执行 build 时，会有报错

### ISSUE THREAD

**Issue by cklwblove** [umijs/umi#11357]
## Mini Showcase Repository(REQUIRED)

使用 `yarn create umi` 创建一个 `vue` 项目时，开启 `.umirc` 配置文件中的 `legacy` 配置，如下：

```diff
export default defineConfig({
  npmClient: 'yarn',
  presets: [require.resolve('@umijs/preset-vue')],
+  legacy: {
+   checkOutput: true
+ },
  esbuildMinifyIIFE: true
});

```
在执行 `build` 命令时，会出现以下报错

```
> build
> umi build

info  -  LEGACY MODE  is enabled, we automatically modify the srcTranspiler, jsMinifier, cssMinifier to be compatible with IE 11
info  - [你知道吗？] COMPRESS=none umi build 可以关闭项目构建时的代码压缩功能, 方便调试项目的构建产物。
info  - Umi v4.0.72

✖ Webpack
  Compiled with some errors in 17.74s

info  - Memory Usage: 539.03 MB (RSS: 527.41 MB)
fatal - Error: ERROR in ./src/.umi-production/core/App.vue
Module Error (from ./node_modules/vue-loader/dist/index.js):
At least one <template> or <script> is required in a single file component.
 @ ./node_modules/@umijs/preset-vue/node_modules/@umijs/renderer-vue/dist/browser.js 3:0-34 15:22-25
 @ ./node_modules/@umijs/preset-vue/node_modules/@umijs/renderer-vue/dist/index.js 10:0-56 10:0-56 10:0-56
 @ ./src/.umi-production/umi.ts 397:0-152 462:21-33

ERROR in ./src/layouts/index.vue
Module build failed (from ./node_modules/@umijs/bundler-webpack/compiled/babel-loader/index.js):
SyntaxError: /Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/src/layouts/index.vue: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (17:0)

  15 |   </div>
  16 | </template>
> 17 | <script>
     | ^
  18 | export default {
  19 |   name: 'layouts'
  20 | }
    at instantiate (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:84800:32)
    at constructor (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:85095:12)
    at JSXParserMixin.raise (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:87992:19)
    at JSXParserMixin.jsxParseElementAt (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:91685:18)
    at JSXParserMixin.jsxParseElement (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:91694:17)
    at JSXParserMixin.parseExprAtom (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:91706:19)
    at JSXParserMixin.parseExprSubscripts (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95627:23)
    at JSXParserMixin.parseUpdate (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95610:21)
    at JSXParserMixin.parseMaybeUnary (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95586:23)
    at JSXParserMixin.parseMaybeUnaryOrPrivate (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95424:61)
    at JSXParserMixin.parseExprOps (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95429:23)
    at JSXParserMixin.parseMaybeConditional (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95406:23)
    at JSXParserMixin.parseMaybeAssign (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95367:21)
    at JSXParserMixin.parseExpressionBase (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95321:23)
    at /Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95317:39
    at JSXParserMixin.allowInAnd (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97012:16)
    at JSXParserMixin.parseExpression (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95317:17)
    at JSXParserMixin.parseStatementContent (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97470:23)
    at JSXParserMixin.parseStatementLike (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97321:17)
    at JSXParserMixin.parseModuleItem (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97298:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97922:36)
    at JSXParserMixin.parseBlockBody (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97915:10)
    at JSXParserMixin.parseProgram (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97197:10)
    at JSXParserMixin.parseTopLevel (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97187:25)
    at JSXParserMixin.parse (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:99084:10)
    at parse (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:99104:26)
    at parser (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:43749:34)
    at parser.next (<anonymous>)
    at normalizeFile (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:45060:38)
    at normalizeFile.next (<anonymous>)
    at run (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:44910:50)
    at run.next (<anonymous>)
    at transform (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:44412:41)
    at transform.next (<anonymous>)
    at step (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:10186:32)
    at /Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:10198:13
    at async.call.result.err.err (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:10148:11)
 @ ./src/.umi-production/core/route.tsx 446:23-152
 @ ./src/.umi-production/umi.ts 398:0-41 415:17-26

ERROR in ./src/pages/docs.vue
Module build failed (from ./node_modules/@umijs/bundler-webpack/compiled/babel-loader/index.js):
SyntaxError: /Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/src/pages/docs.vue: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (6:0)

  4 |   </div>
  5 | </template>
> 6 | <script>
    | ^
  7 | export default {
  8 |   name: 'docs'
  9 | }
    at instantiate (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:84800:32)
    at constructor (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:85095:12)
    at JSXParserMixin.raise (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:87992:19)
    at JSXParserMixin.jsxParseElementAt (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:91685:18)
    at JSXParserMixin.jsxParseElement (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:91694:17)
    at JSXParserMixin.parseExprAtom (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:91706:19)
    at JSXParserMixin.parseExprSubscripts (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95627:23)
    at JSXParserMixin.parseUpdate (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95610:21)
    at JSXParserMixin.parseMaybeUnary (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95586:23)
    at JSXParserMixin.parseMaybeUnaryOrPrivate (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95424:61)
    at JSXParserMixin.parseExprOps (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95429:23)
    at JSXParserMixin.parseMaybeConditional (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95406:23)
    at JSXParserMixin.parseMaybeAssign (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95367:21)
    at JSXParserMixin.parseExpressionBase (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95321:23)
    at /Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95317:39
    at JSXParserMixin.allowInAnd (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97012:16)
    at JSXParserMixin.parseExpression (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95317:17)
    at JSXParserMixin.parseStatementContent (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97470:23)
    at JSXParserMixin.parseStatementLike (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97321:17)
    at JSXParserMixin.parseModuleItem (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97298:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97922:36)
    at JSXParserMixin.parseBlockBody (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97915:10)
    at JSXParserMixin.parseProgram (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97197:10)
    at JSXParserMixin.parseTopLevel (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97187:25)
    at JSXParserMixin.parse (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:99084:10)
    at parse (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:99104:26)
    at parser (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:43749:34)
    at parser.next (<anonymous>)
    at normalizeFile (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:45060:38)
    at normalizeFile.next (<anonymous>)
    at run (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:44910:50)
    at run.next (<anonymous>)
    at transform (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:44412:41)
    at transform.next (<anonymous>)
    at step (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:10186:32)
    at /Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:10198:13
    at async.call.result.err.err (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:10148:11)
 @ ./src/.umi-production/core/route.tsx 443:23-103
 @ ./src/.umi-production/umi.ts 398:0-41 415:17-26

ERROR in ./src/pages/index.vue
Module build failed (from ./node_modules/@umijs/bundler-webpack/compiled/babel-loader/index.js):
SyntaxError: /Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/src/pages/index.vue: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (10:0)

   8 |   </div>
   9 | </template>
> 10 | <script>
     | ^
  11 | export default {
  12 |   name: 'index'
  13 | }
    at instantiate (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:84800:32)
    at constructor (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:85095:12)
    at JSXParserMixin.raise (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:87992:19)
    at JSXParserMixin.jsxParseElementAt (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:91685:18)
    at JSXParserMixin.jsxParseElement (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:91694:17)
    at JSXParserMixin.parseExprAtom (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:91706:19)
    at JSXParserMixin.parseExprSubscripts (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95627:23)
    at JSXParserMixin.parseUpdate (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95610:21)
    at JSXParserMixin.parseMaybeUnary (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95586:23)
    at JSXParserMixin.parseMaybeUnaryOrPrivate (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95424:61)
    at JSXParserMixin.parseExprOps (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95429:23)
    at JSXParserMixin.parseMaybeConditional (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95406:23)
    at JSXParserMixin.parseMaybeAssign (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95367:21)
    at JSXParserMixin.parseExpressionBase (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95321:23)
    at /Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95317:39
    at JSXParserMixin.allowInAnd (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97012:16)
    at JSXParserMixin.parseExpression (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95317:17)
    at JSXParserMixin.parseStatementContent (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97470:23)
    at JSXParserMixin.parseStatementLike (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97321:17)
    at JSXParserMixin.parseModuleItem (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97298:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97922:36)
    at JSXParserMixin.parseBlockBody (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97915:10)
    at JSXParserMixin.parseProgram (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97197:10)
    at JSXParserMixin.parseTopLevel (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:97187:25)
    at JSXParserMixin.parse (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:99084:10)
    at parse (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:99104:26)
    at parser (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:43749:34)
    at parser.next (<anonymous>)
    at normalizeFile (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:45060:38)
    at normalizeFile.next (<anonymous>)
    at run (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:44910:50)
    at run.next (<anonymous>)
    at transform (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:44412:41)
    at transform.next (<anonymous>)
    at step (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:10186:32)
    at /Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:10198:13
    at async.call.result.err.err (/Users/liwenbo/Desktop/liwb_work/lab/umijs-demo/vue-demo/node_modules/@umijs/bundler-utils/compiled/babel/index.js:10148:11)
 @ ./src/.umi-production/core/route.tsx 440:23-105
 @ ./src/.umi-production/umi.ts 398:0-41 415:17-26

```

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.72
- **Node Version**: 18.16.0
- **Platform**: mac os

**这个配置项目前对 `vue` 不起作用吗？**

**Comment by fz6m** [comment]
umi 是一个 react 的框架，目前 vue 、vite 模式都是独立的 feature ，用来给某些企业内部统一脚手架使用的，所以其他的选项都不支持和 vue 一起使用，如果你有需求，可以自己编写插件或调整 webpack 配置实现。。

**Comment by fz6m** [comment]
@xierenyuan 你们有 vue 项目需要 legacy 兼容的场景嘛，如果有可以提 PR 支持下 vue 一起使用🌹

**Comment by cklwblove** [comment]
> umi 是一个 react 的框架，目前 vue 、vite 模式都是独立的 feature ，用来给某些企业内部统一脚手架使用的，所以其他的选项都不支持和 vue 一起使用，如果你有需求，可以自己编写插件或调整 webpack 配置实现。。

好的
