### ISSUE TITLE
@sentry/webpack-plugin引入一直在报错

### ISSUE THREAD

**Issue by zegezs** [umijs/umi#11497]
## What happens?
umi3.5版本中引入Sentry，配置上传source-map过程中，在config.ts文件中添加@sentry/webpack-plugin这个plugin，打包项目一直在报错

umi3.5版本中引入Sentry，配置上传source-map过程中，在config.ts文件中添加@sentry/webpack-plugin这个plugin，打包项目一直在报错

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].plugins[10] misses the property 'apply'. Should be:
   function
   -> The run point of the plugin, required method.
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].plugins[10] misses the property 'apply'. Should be:
   function
   -> The run point of the plugin, required method.
    at validate (/Users/mac/Work/Project/imotor-web-pro/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:46383:11)
    at validateSchema (/Users/mac/Work/Project/imotor-web-pro/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:188244:2)
    at create (/Users/mac/Work/Project/imotor-web-pro/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:191683:24)
    at Object.webpack (/Users/mac/Work/Project/imotor-web-pro/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:191725:32)
    at Bundler.setupDevServerOpts (/Users/mac/Work/Project/imotor-web-pro/node_modules/@umijs/bundler-webpack/lib/index.js:202:40)
    at /Users/mac/Work/Project/imotor-web-pro/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/dev.js:300:30
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/mac/Work/Project/imotor-web-pro/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/dev.js:74:103)
    at _next (/Users/mac/Work/Project/imotor-web-pro/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/dev.js:76:194)
## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
