### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by zegezs** [umijs/umi#11500]
umi4引入@sentry/webpack-plugin 项目直接报错了
## What happens?
`
import { defineConfig } from '@umijs/max';
const SentryWebpackPlugin = require('@sentry/webpack-plugin');

export default defineConfig({
  chainWebpack(memo) {
    memo.plugin('sentry').use(SentryWebpackPlugin, [
      {
        ignore: ['node_modules'],
        include: './dist', //上传dist文件的js
        configFile: './sentryclirc', //配置文件地址，这个一定要有，踩坑在这里，忘了写导致一直无法实现上传sourcemap
        release: '1.0.1', //版本号，自己定义的变量，整个版本号在项目里面一定要对应
        deleteAfterCompile: true,
        urlPrefix: '~/', // js的代码路径前缀
      },
    ]);
  },
});

`

fatal - Error: Parse config file failed: [/Users/mac/Work/MyProject/sentry-test-max/.umirc.ts]
    at Function.getUserConfig (/Users/mac/Work/MyProject/sentry-test-max/node_modules/@umijs/core/dist/config/config.js:161:17)
    at Config.getUserConfig (/Users/mac/Work/MyProject/sentry-test-max/node_modules/@umijs/core/dist/config/config.js:58:19)
    at Service.run (/Users/mac/Work/MyProject/sentry-test-max/node_modules/@umijs/core/dist/service/service.js:233:37)
    at Service.run2 (/Users/mac/Work/MyProject/sentry-test-max/node_modules/umi/dist/service/service.js:65:23)
    at /Users/mac/Work/MyProject/sentry-test-max/node_modules/umi/dist/cli/forkedDev.js:24:19
    at Object.<anonymous> (/Users/mac/Work/MyProject/sentry-test-max/node_modules/umi/dist/cli/forkedDev.js:37:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12) {
  [cause]: Error: Cannot find module 'webpack'
  Require stack:
  - /Users/mac/Work/MyProject/sentry-test-max/node_modules/@sentry/webpack-plugin/dist/cjs/index.js
  - /Users/mac/Work/MyProject/sentry-test-max/.umirc.ts
  - /Users/mac/Work/MyProject/sentry-test-max/node_modules/@umijs/core/dist/config/config.js
  - /Users/mac/Work/MyProject/sentry-test-max/node_modules/@umijs/core/dist/index.js
  - /Users/mac/Work/MyProject/sentry-test-max/node_modules/umi/dist/service/service.js
  - /Users/mac/Work/MyProject/sentry-test-max/node_modules/umi/dist/cli/forkedDev.js
  - /Users/mac/Work/MyProject/sentry-test-max/node_modules/umi/bin/forkedDev.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
      at Function.mod._resolveFilename (/Users/mac/Work/MyProject/sentry-test-max/node_modules/umi/dist/service/requireHook.js:13:26)
      at Function.Module._load (node:internal/modules/cjs/loader:833:27)
      at Module.require (node:internal/modules/cjs/loader:1057:19)
      at require (node:internal/modules/cjs/helpers:103:18)
      at Object.<anonymous> (/Users/mac/Work/MyProject/sentry-test-max/node_modules/@sentry/webpack-plugin/dist/cjs/index.js:8:19)
      at Module._compile (node:internal/modules/cjs/loader:1155:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
      at Object.newLoader [as .js] (/Users/mac/Work/MyProject/sentry-test-max/node_modules/@umijs/utils/compiled/pirates/index.js:1:1684)
      at Module.load (node:internal/modules/cjs/loader:1033:32) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/mac/Work/MyProject/sentry-test-max/node_modules/@sentry/webpack-plugin/dist/cjs/index.js',
      '/Users/mac/Work/MyProject/sentry-test-max/.umirc.ts',
      '/Users/mac/Work/MyProject/sentry-test-max/node_modules/@umijs/core/dist/config/config.js',
      '/Users/mac/Work/MyProject/sentry-test-max/node_modules/@umijs/core/dist/index.js',
      '/Users/mac/Work/MyProject/sentry-test-max/node_modules/umi/dist/service/service.js',
      '/Users/mac/Work/MyProject/sentry-test-max/node_modules/umi/dist/cli/forkedDev.js',
      '/Users/mac/Work/MyProject/sentry-test-max/node_modules/umi/bin/forkedDev.js'
    ]
  }
}
fatal - A complete log of this run can be found in:
fatal - /Users/mac/Work/MyProject/sentry-test-max/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
## Mini Showcase Repository(REQUIRED)
https://github.com/zegezs/sentry-test-max

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
umi 4 不支持 sentry 之类的 webpack 插件，因为 umi 构建的产物是单独生成的，不在 webpack 中，所以 sentry 没法知道要上传什么文件，正确的做法是构建完手动或者在构建脚本里用 cli 上传产物。
