### ISSUE TITLE
[Bug] antdpro pnpm i 报错 pnpm esbuild 0.17.19 but got 0.16.17

### ISSUE THREAD

**Issue by shangchuan123** [umijs/umi#11507]
pnpm i 报错 pnpm esbuild 0.17.19 but got 0.16.17
## What happens?
pnpm i报以下错
\node_modules.pnpm\registry.npmmirror.com+esbuild@0.17.19\node_modules\esbuild\install.js:132
│     throw new Error(Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)});
│           ^
│ Error: Expected "0.17.19" but got "0.16.17"
│     at validateBinaryVersion (D:\workspace\meishi-seller-manage\node_modules.pnpm\registry.npmmirror.com+esbuild@0.17.19\node_modules\esbuild\install.js:132:11)
│     at D:\workspace\manage\node_modules.pnpm\registry.npmmirror.com+esbuild@0.17.19\node_modules\esbuild\install.js:283:5
│ Node.js v18.16.0
└─ Failed in 203ms at D:\workspace\manage\node_modules.pnpm\registry.npmmirror.com+esbuild@0.17.19\node_modules\esbuild
 ELIFECYCLE  Command failed with exit code 1.

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
我 clone 了一份新的 [ant pro](https://github.com/ant-design/ant-design-pro) 的仓库，删掉 lock 文件后，把 `@umijs/max` 升级到最新版本，安装依赖后可以启动起来。

如有问题，需要给一个最小复现。
