### ISSUE TITLE
本地开发无任何问题，打包后报错，Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by tanwenchao** [umijs/umi#11529]
TypeError: Cannot read properties of undefined (reading 'length')
    at p__index__index.async.js:1:3519
    at Array.forEach (<anonymous>)
    at N.insertCssText (p__index__index.async.js:1:3473)
    at M.J [as initStyleRules] (p__index__index.async.js:1:5773)
    at M.init (p__index__index.async.js:1:11072)
    at new M (p__index__index.async.js:1:11004)
    at p__index__index.async.js:1:13710
    at y (p__index__index.async.js:1:13979)
    at p__index__index.async.js:1:14023
    at hu (umi.js:14:24392)
Gi @ umi.js:14
umi.js:12 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at p__index__index.async.js:1:3519
    at Array.forEach (<anonymous>)
    at N.insertCssText (p__index__index.async.js:1:3473)
    at M.J [as initStyleRules] (p__index__index.async.js:1:5773)
    at M.init (p__index__index.async.js:1:11072)
    at new M (p__index__index.async.js:1:11004)
    at p__index__index.async.js:1:13710
    at y (p__index__index.async.js:1:13979)
    at p__index__index.async.js:1:14023
    at hu (umi.js:14:24392)

**Comment by fz6m** [comment]
需要给一个会报错的最小复现。
