### ISSUE TITLE
[Bug] max setup 报错

### ISSUE THREAD

**Issue by lis-soft** [umijs/umi#11672]
{
  "private": true,
  "author": "",
  "scripts": {
    "dev": "max dev",
    "build": "max build",
    "format": "prettier --cache --write .",
    "prepare": "husky install",
    "postinstall": "max setup",
    "setup": "max setup",
    "start": "npm run dev"
  },
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^1.1.3",
    "@umijs/max": "^4.0.9",
    "antd": "^4.20.7",
    "qiankun": "^2.7.4"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "husky": "^8.0.1",
    "lint-staged": "^13.0.3",
    "prettier": "^2.7.1",
    "prettier-plugin-organize-imports": "^2",
    "prettier-plugin-packagejson": "^2",
    "typescript": "^4.1.2"
  }
}

错误信息：
> postinstall
> max setup

fatal - Error: EPERM: operation not permitted, open '/Home'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at Proxy.getRoutes (/Users/lis/source/work/main/node_modules/@umijs/preset-umi/dist/features/tmpFiles/routes.js:111:57)
    at Hook.fn (/Users/lis/source/work/main/node_modules/@umijs/preset-umi/dist/features/appData/appData.js:51:35)
    at /Users/lis/source/work/main/node_modules/@umijs/core/dist/service/service.js:136:38
    at eval (eval at create (/Users/lis/source/work/main/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:8410), <anonymous>:84:17)
    at new Promise (<anonymous>)
    at Hook.eval [as promise] (eval at create (/Users/lis/source/work/main/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:8410), <anonymous>:6:8)
    at Hook.PROMISE_DELEGATE [as _promise] (/Users/lis/source/work/main/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4959)
    at Service.applyPlugins (/Users/lis/source/work/main/node_modules/@umijs/core/dist/service/service.js:145:24) {
  errno: -1,
  syscall: 'open',
  code: 'EPERM',
  path: '/Home'
}
fatal - A complete log of this run can be found in:
fatal - /Users/lis/source/work/main/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
npm ERR! code 1
npm ERR! path /Users/lis/source/work/main
npm ERR! command failed
npm ERR! command sh -c max setup

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lis/.npm/_logs/2023-09-21T05_46_15_404Z-debug-0.log

**Comment by sorrycc** [comment]
文件夹权限问题，请检查本地目录权限。
