### ISSUE TITLE
yarn start error

### ISSUE THREAD

**Issue by zwj7181** [umijs/umi#1169]
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'F:\production\scan-front-end\module.js'
    at Object.fs.openSync (fs.js:646:18)
    at fs.readFileSync (fs.js:551:33)
    at _default (F:\production\scan-front-end\node_modules\umi-build-dev\lib\utils\getCodeFrame.js:50:43)
    at Service.initPlugin (F:\production\scan-front-end\node_modules\umi-build-dev\lib\Service.js:145:29)
    at extraPlugins.forEach.plugin (F:\production\scan-front-end\node_modules\umi-build-dev\lib\Service.js:165:14)
    at Array.forEach (<anonymous>)
    at Service.initPlugins (F:\production\scan-front-end\node_modules\umi-build-dev\lib\Service.js:164:20)
    at Service.init (F:\production\scan-front-end\node_modules\umi-build-dev\lib\Service.js:284:10)
    at Service.run (F:\production\scan-front-end\node_modules\umi-build-dev\lib\Service.js:320:10)
    at Object.<anonymous> (F:\production\scan-front-end\node_modules\umi\lib\scripts\realDev.js:28:47)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by zwj7181** [comment]
是通过 create-umi 提供脚手架创建的项目

**Comment by zwj7181** [comment]
开启pwa导致的
