### ISSUE TITLE
umi2.1.1 chunk配置build报错

### ISSUE THREAD

**Issue by Jeephe** [umijs/umi#1171]
[myapp.zip](https://github.com/umijs/umi/files/2430427/myapp.zip)
附件为简单的umi guide里的例子。
将maxSize的值改为非0的值，build将报这样的错误：

[16:12:19] webpack compiled in 10s 557ms

 ERROR  Failed to compile with 1 errors                                                                         16:12:19

 error

file umi.js don't exists in chunksMap {"umi~bf9d5b82.js":"umi~bf9d5b82.js","umi~748942c6.js":"umi~748942c6.async.js","umi~31ecd969.css":"umi~31ecd969.chunk.css","umi~31ecd969.js":"umi~31ecd969.async.js","umi~edb28f9c.js":"umi~edb28f9c.async.js","umi~69d7dbcb.js":"umi~69d7dbcb.async.js","umi~19e05061.js":"umi~19e05061.async.js","umi~4983dd68.js":"umi~4983dd68.async.js","umi~c703ebae.js":"umi~c703ebae.async.js","umi~4c1c065c.js":"umi~4c1c065c.async.js","umi~e9f69f62.js":"umi~e9f69f62.async.js","umi~add8a43f.js":"umi~add8a43f.async.js","umi~a59d06cc.js":"umi~a59d06cc.async.js","umi~99cb14b8.js":"umi~99cb14b8.async.js","umi~8be69c33.js":"umi~8be69c33.async.js","umi~51138715.js":"umi~51138715.async.js","umi~6383e19a.js":"umi~6383e19a.async.js","umi~2627d776.js":"umi~2627d776.async.js"}

**Comment by superlbr** [comment]
刚想提，这边就有了，给力，类似这样
```
  chainWebpack(config) {
    config.optimization.splitChunks({
      chunks: 'async',
      minSize: 38000,
      maxSize: 1000,
    })
  },
```

**Comment by Jeephe** [comment]
maxSize设为0，umi build没问题的。设为非0值，就报错。

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/46252548-ae1eda80-c49c-11e8-9430-798a5a6ae9a9.png)
这个配置有问题吧，打包出了这么多文件，分析不出哪个是 umi.js 了，可以再研究下怎么配 splitChunks。

**Comment by sorrycc** [comment]
可以参考 umi-plugin-react/test/chunks 的例子。

**Comment by superlbr** [comment]
这边maxSize>0的报错有点不一样

```
/Users/dva/admin/node_modules/webpack/lib/util/deterministicGrouping.js:168
                                leftSize += group.nodes[left].size;
                                                              ^

TypeError: Cannot read property 'size' of undefined
    at module.exports (/Users/dva/admin/node_modules/webpack/lib/util/deterministicGrouping.js:168:35)
    at compilation.hooks.optimizeChunksAdvanced.tap.chunks (/Users/dva/admin/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:797:23)
    at SyncBailHook.eval (eval at create (/Users/dva/admin/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:16)
    at SyncBailHook.lazyCompileHook (/Users/dva/admin/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/dva/admin/node_modules/webpack/lib/Compilation.js:1208:38)
    at hooks.make.callAsync.err (/Users/dva/admin/node_modules/webpack/lib/Compiler.js:547:17)
    at _err0 (eval at create (/Users/dva/admin/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _addModuleChain (/Users/dva/admin/node_modules/webpack/lib/Compilation.js:1065:12)
    at processModuleDependencies.err (/Users/dva/admin/node_modules/webpack/lib/Compilation.js:981:9)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
error Command failed with exit code 1.
```

**Comment by sorrycc** [comment]
@superlbr 这是 webpack 内部逻辑抛的错了。

**Comment by liweiSm** [comment]
我也有遇到一样的问题，配置splitChunks后，报错 
file vendors.js don't exists in chunksMap {"1.css":"1.chunk.css","1.js":"1.async.js","2.js":"2.async.js", .........}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `umi build`
npm ERR! Exit status 1
我试着改变node 版本，然后再build，但是还是会报错，无法找到问题所在

**Comment by GSBL** [comment]
> 我也有遇到一样的问题，配置splitChunks后，报错
> file vendors.js don't exists in chunksMap {"1.css":"1.chunk.css","1.js":"1.async.js","2.js":"2.async.js", .........}
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @ build: `umi build`
> npm ERR! Exit status 1
> 我试着改变node 版本，然后再build，但是还是会报错，无法找到问题所在

解决了吗
