### ISSUE TITLE
大小写不敏感导致的问题

### ISSUE THREAD

**Issue by WG-Com** [umijs/umi#1177]
```
> umi build


WARNING!!
umi-plugin-polyfills is deprecated, use config.targets instead.




Compiling

● webpack █████████████████████████ building modules (26%) 138/143 modules 5 active
  node_modules/_umi@2.1.1@umi/lib/link.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0 build: `umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-29T16_30_51_858Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build', '-p' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@2.0.0~prebuild: ant-design-pro@2.0.0
6 info lifecycle ant-design-pro@2.0.0~build: ant-design-pro@2.0.0
7 verbose lifecycle ant-design-pro@2.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/test/bi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle ant-design-pro@2.0.0~build: CWD: /root/test/x
10 silly lifecycle ant-design-pro@2.0.0~build: Args: [ '-c', 'umi build' ]
11 silly lifecycle ant-design-pro@2.0.0~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.0.0~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@2.0.0 build: `umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid ant-design-pro@2.0.0
15 verbose cwd /root/test/bi
16 verbose Linux 3.10.0-693.2.2.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "-p"
18 verbose node v10.11.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.0.0 build: `umi build`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


```

**Comment by WG-Com** [comment]
```
node --version
v10.11.0

WINDOWS / CENTOS都是报一样的错，多台机器都是这个错误
```

**Comment by sorrycc** [comment]
问题是什么？卡住不动？需要提供可重现的库给我。

**Comment by WG-Com** [comment]
@sorrycc  查出来了，路由和pages大小写不一致问题，但是这里一点报错都没有，npm start可以看出来

**Comment by xiaohuoni** [comment]
@sorrycc 大小写敏感的问题，我觉得可以再跟进一下吧？要是觉得没有必要的话，就关闭吧

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/2379

**Comment by sorrycc** [comment]
有需要的可以自己加 [case-sensitive-paths-webpack-plugin](https://github.com/Urthen/case-sensitive-paths-webpack-plugin)，这个插件消耗性能比较多，就不内置了。

**Comment by CyanPZ** [comment]
路由应该要小写吗？我也遇到这个问题了，没找到解决办法
