### ISSUE TITLE
[Bug] umi4 接入sentry/webpack-plugin 报错无法打包

### ISSUE THREAD

**Issue by iceshu** [umijs/umi#11844]
## umi4 接入sentry/webpack-plugin 报错无法打包

  新建项目
```ts
import { sentryWebpackPlugin } from '@sentry/webpack-plugin';
import { defineConfig } from '@umijs/max';

export default defineConfig({
//...
  devtool: 'source-map',
  chainWebpack: (memo) => {
    memo.plugin('sentry').use(sentryWebpackPlugin, [
      {
        include: './dist',
        configFile: './sentryclirc', 
        release: '1.0.1', 
        deleteAfterCompile: true,
      },
    ]);
  },
//....
});
```
## Mini Showcase Repository(REQUIRED)

新建项目 如何接入 @sentry/webpack-plugin 配置  执行build 提示如下
```ts
 TypeError: e is not a constructor
    at /Users/ice/Desktop/pro/umijs-qiankun/app1/node_modules/@umijs/bundler-webpack/compiled/webpack-5-chain/index.js:1:19639
    at Object.toConfig (/Users/ice/Desktop/pro/umijs-qiankun/app1/node_modules/@umijs/bundler-webpack/compiled/webpack-5-chain/index.js:1:20549)
    at /Users/ice/Desktop/pro/umijs-qiankun/app1/node_modules/@umijs/bundler-webpack/compiled/webpack-5-chain/index.js:1:13918
    at Array.map (<anonymous>)
    at e.exports.toConfig (/Users/ice/Desktop/pro/umijs-qiankun/app1/node_modules/@umijs/bundler-webpack/compiled/webpack-5-chain/index.js:1:13908)
    at Proxy.getConfig (/Users/ice/Desktop/pro/umijs-qiankun/app1/node_modules/@umijs/bundler-webpack/dist/config/config.js:226:30)
    at async Proxy.build (/Users/ice/Desktop/pro/umijs-qiankun/app1/node_modules/@umijs/bundler-webpack/dist/build.js:47:25)
    at async Command.fn (/Users/ice/Desktop/pro/umijs-qiankun/app1/node_modules/@umijs/preset-umi/dist/commands/build.js:143:17)
    at async Service.run (/Users/ice/Desktop/pro/umijs-qiankun/app1/node_modules/@umijs/core/dist/service/service.js:328:15)
    at async Service.run2 (/Users/ice/Desktop/pro/umijs-qiankun/app1/node_modules/umi/dist/service/service.js:65:12)
    at async run (/Users/ice/Desktop/pro/umijs-qiankun/app1/node_modules/umi/dist/cli/cli.js:56:7)
```

## Context

- **Umi Version**:  "@umijs/max": "^4.0.87",
- **Node Version**: v16.18.0
- **Platform**: macos

**Comment by fz6m** [comment]
试试这个：

```ts
// .umirc.ts

  devtool: "source-map",
  chainWebpack(memo) {
    const { sentryWebpackPlugin } = require("@sentry/webpack-plugin");
    const sentryPlugin = sentryWebpackPlugin(
      {
         // ...
      }
    )
    memo.set(
      'plugins',
      [
        ...memo.plugins.values(),
        sentryPlugin
      ]
    )
  }
```

**Comment by iceshu** [comment]
@fz6m 谢谢不报错了但是好像资源没上传上去 我在研究研究

**Comment by abingbaba** [comment]
@iceshu  问题解决了吗？怎么解决的

**Comment by noxxxxxxxx** [comment]
> 试试这个：
> 
> ```ts
> // .umirc.ts
> 
>   devtool: "source-map",
>   chainWebpack(memo) {
>     const { sentryWebpackPlugin } = require("@sentry/webpack-plugin");
>     const sentryPlugin = sentryWebpackPlugin(
>       {
>          // ...
>       }
>     )
>     memo.set(
>       'plugins',
>       [
>         ...memo.plugins.values(),
>         sentryPlugin
>       ]
>     )
>   }
> ```

为什么需要使用这种特殊处理？默认写法报错的问题什么时候能 fix？尝试了这种写法依旧无法上传 sourcemap

**Comment by fz6m** [comment]
由于 chain webpack 的配置限制，不支持构造函数式的写法（`new Class` 的操作在 `sentryWebpackPlugin` 内部，而不是外部，chain webpack 不支持），所以如果你需要使用 sentry webpack 插件，目前唯一的配置方式可以参考上文中的回复。

如果有其他问题，需要自行排查，或者给一个最小复现仓库。

**Comment by xiaohuoni** [comment]
```
// .umirc.ts

  devtool: "source-map",
  chainWebpack(memo) {
    const { sentryWebpackPlugin } = require(https://github.com/getsentry/sentry-javascript-bundler-plugins);
   memo.plugin('sentry').use(sentryWebpackPlugin({
     // ...
   }))
   return memo;
  }
```
