### ISSUE TITLE
[Bug] 启动有yarn.lock的umi3项目 AssertionError [ERR_ASSERTION]: chunk of umi not found

### ISSUE THREAD

**Issue by panjunqiu** [umijs/umi#12104]
## What happens?
启动有yarn.lock的umi3项目 AssertionError [ERR_ASSERTION]: chunk of umi not found

之前云构建，历史发布代码无法启动调试

## Mini Showcase Repository(REQUIRED)
https://github.com/panjunqiu/umi2_error

复现最小示例已经去掉了所有业务代码和部分内网依赖，测试了可以复现，帮忙看下是什么问题，谢谢。

我的业务代码yarn start 报错，但是yarn build 可以正常打包成功。

## How To Reproduce
1. yarn install
2. yarn start

```
(base) ➜  umi2_error git:(main) ✗ yarn start
yarn run v1.22.19
$ cross-env REACT_APP_ENV=dev umi dev
Starting the development server...

● Webpack █████████████████████████ building (10%) 3/10 modules 7 active
 css-loader › postcss-loader › less-loader › node_modules/antd/dist/antd.less

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at /Users/panjunqiu/dev/project/mindopt/umi2_error/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (/Users/panjunqiu/dev/project/mindopt/umi2_error/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
    at /Users/panjunqiu/dev/project/mindopt/umi2_error/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:189:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/panjunqiu/dev/project/mindopt/umi2_error/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
    at _next (/Users/panjunqiu/dev/project/mindopt/umi2_error/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
✨  Done in 3.96s.
```

## Context

- **Umi Version**: 3.5.41
- **Node Version**: v16.18.1
- **Platform**: macOS

**Comment by fz6m** [comment]
我没复现你这个问题，我把你的这个项目 clone 下来删除 lock 文件后（里面是内网源我用不了），安装依赖后可以正常跑起来。

umi 3 已经不维护了，建议升级到 umi 4 ，现在 umi 3 的问题都不看了。

我不是阿里蚂蚁的，要不你找蚂蚁的 umi oncall 同学问问，他们的经验肯定比较多。

**Comment by xiaohuoni** [comment]
@fz6m 手快，他私聊我了，我也没复现，正想来回复
