### ISSUE TITLE
因为有next项目，所以之前升级了node版本，Node.js v20.11.1，umi版本3.5.36 启动访问项目 会报错AssertionError [ERR_ASSERTION]: chunk of umi not found.

### ISSUE THREAD

**Issue by LBJDJW** [umijs/umi#12239]
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at D:\project\sangon-web\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (D:\project\sangon-web\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:93:14)
    at D:\project\sangon-web\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:189:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\project\sangon-web\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:62:103)
    at _next (D:\project\sangon-web\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:64:194)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

Node.js v20.11.1
Done in 88.66s.

**Comment by xiaohuoni** [comment]
群里看到类似的，加一个环境变量试试  NODE_OPTIONS=--openssl-legacy-provider

**Comment by LBJDJW** [comment]
> 群里看到类似的，加一个环境变量试试 NODE_OPTIONS=--openssl-legacy-provider

我试过了 这次不行 我现在降node版本了

**Comment by fz6m** [comment]
有很多项目他们要求的 node 版本号不同是很正常的，因为新旧不同，不可能都能用最新的 node 跑起来，不然 node 还发大版本干啥，必然可能有 breaking change 。

所以最好得在项目里加入 nvm 的配置，让 nvm 自动去切换 node 版本，如果 nvm 觉得太重影响终端启动时间，就用 fnm 手动去修改 node 版本再启动项目即可，你可以设定一些 alias 来加快切换 node 版本的过程。

或者你可以尝试 node v18 能不能用，能用的话就没必要 v20 。

**Comment by xiongying1994** [comment]
我node版本都降到16.14.2了，还是不行啊
