### ISSUE TITLE
umi线上打包报错

### ISSUE THREAD

**Issue by tiancaizhu** [umijs/umi#1228]
#### 环境
* 系统版本: Linux 3.16
* node: 8.9.3
* npm: 6.4.1

#### package.json

```json
{
  "private": true,
  "scripts": {
    "start:mock": "umi dev",
    "start": "umi dev mock=NONE",
    "build": "umi build",
    "test": "umi test",
    "lint": "eslint --ext .js src mock tests",
    "precommit": "lint-staged"
  },
  "devDependencies": {
    "babel-eslint": "^9.0.0",
    "css-loader": "^0.28.7",
    "eslint": "^5.4.0",
    "eslint-config-umi": "^0.1.5",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^0.14.3",
    "intersection-observer": "^0.5.0",
    "lint-staged": "^7.2.2",
    "node-sass": "^4.9.3",
    "object-assign": "^4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "preload-webpack-plugin": "^2.3.0",
    "promise": "8.0.1",
    "react-hot-loader": "^4.1.3",
    "sass-loader": "^7.1.0",
    "string-includes": "^2.0.0",
    "style-loader": "^0.19.0",
    "swiper": "^3.4.2",
    "umi": "^2.1.2",
    "umi-plugin-react": "^1.0.0-0"
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "eslint --fix",
      "git add"
    ]
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "dependencies": {
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "rc-queue-anim": "^1.6.6",
    "rc-tween-one": "^2.2.8",
    "reqwest": "^2.0.5"
  }
}

```

#### .umirc.js

```js

const path = require('path');
export default {
    outputPath: 'background',
    history: 'hash',
    plugins: [
        ['umi-plugin-react', {
        antd: true,
        dva: true,
        dynamicImport: false,
        title: '',
        dll: false,
        pwa: false,
        routes: {
            exclude: [/component/, /models/, /utils/],
        },
        hardSource: false,
        }],
    ],
    alias: {
        '$AppUtils': path.resolve(__dirname, 'src/utils'),
        '$AppRoot': path.resolve(__dirname, 'src'),
        '$Mock': path.resolve(__dirname, 'mock'),
        '$Images': path.resolve(__dirname, 'src/images'),
        '$Common': path.resolve(__dirname, 'src/common')
    },
    disableCSSModules:true,
    sass:{
        test: /\.(scss)$/,
        use: [
            'style-loader',
            // 'css-loader',
            {
                loader: 'postcss-loader',
                options: {
                    plugins: [
                        require('autoprefixer')({
                            browsers: [
                                'iOS >= 8.0',
                                'Android >= 4.0',
                                'ie >= 9',
                                'Edge >= 12'
                            ]
                        })
                    ]
                }
            },
            'sass-loader'
        ]
    },
    publicPath: '//cloudgame-res.127.net/background/',
    proxy: {
        "/game": {
            "target": "http://10.242.117.28:8080",
            "changeOrigin": true,
        },
    }
}

```

#### 操作步骤
1. npm i
2. npm run build

#### error log

```
13 verbose stack Error: @ build: `umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ndp-soft/node-v8.9.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/ndp-soft/node-v8.9.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid 
```

**Comment by sorrycc** [comment]
给个可重现的库？

**Comment by sorrycc** [comment]
或者你用 `DEBUG=umi*,af-webpack* umi build` 跑跑看，有更详细的出错日志的。

**Comment by tiancaizhu** [comment]
好的   我试试看

**Comment by tiancaizhu** [comment]
```
webapp:
     [exec] v8.9.3
     [exec] 6.4.1
     [exec] npm WARN babel-plugin-dva-hmr@0.4.1 requires a peer of redbox-react@1.x but none is installed. You must install peer dependencies yourself.
     [exec] npm WARN dva-immer@0.2.3 requires a peer of dva@^2.2.0-0 but none is installed. You must install peer dependencies yourself.
     [exec] npm WARN dva-loading@2.0.5 requires a peer of dva@^2.0.4 but none is installed. You must install peer dependencies yourself.
     [exec] npm WARN eslint-config-react-app@2.1.0 requires a peer of babel-eslint@^7.2.3 but none is installed. You must install peer dependencies yourself.
     [exec] npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint@^4.1.1 but none is installed. You must install peer dependencies yourself.
     [exec] npm WARN eslint-plugin-jsx-a11y@5.1.1 requires a peer of eslint@^2.10.2 || ^3 || ^4 but none is installed. You must install peer dependencies yourself.
     [exec] npm WARN preload-webpack-plugin@2.3.0 requires a peer of webpack@^3.2.0 but none is installed. You must install peer dependencies yourself.
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
     [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
     [exec] 
     [exec] audited 56382 packages in 24.976s
     [exec] found 0 vulnerabilities
     [exec] 
     [exec] 
     [exec] > @ build /home/appops/ndp/source/bg-frontend-test-old
     [exec] > set DEBUG=umi*,af-webpack* & umi build
```

**Comment by xiaohuoni** [comment]
把
```
"umi": "^2.1.2",
"umi-plugin-react": "^1.0.0-0"
```
移到dependencies里面试试行不行

**Comment by tiancaizhu** [comment]
移到dependencies里不行

**Comment by tiancaizhu** [comment]
@sorrycc 用这个命令在本地是有log的    在打包机上log跟之前的没区别

**Comment by sorrycc** [comment]
看不出问题，只提供现在的这些信息帮不上你什么，给可重现步骤再 reopen 吧。

**Comment by boxcc** [comment]
应该是preload要v3才兼容webpack 4?
