### ISSUE TITLE
[Bug] Request调用POST请求的时候异常`Cannot convert object to primitive value`

### ISSUE THREAD

**Issue by DreamParadise** [umijs/umi#12447]
## What happens?

使用request发起POST请求的时候接口异常
请求代码：
```ts
import { request } from '@umijs/max';

export async function saveUpdateConfig(body: Config[], options?: { [key: string]: any }) {
  return request<any>(`/xx-service/api/v1/config`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}
```
上方`body`的值：
```json
[
    {
        "paramId": "1798557673108779010",
        "modelId": "1798557517563015169",
        "paramName": "p",
        "paramText": "p",
        "paramType": "STR",
        "componentType": "INPUT",
        "conditionStr": "LIKE",
        "required": false,
        "multiple": false,
        "pageSort": 1,
        "customSelectOptions": null,
        "paramEn": null,
        "placeholder": null,
        "formatFunc": null,
        "autoFill": false,
        "showInPage": true,
        "deleted": null
    }
]
```
浏览器控制台报错信息：
```
Uncaught (in promise) TypeError: Cannot convert object to primitive value
    at Array.join (<anonymous>)
    at Array.toString (<anonymous>)
    at Object.isFormData (mf-dep____vendor.41206b7e.js:288620:42)
    at Object.transformRequest (mf-dep____vendor.41206b7e.js:287640:15)
    at transform (mf-dep____vendor.41206b7e.js:287568:15)
    at Object.forEach (mf-dep____vendor.41206b7e.js:288696:10)
    at Object.transformData (mf-dep____vendor.41206b7e.js:287567:9)
    at dispatchRequest (mf-dep____vendor.41206b7e.js:287340:31)
```
具体的报错位置（`axios`库中的代码）：
```js
/**
 * Determine if a value is a FormData
 *
 * @param {Object} thing The value to test
 * @returns {boolean} True if value is an FormData, otherwise false
 */
function isFormData(thing) {
  var pattern = '[object FormData]';
  return thing && (
    (typeof FormData === 'function' && thing instanceof FormData) ||
    toString.call(thing) === pattern ||
    (isFunction(thing.toString) && thing.toString() === pattern)
  );
}
```

这里应该是`axios`的这个判断方法有问题，我看`axios`最新的版本都已经到`1.7.2`了，umi依赖的还是`^0.27.2`，什么时候把这个依赖更新下？

## Context

- **Umi Version**: 4.2.10
- **Node Version**: 20.11.1
- **Platform**: Windows Chrome

**Comment by fz6m** [comment]
我在一个新的 umi 4 项目里尝试了以下代码：

```ts
  useEffect(() => {
    request('/api/home', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      data: [
        {
          paramId: '1798557673108779010',
          modelId: '1798557517563015169',
          paramName: 'p',
          paramText: 'p',
          paramType: 'STR',
          componentType: 'INPUT',
          conditionStr: 'LIKE',
          required: false,
          multiple: false,
          pageSort: 1,
          customSelectOptions: null,
          paramEn: null,
          placeholder: null,
          formatFunc: null,
          autoFill: false,
          showInPage: true,
          deleted: null,
        },
      ],
    });
  }, []);
```

请求体 data 是可以正常发送的。

如还有问题，需要给一个最小复现。

**Comment by DreamParadise** [comment]
我在请求拦截器里面加了下面的代码之后可以正常请求了：
```ts
const requestInterceptor = async (config: RequestOptions) => {
  if (config.data && Array.isArray(config.data)) {
    config.data = JSON.stringify(config.data);
  }
  return config;
}
```
