### ISSUE TITLE
[Bug] pnpm dlx create-umi@latest 创建项目报错

### ISSUE THREAD

**Issue by ReinhardChen93** [umijs/umi#12519]
## What happens?

使用pnpm dlx create-umi@latest 创建项目报错 ERR_TTY_INIT_FAILED
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
![image](https://github.com/umijs/umi/assets/43949619/ac548f66-db83-455f-bd46-b6ad21f762b3)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

$ pnpm dlx create-umi@latest
┌   create-umi
Create failed, TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)
SystemError [ERR_TTY_INIT_FAILED]: TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)
    at new WriteStream (node:tty:98:11)
    at SelectPrompt.prompt (C:\Users\chenchen\AppData\Local\pnpm-cache\dlx\4i6ylavtoh73pbbuibppllaji4\1906d7c47d9-6248\node_modules\.pnpm\@umijs+utils@4.3.0\node_modules\@umijs\utils\compiled\@clack\prompts\index.js:1:3778)
    at select (C:\Users\chenchen\AppData\Local\pnpm-cache\dlx\4i6ylavtoh73pbbuibppllaji4\1906d7c47d9-6248\node_modules\.pnpm\@umijs+utils@4.3.0\node_modules\@umijs\utils\compiled\@clack\prompts\index.js:1:12857)
    at selectAppTemplate (C:\Users\chenchen\AppData\Local\pnpm-cache\dlx\4i6ylavtoh73pbbuibppllaji4\1906d7c47d9-6248\node_modules\.pnpm\create-umi@4.3.0\node_modules\create-umi\dist\index.js:60:25)
    at internalTemplatePrompts (C:\Users\chenchen\AppData\Local\pnpm-cache\dlx\4i6ylavtoh73pbbuibppllaji4\1906d7c47d9-6248\node_modules\.pnpm\create-umi@4.3.0\node_modules\create-umi\dist\index.js:111:11)
    at Object.src_default (C:\Users\chenchen\AppData\Local\pnpm-cache\dlx\4i6ylavtoh73pbbuibppllaji4\1906d7c47d9-6248\node_modules\.pnpm\create-umi@4.3.0\node_modules\create-umi\dist\index.js:160:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_TTY_INIT_FAILED',
  info: {
    errno: -4083,
    code: 'EBADF',
    message: 'bad file descriptor',
    syscall: 'uv_tty_init'
  },
  errno: [Getter/Setter: -4083],
  syscall: [Getter/Setter: 'uv_tty_init']
}

## Context

- **Umi Version**: umi@4.0.78
- **Node Version**: v22.3.0
- **Platform**: windows 11

**Comment by fz6m** [comment]
不支持在非交互式终端内创建 umi 项目。

**Comment by SeedHuang** [comment]
我也发现这个问题，我是在windows环境下使用git bash 运行 npx create-umi@latest发生的，公司环境，不知道因为什么导致的
