### ISSUE TITLE
[Bug] Tailwindcss doesn't work when ssr enabled

### ISSUE THREAD

**Issue by burakakca** [umijs/umi#12636]
How can I solve this problem.

![image](https://github.com/user-attachments/assets/8ebaf982-591c-42b8-9850-c80ab6a24e57)

```js
module.exports = {
  content: [
    './src/pages/**/*.tsx',
    './src/components/**/*.tsx',
    './src/layouts/**/*.tsx',
  ],
}
```

```ts
import { defineConfig } from "@umijs/max";

export default defineConfig({
	ssr: {},
	npmClient: "pnpm",
	tailwindcss: {},
	reactQuery: {},
  routes: [
		{ path: '/', redirect: '/kit/products' },
    { path: "/kit/products", component: "@/pages/kit/products" },
		// { path: "/docs", component: "@/pages/docs" },
  ],
});
```

```bash
max dev

info  - [你知道吗？] 如果想点击组件跳转至编辑器源码位置，可尝试新出的 clickToComponent 配置项，详见 https://umijs.org/docs/api/config#clicktocomponent
warn  - SSR feature is in beta, may be unstable
Mako https://makojs.dev is a new fast Rust based bundler from us, which is heavily optimized for umi and much faster than webpack. Visit https://makojs.dev/docs/getting-started#bundle-with-umi for more details if you want to give it a try.
info  - [plugin: ./node_modules/.pnpm/@umijs+plugins@4.3.11_@babel+core@7.25.2_@types+react-dom@18.3.0_@types+react@18.3.3_antd@4.2_daoykeix4hyj63bqvg6kbmzzbq/node_modules/@umijs/plugins/dist/react-query] [reactQuery] use local package, version: 4.36.1
info  - Umi v4.3.11
info  - Preparing...
wait  - [SSR] Compiling...
warn  - SSR feature is in beta, may be unstable
info  - [MFSU][eager] worker init, takes 482ms
fatal - Error: ERROR in ./src/.umi/umi.server.ts 12:0-102
Module not found: Error: Can't resolve '/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/src/.umi/plugin-tailwindcss/tailwind.css' in '/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/src/.umi'

umi compiled with 1 error
    at Watching.handler (/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-webpack@4.3.11_type-fest@0.20.2_typescript@5.5.4_webpack@5.93.0/node_modules/@umijs/bundler-webpack/dist/build.js:82:79)
    at /home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-webpack@4.3.11_type-fest@0.20.2_typescript@5.5.4_webpack@5.93.0/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:93594:9
    at Hook.eval [as callAsync] (eval at create (/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-utils@4.3.11/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:24:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-utils@4.3.11/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4851)
    at Watching._done (/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-webpack@4.3.11_type-fest@0.20.2_typescript@5.5.4_webpack@5.93.0/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:93590:28)
    at onCompiled (/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-webpack@4.3.11_type-fest@0.20.2_typescript@5.5.4_webpack@5.93.0/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:93470:19)
    at /home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-webpack@4.3.11_type-fest@0.20.2_typescript@5.5.4_webpack@5.93.0/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:63704:17
    at Hook.eval [as callAsync] (eval at create (/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-utils@4.3.11/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-utils@4.3.11/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4851)
    at /home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-webpack@4.3.11_type-fest@0.20.2_typescript@5.5.4_webpack@5.93.0/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:63700:33
    at finalCallback (/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-webpack@4.3.11_type-fest@0.20.2_typescript@5.5.4_webpack@5.93.0/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:59981:11)
    at /home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-webpack@4.3.11_type-fest@0.20.2_typescript@5.5.4_webpack@5.93.0/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:60286:11
    at Hook.eval [as callAsync] (eval at create (/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-utils@4.3.11/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-utils@4.3.11/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4851)
    at /home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-webpack@4.3.11_type-fest@0.20.2_typescript@5.5.4_webpack@5.93.0/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:60279:38
    at eval (eval at create (/home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.pnpm/@umijs+bundler-utils@4.3.11/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:17:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
fatal - A complete log of this run can be found in:
fatal - /home/burak/Desktop/hotwire/rails-7-fullstack/umijs/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

```

**Comment by tylerrrkd** [comment]
the same issue with, have tried to upgrade to the latest `@umijs/max` but does not work

**Comment by daizeyao** [comment]
有什么临时的解决方案吗

**Comment by deng-yc** [comment]
+1
