### ISSUE TITLE
[Feature Request] Package subpath './package.json' is not defined by "exports" in @umijs/max with pro-components@beta (2.8.0)

### ISSUE THREAD

**Issue by s952787097** [umijs/umi#12747]
在@umijs/max中尝试使用beta版本（2.8.0）的@ant-design/pro-components，在"postinstall" : "max setup", 报错。

---
错误信息如下：
---
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/fb37cb95-8d51-4e8e-9dc5-39c9c1d3e4d2">

>  fatal - Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in [路径已省略]/node_modules/.pnpm/@umijs+plugins@4.3.27_@babel+core@7.25.8_antd@4.24.16_dva@2.5.0-beta.2_rc-field-form@2.4.0_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/pro-components/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
    at resolveExports (node:internal/modules/cjs/loader:556:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:596:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1014:27)
    at Function.mod._resolveFilename ([路径已省略]/node_modules/.pnpm/umi@4.3.27_@babel+core@7.25.8_eslint@8.35.0_prettier@3.3.3_react-dom@18.3.1_react@18.3.1_styl_va6ei2r5uqytswunwrj5oay7qy/node_modules/umi/dist/service/requireHook.js:13:26)
    at Function.resolve (node:internal/modules/cjs/helpers:125:19)
    at getPkgPath ([路径已省略]/node_modules/.pnpm/@umijs+plugins@4.3.27_@babel+core@7.25.8_antd@4.24.16_dva@2.5.0-beta.2_rc-field-form@2.4.0_react-dom@18.3.1_react@18.3.1/node_modules/@umijs/plugins/dist/layout.js:102:45)
    at layout_default ([路径已省略]/node_modules/.pnpm/@umijs+plugins@4.3.27_@babel+core@7.25.8_antd@4.24.16_dva@2.5.0-beta.2_rc-field-form@2.4.0_react-dom@18.3.1_react@18.3.1/node_modules/@umijs/plugins/dist/layout.js:104:52) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

---
目前尝试方法
---
在`/node_modules/.pnpm/@umijs+plugins@4.3.27_@babel+core@7.25.8_antd@4.24.16_dva@2.5.0-beta.2_rc-field-form@2.4.0_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/pro-components/package.json`

文件中, 在exports中增加`"./package.json": "./package.json"`,如下图：

<img width="409" alt="image" src="https://github.com/user-attachments/assets/a6b38a3f-69a6-4c7c-9ae2-581e927cd85e">

---
导致此问题的位置大致位置
---
`/node_modules/.pnpm/@umijs+plugins@4.3.27_@babel+core@7.25.8_antd@4.24.16_dva@2.5.0-beta.2_rc-field-form@2.4.0_react-dom@18.3.1_react@18.3.1/node_modules/@umijs/plugins/dist/layout.js:104:52`
<img width="873" alt="image" src="https://github.com/user-attachments/assets/ae6ad66a-a71c-4b37-89c4-b61094cba8ef">

**Comment by s952787097** [comment]
https://nodejs.org/api/packages.html#package-entry-points

![image](https://github.com/user-attachments/assets/e984d24c-067b-480c-ad7b-69065934e659)

**Comment by Jinbao1001** [comment]
`@ant-design/pro-components@2.8.1` 已经在 `package.json` 中删除 `exports` 字段.
