### ISSUE TITLE
@babel/runtime 版本是否可以改为 7.x？

### ISSUE THREAD

**Issue by afc163** [umijs/umi#12803]
目前是写死的，容易和应用自身的 @babel/runtime 依赖声明产生多版本，增加不必要的体积：https://github.com/umijs/umi/blob/9c76d40101bffb69178cc53b5fa78a1abc7059db/packages/babel-preset-umi/package.json#L24

比如这里：https://github.com/ant-design/x/actions/runs/12002837217/job/33455385061?pr=229

```
error - Error: @babel/runtime
  Multiple versions of @babel/runtime found:
    7.23.6 ./~/@umijs/babel-preset-umi/~/@babel/runtime from ./components/sender/index.tsx
    7.26.0 ./~/@babel/runtime from ./~/rc-util/lib/pickAttrs.js

Check how you can resolve duplicate packages: 
https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle

    at /home/runner/work/x/x/node_modules/@madccc/duplicate-package-checker-webpack-plugin/lib/index.js:187:18
    at Array.map (<anonymous>)
    at /home/runner/work/x/x/node_modules/@madccc/duplicate-package-checker-webpack-plugin/lib/index.js:169:27
    at _next0 (eval at create (/home/runner/work/x/x/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7744), <anonymous>:8:1)
    at eval (eval at create (/home/runner/work/x/x/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7744), <anonymous>:23:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error: script "compile" exited with code 1
Error: Process completed with exit code 1.
```

@babel/runtime 本身好像没出现过问题，是否有必要锁死？

**Comment by Jinbao1001** [comment]
let me cc

**Comment by afc163** [comment]
https://github.com/ant-design/x/pull/229 is pending for this issue.

**Comment by Jinbao1001** [comment]
锁死的背景历史有点久远, 目前不太好考察, 但是肯定是因为某些具体问题锁死的.

目前 `babel/core` 等模块在`umi`是预编译模式, 放开可能会导致后续版本更迭导致 `core` 与 `runtime` 不兼容的情况出现.

插件配置下 `exclude` 先忽略 `babel-runtime`?

**Comment by afc163** [comment]
@Jinbao1001 哪个配置？文档里我没找到。

**Comment by afc163** [comment]
这个有进展么？

**Comment by afc163** [comment]
ping~

**Comment by xierenyuan** [comment]
+1

**Comment by jk4235** [comment]
7.23.6有漏洞了，需尽快升级到7.27
