### ISSUE TITLE
subscrpitions中history.listen方法被多次调用。

### ISSUE THREAD

**Issue by hopperhuang** [umijs/umi#129]
bug用例地址：[https://github.com/hopperhuang/umi-bug](url)

复现步骤，从首页进入/list页面。然后从/list页面回退到首页，控制台中，histroy对象被打印了两次，也就是说count.js中的subscriptions被调用了两次，history.listen方法被调用了两次。

expected: 控制台只打印出一个hisitory对象，count.js中的subscriptions只被调用一次

**Comment by xiaohuoni** [comment]
@hopperhuang 请问你的umi版本是多少的，我的是rc20的，下了你的代码。C:\Users\admin\AppData\Roaming\npm\node_modules\umi\node_modules\umi-build-dev\lib\getPlugins.js:50
        throw new Error(`Plugin ${p} don't exists.`);
              ^
Error: Plugin umi-plugin-dva don't exists.
    at plugins.map.p (C:\Users\admin\AppData\Roaming\npm\node_modules\umi\node_modules\umi-build-dev\lib\getPlugins.js:50:15)
    at Array.map (<anonymous>)
    at pluginToPath (C:\Users\admin\AppData\Roaming\npm\node_modules\umi\node_modules\umi-build-dev\lib\getPlugins.js:33:20)
    at _default (C:\Users\admin\AppData\Roaming\npm\node_modules\umi\node_modules\umi-build-dev\lib\getPlugins.js:56:27)
    at Service.initPlugins (C:\Users\admin\AppData\Roaming\npm\node_modules\umi\node_modules\umi-build-dev\lib\Service.js:286:44)
    at Service.dev (C:\Users\admin\AppData\Roaming\npm\node_modules\umi\node_modules\umi-build-dev\lib\Service.js:141:10)
    at Object.dev [as default] (C:\Users\admin\AppData\Roaming\npm\node_modules\umi\node_modules\umi-build-dev\lib\dev.js:14:18)
    at _default (C:\Users\admin\AppData\Roaming\npm\node_modules\umi\lib\dev.js:28:50)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\umi\lib\scripts\realDev.js:14:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)

**Comment by hopperhuang** [comment]
@xiaohuoni 你把umi-plugin-dva装了再试试看。

**Comment by xiaohuoni** [comment]
@sorrycc 这个bug是在切换到list的时候，报一个错误之后才会调用两次的。
错误如下：
<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions.

首次执行npm start才会，刷新一下页面，不会再报错，就不会调用两次了

**Comment by xiaohuoni** [comment]
@sorrycc @hopperhuang 安装了可以。但是我不理解，在.umirc.js中设置了
```js
module.exports = {
  plugins: ['umi-plugin-dva'],
};
```
为什么还要安装umi-plugin-dva？

**Comment by sorrycc** [comment]
这是业界约定吧，所有插件机制都需要自行安装依赖的，.umirc.js 里设置了仅仅是告诉 umi 在执行时装载这个插件。
