### ISSUE TITLE
参照官网快速上手文档操作构建应用时失败

### ISSUE THREAD

**Issue by dkvirus** [umijs/umi#131]
- 1. 参照[官网快速上手](https://umijs.org/docs/zh-Hans/getting-started.html)进行操作；
- 2. 构建应用时报错如下；
- 3. node 版本 :8.0.0；
- 4. Umi 版本：1.0.0-rc.20（npm 自动安装的版本）。
```
D:\study\umi\myapp>umi build
Failed to compile.

Failed to minify the bundle. Error: umi.e15fbc0c.js from UglifyJs
Unexpected character '`' [umi.e15fbc0c.js:2355,11]
    at doneHandler (D:\software\nvm\v8.0.0\node_modules\umi\node_modules\af-webpack\lib\build.js:93:27)
    at emitRecords.err (D:\software\nvm\v8.0.0\node_modules\umi\node_modules\webpack\lib\Compiler.js:265:13)
    at Compiler.emitRecords (D:\software\nvm\v8.0.0\node_modules\umi\node_modules\webpack\lib\Compiler.js:371:38)
    at emitAssets.err (D:\software\nvm\v8.0.0\node_modules\umi\node_modules\webpack\lib\Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (D:\software\nvm\v8.0.0\node_modules\umi\node_modules\webpack\lib\Compiler.js:364:12)
    at next (D:\software\nvm\v8.0.0\node_modules\umi\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (D:\software\nvm\v8.0.0\node_modules\umi\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (D:\software\nvm\v8.0.0\node_modules\umi\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (D:\software\nvm\v8.0.0\node_modules\umi\node_modules\webpack\lib\Compiler.js:361:9)
    at require.forEach.err (D:\software\nvm\v8.0.0\node_modules\umi\node_modules\webpack\lib\Compiler.js:350:15)
    at D:\software\nvm\v8.0.0\node_modules\umi\node_modules\async\dist\async.js:473:16
    at iteratorCallback (D:\software\nvm\v8.0.0\node_modules\umi\node_modules\async\dist\async.js:1050:13)
    at D:\software\nvm\v8.0.0\node_modules\umi\node_modules\async\dist\async.js:958:16
    at D:\software\nvm\v8.0.0\node_modules\umi\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
Read more here: http://bit.ly/2tRViJ9
```

**Comment by sorrycc** [comment]
不压缩正常？

```bash
$ set COMPRESS=none&&umi build
```

**Comment by dkvirus** [comment]
@sorrycc 使用你提供的指令 `$ set COMPRESS=none&&umi build` 打包正常了。

在阅读[官方文档](https://umijs.org/docs/en/getting-started.html)中总体体验爽的不行，另外，发现两处拼写错误：

1. [定制主题](https://umijs.org/docs/en/theme.html)

![image](https://user-images.githubusercontent.com/29170168/36544801-4d2ae790-1822-11e8-9e52-26e14860071e.png)

2. [在页面间跳转](https://umijs.org/docs/en/navigate-between-pages.html)

![image](https://user-images.githubusercontent.com/29170168/36544854-6f8bce26-1822-11e8-9471-1607ea8eeef9.png)

**Comment by sorrycc** [comment]
umi build 和文档的问题都已修复。
