### ISSUE TITLE
umi dev 出现Duplicate plugin/preset detected

### ISSUE THREAD

**Issue by superlbr** [umijs/umi#1334]
ERROR  Failed to compile with 1 errors                                         14:58:25

 error  in ./src/pages/.umi/umi.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
    at assertNoDuplicates (/Users/dva/Documents/js/antd-admin/node_modules/@babel/core/lib/config/config-descriptors.js:205:13)
    at createDescriptors (/Users/dva/Documents/js/antd-admin/node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
    at createPluginDescriptors (/Users/dva/Documents/js/antd-admin/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/Users/dva/Documents/js/antd-admin/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
    at cachedFunction (/Users/dva/Documents/js/antd-admin/node_modules/@babel/core/lib/config/caching.js:33:19)

**Comment by sorrycc** [comment]
给可复现的库。

**Comment by superlbr** [comment]
https://github.com/zuiidea/antd-admin/tree/develop

**Comment by sorrycc** [comment]
估计 key 冲突了，[这几行](https://github.com/zuiidea/antd-admin/blob/develop/.umirc.js#L93-L102)删了吧。

相关 PR: https://github.com/umijs/umi/pull/1297
