### ISSUE TITLE
sudo npm i umi -g  安装失败，已经是sudo权限 

### ISSUE THREAD

**Issue by tianlinzx** [umijs/umi#137]
> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/local/lib/node_modules/umi/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> antd-mobile@2.1.6 postinstall /usr/local/lib/node_modules/umi/node_modules/antd-mobile
> node scripts/update-tip.js

fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/umi/node_modules/antd-mobile/lib/_util/version.json'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.writeFileSync (fs.js:1322:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/umi/node_modules/antd-mobile/scripts/update-tip.js:59:6)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antd-mobile@2.1.6 postinstall: `node scripts/update-tip.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd-mobile@2.1.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/calvin/.npm/_logs/2018-02-24T15_17_28_519Z-debug.log

**Comment by sorrycc** [comment]
@zhang740 看下，antd-mobile 的 postscript 的问题。

**Comment by sorrycc** [comment]
最好全程都别用 sudo，用 nvm 安装 node，然后用这个 node 和 npm 去安装，就不会有权限问题。

**Comment by tiodot** [comment]
同样遇到一个安装问题
![image](https://user-images.githubusercontent.com/5645617/36726986-9201771c-1bf6-11e8-93a6-d6c1da7936ae.png)

**Comment by sorrycc** [comment]
试试 cnpm 。

```bash
$ npm install cnpm -g --registry=https://registry.npm.taobao.org
$ cnpm i umi -g
```
