### ISSUE TITLE
在jenkins环境下build报错

### ISSUE THREAD

**Issue by xjchenhao** [umijs/umi#1428]
在本地build是没问题的，但在服务器上使用jenkins构建就不行了。

错误信息如下：
```
> egg-admin-service@1.0.0 build /usr/local/eas
> APP_ROOT=$PWD/app/assets HTML=none umi build


Compiling

● webpack █████████████████████████ building modules (34%) 205/215 modules 10 active
  node_modules/core-js/modules/_array-species-constructor.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-admin-service@1.0.0 build: `APP_ROOT=$PWD/app/assets HTML=none umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-admin-service@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-08T03_30_36_830Z-debug.log


root@daba41d4ff4f:/usr/local/eas# cat /root/.npm/_logs/2018-11-08T03_30_36_830Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle egg-admin-service@1.0.0~prebuild: egg-admin-service@1.0.0
6 info lifecycle egg-admin-service@1.0.0~build: egg-admin-service@1.0.0
7 verbose lifecycle egg-admin-service@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle egg-admin-service@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/eas/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle egg-admin-service@1.0.0~build: CWD: /usr/local/eas
10 silly lifecycle egg-admin-service@1.0.0~build: Args: [ '-c', 'APP_ROOT=$PWD/app/assets HTML=none umi build' ]
11 silly lifecycle egg-admin-service@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle egg-admin-service@1.0.0~build: Failed to exec build script
13 verbose stack Error: egg-admin-service@1.0.0 build: `APP_ROOT=$PWD/app/assets HTML=none umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid egg-admin-service@1.0.0
15 verbose cwd /usr/local/eas
16 verbose Linux 3.10.0-514.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error egg-admin-service@1.0.0 build: `APP_ROOT=$PWD/app/assets HTML=none umi build`
22 error Exit status 1
23 error Failed at the egg-admin-service@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

--- 

工程地址：[https://github.com/xjchenhao/egg-admin-service](https://github.com/xjchenhao/egg-admin-service)

**Comment by JonasGao** [comment]
我们之前也遇到类似问题。可以仔细检查一下，是否有文件大小写问题

当时我们的情况是，本地 build OK，本地是 mac 环境
线上 build 报错。线上 build 是 linux 环境

后来发现是文件名为 AbC.tsx 但是代码是 import xxx from "....../abC"

修改后，就 build 成功了

**Comment by xjchenhao** [comment]
> 我们之前也遇到类似问题。可以仔细检查一下，是否有文件大小写问题
> 
> 当时我们的情况是，本地 build OK，本地是 mac 环境
> 线上 build 报错。线上 build 是 linux 环境
> 
> 后来发现是文件名为 AbC.tsx 但是代码是 import xxx from "....../abC"
> 
> 修改后，就 build 成功了

这么神奇吗？大海捞针的感觉 😂

**Comment by Dollyn** [comment]
遇到类似的问题，本地打包正常，服务器上打包报错，错误信息没用，不知道怎么查

**Comment by Dollyn** [comment]
发现了一个方法貌似有点用：服务端用npm run start这时候会把真实的错误信息报出来。 
结果还真的也是大小写的问题。。。。


希望build也能优化一下，报错信息能明确一点，报出具体哪里有错。

**Comment by xjchenhao** [comment]
这个issuse由作者自己关闭吧，希望他能看到，解决一下。。

**Comment by sorrycc** [comment]
有需要的自行加 [case-sensitive-paths-webpack-plugin](https://www.npmjs.com/package/case-sensitive-paths-webpack-plugin) 插件。

**Comment by xiaohuoni** [comment]
👀

**Comment by sorrycc** [comment]
在 #1288 跟进。

**Comment by JonasGao** [comment]
@xjchenhao 突然想起来可以 debug build 过程。之前问过。。。。
在你的 CI 环境运行 `DEBUG=umi* umi build` 就可以了，会输出具体哪里编译失败
