### ISSUE TITLE
umi dev报错

### ISSUE THREAD

**Issue by buyou0821** [umijs/umi#1554]
环境:
系统版本: macos 10.13.3
node: 8.12.0
npm: 6.4.1
umi: 2.2.7
问题：
运行umi dev报错:
```
module.js:550
    throw err;
    ^
Error: Cannot find module 'ajv/lib/compile/equal'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/x/Documents/temp/umitmp/node_modules/table/dist/validateConfig.js:2:13)
    at Module._compile (module.js:653:30)
    at Module._compile (/Users/x/Documents/temp/umitmp/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (/Users/x/Documents/temp/umitmp/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:566:32)
```

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/1556

**Comment by sorrycc** [comment]
Duplicated #1556
