### ISSUE TITLE
脚手架新建umi项目，yarn过后，start报错了

### ISSUE THREAD

**Issue by weizhanzhan** [umijs/umi#1563]
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'ajv/lib/compile/equal'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\G\umi-admin\node_modules\webpackbar\node_modules\table\dist\validateConfig.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (D:\G\umi-admin\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (D:\G\umi-admin\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by weizhanzhan** [comment]
不止我自己，我同事也是

**Comment by weizhanzhan** [comment]
@sorrycc 可以给个解决方案嘛

**Comment by yutingzhao1991** [comment]
https://github.com/epoberezkin/ajv/issues/889

**Comment by sorrycc** [comment]
ajv 已经解决这个问题了，清下缓存，比如 `yarn cache clean` 和 `npm cache clean`，删除 node_modules 后重试试试。

**Comment by weizhanzhan** [comment]
> ajv 已经解决这个问题了，清下缓存，比如 `yarn cache clean` 和 `npm cache clean`，删除 node_modules 后重试试试。

谢谢

**Comment by weizhanzhan** [comment]
> [epoberezkin/ajv#889](https://github.com/epoberezkin/ajv/issues/889)

谢谢
