### ISSUE TITLE
path.replace is not a function

### ISSUE THREAD

**Issue by dargonpaul** [umijs/umi#1715]
使用antd pro2 ，在开发是，自动编译的时候报错：path.replace is not a function
在升级"umi-plugin-react": "^1.2.4" 以及"umi": "^2.2.9"后出现这个问题。

**Comment by yutingzhao1991** [comment]
ant-design-pro 最新的代码？我试了下没问题，能够提供下复现的仓库吗？

**Comment by dargonpaul** [comment]
@yutingzhao1991  我在不停的触发编译，大概不停修改保存试了5分钟了，又没有复现出来，等我复现出来再提供详细的报错信息。

**Comment by yoyooyooo** [comment]
前几天我也遇到过，是webpackBar里的一个文件，不知道你是不是。
我是生成了文件在public文件夹下，会触发重新编译，然后就报错了，后面不生成在public就没报错了。

刚试了下复制了个东西进public文件夹，又报错了
_webpackbar@3.1.3@webpackbar\dist\utils\index.js:57
  return path.replace(cwd, '');
              ^
TypeError: path.replace is not a function
    at shortenPath (D:\test\socket.io\node_modules\_webpackbar@3.1.3@webpackbar\dist\utils\index.js:57:15)
    at D:\test\socket.io\node_modules\_webpackbar@3.1.3@webpackbar\dist\plugin.js:182:43
    at SyncHook.eval (eval at create (D:\test\socket.io\node_modules\_tapable@1.1.1@tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Watchpack.watcher.compiler.watchFileSystem.watch (D:\test\socket.io\node_modules\_webpack@4.19.0@webpack\lib\Watching.js:139:33)
    at Object.onceWrapper (events.js:273:13)
    at Watchpack.emit (events.js:182:13)
    at Watchpack._onChange (D:\test\socket.io\node_modules\_watchpack@1.6.0@watchpack\lib\watchpack.js:118:7)
    at Watchpack.<anonymous> (D:\test\socket.io\node_modules\_watchpack@1.6.0@watchpack\lib\watchpack.js:109:8)
    at Watcher.emit (events.js:182:13)
    at DirectoryWatcher.<anonymous> (D:\test\socket.io\node_modules\_watchpack@1.6.0@watchpack\lib\DirectoryWatcher.js:238:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by Fntys** [comment]
最近经常遇到
这是日志：
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.14.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ant-design-pro@2.1.1~prestart: ant-design-pro@2.1.1
6 info lifecycle ant-design-pro@2.1.1~start: ant-design-pro@2.1.1
7 verbose lifecycle ant-design-pro@2.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.1.1~start: PATH: D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\work\met_account\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\microsoft shared\TigerKin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Microsoft VS Code\bin;C:\WINDOWS\System32\OpenSSH\;D:\nodejs\;C:\Program Files (x86)\Yarn\bin\;D:\nodejs\node_global\;C:\Users\admin\AppData\Local\Programs\Python\Python35\;C:\Ruby23-x64\bin;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Users\admin\AppData\Local\atom\bin;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;D:\Microsoft VS Code\bin;D:\zhaoye\Microsoft VS Code\bin;D:\zhaoye\WebStorm 2018.3\bin;D:\zhaoye\Fiddler;C:\Users\admin\AppData\Roaming\npm;C:\Users\admin\AppData\Local\Yarn\bin;
9 verbose lifecycle ant-design-pro@2.1.1~start: CWD: D:\work\met_account
10 silly lifecycle ant-design-pro@2.1.1~start: Args: [ '/d /s /c', 'cross-env APP_TYPE=site umi dev' ]
11 silly lifecycle ant-design-pro@2.1.1~start: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.1.1~start: Failed to exec start script
13 verbose stack Error: ant-design-pro@2.1.1 start: `cross-env APP_TYPE=site umi dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid ant-design-pro@2.1.1
15 verbose cwd D:\work\met_account
16 verbose Windows_NT 10.0.17134
17 verbose argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.14.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.1.1 start: `cross-env APP_TYPE=site umi dev`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

报错信息：
return path.replace(cwd, '');
              ^

TypeError: path.replace is not a function
    at shortenPath (D:\work\met_account\node_modules\webpackbar\dist\utils\index.js:57:15)
    at D:\work\met_account\node_modules\webpackbar\dist\plugin.js:182:43
    at SyncHook.eval (eval at create (D:\work\met_account\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Watchpack.watcher.compiler.watchFileSystem.watch (D:\work\met_account\node_modules\webpack\lib\Watching.js:139:33)
    at Object.onceWrapper (events.js:273:13)
    at Watchpack.emit (events.js:182:13)
    at Watchpack._onChange (D:\work\met_account\node_modules\watchpack\lib\watchpack.js:118:7)
    at Watchpack.<anonymous> (D:\work\met_account\node_modules\watchpack\lib\watchpack.js:109:8)
    at Watcher.emit (events.js:182:13)
    at DirectoryWatcher.<anonymous> (D:\work\met_account\node_modules\watchpack\lib\DirectoryWatcher.js:238:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.1.1 start: `cross-env APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     d:\nodejs\node_cache\_logs\2018-12-29T07_50_28_922Z-debug.log

**Comment by sorrycc** [comment]
有复现步骤了再 reopen 。

**Comment by sorrycc** [comment]
webpackbar\dist\utils\index.js 打印下 path 看看是什么。

**Comment by boxcc** [comment]
@sorrycc 是一串数字

**Comment by dargonpaul** [comment]
> webpackbar\dist\utils\index.js 打印下 path 看看是什么。

我突然想到，各位主创平时用的都是MAC OS ， 所以觉得可能是系统引起的，然后叫一个同事换了用WSL的nodejs，之后这个崩溃问题好像就没出现了，还是期待针对window系统做个彻底的解决方案。

**Comment by Web-Delevan** [comment]
各位大佬，这个问题解决了么？
