### ISSUE TITLE
Gracefully handle xsel missing

### ISSUE THREAD

**Issue by theshire-io** [umijs/umi#1741]
It shouldn't throw an unhandled exception when trying to copy the server url to the clipboard. 
When running inside a Docker container installing `xsel` doesn't solve this because you also need to pull in an X server.

```
(node:35) UnhandledPromiseRejectionWarning: Error: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel
    at handler (/app/node_modules/clipboardy/lib/linux.js:7:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:35) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sorrycc** [comment]
It's the problem of [clipboardy](https://github.com/sindresorhus/clipboardy/issues?q=is%3Aissue+sort%3Aupdated-desc+xsel+is%3Aclosed).

**Comment by theshire-io** [comment]
@sorrycc 

My understanding is that clipboardy legitimately throws an exception because it can't perform a "copy to clipboard" (clipboard on Linux are part of X11). So it throws to let Umi know about it. Umi should then simply wrap the use of clipboardy with a `try/catch` and perhaps print a message "failed to use the clipboard". This way you don't get an unhandled exception error.
