### ISSUE TITLE
umi g page index 执行报错

### ISSUE THREAD

**Issue by wulinjie122** [umijs/umi#1834]
我用的是umi.js版本2.4.2，node.js是v8.11.4，npm版本是5.6.0，版本切换是用的nodist.js，但是初次使用按照教程，报错如下，实际该路径下存在文件C:\Program Files (x86)\Nodist\bin\node_modules\umi\node_modules\umi-build-dev\
template\generators\page.js
---
>umi g page index
events.js:183 throw er; // Unhandled 'error' event
      ^
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist
: C:\Program Files (x86)\Nodist\bin\node_modules\umi\node_modules\umi-build-dev\
template\generators\page.js
    at EditionInterface.exports.copy (C:\Program Files (x86)\Nodist\bin\node_mod
ules\umi\node_modules\mem-fs-editor\lib\actions\copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Program Files (x86)\Nodi
st\bin\node_modules\umi\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)

    at Generator.writing (C:\Program Files (x86)\Nodist\bin\node_modules\umi\nod
e_modules\umi-build-dev\lib\plugins\commands\generate\page.js:43:15)
    at Object.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\umi\no
de_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Program Files (x86)\Nodist\bin\node_modules\umi\node_modules\run-async
\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Program Files (x86)\Nodist\bin\node_modules\umi\node_modules\run-async
\index.js:24:19
    at self.env.runLoop.add.completed (C:\Program Files (x86)\Nodist\bin\node_mo
dules\umi\node_modules\yeoman-generator\lib\index.js:425:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
---

**Comment by yutingzhao1991** [comment]
看了下这个文件是有的，试试重装下 node_modules  看看、

PS: 现在有区块能够更方便的初始化页面，比如 `umi block add blank`。

**Comment by wulinjie122** [comment]
我卸载了yarn，重新安装最新版本yarn，然后执行yarn global add umi，然后将 C:\Program Files (x86)\Nodist\bin\bin 添加到window 7环境变量，重新打开命令窗口执行umi g page index就可以了。

**Comment by AlexZhong22c** [comment]
路径尽量不能带括号，我去了括号就行了，坑死我了......
