### ISSUE TITLE
af-webpack中使用的cssnano需要更新

### ISSUE THREAD

**Issue by leiysky** [umijs/umi#1883]
postcss-loader和mini-css-extract-plugin有冲突，原因是cssnano。

https://github.com/postcss/postcss-loader/issues/392
https://github.com/cssnano/cssnano/issues/618
在cssnano 4.1.8 中已修复。

**Comment by leiysky** [comment]
场景是在`ant-design-pro`中使用`react-monaco-editor`，编译时报错：

```
 error  in ./node_modules/monaco-editor/esm/vs/editor/standalone/browser/quickOpen/quickOutline.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/index.js):
TypeError: exports[name].indexOf is not a function
    at exportScopedName (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:50:25)
    at localizeNode (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:64:28)
    at Array.map (<anonymous>)
    at localizeNode (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:60:38)
    at traverseNode (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:78:20)
    at Array.map (<anonymous>)
    at traverseNode (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:84:38)
    at Array.map (<anonymous>)
    at traverseNode (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:84:38)
    at /Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:103:25
    at callback (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/node_modules/postcss/lib/container.es6:198:28)
    at callback (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/node_modules/postcss/lib/container.es6:109:26)
    at Root.callback [as each] (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/node_modules/postcss/lib/container.es6:77:22)
    at Root.each (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/node_modules/postcss/lib/container.es6:108:21)
    at Root.walk [as walkRules] (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/node_modules/postcss/lib/container.es6:196:25)
    at /Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:101:9
    at runLoaders (/Users/leiysky/work/ttarch/archcloud/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/leiysky/work/ttarch/archcloud/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/leiysky/work/ttarch/archcloud/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/leiysky/work/ttarch/archcloud/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.<anonymous> (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/lib/loader.js:44:18)
    at /Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/lib/processCss.js:216:4

 @ ./node_modules/monaco-editor/esm/vs/editor/standalone/browser/quickOpen/quickOutline.js 18:0-28
 @ include-loader!./node_modules/monaco-editor/esm/vs/editor/editor.api.js
 @ ./node_modules/react-monaco-editor/lib/editor.js
 @ ./node_modules/react-monaco-editor/lib/index.js
 @ ./src/pages/CDS/ConfigDiff.tsx
 @ ./src/pages/CDS/Detail.tsx
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

 error  in ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/media/suggest.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/index.js):
TypeError: exports[name].indexOf is not a function
    at exportScopedName (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:50:25)
    at localizeNode (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:64:28)
    at Array.map (<anonymous>)
    at localizeNode (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:60:38)
    at traverseNode (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:78:20)
    at Array.map (<anonymous>)
    at traverseNode (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:84:38)
    at Array.map (<anonymous>)
    at traverseNode (/Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:84:38)
    at /Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:103:25
    at callback (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/node_modules/postcss/lib/container.es6:198:28)
    at callback (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/node_modules/postcss/lib/container.es6:109:26)
    at Root.callback [as each] (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/node_modules/postcss/lib/container.es6:77:22)
    at Root.each (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/node_modules/postcss/lib/container.es6:108:21)
    at Root.walk [as walkRules] (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/node_modules/postcss/lib/container.es6:196:25)
    at /Users/leiysky/work/ttarch/archcloud/node_modules/postcss-modules-scope/lib/index.js:101:9
    at runLoaders (/Users/leiysky/work/ttarch/archcloud/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/leiysky/work/ttarch/archcloud/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/leiysky/work/ttarch/archcloud/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/leiysky/work/ttarch/archcloud/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.<anonymous> (/Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/lib/loader.js:44:18)
    at /Users/leiysky/work/ttarch/archcloud/node_modules/css-loader/lib/processCss.js:216:4

 @ ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/suggestWidget.js 25:0-29
 @ ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/suggestController.js
 @ include-loader!./node_modules/monaco-editor/esm/vs/editor/editor.api.js
 @ ./node_modules/react-monaco-editor/lib/editor.js
 @ ./node_modules/react-monaco-editor/lib/index.js
 @ ./src/pages/CDS/ConfigDiff.tsx
 @ ./src/pages/CDS/Detail.tsx
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js
```
