### ISSUE TITLE
SecurityError: localStorage is not available for opaque origins

### ISSUE THREAD

**Issue by thunkli** [umijs/umi#1965]
```
lijinbiao@21410 ~/D/w/a/wms> npm test

> ant-design-pro@2.1.1 test /Users/lijinbiao/Documents/work/ant/wms
> PORT=4000 umi test

 PASS  src/pages/basicInfo/receipts/index.test.js
 FAIL  src/pages/basicInfo/receipts/index.test.tsx
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/umi-test/node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
      at Object.defineProperty.value (node_modules/lujing-fe-react-antdcommon/dist/index.js:94:50)
      at __webpack_require__ (node_modules/lujing-fe-react-antdcommon/dist/index.js:30:30)
      at Object.<anonymous> (node_modules/lujing-fe-react-antdcommon/dist/index.js:576:21)
      at __webpack_require__ (node_modules/lujing-fe-react-antdcommon/dist/index.js:30:30)
      at Object.defineProperty.value (node_modules/lujing-fe-react-antdcommon/dist/index.js:611:18)
      at __webpack_require__ (node_modules/lujing-fe-react-antdcommon/dist/index.js:30:30)
      at Object.defineProperty.value (node_modules/lujing-fe-react-antdcommon/dist/index.js:76:18)
      at node_modules/lujing-fe-react-antdcommon/dist/index.js:79:10
      at webpackUniversalModuleDefinition (node_modules/lujing-fe-react-antdcommon/dist/index.js:3:20)

Test Suites: 1 failed, 11 passed, 12 total
Tests:       44 passed, 44 total
Snapshots:   0 total
Time:        9.869s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

```js
// index.test.js
it('my test', () => {
  expect(2 + 2).toBe(4);
});
```

```typescript
// index.test.tsx
import * as enzyme from 'enzyme';
import * as React from 'react';
import Index from './index'; 
it('检查备注', () => {
  const wrapper = enzyme.shallow(<Index />);
  expect(wrapper.find(".query-ft").text()).toEqual('...')
});
```

```js
// jest.config.js
module.exports = {
  testURL: "http://localhost:4000",
  preset: 'jest-puppeteer',
};
```

**Comment by sorrycc** [comment]
非 umi 问题，搜下 [jest + localStorage](https://www.google.com/search?q=jest+localStorage&oq=jest+localStorage&aqs=chrome..69i57j0l5.1616j0j1&sourceid=chrome&ie=UTF-8) 吧。

**Comment by thunkli** [comment]
我搜了很多都是让修改testURL，但是不起作用
