### ISSUE TITLE
使用sass时报错ModuleNotFoundError

### ISSUE THREAD

**Issue by twilroad** [umijs/umi#1988]
版本: umi: 2.5.0

报错信息：
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve '../../assets/images/templateCenter/16pxWancheng.svg' in 'D:\projects\designers\src'
    at factory.create (D:\projects\designers\node_modules\webpack\lib\Compilation.js:823:10)
    at factory (D:\projects\designers\node_modules\webpack\lib\NormalModuleFactory.js:397:22)
    at resolver (D:\projects\designers\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (D:\projects\designers\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at D:\projects\designers\node_modules\neo-async\async.js:2825:7
    at D:\projects\designers\node_modules\neo-async\async.js:6886:13
    at normalResolver.resolve (D:\projects\designers\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (D:\projects\designers\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
    at hook.callAsync (D:\projects\designers\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\projects\designers\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)

 @ ./src/pages/.umi/umi.js 44:0-28
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js
```

补充：
只要入口scss文件和import进来的scss文件不在同一级目录，就会出现这个bug：
![image](https://user-images.githubusercontent.com/5193767/52935148-8d93e600-3393-11e9-9314-4418982120bd.png)

**Comment by sorrycc** [comment]
新 bug？umi@2.4.x 是好的？

**Comment by sorrycc** [comment]
给可复现例子。

**Comment by twilroad** [comment]
压缩包可以么？
[test.zip](https://github.com/umijs/umi/files/2874513/test.zip)
