### ISSUE TITLE
npm test时出现的错误，npm start没问题，不知道怎么纠正？

### ISSUE THREAD

**Issue by eruca** [umijs/umi#2076]
```jsx
import renderer from 'react-test-renderer';

import GlobalHeader from './GlobalHeader';

describe('GlobalHeader can work', () => {
    it('GlobalHeader render', () => {
        const wrapper = renderer.create(<GlobalHeader />);

        expect(wrapper.root.children.length).toBe(1);
    });
});
```

```bash
FAIL  src/layouts/__tests__/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/nick/Project/king/node_modules/_umi@2.6.1@umi/lib/link.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Link } from 'react-router-dom';
                                                                                                    ^

    SyntaxError: Unexpected token {

      1 | import React from 'react';
      2 | import { Icon, Menu } from 'antd';
    > 3 | import Link from 'umi/link';
        | ^
      4 |
      5 | import Flex from '../Flex';
      6 | import cfg from './config';

      at ScriptTransformer._transformAndBuildScript (node_modules/_@jest_transform@24.3.1@@jest/transform/build/ScriptTransformer.js:451:17)
      at ScriptTransformer.transform (node_modules/_@jest_transform@24.3.1@@jest/transform/build/ScriptTransformer.js:493:19)
      at Object.<anonymous> (src/components/GlobalHeader/GlobalHeader.jsx:3:1)
```

**Comment by sorrycc** [comment]
请提供可复现仓库。
