### ISSUE TITLE
umi-library使用esm编译typescript源码时报错

### ISSUE THREAD

**Issue by leftstick** [umijs/umi#2113]
## What happens?

With below `.umirc.library.js`, error occurred

```javascript
export default {
  file: 'test',
  esm: 'rollup'
}
```

**error**

```
ℹ  info      Clean dist directory
ℹ  info      Build esm with rollup
✖  error     Error: failed to open 'undefined'
    at parseTsConfig (/Users/admin/codes/umi-library-ts-test/node_modules/rollup-plugin-typescript2/src/parse-tsconfig.ts:18:9)
    at Object.options (/Users/admin/codes/umi-library-ts-test/node_modules/rollup-plugin-typescript2/src/index.ts:95:19)
    at applyOptionHook (/Users/admin/codes/umi-library-ts-test/node_modules/rollup/dist/rollup.js:18381:31)
    at Array.reduce (<anonymous>)
    at getInputOptions$1 (/Users/admin/codes/umi-library-ts-test/node_modules/rollup/dist/rollup.js:18399:41)
    at rollup (/Users/admin/codes/umi-library-ts-test/node_modules/rollup/dist/rollup.js:18443:30)
    at /Users/admin/codes/umi-library-ts-test/node_modules/umi-library/lib/rollup.js:68:51
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/admin/codes/umi-library-ts-test/node_modules/umi-library/lib/rollup.js:26:103)
    at _next (/Users/admin/codes/umi-library-ts-test/node_modules/umi-library/lib/rollup.js:28:194)
```

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

https://github.com/leftstick/umi-library-ts-test

## How To Reproduce
**Steps to reproduce the behavior:**
1. `yarn`, install dependencies
2. `yarn run build`, compile `src/index.ts` to dist

**Expected behavior**
1. Final bundle generated

## Context

- **Node Version**: v11.11.0
- **Platform**: macOS Mojave 10.14.3

**Comment by sorrycc** [comment]
ts 项目根目录需要有 `tsconfig.json`。

**Comment by leftstick** [comment]
好难受，但是真的，哈哈。谢了
