### ISSUE TITLE
jest 执行时报错： SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Veath** [umijs/umi#2159]
## What happens?
使用ant-design-pro搭建，添加单元测试 demo.test.js

步骤：1、创建demo.test.js
```js
 import Dafy from '@dafy/dafy-evoke-app';
   describe('fixedZero tests', () => {
     it('call dafy', () => {
          expect(new Dafy()).toEqual(10);
       });
   });
```
2、npm run test
3、 报错代码：
```js
 /Users//xxxxxx/system/node_modules/@babel/runtime/helpers/esm/objectSpread.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import defineProperty from "./defineProperty";
                                                                                                    ^^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:451:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:493:19)
      at Object.<anonymous> (node_modules/@dafy/dafy-evoke-app/lib/index.js:5:45)
```

**Comment by XingtianXin** [comment]
我在wepy框架下写小程序的单元测试，相同的错误报告。
请问您解决了么？

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/54935152-b000bc80-4f5a-11e9-850e-ab8631234b43.png)

404，`@dafy/dafy-evoke-app` 是私库？

**Comment by Veath** [comment]
@sorrycc 
是的， dafy-evoke-app 里面会使用到babel配置
dafy-evoke-app  中.babelrc 如下：
```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": "false"
      }
    ]
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "corejs": false,
      "helpers": true,
      "regenerator": true,
      "useESModules": true
    }],
    [
      "@babel/plugin-proposal-object-rest-spread"
    ],
    [
      "@babel/plugin-syntax-dynamic-import"
    ],
    "@babel/plugin-transform-object-assign"
  ],
  "env": {
    "production": {
      "plugins": [
        "transform-remove-console"
      ]
    },
    "es": {
      "presets": [
        [
          "@babel/preset-env",
          {
            "modules": false
          }
        ]
      ]
    },
    "cjs": {
      "presets": [
        [
          "@babel/preset-env",
          {
            "modules": "commonjs"
          }
        ]
      ]
    }
  }
}
```
编译后输入的文件头部有以下代码：
dafy-evoke-app  /lib/index.js
```js
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

var _objectSpread2 = _interopRequireDefault(require("@babel/runtime/helpers/esm/objectSpread"));

var _objectWithoutProperties2 = _interopRequireDefault(require("@babel/runtime/helpers/esm/objectWithoutProperties"));

var _classCallCheck2 = _interopRequireDefault(require("@babel/runtime/helpers/esm/classCallCheck"));

var _createClass2 = _interopRequireDefault(require("@babel/runtime/helpers/esm/createClass"));

Object.defineProperty(exports, "__esModule", {
  value: true
});

// 其余是功能代码忽略.......

```

当 test 执行到 
```js
import Dafy from '@dafy/dafy-evoke-app';
   describe('fixedZero tests', () => {
     it('call dafy', () => {
          expect(new Dafy()).toEqual(10);
       });
   });
```

错误提示：
```js
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import defineProperty from "./defineProperty";
                                                                                                    ^^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:451:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:493:19)
      at Object.<anonymous> (node_modules/@dafy/dafy-evoke-app/lib/index.js:5:45)
```

对应的位置是，
dafy-evoke-app  /lib/index.js
```js
var _objectSpread2 = _interopRequireDefault(require("@babel/runtime/helpers/esm/objectSpread"));
```

**Comment by sorrycc** [comment]
搞一个可复现的仓库吧。

**Comment by Veath** [comment]
@sorrycc 
请使用 npm i v-evoke-app -S

步骤还是上面的，谢谢。

**Comment by sorrycc** [comment]
等 https://github.com/umijs/umi/pull/2181 合并后，通过 --transform-include 解决。

```bash
$ umi test --transform-include @babel/runtime/helpers/esm
```

原因说到底其实是这个库生成代码不规范引起的，其输出的 [cjs 格式的代码](https://unpkg.com/v-evoke-app@1.0.1/lib/index.js)却引用了 esm 格式的 @babel/runtime helper 方法。

**Comment by Veath** [comment]
@sorrycc 
请问下怎么设置babel,能引用cjs模式的 helper

**Comment by sorrycc** [comment]
cjs 格式无需加 `@babel/runtime` 的 helper，内置打进去就好了。这是个 node 端用的，浏览器端用 esm 格式。

广告：建议用 umi-library 打包，这些情况都已经考虑进去了。
