### ISSUE TITLE
在最新的antd-design-pro项目中使用umi block add demo报错

### ISSUE THREAD

**Issue by Symboler** [umijs/umi#2201]
## What happens?

在最新的antd-design-pro项目中使用umi block add demo报错，文件引入了，但是修改路由失败了

## 最小可复现仓库
无

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

✖ Write route /demo to /Users/dtdream/Documents/newbee/ant-design-pro/config/config.js
✖  error     Error: Error: Line 37: Unexpected token ...
    at /Users/dtdream/Documents/l1449/ant-design-pro/node_modules/_umi-build-dev@1.7.7@umi-build-dev/lib/plugins/commands/block/index.js:381:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/dtdream/Documents/l1449/ant-design-pro/node_modules/_umi-build-dev@1.7.7@umi-build-dev/lib/plugins/commands/block/index.js:36:103)
    at _next (/Users/dtdream/Documents/l1449/ant-design-pro/node_modules/_umi-build-dev@1.7.7@umi-build-dev/lib/plugins/commands/block/index.js:38:194)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by imhele** [comment]
你使用的是 ant-design/ant-design-pro 仓库，还是 umijs/ant-design-pro 仓库？
> 目前 ant-design-pro v2.x 暂时不支持直接使用 block 命令，你可以试着把路由配置移到 config.js 中，再执行 block 命令，或者使用 https://github.com/umijs/ant-design-pro 仓库的版本，或者等待 ant-design-pro v4.0

**Comment by sorrycc** [comment]
得用 umi/ant-design-pro 才行。
