### ISSUE TITLE
umi-plugin-dll

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#250]
Enable webpack dll.

## 使用

.umirc.js

```
export default {
  plugins: [
    ['umi-plugin-dll', {
      exclude: ["@babel/runtime"],
      include: ["dva/router", "dva/saga", "dva/fetch"],
    }],
  ],
};
```

## 方案

1. dev 之前做 build:dll 构建
1.1 有 dll 则不做
1.2 缓存 package.json，有 diff 则构建
2. dev 引用 dll
3. dev 时 copy dll 文件输出目录
4. dev 时 html 额外引入 dll 文件

## 参考

* https://github.com/sorrycc/roadhog/pull/193

**Comment by elivoa** [comment]
赞

**Comment by sorrycc** [comment]
以 antd-admin 为例统计了下数据，

* 开按需编译打开 dashboard 32s（开 dll 16s）
* 关闭按需编译 41s（开 dll 21s）

**Comment by sorrycc** [comment]
最简项目，

* 开按需编译，有 dll 7.3s，无 dll 8.8s
* 关按需编译，有 dll 7.0s，无 dll 8.4s

**Comment by demohi** [comment]
```js
export default {
  plugins: ['umi-plugin-dva',
    ['umi-plugin-dll', {
      exclude: [],
      include: ['dva/router'],
    }],
  ],
  hashHistory: false,
  disableServiceWorker: true
};
```

```
> umi dev

Plugin user:/node_modules/umi-plugin-dll/lib/index.js initialize failed, Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at join (path.js:1251:7)
    at _default (node_modules/_umi-plugin-dll@0.1.0@umi-plugin-dll/lib/index.js:31:33)
    at plugins.forEach (/_umi-build-dev@0.13.0@umi-build-dev/lib/Service.js:280:9)
    at Array.forEach (<anonymous>)
    at Service.initPlugins (/node_modules/_umi-build-dev@0.13.0@umi-build-dev/lib/Service.js:274:18)
    at Service.dev (/node_modules/_umi-build-dev@0.13.0@umi-build-dev/lib/Service.js:141:10)
    at Object.dev [as default] (//node_modules/_umi-build-dev@0.13.0@umi-build-dev/lib/dev.js:14:18)
    at _default (/node_modules/_umi@1.1.0@umi/lib/dev.js:28:50)
    at Object.<anonymous> (/node_modules/_umi@1.1.0@umi/lib/scripts/realDev.js:14:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
```

**Comment by sorrycc** [comment]
@demohi 升级 umi 到 1.1.2
