### ISSUE TITLE
yarn create umi 选择 ant-design-pro 报错 clone ant-design-pro 报错

### ISSUE THREAD

**Issue by Chad97** [umijs/umi#2518]
## What happens?
yarn create umi 选择 ant-design-pro 报错 clone ant-design-pro 报错

## Mini Showcase Repository(REQUIRED)

无法提供 create失败

## How To Reproduce
**Steps to reproduce the behavior:**
1.yarn create umi
2.ant-design-pro

**Expected behavior**
- 估计是 clone 路径变更

## Context
如下：
```
> git clone https://github.com/ant-design/ant-design-pro --depth=1 ./
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at notFoundError (C:\Users\lp\AppData\Local\Yarn\Data\global\node_modules\cr
oss-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\lp\AppData\Local\Yarn\Data\global\node_modules\cro
ss-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\lp\AppData\Local\Yarn\Data\global\node_mod
ules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\lp\AppData\Local\Yarn\Data\global\node_m
odules\yeoman-generator\lib\index.js:436:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
```

**Comment by sorrycc** [comment]
本地有 git 命令吗？ cc @zombieJ

**Comment by Chad97** [comment]
> 本地有 git 命令吗？ cc @zombieJ
 umi文档中需要的环境都有

**Comment by dingpengxin** [comment]
我也遇到了怎么回事

**Comment by dtcymmtc** [comment]
同样的问题

**Comment by sorrycc** [comment]
@dingpengxin @dtcymmtc 系统是啥？windows？

**Comment by dtcymmtc** [comment]
@sorrycc mac os 10.14.5

**Comment by dingpengxin** [comment]
嗯呐

**Comment by Chad97** [comment]
@sorrycc windows 和 mac 都有这个问题
单独 clone 没问题
```
$ git clone https://github.com/ant-design/ant-design-pro --depth=1
Cloning into 'ant-design-pro'...
remote: Enumerating objects: 170, done.
remote: Counting objects: 100% (170/170), done.
remote: Compressing objects: 100% (152/152), done.
remote: TotalReceiving objec 170 (tdeltas: 20), reus  92% e(15d 78 (del8/170), 11t6a 10), pack-reused 0
Receiving objects: 100% (170/170), 116.65 KiB | 1024 bytes/s, done.
Resolving deltas: 100% (20/20), done.
Checking connectivity... done.

```

**Comment by songjingyang** [comment]
![image](https://user-images.githubusercontent.com/37998341/59917249-101cd700-9454-11e9-92d5-0a643aeecf2b.png)

**Comment by songjingyang** [comment]
也是clone的时候报错，但是clone成功了 ，项目装完依赖后，运行项目报错。

**Comment by WangSiTu** [comment]
<img width="797" alt="WX20190705-171225@2x" src="https://user-images.githubusercontent.com/17542189/60711731-188f0a80-9f48-11e9-9134-7994b0481d40.png">

**Comment by sorrycc** [comment]
@WangSiTu 当前目录不为空，仔细看报错信息。

**Comment by xiaohuoni** [comment]
这个问题最后被关闭的原因和最开始问的问题不是同一个。
相同的问题 https://github.com/umijs/umi/issues/3022

**Comment by liushouqian** [comment]
所以这个问题怎么解决？
