### ISSUE TITLE
Invalid key initialProps from plugin

### ISSUE THREAD

**Issue by ondc** [umijs/umi#2698]
## What happens?
```
assert.js:195 Uncaught 
AssertionError {name: "AssertionError", actual: false, expected: true, operator: "==", message: "Invalid key initialProps from plugin", …}
actual: false
expected: true
generatedMessage: false
message: "Invalid key initialProps from plugin"
name: "AssertionError"
operator: "=="
stack: "AssertionError: Invalid key initialProps from plugin↵    at http://127.0.0.1:10000/umi.dll.js:46274:25↵    at Array.forEach (<anonymous>)↵    at Object.use (http://127.0.0.1:10000/umi.dll.js:46271:23)↵    at Object../app/web/src/pages/.umi/umi.js (http://127.0.0.1:10000/umi.js:12485:9)↵    at __webpack_require__ (http://127.0.0.1:10000/umi.js:772:30)↵    at fn (http://127.0.0.1:10000/umi.js:130:20)↵    at Object.0 (http://127.0.0.1:10000/umi.js:240883:18)↵    at __webpack_require__ (http://127.0.0.1:10000/umi.js:772:30)↵    at http://127.0.0.1:10000/umi.js:948:37↵    at http://127.0.0.1:10000/umi.js:951:10"
__proto__: Error
```

## Context

- **Umi Version**: 2.7.7
- **Dva Version**: 2.4.0
- **Node Version**: 8.15.0
- **Platform**:macosx 10.14.5

**Comment by feibi** [comment]
可以锁定版本 ` "umi-plugin-react": "1.8.4" `

**Comment by ondc** [comment]
nice.完美解决

**Comment by chenqiuxia** [comment]
我也出现上面的问题，最后我发现umi的版本问题，我的umi版本是2.7.X，升级到2.10.X就没有这个问题了。

**Comment by gaoyafengyagao** [comment]
请问是怎么解决的？
