### ISSUE TITLE
TypeError: Cannot mix BigInt and other types, use explicit conversions

### ISSUE THREAD

**Issue by hujinbo** [umijs/umi#2771]
## What happens?

使用create-umi脚手架创建ant-design-pro项目，启动后报错TypeError: Cannot mix BigInt and other types, use explicit conversions

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

**复现步骤如下：**
1. 通过脚手架创建项目：`yarn create umi`
2. 选择项目：`ant-design-pro`
3. 选择使用：`TypeScript`
4. 安装依赖：`npm install`
5. 启动项目：`npm start`

**启动后报错信息如下：**
```
npm run start

> ant-design-pro@1.0.0 start D:\Program\antd-pro-example
> umi dev

Starting the development server...

(node:6644) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (D:\Program\antd-pro-example\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (D:\Program\antd-pro-example\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (D:\Program\antd-pro-example\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (D:\Program\antd-pro-example\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (D:\Program\antd-pro-example\node_modules\readdirp\index.js:163:23)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6644) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (D:\Program\antd-pro-example\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (D:\Program\antd-pro-example\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (D:\Program\antd-pro-example\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (D:\Program\antd-pro-example\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (D:\Program\antd-pro-example\node_modules\readdirp\index.js:163:23)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6644) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (D:\Program\antd-pro-example\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (D:\Program\antd-pro-example\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (D:\Program\antd-pro-example\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (D:\Program\antd-pro-example\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (D:\Program\antd-pro-example\node_modules\readdirp\index.js:163:23)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:6644) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (D:\Program\antd-pro-example\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (D:\Program\antd-pro-example\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (D:\Program\antd-pro-example\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (D:\Program\antd-pro-example\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (D:\Program\antd-pro-example\node_modules\readdirp\index.js:163:23)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:6644) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (D:\Program\antd-pro-example\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (D:\Program\antd-pro-example\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (D:\Program\antd-pro-example\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (D:\Program\antd-pro-example\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (D:\Program\antd-pro-example\node_modules\readdirp\index.js:163:23)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:6644) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (D:\Program\antd-pro-example\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (D:\Program\antd-pro-example\node_modules\chokidar\index.js:191:16)
    at WatchHelper.wh.filterPath.entry [as filterPath] (D:\Program\antd-pro-example\node_modules\chokidar\lib\nodefs-handler.js:524:38)
    at ReaddirpStream.fileFilter [as _fileFilter] (D:\Program\antd-pro-example\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (D:\Program\antd-pro-example\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (D:\Program\antd-pro-example\node_modules\readdirp\index.js:163:23)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
Extracted theme color css content length: 9671
 DONE  Compiled successfully in 54565ms10:15:33 PM


  App running at:
  - Local:   http://localhost:8000/ (copied to clipboard)
  - Network: http://10.1.199.188:8000/
```

## 相关环境信息

- **Umi 版本**：2.8.9
- **Node 版本**：v10.16.0
- **操作系统**：Windows 10 专业版

**Comment by sorrycc** [comment]
警告信息，可以忽略的。非 umi 问题，chokidar 抛的，我觉得和本地环境有关，看下安装依赖时有没有啥报错信息，再 google 下相关关键词。

**Comment by sorrycc** [comment]
和 #2769 重复。
