### ISSUE TITLE
`npm create umi app` doesn't start. Cannot find module 'react-router/matchPath'

### ISSUE THREAD

**Issue by jwmann** [umijs/umi#2896]
## What happens?
```
> @ start /Users/jwm/myumiapp
> umi dev

✖  error     Error: Cannot find module 'react-router/matchPath'
```

## How To Reproduce
**Steps to reproduce the behavior:**
1. `npm create umi`
2. Select `app`
3. Type `y` for typescript
4. Select `dva`, `code splitting`, `dll`, `internationalization`
5. Press Enter

**Expected behavior**
1. `npm start`
2. Working local dev server

## Context

- **Umi Version**:
`2.8.16`
- **Node Version**:
`12.7.0` && `npm 6.10.0`
- **Platform**:
MacOS 10.14.5

**Comment by jwmann** [comment]
Here's the stack trace:
```
Require stack:
- /Users/jwm/app/node_modules/react-router-config/matchRoutes.js
- /Users/jwm/app/node_modules/react-router-config/index.js
- /Users/jwm/app/node_modules/umi-build-dev/lib/html/HTMLGenerator.js
- /Users/jwm/app/node_modules/umi-build-dev/lib/plugins/commands/getHtmlGenerator.js
- /Users/jwm/app/node_modules/umi-build-dev/lib/plugins/commands/dev/createRouteMiddleware.js
- /Users/jwm/app/node_modules/umi-build-dev/lib/plugins/commands/dev/index.js
- /Users/jwm/app/node_modules/umi-build-dev/lib/getPlugins.js
- /Users/jwm/app/node_modules/umi-build-dev/lib/Service.js
- /Users/jwm/app/node_modules/umi/lib/scripts/realDev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/jwm/app/node_modules/react-router-config/matchRoutes.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Module._compile (/Users/jwm/app/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Object.newLoader [as .js] (/Users/jwm/app/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
```

**Comment by jwmann** [comment]
So I decided to roll back from: `dva@2.6.0-beta.6`
To: `dva@2.4.1`

And now I get this error:
```
 jwm/app$ npm start

> @ start /Users/jwm/app
> umi dev

internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'webpack'

**Comment by jwmann** [comment]
I managed to fix this by rolling back everything to this:

```
"dependencies": {
    "dva": "^2.5.0-beta.2",
},
"devDependencies": {
    "umi": "~2.7.0",
    "umi-plugin-react": "~1.6.0",
}
```

I think you guys need to sort out which versions are compatible with what.

**Comment by sorrycc** [comment]
I try the reproduce process with both npm and yarn, can't reproduce it.
