### ISSUE TITLE
请教如何捕捉 CORS 这类的请求异常

### ISSUE THREAD

**Issue by neewbee** [umijs/umi#2987]
## What happens?

CORS 引起的 request failed 错误无法捕捉
## 最小可复现仓库

```sh
git clone ant-design-pro
npm run start:no-mock
```

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
更改接口请求地址为一个不存在的地址或者有 跨域 限制的接口，
控制台报错
```sh
index.js:1 uncaught at _callee TypeError: Cannot read property 'status' of undefined
    at registerHandle (http://localhost:8000/p__user__register__model.ts.async.js:65:25)
    at http://localhost:8000/umi.js:22030:14
    at http://localhost:8000/umi.js:22044:14
    at Array.reduce (<anonymous>)
    at http://localhost:8000/umi.js:22043:21
    at http://localhost:8000/umi.js:22057:12
    at combination (http://localhost:8000/umi.js:23432:29)
    at p (<anonymous>:1:36402)
    at v (<anonymous>:1:36684)
    at <anonymous>:1:40069
    at Object.dispatch (http://localhost:8000/umi.js:23668:22)
    at e (<anonymous>:1:40553)
    at http://localhost:8000/umi.js:78363:22
    at http://localhost:8000/umi.js:21512:18
    at http://localhost:8000/umi.js:73920:18
    at dispatch (http://localhost:8000/umi.js:23223:18)
    at http://localhost:8000/umi.js:79887:12
    at http://localhost:8000/umi.js:78891:52
    at exec (http://localhost:8000/umi.js:79568:5)
    at flush (http://localhost:8000/umi.js:79609:5)
    at asap (http://localhost:8000/umi.js:79582:5)
    at runPutEffect (http://localhost:8000/umi.js:78888:25)
    at runEffect (http://localhost:8000/umi.js:78837:184)
    at next (http://localhost:8000/umi.js:78717:9)
    at currCb (http://localhost:8000/umi.js:78790:7)
```

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
还有问题？我看 ant-design-pro 有先检测 response 的，https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.ts#L31

**Comment by sorrycc** [comment]
截下堆栈看看是哪里抛的。

**Comment by neewbee** [comment]
不好意思，之前用的 v2 版本
