### ISSUE TITLE
安装脚手架失败

### ISSUE THREAD

**Issue by wo4558771** [umijs/umi#3022]
今天重新安装antd-pro 4.0结果不管是yarn还是npm安装都会报错,yarn create v1.17.3ro> yarn create umi
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-umi@0.14.0" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
? Which language do you want to use? JavaScript
> git clone https://github.com.cnpmjs.org/ant-design/ant-design-pro --depth=1 D:\project\new pro
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\86177\AppData\Local\Yarn\Data\global\node_modules\yeoman-generator\lib\index.js:436:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
error Command failed.
Exit code: 1
Command: C:\Users\86177\AppData\Local\Yarn\bin\create-umi
Arguments:
Directory: D:\project\new pro
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
重新选择安装app是没有问题

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：0.14.0
- **Node 版本**：10.16.1
- **操作系统**：win10

**Comment by INTMIN** [comment]
你确定你的umi是这个0.14.0版本的？

**Comment by wo4558771** [comment]
> 你确定你的umi是这个0.14.0版本的？

不好意思umi版本写错了，是2.8.17的

**Comment by liushouqian** [comment]
这个问题很久之前就出现了，现在还没有解决？我也遇到了

**Comment by wo4558771** [comment]
> 这个问题很久之前就出现了，现在还没有解决？我也遇到了

不知道，我那天是帮别人看的，我自己用app搭建了项目

**Comment by GODhandsome** [comment]
是不是没装git...我前面忘装git就报的这个错

**Comment by wo4558771** [comment]
> 是不是没装git...我前面忘装git就报的这个错
这个真的是装了，而且我安装app这个是没有问题的

**Comment by liushouqian** [comment]
我自己出现这个问题，但是解决了。

首先一开始出现这个问题的时候没有安装git

安装过后还是报这个错误。当时用的是vscode自带的终端。

然后改用cmd去执行，通过
