### ISSUE TITLE
安装区块失败

### ISSUE THREAD

**Issue by sankooc** [umijs/umi#3039]
##  通过 npx umi block list 方式无法安装区块

> npx umi block list

根据向导选择ListTableList
```
✔ 🚣  fetch block list
✔ 🔍  find block list form https://github.com/ant-design/pro-blocks
? ⛰  请选择区块（共 28 个 ) 📦  ListTableList  预览
? 🏗  请输入输出安装区块的路径 base
? 🤔  将 Typescript 区块转化为 js? Yes
? 🌎  删除 i18n 代码?  Yes
? 🌎  请输入你的选择的语言?  zh-CN
✔ 😁  Parse url and args
✖ 🔍  clone git repo from https://github.com.cnpmjs.org/ant-design/pro-blocks.git
✖  error     Error: Error: Command failed: git clone https://github.com.cnpmjs.org/ant-design/pro-blocks.git github.com/ant-design/pro-blocks --single-branch --recurse-submodules -b master
Cloning into 'github.com/ant-design/pro-blocks'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed


    at /Users/yj431/work/umi/node_modules/umi-build-dev/lib/plugins/commands/block/util.js:345:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/Users/yj431/work/umi/node_modules/umi-build-dev/lib/plugins/commands/block/util.js:41:103)
    at _throw (/Users/yj431/work/umi/node_modules/umi-build-dev/lib/plugins/commands/block/util.js:43:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

## 相关环境信息

- **Umi 版本**：2.8.18
- **Node 版本**：10.15.3
- **操作系统**：osx

**Comment by timestrider** [comment]
墙的锅。你再装一次它就自动切到gitee了。
