### ISSUE TITLE
使用官方插件@umijs/plugin-prerender遇到的问题

### ISSUE THREAD

**Issue by 419280377** [umijs/umi#3226]
https://deploy-preview-2963--umijs.netlify.com/zh/plugin/umi-plugin-prerender.html#%E5%AE%89%E8%A3%85
按照官网步骤安装、配置@umijs/plugin-prerender插件后，会报一些Error，比如下面(有时候是其他报错)。请问这是什么原因造成的呀？
![image](https://user-images.githubusercontent.com/20454290/65120314-02a9c580-da20-11e9-90c3-20bc64a9ebe3.png)

**Comment by ycjcl868** [comment]
给个可复现的 demo

**Comment by 419280377** [comment]
> 给个可复现的 demo

https://gitee.com/ToDanger/plugin-prerender-demo.git

**Comment by ycjcl868** [comment]
antd pro 里有很多副作用，ssr 要改不少

**Comment by LBC100** [comment]
出现同样的问题

**Comment by 419280377** [comment]
> 中后台项目不建议使用 SSR，SSR 主要场景在于前台，用于提升首屏渲染以及 SEO。

明白了，非常感谢您的回答。

**Comment by LBC100** [comment]
> 中后台项目不建议使用 SSR，SSR 主要场景在于前台，用于提升首屏渲染以及 SEO。

想用umi做前台~~~

**Comment by 419280377** [comment]
> 中后台项目不建议使用 SSR，SSR 主要场景在于前台，用于提升首屏渲染以及 SEO。

我用的pro写了个官网，🤦‍♂️

**Comment by LBC100** [comment]
官网需要seo的啊. https://github.com/kriasoft/react-starter-kit 了解一下

**Comment by LBC100** [comment]
![image](https://user-images.githubusercontent.com/38514123/65224216-51755f00-daf5-11e9-8c3d-1e122d45b32a.png)

**Comment by LBC100** [comment]
![image](https://user-images.githubusercontent.com/38514123/65224274-6e119700-daf5-11e9-9cc8-fb02097b5f2d.png)

**Comment by LBC100** [comment]
最新的umi项目. 这是设置: https://user-images.githubusercontent.com/38514123/65224274-6e119700-daf5-11e9-9cc8-fb02097b5f2d.png

**Comment by LBC100** [comment]
最新的umi项目. 这是设置 
![image](https://user-images.githubusercontent.com/38514123/65224377-a1542600-daf5-11e9-9ac5-01af75204348.png)

**Comment by LBC100** [comment]
报错: `
►  start     umiJS prerender start
(node:24732) UnhandledPromiseRejectionWarning: E:\myProject\umi\testUmiAntDesignProBootstrapFormik\node_modules\antd\lib\style\index.less:1
@import './themes/index';
^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (E:\myProject\umi\testUmiAntDesignProBootstrapFormik\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\myProject\umi\testUmiAntDesignProBootstrapFormik\node_modules\antd\lib\layout\style\layout\style\index.jsx:1:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (E:\myProject\umi\testUmiAntDesignProBootstrapFormik\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (E:\myProject\umi\testUmiAntDesignProBootstrapFormik\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:24732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 33.50s.`

![image](https://user-images.githubusercontent.com/38514123/65224549-f98b2800-daf5-11e9-90ce-1ed94a9baec6.png)

**Comment by 419280377** [comment]
> 最新的umi项目. 这是设置
> ![image](https://user-images.githubusercontent.com/38514123/65224377-a1542600-daf5-11e9-9ac5-01af75204348.png)

https://github.com/umijs/umi-example-ssr  umi写官网可以参照这个
