### ISSUE TITLE
运行时配置的动态路由，控制台警告异常，Error: Debug Failure. Output generation failed 无法编译.d.ts文件

### ISSUE THREAD

**Issue by leshalv** [umijs/umi#3502]
今天配置了一下运行时配置的动态路由，控制台警告异常，无法编译.d.ts文件
![image](https://user-images.githubusercontent.com/30397655/67463731-8c2e6200-f674-11e9-871e-45fd1016c21f.png)

**Comment by CocoChen917** [comment]
怎么关了

**Comment by tikazyq** [comment]
同样的问题，无法编译`.d.ts`文件。

错误如下：

```
 error  in ./src/pages/sites/models/index.d.ts

Module build failed (from ./node_modules/af-webpack/node_modules/ts-loader/index.js):
Error: Debug Failure. Output generation failed
    at Object.transpileModule (/Users/xxx/frontend/node_modules/af-webpack/node_modules/typescript/lib/typescript.js:116825:29)
    at getTranspilationEmit (/Users/xxx/frontend/node_modules/af-webpack/node_modules/ts-loader/dist/index.js:283:74)
    at successLoader (/Users/xxx/frontend/node_modules/af-webpack/node_modules/ts-loader/dist/index.js:66:15)
    at Object.loader (/Users/xxx/frontend/node_modules/af-webpack/node_modules/ts-loader/dist/index.js:22:12)
```

后来我发现可能是用了[af-webpack](https://www.npmjs.com/package/af-webpack)这个打包工具，而其中的`package.json`里引用的ts版本为`"typescript": "3.7.2"`，怀疑很可能是这个版本导致的问题。

以下是我的`package.json`。

```json
{
  "name": "xxx",
  "version": "0.0.1",
  "description": "xxx",
  "scripts": {
    "start:dev": "umi dev --port=8082",
    "build:prod": "umi build",
    "build": "npm run build:prod",
    "test": "umi test",
    "lint": "umi-lint --eslint.ext='.ts,tsx' ."
  },
  "dependencies": {
    "@ant-design/icons": "^4.3.0",
    "antd": "^4.8.2",
    "array-move": "^3.0.1",
    "dva": "^2.6.0-beta.6",
    "format-duration": "^1.3.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router-breadcrumbs-hoc": "^3.2.10",
    "react-sortable-hoc": "^1.11.0",
    "socket.io-client": "^3.0.1"
  },
  "devDependencies": {
    "@types/jest": "^23.3.12",
    "@types/react": "^16.7.18",
    "@types/react-dom": "^16.0.11",
    "@types/react-test-renderer": "^16.0.3",
    "@typescript-eslint/eslint-plugin": "^4.8.1",
    "@typescript-eslint/parser": "^4.8.1",
    "@umijs/plugin-dva": "^0.9.1",
    "@umijs/plugin-layout": "^0.12.5",
    "babel-eslint": "^9.0.0",
    "eslint": "^7.13.0",
    "eslint-config-umi": "^1.4.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "react-hot-loader": "^4.13.0",
    "react-test-renderer": "^16.7.0",
    "typescript": "^4.0.5",
    "typescript-estree": "^18.1.0",
    "umi": "^2.9.0",
    "umi-lint": "^2.0.2",
    "umi-plugin-react": "^1.8.0",
    "umi-types": "^0.3.0"
  },
  "lint-staged": {
    "*.{ts,tsx}": [
      "eslint --fix",
      "git add"
    ],
    "*.{js,jsx}": [
      "eslint --fix",
      "git add"
    ]
  },
  "eslintConfig": {
    "extends": "eslint-config-umi",
    "rules": {
      "@typescript-eslint/no-unused-vars": "off"
    }
  },
  "eslintIgnore": [
    "**/node_modules",
    "**/*.js"
  ]
}
```

**Comment by tikazyq** [comment]
这个问题其实可以这么解决，不要在 `pages` 这些跟 `routes` 相关的目录里创建 `.d.ts` 文件，这些文件似乎默认会被 umi 看做 models 文件去编译，从而导致编译失败。我将它们全部移动到了其他地方，例如 `types` 目录，完美解决了问题。

![image](https://user-images.githubusercontent.com/3393101/100204382-c71d5c00-2f3e-11eb-99f8-53388b2827b6.png)
