### ISSUE TITLE
af-webpack highestPort 需要可以配置

### ISSUE THREAD

**Issue by GongT** [umijs/umi#3586]
`getPort.js`:
```js
  portfinder.basePort = process.env.BASE_PORT || 8000;
  portfinder.highestPort = 9000;
```

如果highestPort不能配置，那这个BASE_PORT没意义。。。

会出现这样的错误：
```
Error: Provided options.stopPort(9000is less than options.startPort (15001)
    at Object.exports.getPort (/data/DevelopmentRoot/github.com/gongt/umi-project-test/node_modules/portfinder/lib/portfinder.js:124:13)
    at /data/DevelopmentRoot/github.com/gongt/umi-project-test/node_modules/portfinder/lib/portfinder.js:224:13
    at new Promise (<anonymous>)
    at Object.exports.getPortPromise (/data/DevelopmentRoot/github.com/gongt/umi-project-test/node_modules/portfinder/lib/portfinder.js:223:10)
    at /data/DevelopmentRoot/github.com/gongt/umi-project-test/node_modules/af-webpack/lib/getPort.js:48:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/data/DevelopmentRoot/github.com/gongt/umi-project-test/node_modules/af-webpack/lib/getPort.js:30:103)
    at _next (/data/DevelopmentRoot/github.com/gongt/umi-project-test/node_modules/af-webpack/lib/getPort.js:32:194)
    at /data/DevelopmentRoot/github.com/gongt/umi-project-test/node_modules/af-webpack/lib/getPort.js:32:364
    at new Promise (<anonymous>)
```

**Comment by GongT** [comment]
closed by #3587
