### ISSUE TITLE
jenkins打包部署报错，本地mac，windows都可以

### ISSUE THREAD

**Issue by jayguojianhai** [umijs/umi#3623]
## What happens?
��� Webpack
Compiled with some errors in 1.63m

ERROR Failed to compile with 14 errors9:21:43 AM

Unhandled rejection TypeError: Cannot read property 'stats' of undefined
at getErrorInfo (/root/.jenkins/workspace/test_3.0/node_modules/af-webpack/lib/build.js:137:14)
at /root/.jenkins/workspace/test_3.0/node_modules/af-webpack/lib/build.js:110:16
at finalCallback (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/MultiCompiler.js:254:12)
at runWithDependencies.err (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/MultiCompiler.js:275:14)
at /root/.jenkins/workspace/test_3.0/node_modules/neo-async/async.js:2830:7
at done (/root/.jenkins/workspace/test_3.0/node_modules/neo-async/async.js:2925:13)
at err (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/MultiCompiler.js:186:23)
at compiler.run (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/MultiCompiler.js:267:15)
at finalCallback (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/Compiler.js:257:39)
at hooks.done.callAsync.err (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/Compiler.js:272:22)
at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/.jenkins/workspace/test_3.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), :30:1)
at AsyncSeriesHook.lazyCompileHook (/root/.jenkins/workspace/test_3.0/node_modules/tapable/lib/Hook.js:154:20)
at onCompiled (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/Compiler.js:271:21)
at hooks.afterCompile.callAsync.err (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/Compiler.js:681:15)
at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/.jenkins/workspace/test_3.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), :6:1)
at AsyncSeriesHook.lazyCompileHook (/root/.jenkins/workspace/test_3.0/node_modules/tapable/lib/Hook.js:154:20)
Finished: SUCCESS

- **Umi Version**:2.11.3
- **Node Version**:
10.15.3
npm:6.4.1
centOs:6.9
- **Platform**:

**Comment by sorrycc** [comment]
应该是打包出错了，`/root/.jenkins/workspace/test_3.0/node_modules/af-webpack/lib/build.js:137` 把 error 打出来看下。

**Comment by jayguojianhai** [comment]
jay--------------------- TypeError: Cannot read property 'startsWith' of undefined
    at isRelative (/root/.jenkins/workspace/test_3.0/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:5:17)
    at Array.from.map.module (/root/.jenkins/workspace/test_3.0/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:64:15)
    at Array.map (<anonymous>)
    at groupModules (/root/.jenkins/workspace/test_3.0/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:62:43)
    at formatErrors (/root/.jenkins/workspace/test_3.0/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:74:18)
    at format (/root/.jenkins/workspace/test_3.0/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:87:10)
    at format (/root/.jenkins/workspace/test_3.0/node_modules/friendly-errors-webpack-plugin/src/core/formatErrors.js:12:33)
    at Array.map (<anonymous>)
    at formatErrors (/root/.jenkins/workspace/test_3.0/node_modules/friendly-errors-webpack-plugin/src/core/formatErrors.js:15:21)
    at FriendlyErrorsWebpackPlugin.displayErrors (/root/.jenkins/workspace/test_3.0/node_modules/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:110:5)
    at doneFn (/root/.jenkins/workspace/test_3.0/node_modules/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:51:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/.jenkins/workspace/test_3.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (/root/.jenkins/workspace/test_3.0/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/.jenkins/workspace/test_3.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
Unhandled rejection ReferenceError: connsole is not defined
    at getErrorInfo (/root/.jenkins/workspace/test_3.0/node_modules/af-webpack/lib/build.js:138:1)
    at /root/.jenkins/workspace/test_3.0/node_modules/af-webpack/lib/build.js:110:16
    at finalCallback (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at runWithDependencies.err (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/MultiCompiler.js:275:14)
    at /root/.jenkins/workspace/test_3.0/node_modules/neo-async/async.js:2830:7
    at done (/root/.jenkins/workspace/test_3.0/node_modules/neo-async/async.js:2925:13)
    at err (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/MultiCompiler.js:186:23)
    at compiler.run (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/MultiCompiler.js:267:15)
    at finalCallback (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/Compiler.js:257:39)
    at hooks.done.callAsync.err (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/Compiler.js:272:22)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/.jenkins/workspace/test_3.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at AsyncSeriesHook.lazyCompileHook (/root/.jenkins/workspace/test_3.0/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (/root/.jenkins/workspace/test_3.0/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/.jenkins/workspace/test_3.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/.jenkins/workspace/test_3.0/node_modules/tapable/lib/Hook.js:154:20)

**Comment by jayguojianhai** [comment]
![image](https://user-images.githubusercontent.com/15603321/69314765-e7517580-0c6f-11ea-85d2-2904292d3942.png)

**Comment by sorrycc** [comment]
进度条插件报错了，加环境变量 PROGRESS=none 再执行试试。

**Comment by jayguojianhai** [comment]
还是一样呀
![image](https://user-images.githubusercontent.com/15603321/69510836-51706000-0f79-11ea-9ca9-cd534d30fd60.png)

**Comment by sorrycc** [comment]
给个复现仓库吧，我找台 windows 跑跑看。

**Comment by jayguojianhai** [comment]
不是windows哦 是linux系统，我下午整一个demo

**Comment by fengyun2** [comment]
在windows10上，设置 `base: '/ant/'` 之后就会报这个错误 `TypeError: Cannot read property 'stats' of undefined`

**Comment by areyouse7en** [comment]
所以解决了吗？umi 3.3.11也遇到了
