### ISSUE TITLE
使用ssr渲染，antd样式引入出错

### ISSUE THREAD

**Issue by OnPure** [umijs/umi#3672]
umi build打包成功，但是报下面的错误
(function (exports, require, module, __filename, __dirname) { import '../../style/index.less';
SyntaxError: Unexpected string
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)

**Comment by OnPure** [comment]
\node_modules\antd\es\icon\style\index.js:1
