### ISSUE TITLE
pwa initialize 是好的， 但是 run build 出现错误

### ISSUE THREAD

**Issue by zuolung** [umijs/umi#3722]
在webpack build 进程 emitting时抛出操作
● Webpack █████████████████████████ emitting (95%) CopyPlugin 
(node:61809) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stats' of undefined
    at getErrorInfo (/Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/af-webpack/lib/build.js:137:14)
    at /Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/af-webpack/lib/build.js:110:16
    at finalCallback (/Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/af-webpack/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at runWithDependencies.err (/Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/af-webpack/node_modules/webpack/lib/MultiCompiler.js:275:14)
    at /Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/neo-async/async.js:2830:7
    at done (/Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/neo-async/async.js:2925:13)
    at err (/Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/af-webpack/node_modules/webpack/lib/MultiCompiler.js:186:23)
    at compiler.run (/Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/af-webpack/node_modules/webpack/lib/MultiCompiler.js:267:15)
    at finalCallback (/Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/af-webpack/node_modules/webpack/lib/Compiler.js:257:39)
    at emitAssets.err (/Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/af-webpack/node_modules/webpack/lib/Compiler.js:279:21)
    at hooks.emit.callAsync.err (/Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/af-webpack/node_modules/webpack/lib/Compiler.js:492:20)
    at _promise3.then._err3 (eval at create (/Users/apple/Desktop/schoolManager/school_manager_main__2.01/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
(node:61809) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:61809) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zuolung** [comment]
function getErrorInfo(err, stats) {
  if (!stats.stats) {
    return {
      err: err || stats.compilation && stats.compilation.errors && stats.compilation.errors[0],
      stats,
      rawStats: stats
    };
  }

**Comment by sorrycc** [comment]
打印下 err 和 stats 看下，然后给个复现。

**Comment by zuolung** [comment]
**err**
{ [Error: ENOENT: no such file or directory, open '/Users/apple/Desktop/schoolManager/school_manager_main__2.01/src/service-worker.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path:
   '/Users/apple/Desktop/schoolManager/school_manager_main__2.01/src/service-worker.js' } 
**stats**
undefined

**Comment by tongsu** [comment]
我遇到了相同的问题 errno: -4058

**Comment by lisztj** [comment]
有可能注释的地方没有删除，或者引入了 react-copy-to-clipboard模块，没有用，最好注释或者删除代码行
