### ISSUE TITLE
umi ui 执行构建任务后 服务自动退出

### ISSUE THREAD

**Issue by feifei8** [umijs/umi#3747]
![Snap1](https://user-images.githubusercontent.com/8944081/70221391-383e8f00-1783-11ea-90e6-4a9572bd9281.jpg)
## What happens?
使用 umi ui  打开页面管理后，在执行任务-构建后
umi ui 服务会自动退出，报如下错误
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
PS E:\umi\deer>
![Snap1](https://user-images.githubusercontent.com/8944081/70221439-560bf400-1783-11ea-91a8-b0e7cd6ee1e7.jpg)

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:umi@2.12.4
- **Node Version**:v8.11.2
- **Platform**: win10

**Comment by ycjcl868** [comment]
spawn windows 兼容问题，要修下

**Comment by pccai** [comment]
![image](https://user-images.githubusercontent.com/2232794/79113178-e3ef8f80-7db2-11ea-928e-a0ee2faa3d48.png)
