### ISSUE TITLE
yarn create umi后安装依赖报错

### ISSUE THREAD

**Issue by Sayid1** [umijs/umi#3766]
## What happens?
安装依赖报错

## How To Reproduce
**Steps to reproduce the behavior:**
1. yarn create umi 选antd pro 和 ts
2. yarn

报错信息如下
```
warning Error running install script for optional dependency: "/Users/Sayid/vscode_space/umi-template/node_modules/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /Users/Sayid/vscode_space/umi-template/node_modules/node-pty
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.0 | darwin | x64
gyp info find Python using Python version 2.7.10 found at \"/usr/bin/python\"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Sayid/vscode_space/umi-template/node_modules/node-pty/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Sayid/Library/Caches/node-gyp/10.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Sayid/Library/Caches/node-gyp/10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Sayid/Library/Caches/node-gyp/10.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Sayid/vscode_space/umi-template/node_modules/node-pty',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcrun: error: active developer path (\"/Applications/Xcode.app/Contents/Developer\") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/Sayid/vscode_space/umi-template/node_modules/node-pty
success Saved lockfile.
✨  Done in 247.21s.
```
**Expected behavior**
1. 正常启动

## Context

- **Umi Version**: 2.12.5
- **Node Version**: v10.16.0
- **Platform**: macOS and Windows

**Comment by williamnie** [comment]
这个和umi没关系，这是你没装g++，去百度下错误就知道了

**Comment by Sayid1** [comment]
我其它的项目没问题啊，我同事的电脑也这样

**Comment by sorrycc** [comment]
这是可选依赖，安装出错不影响使用。

**Comment by Sayid1** [comment]
初始化不影响，但是我后面添加依赖会报错而且添加失败

**Comment by sorrycc** [comment]
@ycjcl868 这个依赖得再考虑下，感觉按需下会比较好。

**Comment by wscart** [comment]
我这边也是这种情况。之前还好的，不知道后来怎么变成这样的，求解决

**Comment by ycjcl868** [comment]
这个不使用 umi ui 的终端功能不会有其它问题，正常构建和 dev 是没有影响的

**Comment by fengyun2** [comment]
这个报错问题还没有解决吗？

**Comment by JLoveI** [comment]
> 这个不使用 umi ui 的终端功能不会有其它问题，正常构建和 dev 是没有影响的

这个问题不考虑解决下吗，一直看到错误太恶心了。

**Comment by SilentFlute** [comment]
从mbp换成windows，mbp的时候怎么用的没问题，换成win第一天就报错了，后来发现是装umi的时候会装node-pty，各种找方法也没能解决，装nodejs的时候有个提示，说要装些额外的比如python，c++什么的，自动装失败了，然后到node-gyp的github中照步骤手动装node-gyp，py2.7，c++什么的，再配置node-gyp，msvs_version，当然了，自动那个什么windows-build-tools也试了，最后还去microsoft/node-gyp的github里下了win 10 sdk，一开始各种报错装不上，后来删除了umi装其他的，装完之后再单独装umi就可以了！但是一起装就又会报错：
```
[5/5] Building fresh packages...
[-/9] ⠄ waiting...
[8/9] ⡀ node-pty
[-/9] ⡀ waiting...
[-/9] ⡀ waiting...
warning Error running install script for optional dependency: "D:\\huodong\\node_modules\\node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: D:\\huodong\\node_modules\\node-pty
Output:
D:\\huodong\\node_modules\\node-pty>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"C:\\Users\\Petrelli\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.16.2 | win32 | x64
gyp info find Python using Python version 2.7.18 found at \"C:\\Python27\\python.exe\"
gyp info find VS using VS2017 (15.9.28307.1093) found at:
gyp info find VS \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\\Python27\\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\\\Users\\\\Petrelli\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\\\huodong\\\\node_modules\\\\node-pty\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\Petrelli\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\node-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\Petrelli\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.16.2\\\\include\\\\node\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\Petrelli\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.16.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Users\\\\Petrelli\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\\\\\Users\\\\\\\\Petrelli\\\\\\\\AppData\\\\\\\\Local\\\\\\\\node-gyp\\\\\\\\Cache\\\\\\\\12.16.2\\\\\\\\<(target_arch)\\\\\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\\\huodong\\\\node_modules\\\\node-pty',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\\\huodong\\\\node_modules\\\\node-pty\\\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
  conpty.cc
  path_util.cc
  win_delay_load_hook.cc
C:\\\\Users\\\\Petrelli\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.16.2\\\\x64\\\\node.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x2FCB20 [D:\\huodong\\node_modules\\node-pty\\build\\conpty.vcxproj]
  conpty_console_list.cc
  win_delay_load_hook.cc
C:\\\\Users\\\\Petrelli\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.16.2\\\\x64\\\\node.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x2FCB20 [D:\\huodong\\node_modules\\node-pty\\build\\conpty_console_l
ist.vcxproj]
  AgentLocation.cc
  winpty.cc
  BackgroundDesktop.cc
  Buffer.cc
  DebugClient.cc
  GenRandom.cc
  OwnedHandle.cc
  StringUtil.cc
  WindowsSecurity.cc
  WindowsVersion.cc
  WinptyAssert.cc
  WinptyException.cc
  WinptyVersion.cc
  win_delay_load_hook.cc
C:\\\\Users\\\\Petrelli\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.16.2\\\\x64\\\\node.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x2FCB20 [D:\\huodong\\node_modules\\node-pty\\build\\deps\\winpty\\sr
c\\winpty.vcxproj]
  Agent.cc
  AgentCreateDesktop.cc
  ConsoleFont.cc
  ConsoleInput.cc
  ConsoleInputReencoding.cc
  ConsoleLine.cc
  DebugShowInput.cc
  DefaultInputMap.cc
  EventLoop.cc
  InputMap.cc
  LargeConsoleRead.cc
  NamedPipe.cc
  Scraper.cc
  Terminal.cc
  Win32Console.cc
  Win32ConsoleBuffer.cc
  main.cc
  BackgroundDesktop.cc
  Buffer.cc
  DebugClient.cc
  GenRandom.cc
  OwnedHandle.cc
  StringUtil.cc
  WindowsSecurity.cc
  WindowsVersion.cc
  WinptyAssert.cc
  WinptyException.cc
  WinptyVersion.cc
  win_delay_load_hook.cc
C:\\\\Users\\\\Petrelli\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.16.2\\\\x64\\\\node.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x2FCB20 [D:\\huodong\\node_modules\\node-pty\\build\\deps\\winpty\\sr
c\\winpty-agent.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Users\\Petrelli\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\lib\\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\Petrelli\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd D:\\huodong\\node_modules\\node-pty
success Saved lockfile.
Done in 471.61s.
```
然后umi dev也起不来：
```
$ umi dev
  build [==                  ] 10%events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL: address not available 103.53.125.37:8000
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at GetAddrInfoReqWrap.doListen (net.js:1500:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:10)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '103.53.125.37',
  port: 8000
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by SilentFlute** [comment]
emmmmmm，分批装成功了居然也没法umi dev跑起来，也是报同样的错，求支援啊

**Comment by SilentFlute** [comment]
看了node_modules中，node-pty并没有安装成功......
