### ISSUE TITLE
umi test 使用生成`覆盖率表格` 会报 cov_bur8rx1wt 未定义

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#3787]
使用`umi test` 验证 `e2e` 测试，用例通过了。
使用 `umi-test --coverage` 报错如下
```bash
Evaluation failed: ReferenceError: cov_bur8rx1wt is not defined

      at __puppeteer_evaluation_script__:3:15
      at ExecutionContext._evaluateInternal (node_modules/puppeteer/lib/ExecutionContext.js:122:13)
        -- ASYNC --
      at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at DOMWorld.evaluate (node_modules/puppeteer/lib/DOMWorld.js:112:20)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.evaluate (node_modules/puppeteer/lib/Page.js:863:43)
      at Page.evaluate (node_modules/puppeteer/lib/helper.js:112:23)
      at _callee$ (packages/abc/test/fixtures/normal1/test.js:6:27)
      at tryCatch (node_modules/umi-test/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/umi-test/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/umi-test/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (packages/abc/test/fixtures/normal1/test.js:132:103)
      at _next (packages/abc/test/fixtures/normal1/test.js:134:194)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |       50 |      100 |       50 |       50 |                   |
 test.js  |       50 |      100 |       50 |       50 |               7,9 |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
```
重现demo [umi-plugin-hello](https://github.com/sorrycc/umi-plugin-hello)
只需将这里改成 `umi-test --coverage`  

https://github.com/sorrycc/umi-plugin-hello/blob/7a2359d2802e8a3bdc291506971c596433f9352a/package.json#L7

**Comment by sorrycc** [comment]
jest.config.js 里配，

```js
module.exports = {
  collectCoverageFrom: [
    'index.js'
  ],
};
```
