### ISSUE TITLE
umi ui 启动项目后报异常UnhandledPromiseRejectionWarning: BaseTaskError: Not umi

### ISSUE THREAD

**Issue by mega16** [umijs/umi#3806]
## 使用umi ui 创建项目后，进入项目后点击启动项目，页面无反应无日志输入，控制台报异常?

```
➜  checkout-wallet umi ui
🚀 Starting Umi UI using umi@2.12.6...
⛽️ Ready on http://localhost:3000/
(node:10427) UnhandledPromiseRejectionWarning: BaseTaskError: Not umi
    at DevTask.error (/Users/pi/code/tempdir/checkout-wallet/node_modules/umi-ui-tasks/lib/server/core/Tasks/Base.js:238:17)
    at DevTask.getScript (/Users/pi/code/tempdir/checkout-wallet/node_modules/umi-ui-tasks/lib/server/core/Tasks/Dev.js:176:12)
    at /Users/pi/code/tempdir/checkout-wallet/node_modules/umi-ui-tasks/lib/server/core/Tasks/Dev.js:59:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/pi/code/tempdir/checkout-wallet/node_modules/umi-ui-tasks/lib/server/core/Tasks/Dev.js:32:103)
    at _next (/Users/pi/code/tempdir/checkout-wallet/node_modules/umi-ui-tasks/lib/server/core/Tasks/Dev.js:34:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10427) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10427) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10427) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pid' of undefined
    at /Users/pi/code/tempdir/checkout-wallet/node_modules/umi-ui-tasks/lib/server/index.js:109:30
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/pi/code/tempdir/checkout-wallet/node_modules/umi-ui-tasks/lib/server/index.js:30:103)
    at _next (/Users/pi/code/tempdir/checkout-wallet/node_modules/umi-ui-tasks/lib/server/index.js:32:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## How To Reproduce
**Steps to reproduce the behavior:**
1.使用umi ui 创建项目
2.进入项目后点击启动项目
3.页面无反应，无日志输入

**Expected behavior**
1.点击启动，项目正常运行

## Context

- **Umi Version**: 2.12.6
- **Node Version**: v12.13.1
- **Platform**: macOS Mojave v10.14.4

**Comment by ycjcl868** [comment]
看下你的 `package.json`

**Comment by mega16** [comment]
{
  "private": true,
  "scripts": {
    "start": "better-npm-run start",
    "build": "umi build",
    "test": "umi test",
    "lint": "eslint --ext .js src mock tests",
    "precommit": "lint-staged"
  },
  "betterScripts": {
    "start": {
      "command": "PORT=4040 umi dev",
      "env": {
        "HOST_API": "local"
      }
    }
  },
  "dependencies": {
    "antd": "^3.19.5",
    "dva": "^2.6.0-beta.6",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "babel-eslint": "^9.0.0",
    "better-npm-run": "^0.1.1",
    "eslint": "^5.4.0",
    "eslint-config-umi": "^1.4.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "react-test-renderer": "^16.7.0",
    "umi": "^2.7.7",
    "umi-plugin-react": "^1.8.4"
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "eslint --fix",
      "git add"
    ]
  },
  "engines": {
    "node": ">=8.0.0"
  }
}

**Comment by ycjcl868** [comment]
`better-npm-run` 😂

**Comment by mega16** [comment]
应该是better-npm-run 造成umi ui 启动项目报错，命令行 yarn start 运行正常。引入better-npm-run目的是为了方便管理多个环境变量
