### ISSUE TITLE
umi ui 创建项目报错

### ISSUE THREAD

**Issue by Nymph-fan** [umijs/umi#3838]
选择的是基础模版
包管理选择的是yarn
后台日志如下
yarn 版本 1.6.0
cnpm 6.1.1
`
Error: spawn npm ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`

**Comment by ycjcl868** [comment]
日志可以再全一点吗？
