### ISSUE TITLE
UMI 开启SSR 使用‘braft-editor'组件，出现ReferenceError: document is not defined  

### ISSUE THREAD

**Issue by 810106148** [umijs/umi#3849]
https://umijs.org/zh/guide/faq.html#ssr
这里的方法不能解决。我只引用，还没使用，就出错了。

**Comment by ycjcl868** [comment]
给个复现 demo

**Comment by 810106148** [comment]
> 给个复现 demo

git@github.com:810106148/umi-ssr-test.git
使用：npm start
错误信息：
ReferenceError: document is not defined
    at D:\wwwroot\umi-server\examples\ant-motion\node_modules\braft-finder\dist\index.js:591:19
    at D:\wwwroot\umi-server\examples\ant-motion\node_modules\braft-finder\dist\index.js:580:46
    at module.exports (D:\wwwroot\umi-server\examples\ant-motion\node_modules\braft-finder\dist\index.js:645:88)
    at Object.defineProperty.value (D:\wwwroot\umi-server\examples\ant-motion\node_modules\braft-finder\dist\index.js:1095:37)
    at __webpack_require__ (D:\wwwroot\umi-server\examples\ant-motion\node_modules\braft-finder\dist\index.js:30:30)
    at Object.defineProperty.value (D:\wwwroot\umi-server\examples\ant-motion\node_modules\braft-finder\dist\index.js:1116:1)
    at __webpack_require__ (D:\wwwroot\umi-server\examples\ant-motion\node_modules\braft-finder\dist\index.js:30:30)
    at Object.<anonymous> (D:\wwwroot\umi-server\examples\ant-motion\node_modules\braft-finder\dist\index.js:2095:13)
    at __webpack_require__ (D:\wwwroot\umi-server\examples\ant-motion\node_modules\braft-finder\dist\index.js:30:30)
    at Object.defineProperty.value (D:\wwwroot\umi-server\examples\ant-motion\node_modules\braft-finder\dist\index.js:94:18)
[nodemon] app crashed - waiting for file changes before starting...
问题文件位置：
src\pages\admin\article\show.jsx

import BraftEditor from 'braft-editor'
import { ContentUtils } from 'braft-utils'
引用了braft-editor braft-utils就会出现错误。


使用环境：win10 64,node v10.15.1
