### ISSUE TITLE
在.umirc.ts文件中导入routes文件报错

### ISSUE THREAD

**Issue by alwaysRemember** [umijs/umi#3850]
## What happens?
自己在src中写了个routes文件，当引用到.umirc.ts中报错

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
1.添加routes.ts文件
内容：
```
import { IRoute } from 'umi-types';

const routes: Array<IRoute> = [
  {
    path: '/login',
    component: './Login',
    title: '登录',
  },
];

export default routes;
```
2. .umirc.ts中导入文件
```
import routes from "./src/routes";
console.log(routes);

const config:IConfig = {
// some code
    routes,
}
```
3. 报错
```
import { IRoute } from 'umi-types';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Module._compile (/Users/tang/Documents/myProject/weChatSalesSystem/node_modules/_pirates@4.0.1@pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.newLoader [as .ts] (/Users/tang/Documents/myProject/weChatSalesSystem/node_modules/_pirates@4.0.1@pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

## 相关环境信息

- **Umi 版本**：2.9.0
- **Node 版本**：v10.15.3
- **操作系统**：mac os

**Comment by ycjcl868** [comment]
给个复现，看起来像是没加 `tsconfig.json`

**Comment by alwaysRemember** [comment]
@ycjcl868 有tsconfig.json
[https://github.com/alwaysRemember/managementSystem](项目地址)

**Comment by ycjcl868** [comment]
把 src/routes， 放在 `.umirc.ts` 同目录

**Comment by jianhao** [comment]
我也遇到了同样的问题，目测是 umi 的bug或者不支持，暂时的解决办法是，用另一种配置方式，在根目录建立 config 目录，然后添加 config.ts（代替 .umirc.ts） 和 routes.ts 文件，这样是可以的。
