### ISSUE TITLE
使用 npx umi ui 启动 web 界面创建项目失败

### ISSUE THREAD

**Issue by xiedacon** [umijs/umi#4001]
## What happens?

使用 ``npx umi ui`` 启动 web 界面创建项目失败

* 模版：ant-design-pro
* 语言：typescript
* 包管理：npm

```
🚀 Starting Umi UI using umi@2.13.3...
⛽️ Ready on http://localhost:3000/
✔ 🔍  find block list form https://gitee.com/ant-design/ant-design-blocks/raw/master/umi-block.json
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: self.env.emit is not a function
    at /Users/xieda/.umi/creator/create-umi/node_modules/yeoman-generator/lib/index.js:653:22
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/xieda/.umi/creator/create-umi/node_modules/yeoman-generator/lib/index.js:668:20)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
```

## How To Reproduce
**Steps to reproduce the behavior:**

**Expected behavior**

## Context

- **Umi Version**: 2.13.3
- **Node Version**: v10.9.0
- **Platform**: mac

**Comment by xiedacon** [comment]
补充：把报错处的 self.env.emit 改为 self.emit 就行了

**Comment by CodeGueas** [comment]
edit  'self.env.emit' to 'self.emit' ,work
