### ISSUE TITLE
TypeError: self.env.emit is not a function

### ISSUE THREAD

**Issue by gaozhiwei-1994** [umijs/umi#4006]
? Select the boilerplate type app
? Do you want to use typescript? Yes
? What functionality do you want to enable? antd, dva
events.js:187
      throw er; // Unhandled 'error' event
      ^

TypeError: self.env.emit is not a function
    at C:\Users\GZW\node\global\node_modules\create-umi\node_modules\yeoman-generator\lib\index.js:653:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (C:\Users\GZW\node\global\node_modules\create-umi\node_modules\yeoman-generator\lib\index.js:668:20)
    at processImmediate (internal/timers.js:439:21)

**Comment by pyyzcwg2833** [comment]
同样遇到了这个问题

**Comment by icowan** [comment]
同样遇到该问题！

**Comment by 282159468** [comment]
同样遇到了这个问题

**Comment by GravityInc** [comment]
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: self.env.emit is not a function
    at /Users/u352443/.npm/_npx/46441/lib/node_modules/create-umi/node_modules/yeoman-generator/lib/index.js:653:22
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/u352443/.npm/_npx/46441/lib/node_modules/create-umi/node_modules/yeoman-generator/lib/index.js:668:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by ywy94ywy** [comment]
+1

**Comment by chemieliu** [comment]
今天，mac环境下突然遇到了这样的问题

**Comment by A1Darkwing** [comment]
Not only me. Thank for reporting..

**Comment by nealchen2014** [comment]
me too...

**Comment by xiaohuoni** [comment]
如何复现？

**Comment by ycjcl868** [comment]
还有吗？

**Comment by Wmstone** [comment]
我换了浏览器就好了，感觉是浏览器有一下缓存或者cookie和umi里面冲突了
