### ISSUE TITLE
Path must be string: app fails top start after upgrading

### ISSUE THREAD

**Issue by cemremengu** [umijs/umi#4062]
## What happens?

```
Path must be a string.
TypeError: Path must be a string.
    at Function.resolveSync [as sync] (C:\Users\cemre.mengu\Desktop\synergy-web-app\node_modules\resolve\lib\sync.js:51:15)
    at C:\Users\cemre.mengu\Desktop\synergy-web-app\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js:109:29
    at Array.map (<anonymous>)
    at getPluginsOrPresets (C:\Users\cemre.mengu\Desktop\synergy-web-app\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js:108:99)
    at resolvePlugins (C:\Users\cemre.mengu\Desktop\synergy-web-app\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js:202:19)
    at new Service (C:\Users\cemre.mengu\Desktop\synergy-web-app\node_modules\@umijs\core\lib\Service\Service.js:176:59)
    at new Service (C:\Users\cemre.mengu\Desktop\synergy-web-app\node_modules\umi\lib\ServiceWithBuiltIn.js:50:5)
    at C:\Users\cemre.mengu\Desktop\synergy-web-app\node_modules\umi\lib\forkedDev.js:38:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\cemre.mengu\Desktop\synergy-web-app\node_modules\umi\lib\forkedDev.js:29:103)
```

## Mini Showcase Repository(REQUIRED)

```
// umirc

import { resolve } from 'path';
import aliyunTheme from '@ant-design/aliyun-theme';

export default {
  treeShaking: true,
  theme: {
    ...aliyunTheme,
  },
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    [
      'umi-plugin-react',
      {
        antd: true,
        dva: { immer: true },
        dynamicImport: { webpackChunkName: true },
        dll: true,
        title: 'Synergy',
        routes: {
          exclude: [
            /models\//,
            /services\//,
            /model\.(t|j)sx?$/,
            /service\.(t|j)sx?$/,
            /components\//,
          ],
        },
      },
    ],
  ],
  alias: {
    components: resolve(__dirname, './src/components'),
    themes: resolve(__dirname, './src/themes'),
    utils: resolve(__dirname, './src/utils'),
    assets: resolve(__dirname, './src/assets'),
  },
};
```
## How To Reproduce

`npm start`

## Context

- **Umi Version: *3.0.2*
- **antd: *4.0.0*
- **Node Version: *12.x*
- **Platform: *Windows*

**Comment by hzgotb** [comment]
Your config must be change.
See also : https://umijs.org/guide/upgrade-antd-pro-to-umi-3

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
