### ISSUE TITLE
SyntaxError: unknown: Unexpected token (10:10)

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#412]
clone了umi的项目
安装完插件之后，执行
```base
D:\work\umi>node scripts/build.js
```
```js
[TRANSFORM] D:\work\umi\packages\umi\src\build.js
[TRANSFORM] D:\work\umi\packages\af-webpack\src\build.js
[TRANSFORM] D:\work\umi\packages\umi-build-dev\src\Compiling.js
D:\work\umi\node_modules\@babel\core\lib\transformation\normalize-file.js:175
    throw err;
    ^

SyntaxError: unknown: Unexpected token (10:11)

   8 |   }
   9 |   render() {
> 10 |     return <div>Compiling...</div>;
     |            ^
  11 |   }
  12 | }
  13 |
    at Parser.raise (D:\work\umi\node_modules\babylon\lib\index.js:779:15)
    at Parser.unexpected (D:\work\umi\node_modules\babylon\lib\index.js:2082:16)
    at Parser.parseExprAtom (D:\work\umi\node_modules\babylon\lib\index.js:3158:20)
    at Parser.parseExprSubscripts (D:\work\umi\node_modules\babylon\lib\index.js:2758:21)
    at Parser.parseMaybeUnary (D:\work\umi\node_modules\babylon\lib\index.js:2737:21)
    at Parser.parseExprOps (D:\work\umi\node_modules\babylon\lib\index.js:2646:21)
    at Parser.parseMaybeConditional (D:\work\umi\node_modules\babylon\lib\index.js:2618:21)
    at Parser.parseMaybeAssign (D:\work\umi\node_modules\babylon\lib\index.js:2565:21)
    at Parser.parseExpression (D:\work\umi\node_modules\babylon\lib\index.js:2518:21)
    at Parser.parseReturnStatement (D:\work\umi\node_modules\babylon\lib\index.js:4311:28)

```
定位错误是
```js
import React, { Component } from 'react';

class Compiling extends Component {
  componentDidMount() {
    new Image().src = `${window.resourceBaseUrl}__umi_dev/compiling${
      this.props.route
    }`;
  }
  render() {
    return <div>Compiling...</div>; //这里错误
  }
}

export default Compiling;
```
没看出有什么错误，请问这个问题怎么修复

**Comment by xiaohuoni** [comment]
补充一句，环境是win10

**Comment by sorrycc** [comment]
umi 本身的 build 脚本不支持 windows 系统的，应该是路径问题，有兴趣可以提 PR。
