### ISSUE TITLE
crash after update to 3.0

### ISSUE THREAD

**Issue by nguyenhuutinh** [umijs/umi#4124]
$ cross-env ENV=staging COUNTRY=hk umi dev
Path must be a string.
TypeError: Path must be a string.
    at Function.resolveSync [as sync] (/Users/nguyenhuutinh/THProjects/oldhenry-vn/oldhenry-vn/node_modules/resolve/lib/sync.js:51:15)
    at /Users/nguyenhuutinh/THProjects/oldhenry-vn/oldhenry-vn/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:109:29
    at Array.map (<anonymous>)
    at getPluginsOrPresets (/Users/nguyenhuutinh/THProjects/oldhenry-vn/oldhenry-vn/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:108:99)
    at resolvePlugins (/Users/nguyenhuutinh/THProjects/oldhenry-vn/oldhenry-vn/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:202:19)
    at new Service (/Users/nguyenhuutinh/THProjects/oldhenry-vn/oldhenry-vn/node_modules/@umijs/core/lib/Service/Service.js:177:59)
    at new Service (/Users/nguyenhuutinh/THProjects/oldhenry-vn/oldhenry-vn/node_modules/umi/lib/ServiceWithBuiltIn.js:50:5)
    at /Users/nguyenhuutinh/THProjects/oldhenry-vn/oldhenry-vn/node_modules/umi/lib/forkedDev.js:40:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/nguyenhuutinh/THProjects/oldhenry-vn/oldhenry-vn/node_modules/umi/lib/forkedDev.js:31:103)
✨  Done in 2.06s.

**Comment by rmlzy** [comment]
请问您是怎么解决的? 我也遇到了同样的问题

umi^2.13.0 版本没问题, umi^3.0.13 报错: `Path must be a string.`

我删除了 node_modules 重新安装后, 还是会报错

**Comment by rmlzy** [comment]
用 ant-design-pro 的用户不能直接升级 umi, 参照: 

https://github.com/ant-design/ant-design-pro/issues/6178
