### ISSUE TITLE
约定路由，无法重定向

### ISSUE THREAD

**Issue by paulzanmei** [umijs/umi#4138]
## 约定路由，无法重定向

约定路由  不同的全局 layout 方案。 使用 <Redirect to="/user/login"/> 重定向，不跳转。
报错不知道是不是这问题报的错：
index.js:1 uncaught at _callee3 at _callee3 
 at _callee7 
 at takeEvery 
 at _callee 
 at _callee 
 Error: TypeError: Cannot read property 'map' of undefined
    at formatter (http://localhost:8000/umi.js:187645:15)
    at fetchMenuData$ (http://localhost:8000/umi.js:187688:26)
    at tryCatch (http://localhost:8000/umi.js:162807:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/umi.js:163033:22)
    at Generator.prototype.<computed> [as next] (http://localhost:8000/umi.js:162859:21)
    at next (http://localhost:8000/umi.js:160841:27)
    at currCb (http://localhost:8000/umi.js:160918:7)
    at http://localhost:8000/umi.js:81788:17
    at http://localhost:8000/umi.js:80933:26
    at onError (http://localhost:8000/umi.js:81789:11)
    at sagaWithCatch$ (http://localhost:8000/umi.js:81213:13)
    at tryCatch (http://localhost:8000/umi.js:162807:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/umi.js:163033:22)
    at Generator.prototype.<computed> [as throw] (http://localhost:8000/umi.js:162859:21)
    at next (http://localhost:8000/umi.js:160819:32)
    at Object.currCb [as cont] (http://localhost:8000/umi.js:160918:7)
    at end (http://localhost:8000/umi.js:160886:23)
    at abort (http://localhost:8000/umi.js:160609:5)
    at Object.task.cont (http://localhost:8000/umi.js:160622:9)
    at next (http://localhost:8000/umi.js:160858:16)
    at currCb (http://localhost:8000/umi.js:160918:7)

**Comment by feibi** [comment]
你这是发请求报错了吧

**Comment by paulzanmei** [comment]
> 你这是发请求报错了吧
我是在发请求，处理错误回调 errorHandler 里面，判断status 如果是 401 就执行 Redirect 组件进行跳转到登入。  可是执行Redirect 组件的时候不跳转。   之前不是用约定路由的时候，这个跳转是生效的

**Comment by sorrycc** [comment]
`Cannot read property 'map' of undefined` 这类报错信息和框架无关，逻辑问题。

**Comment by paulzanmei** [comment]
> `Cannot read property 'map' of undefined` 这类报错信息和框架无关，逻辑问题。

那为什么，Redirect 重定向是不会跳转的。  在配置文件配置路由的方式是可以的。  换成了 约定路由就无效了

**Comment by wcdmax** [comment]
> > `Cannot read property 'map' of undefined` 这类报错信息和框架无关，逻辑问题。
> 
> 那为什么，Redirect 重定向是不会跳转的。 在配置文件配置路由的方式是可以的。 换成了 约定路由就无效了

我也遇到同样的问题，不知道怎么解决，希望官方能够给出解决方案
