### ISSUE TITLE
After upgrading to umi3, the JSX syntax is used to report errors in the model.jsx

### ISSUE THREAD

**Issue by erichDuanET** [umijs/umi#4141]
After upgrading to umi3, the JSX syntax is used to report errors in the model.jsx
升级umi3后，model中使用jsx语法报错

## What happens?
model.jsx 文件中，添加jsx语法代码(原生组件)：
```jsx
          item.renderFormItem = (text, props) => <div>1123</div>
```
执行umi dev 获得如下错误：
```
Unterminated regular expression (78:60)
SyntaxError: Unterminated regular expression (78:60)
    at Object._raise ({项目地址}/node_modules/@babel/parser/src/parser/location.js:233:45)
    at Object.raiseWithData ({项目地址}/node_modules/@babel/parser/src/parser/location.js:228:17)
    at Object.raise ({项目地址}/node_modules/@babel/parser/src/parser/location.js:212:17)
    at Object.readRegexp ({项目地址}/node_modules/@babel/parser/src/tokenizer/index.js:845:20)
    at Object.readToken_slash ({项目地址}/node_modules/@babel/parser/src/tokenizer/index.js:442:12)
    at Object.getTokenFromCode ({项目地址}/node_modules/@babel/parser/src/tokenizer/index.js:767:14)
    at Object.getTokenFromCode ({项目地址}/node_modules/@babel/parser/src/plugins/typescript/index.js:2527:22)
    at Object.nextToken ({项目地址}/node_modules/@babel/parser/src/tokenizer/index.js:240:12)
    at Object.next ({项目地址}/node_modules/@babel/parser/src/tokenizer/index.js:154:10)
    at Object.parseExprOp ({项目地址}/node_modules/@babel/parser/src/parser/expression.js:374:14)
```

model.jsx 文件中，添加jsx语法代码(React组件)：
```jsx
         item.renderFormItem = (text, props) => <TimePickerRange />;
```
执行umi dev 获得如下错误：
```
        Unexpected token, expected "," (78:66)
        SyntaxError: Unexpected token, expected "," (78:66)
            at Object._raise ({项目地址}/node_modules/@babel/parser/src/parser/location.js:233:45)
            at Object.raiseWithData ({项目地址}/node_modules/@babel/parser/src/parser/location.js:228:17)
            at Object.raise ({项目地址}/node_modules/@babel/parser/src/parser/location.js:212:17)
            at Object.unexpected ({项目地址}/node_modules/@babel/parser/src/parser/util.js:151:16)
            at Object.expect ({项目地址}/node_modules/@babel/parser/src/parser/util.js:131:28)
            at Object.tsParseDelimitedListWorker ({项目地址}/node_modules/@babel/parser/src/plugins/typescript/index.js:265:16)
            at Object.tsParseDelimitedList ({项目地址}/node_modules/@babel/parser/src/plugins/typescript/index.js:225:14)
            at Object.tsParseBracketedList ({项目地址}/node_modules/@babel/parser/src/plugins/typescript/index.js:287:27)
            at Object.tsParseTypeParameters ({项目地址}/node_modules/@babel/parser/src/plugins/typescript/index.js:387:26)
            at {项目地址}/node_modules/@babel/parser/src/plugins/typescript/index.js:2305:31
```

项目中未使用typescript

临时解决方案：
```jsx

          item.renderFormItem = (text, props) =>
            React.createElement(TimePickerRange, _extends({
              format: "HH:mm:ss",
            }, props));
```

## 复现步骤，错误日志以及相关配置

在model中添加jsx语法即可复现

## 相关环境信息

- **Umi 版本**：v3.0.7
- **antd**：v4.0.2
- **@ant-design/pro-layout**：^5.0.4
- **Node 版本**：v13.5.0
- **操作系统**：mac

**Comment by sorrycc** [comment]
model 里为啥要混合视图的部分？

**Comment by erichDuanET** [comment]
> model 里为啥要混合视图的部分？

在获取后台数据后，根据数据类型，生成protable的form渲染模版，多个业务组件在使用，统一走了公共的model

**Comment by erichDuanET** [comment]
https://github.com/umijs/umi/pull/409
its a feature，upgrading to umi3，report errors，😂
@sorrycc

**Comment by sorrycc** [comment]
可以先配这个绕过，https://umijs.org/plugins/plugin-dva#skipmodelvalidate
