### ISSUE TITLE
yarn create umi报错

### ISSUE THREAD

**Issue by xofox** [umijs/umi#4273]
## What happens?
安装 umi后，建立脚手架报错，
yarn add global umi
yarn create umi报错：
$ yarn create umi
yarn create v1.22.0
warning ../../../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@umijs/create-umi-app > @umijs/utils > @babel/register@7.8.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "generator-jhipster-vuejs > eslint-config-airbnb@17.1.0" has unmet peer dependency "eslint@^4.19.1 || ^5.3.0".
warning "generator-jhipster-vuejs > eslint-config-airbnb@17.1.0" has unmet peer dependency "eslint-plugin-import@^2.14.0".
warning "generator-jhipster-vuejs > eslint-config-airbnb@17.1.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.1.1".
warning "generator-jhipster-vuejs > eslint-config-airbnb@17.1.0" has unmet peer dependency "eslint-plugin-react@^7.11.0".
warning "generator-jhipster-vuejs > eslint-config-airbnb > eslint-config-airbnb-base@13.2.0" has unmet peer dependency "eslint@^4.19.1 || ^5.3.0".
warning "generator-jhipster-vuejs > eslint-config-airbnb > eslint-config-airbnb-base@13.2.0" has unmet peer dependency "eslint-plugin-import@^2.17.2".
[4/4] 🔨  Building fresh packages...
success Installed "create-umi@0.20.3" with binaries:
      - create-umi
internal/modules/cjs/loader.js:422
      throw e;
      ^

Error: Package exports for '/Users/fox/.config/yarn/global/node_modules/clipboardy' do not define a '.' subpath
    at resolveExports (internal/modules/cjs/loader.js:419:17)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/fox/.config/yarn/global/node_modules/create-umi/lib/run.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32) {
  code: 'MODULE_NOT_FOUND'
}
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-umi
Arguments:
Directory: /Users/fox/Documents/jswork/umijs-antd-pro-v4/demo
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

但是通过 yarn create @umijs/umi-app是正常的

## 最小可复现仓库
https://github.com/xofox/demo.git

## 相关环境信息

-  umi 3.0.4
-  node 13.0.1
-  macos

**Comment by ycjcl868** [comment]
未复现啊

**Comment by zhaihaoran** [comment]
我碰到类似的问题，n 模块重新安装node即可
