### ISSUE TITLE
http2 and https crash dev server

### ISSUE THREAD

**Issue by kapolos** [umijs/umi#4337]
## What happens?

Dev server dies.

This happens the moment I refresh the page after restarting the dev server:

```
App running at:
  - Local:   https://localhost:8000 (copy to clipboard failed)
  - Network: https://172.17.0.2:8000
internal/buffer.js:944
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:944:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:185:19)
    at Stream.<anonymous> (/code/app/node_modules/handle-thing/lib/handle.js:88:10)
    at Stream.emit (events.js:323:22)
    at endReadableNT (/code/app/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:1094:12)
```

## How To Reproduce

**Steps to reproduce the behavior:** 

Put this on `.umirc.js`:

```
  devServer: {
    https: true,
    http2: true
  }
```

**Expected behavior** 

Dev server should work.

## Context

- **Umi Version**: `^3.0.16`
- **Node Version**: `v12.16.1`
- **Platform**: Ubuntu 18.04, inside Docker

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
