### ISSUE TITLE
Maximum file size for umi build?

### ISSUE THREAD

**Issue by ltt1987** [umijs/umi#434]
umi build时，提示打包文件过大，请问是什么问题？
```
Skipping static resource "/Users/paul/Documents/demo/ybx-web-v2-dev/wx/dist/static/2.7a2d2c95.async.js" (8.67 MB) - max size is 2.1 MB
Total precache size is about 4.92 MB for 35 resources.
Build completed in 36.995s

Failed to compile.

Failed to minify the bundle. Error: 1.8e00438d.async.js from UglifyJs
Unexpected token: name (matches) [1.8e00438d.async.js:22649,5]
    at doneHandler (/Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/af-webpack/lib/build.js:91:27)
    at emitRecords.err (/Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at next (/Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/tapable/lib/Tapable.js:220:14)
    at callback (/Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/copy-webpack-plugin/dist/index.js:126:17)
    at Compiler.afterEmit (/Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/copy-webpack-plugin/dist/index.js:220:13)
    at next (/Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/tapable/lib/Tapable.js:220:14)
    at /Users/paul/Documents/demo/ybx-web-v2-dev/wx/node_modules/sw-precache-webpack-plugin/lib/index.js:98:18
    at <anonymous>
Read more here: http://bit.ly/2tRViJ9
```

**Comment by sorrycc** [comment]
和尺寸无关，参考 https://github.com/sorrycc/blog/issues/68
