### ISSUE TITLE
umi ui 创建项目后报错，config/config.js" 中配置的 "antd" 并非约定的配置项，请选择 "base, 

### ISSUE THREAD

**Issue by wusankai** [umijs/umi#4355]
## What happens?

config/config.js" 中配置的 "antd" 并非约定的配置项，请选择 "base, 。。。。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by wusankai** [comment]
Error: Attach Project of key f0b1f7 FAILED
ActiveProjectError: "...test/config/config.js" 中配置的 "antd" 并非约定的配置项，请选择 "base, chainWebpack, context, disableGlobalVariables, disableRedirectHoist, exportStatic, outputPath, plugins, routes, runtimePublicPath, singular, ssr, treeShaking, block, mountElementId, mock, history, alias, autoprefixer, babel, browserslist, chainConfig, copy, cssLoaderOptions, cssLoaderVersion, cssModulesExcludes, cssModulesWithAffix, cssnano, cssPublicPath, define, devServer, devtool, disableCSSModules, disableCSSSourceMap, disableDynamicImport, env, es5ImcompatibleVersions, externals, extraBabelIncludes, extraBabelPlugins, extraBabelPresets, extraPostCSSPlugins, generateCssModulesTypings, hash, ignoreMomentLocale, lessLoaderOptions, manifest, minimizer, proxy, publicPath, sass, styleLoader, stylus, terserJSOptions, theme, tsConfigFile, typescript, uglifyJSOptions, urlLoaderExcludes, targets" 中的一项
    at ...\AppData\Local\Yarn\Data\global\node_modules\umi-build-dev\lib\UserConfig.js:230:15
    at Array.forEach (<anonymous>)
    at UserConfig.getConfig (...\AppData\Local\Yarn\Data\global\node_modules\umi-build-dev\lib\UserConfig.js:219:25)
    at Service.init (...\AppData\Local\Yarn\Data\global\node_modules\umi-build-dev\lib\Service.js:403:31)
    at UmiUI.openProject (...\AppData\Local\Yarn\Data\global\node_modules\umi-ui\lib\UmiUI.js:360:17)
    at UmiUI.handleCoreData (...\AppData\Local\Yarn\Data\global\node_modules\umi-ui\lib\UmiUI.js:854:16)
    at SockJSConnection.<anonymous> (...\AppData\Local\Yarn\Data\global\node_modules\umi-ui\lib\UmiUI.js:1321:26)
    at SockJSConnection.emit (events.js:311:20)
    at Session.didMessage (...\AppData\Local\Yarn\Data\global\node_modules\sockjs\lib\transport.js:246:25)
    at WebSocketReceiver.didMessage (...\AppData\Local\Yarn\Data\global\node_modules\sockjs\lib\trans-websocket.js:104:39) {
  actions: [ { title: 'Back To Home', browserHandler: 'BACK_TO_HOME' } ],
  exception: true,
  title: 'Other Errors'
}

**Comment by wusankai** [comment]
项目创建后在本地可以跑起来，只是在Umi UI 里面点击Project List里面对应的项目就报错

**Comment by ycjcl868** [comment]
Umi UI 只适用于 umi 2.x，先用 UMI_UI=1 umi dev 的方式来使用 umi ui

**Comment by wusankai** [comment]
![image](https://user-images.githubusercontent.com/59362571/78127173-473e0100-7446-11ea-82d7-6d5ed51a7516.png)

**Comment by wusankai** [comment]
🚀 Starting Umi UI using umi@2.13.0...
⛽️ Ready on http://localhost:3000/
