### ISSUE TITLE
ANALYZE=1 umi build 报错,  不能进行分析

### ISSUE THREAD

**Issue by hopperhuang** [umijs/umi#4489]
## What happens?
ANALYZE=1 umi build 报错
```
Plugin user:/node_modules/umi-plugin-react/lib/index.js initialize failed, api.onOptionChange is not a function
TypeError: api.onOptionChange is not a function
    at _default (/Users/jiawei/Desktop/develop/zhuanye/node_modules/umi-plugin-react/lib/index.js:62:7)
    at plugins.forEach (/usr/local/lib/node_modules/umi/node_modules/umi-build-dev/lib/Service.js:306:9)
    at Array.forEach (<anonymous>)
    at Service.initPlugins (/usr/local/lib/node_modules/umi/node_modules/umi-build-dev/lib/Service.js:300:18)
    at Service.build (/usr/local/lib/node_modules/umi/node_modules/umi-build-dev/lib/Service.js:380:10)
    at Object.build [as default] (/usr/local/lib/node_modules/umi/node_modules/umi-build-dev/lib/build.js:14:18)
    at _default (/usr/local/lib/node_modules/umi/lib/build.js:19:52)
    at Object.<anonymous> (/usr/local/lib/node_modules/umi/lib/scripts/build.js:12:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
正常开发，然后 输入命令，分析打包情况
ANALYZE=1 umi build
**Expected behavior** 1. 2.
生成分析文件
## Context

package.json
```
{
  "private": true,
  "sideEffects": [
    "./src/global.js",
    "*.css",
    "*.less"
  ],
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "test": "umi test",
    "lint": "eslint {src,mock,tests}/**/*.{js,jsx} --fix",
    "precommit": "lint-staged"
  },
  "dependencies": {
    "@antv/data-set": "^0.11.4",
    "@antv/f2": "^3.6.3",
    "antd-mobile": "^2.3.1",
    "normalize.css": "^8.0.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "umi-hd": "^5.0.1"
  },
  "devDependencies": {
    "babel-eslint": "^9.0.0",
    "eslint": "^5.4.0",
    "eslint-config-umi": "^1.4.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "postcss-plugin-px2rem": "^0.8.1",
    "react-test-renderer": "^16.7.0",
    "umi": "^2.7.7",
    "umi-plugin-react": "^1.8.4",
    "vconsole-webpack-plugin": "^1.5.1"
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "eslint --fix",
      "git add"
    ]
  },
  "engines": {
    "node": ">=8.0.0"
  }
}

```

umirc:
```

const path = require('path')
// ref: https://umijs.org/config/
const px2rem = require('postcss-plugin-px2rem')
const vConsolePlugin = require('vconsole-webpack-plugin');
export default {
  treeShaking: true,
  exportStatic: true,
  hash: true,
  chainWebpack(config, { webpack }) {
    // 设置 alias
    // config.resolve.alias.set('a', 'path/to/a');

    // 删除进度条插件
    // config.plugins.delete('progress');
    // 配置vconsole
    config.plugin('vconsole')
      .use(vConsolePlugin, [{ filter: [], enable: true }])
    // 打印config 配置
    // console.log(config.toString(), 'webpack-config')
  },
  // routes: [
  //   {
  //     path: '/',
  //     component: '../layouts/index',
  //     routes: [
  //       { path: '/', component: '../pages/index' }
  //     ]
  //   }
  // ],
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      antd: true,
      dva: false,
      dynamicImport: { webpackChunkName: true, loadingComponent: './components/PageLoading/index' },
      title: 'zhuanye',
      dll: false,
      hd: false,
      fastClick: true,
      targets: {
        android: 5,
        ios: 7,
        chrome: 58,
        ie: 9,
      },
      alias: {
        '@': path.resolve(__dirname, 'src'),
      },
      metas: [
        {
          name: "apple-mobile-web-app-capable",
          content: "yes"
        },
        {
          "name": "apple-mobile-web-app-status-bar-style",
          "content": "black"
        },
        {
          "http-equiv": 'pragma',
          "content": 'no-cache'
        },
        {
          "http-equiv": "cache-control",
          content: "no-cache, no-store, must-revalidate"
        },
        {
          "http-equiv": "expires",
          "content": "Wed, 26 Feb 1999 08:21:57 GMT"
        },
        {
          "http-equiv": "expires",
          content: "0"
        },
        {
          "name": "format-detection",
          content: "telephone=no"
        },
        {
          name: "format-detection",
          content: "email=no"
        },
      ],
      routes: {
        exclude: [
          /components\//,
        ],
      },
    }],
  ],
  extraPostCSSPlugins: [px2rem({ rootValue: 100 })],

}

```

- **Umi Version**:2.7.7
- **Node Version**:8.11.3
- **Platform**:macos

**Comment by ycjcl868** [comment]
把 umi-plugin-react 包从 package.json 删了

**Comment by ycjcl868** [comment]
是不是用了 umi 3，`npm ls umi` 看下

**Comment by hopperhuang** [comment]
> 是不是用了 umi 3，`npm ls umi` 看下

```
 umi@2.13.11 
```

**Comment by hopperhuang** [comment]
问题找到了吗 @ycjcl868

**Comment by onReadyL** [comment]
加个依赖 cross-env, 改成 cross-env ANALYZE=1 umi build,试试

**Comment by sorrycc** [comment]
这是 umi 3 里用了 umi 2 的插件，依赖重装试试。

**Comment by hopperhuang** [comment]
@sorrycc  还是不行 , package-lock.json文件和node_modules都删了重装过了，还是那样子的报错
版本如下：
```
umi@2.13.13
umi-plugin-react@1.15.8  
```

**Comment by xiaohuoni** [comment]
@hopperhuang 别猜了，给个复现demo吧。

**Comment by hopperhuang** [comment]
@xiaohuoni 
[demo地址](https://github.com/hopperhuang/umi_analyze_bug)在这里，本机可以复现。

麻烦了。

**Comment by xiaohuoni** [comment]
@hopperhuang 你给的demo有文件引用错误
![image](https://user-images.githubusercontent.com/11746742/80331338-67f94b00-887a-11ea-96b0-c45c20873bd0.png)

我注释掉之后。可以
![image](https://user-images.githubusercontent.com/11746742/80331323-5ca61f80-887a-11ea-91ba-41943b5088f3.png)

然后你的optimization 打包之后部署应该会有空白页的问题，你可以尝试添加https://v2.umijs.org/plugin/umi-plugin-react.html#chunks

**Comment by hopperhuang** [comment]
@xiaohuoni 
```
> fsevents@1.2.12 install /Users/jiawei/Desktop/develop/zhuanye/node_modules/jest-haste-map/node_modules/fsevents
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> node-pty@0.10.0-beta8 install /Users/jiawei/Desktop/develop/zhuanye/node_modules/node-pty
> node scripts/install.js

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node

> fsevents@1.2.12 install /Users/jiawei/Desktop/develop/zhuanye/node_modules/react-dev-utils/node_modules/fsevents
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.12 install /Users/jiawei/Desktop/develop/zhuanye/node_modules/watchpack/node_modules/fsevents
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.12 install /Users/jiawei/Desktop/develop/zhuanye/node_modules/webpack-dev-server/node_modules/fsevents
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
```

安装的时候node-gyp报的错误。会是webpack依赖了node-gyp，因而导致的错误吗？我一开始都没注意。但这报错是umi-plugin-react的问题，会跟这个问题相关吗？因为我本机是没有装x-code的。

**Comment by hopperhuang** [comment]
> @hopperhuang 你给的demo有文件引用错误
> ![image](https://user-images.githubusercontent.com/11746742/80331338-67f94b00-887a-11ea-96b0-c45c20873bd0.png)
> 
> 我注释掉之后。可以
> ![image](https://user-images.githubusercontent.com/11746742/80331323-5ca61f80-887a-11ea-91ba-41943b5088f3.png)
> 
> 然后你的optimization 打包之后部署应该会有空白页的问题，你可以尝试添加https://v2.umijs.org/plugin/umi-plugin-react.html#chunks

emmm，问题的关键在于，我没能进入到build的阶段，在umi调用插件的阶段就崩了。

**Comment by hopperhuang** [comment]
@xiaohuoni 
打印出来的api对象
```
PluginAPI {
  id: 'user:/node_modules/umi-plugin-react/lib/index.js',
  service: 
   Service {
     reload: [Function],
     printWarn: [Function],
     printError: [Function],
     restart: [Function],
     cwd: '/Users/jiawei/Desktop/develop/umi_bug/zhuanye',
     pluginFiles: [],
     babel: '/usr/local/lib/node_modules/umi/lib/babel',
     entryJSTpl: undefined,
     routerTpl: undefined,
     preact: undefined,
     extraResolveModules: [ '/usr/local/lib/node_modules/node_modules' ],
     libraryAlias: 
      { dynamic: '/usr/local/lib/node_modules/umi/lib/dynamic.js',
        link: '/usr/local/lib/node_modules/umi/lib/link.js',
        navlink: '/usr/local/lib/node_modules/umi/lib/navlink.js',
        redirect: '/usr/local/lib/node_modules/umi/lib/redirect.js',
        router: '/usr/local/lib/node_modules/umi/lib/router.js',
        withRouter: '/usr/local/lib/node_modules/umi/lib/withRouter.js',
        _renderRoutes: '/usr/local/lib/node_modules/umi/lib/renderRoutes.js',
        _createHistory: '/usr/local/lib/node_modules/umi/lib/createHistory.js' },
     libraryName: 'umi',
     staticDirectory: 'static',
     tmpDirectory: '.umi',
     outputPath: './dist',
     paths: 
      { cwd: '/Users/jiawei/Desktop/develop/umi_bug/zhuanye',
        outputPath: './dist',
        absOutputPath: '/Users/jiawei/Desktop/develop/umi_bug/zhuanye/dist',
        absNodeModulesPath: '/Users/jiawei/Desktop/develop/umi_bug/zhuanye/node_modules',
        pagesPath: 'src/pages',
        absPagesPath: '/Users/jiawei/Desktop/develop/umi_bug/zhuanye/src/pages',
        absSrcPath: '/Users/jiawei/Desktop/develop/umi_bug/zhuanye/src/',
        tmpDirPath: 'src/pages/.umi-production',
        absTmpDirPath: '/Users/jiawei/Desktop/develop/umi_bug/zhuanye/src/pages/.umi-production',
        absRouterJSPath: '/Users/jiawei/Desktop/develop/umi_bug/zhuanye/src/pages/.umi-production/router.js',
        absLibraryJSPath: '/Users/jiawei/Desktop/develop/umi_bug/zhuanye/src/pages/.umi-production/umi.js',
        absRegisterSWJSPath: '/Users/jiawei/Desktop/develop/umi_bug/zhuanye/src/pages/.umi-production/registerServiceWorker.js',
        absPageDocumentPath: '/Users/jiawei/Desktop/develop/umi_bug/zhuanye/src/pages/document.ejs',
        defaultEntryTplPath: '/usr/local/lib/node_modules/umi/node_modules/umi-build-dev/template/entry.js.tpl',
        defaultRouterTplPath: '/usr/local/lib/node_modules/umi/node_modules/umi-build-dev/template/router.js.tpl',
        defaultRegisterSWTplPath: '/usr/local/lib/node_modules/umi/node_modules/umi-build-dev/template/registerServiceWorker.js',
        defaultDocumentPath: '/usr/local/lib/node_modules/umi/node_modules/umi-build-dev/template/document.ejs',
        absCompilingComponentPath: '/usr/local/lib/node_modules/umi/node_modules/umi-build-dev/lib/Compiling.js' },
     pluginMethods: 
      { onStart: [Array],
        modifyConfigPlugins: [Array],
        modifyEntryFile: [Array],
        modifyPageWatchers: [Array],
        modifyAFWebpackOpts: [Array],
        beforeServerWithApp: [Array] },
     plugins: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     _initialConfig: 
      { treeShaking: true,
        exportStatic: true,
        hash: true,
        chainWebpack: [Function: chainWebpack],
        plugins: [Array],
        extraPostCSSPlugins: [Array] },
     config: 
      { treeShaking: true,
        exportStatic: true,
        hash: true,
        chainWebpack: [Function: chainWebpack],
        plugins: [Array],
        extraPostCSSPlugins: [Array] } },
  utils: 
   { _webpack: 
      { [Function: webpack]
        WebpackOptionsDefaulter: [Function: WebpackOptionsDefaulter],
        WebpackOptionsApply: [Function: WebpackOptionsApply],
        Compiler: [Object],
        MultiCompiler: [Function: MultiCompiler],
        NodeEnvironmentPlugin: [Function: NodeEnvironmentPlugin],
        validate: [Function: bound validateSchema],
        validateSchema: [Function: validateSchema],
        WebpackOptionsValidationError: [Function: WebpackOptionsValidationError],
        DefinePlugin: [Getter],
        NormalModuleReplacementPlugin: [Getter],
        ContextReplacementPlugin: [Getter],
        ContextExclusionPlugin: [Getter],
        IgnorePlugin: [Getter],
        WatchIgnorePlugin: [Getter],
        BannerPlugin: [Getter],
        PrefetchPlugin: [Getter],
        AutomaticPrefetchPlugin: [Getter],
        ProvidePlugin: [Getter],
        HotModuleReplacementPlugin: [Getter],
        SourceMapDevToolPlugin: [Getter],
        EvalSourceMapDevToolPlugin: [Getter],
        EvalDevToolModulePlugin: [Getter],
        CachePlugin: [Getter],
        ExtendedAPIPlugin: [Getter],
        ExternalsPlugin: [Getter],
        JsonpTemplatePlugin: [Getter],
        LibraryTemplatePlugin: [Getter],
        LoaderTargetPlugin: [Getter],
        MemoryOutputFileSystem: [Getter],
        ProgressPlugin: [Getter],
        SetVarMainTemplatePlugin: [Getter],
        UmdMainTemplatePlugin: [Getter],
        NoErrorsPlugin: [Getter],
        NoEmitOnErrorsPlugin: [Getter],
        NewWatchingPlugin: [Getter],
        EnvironmentPlugin: [Getter],
        DllPlugin: [Getter],
        DllReferencePlugin: [Getter],
        LoaderOptionsPlugin: [Getter],
        NamedModulesPlugin: [Getter],
        NamedChunksPlugin: [Getter],
        HashedModuleIdsPlugin: [Getter],
        ModuleFilenameHelpers: [Getter],
        optimize: [Object] },
     _afWebpackGetConfig: [Function: getConfig],
     _afWebpackBuild: [Function: build],
     _webpackHotDevClientPath: '/usr/local/lib/node_modules/umi/node_modules/af-webpack/lib/webpackHotDevClient.js',
     winPath: [Function: _default],
     debug: 
      { [Function: debug]
        namespace: 'umi-plugin: user:/node_modules/umi-plugin-react/lib/index.js',
        enabled: false,
        useColors: true,
        color: 1,
        destroy: [Function: destroy],
        inspectOpts: {} } },
  placeholder: 
   { IMPORT: '<%= IMPORT %>',
     RENDER: '<%= RENDER %>',
     ROUTER_MODIFIER: '<%= ROUTER_MODIFIER %>',
     ROUTES_MODIFIER: '<%= ROUTES_MODIFIER %>',
     HISTORY_MODIFIER: '<%= HISTORY_MODIFIER %>' } } 'api.......'
```

**Comment by hopperhuang** [comment]
@xiaohuoni  谢谢，问题好了。是我本地umi版本的问题。

**Comment by xiaohuoni** [comment]
@hopperhuang 👍
