### ISSUE TITLE
win10安装antd-pro模板出错：UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Rhuaer** [umijs/umi#4494]
## What happens?

Win10
1. yarn create umi
2. 选择：ant-design-pro
3. 提示错误：(node:8716) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'

## 最小可复现仓库

无

## 复现步骤，错误日志以及相关配置

1. yarn create umi
2. 选择：ant-design-pro
3. 提示错误：
```javascript
(node:8716) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
Referenced from: C:\Users\xiao\AppData\Local\Yarn\Data\global\node_modules\eslint-config-airbnb-typescript\index.js
Referenced from:
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at Plugins.load (C:\Users\xiao\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\plugins.js:104:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (C:\Users\xiao\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\plugins.js:165:21)
    at loadFromDisk (C:\Users\xiao\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\config-file.js:529:35)
    at load (C:\Users\xiao\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\config-file.js:587:20)
    at configExtends.reduceRight (C:\Users\xiao\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\config-file.js:453:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (C:\Users\xiao\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\config-file.js:431:26)
(node:8716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
4. 如果我先通过yarn global add @typescript-eslint/eslint-plugin，来安装这个包，则可以继续下一步

## 相关环境信息

- **Umi 版本**：
create-umi@0.21.3
- **Node 版本**：
10.20.0
- **操作系统**：
win10 19041.207

**Comment by Renderz** [comment]
mac 同样有这个问题, 想知道是怎么解决的.

**Comment by chenshuai2144** [comment]
升级一下node版本
