### ISSUE TITLE
umi build 过程中如果构建失败关键日志缺失，希望能优化一下

### ISSUE THREAD

**Issue by Carrotzpc** [umijs/umi#4512]
## umi build 过程中失败，日志只有一个 build failed，希望能优化一下

![image](https://user-images.githubusercontent.com/10265417/79945147-c94aa400-849f-11ea-950e-62b49b7b332b.png)

## 复现步骤，错误日志以及相关配置

umi 相关源码：

https://github.com/umijs/umi/blob/94f47a9039889244a95119056751d5bd1422d37c/packages/bundler-webpack/src/index.ts#L44-L50

源码中只处理了`stats.hasErrors() ` 的情况，没有处理 `err` ，修改源码打印出的 err 为：
```
err { JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 41.66666667%; - 15px
^..............^
    at /Users/zhangpc/Projects/app-stack-portal/p__Tenant__Quota.chunk.css:3224:3
    at Object.parseError (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/dist/parser.js:1200:15)
    at Object.lexer_parseError [as parseError] (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/dist/parser.js:2333:44)
    at Object.lexer_next [as next] (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/dist/parser.js:3328:22)
    at Object.lexer_fastLex [as fastLex] (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/dist/parser.js:3403:18)
    at fastLex (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/dist/parser.js:1603:27)
    at Parser.parse (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/dist/parser.js:1677:30)
    at /Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/dist/lib/transform.js:33:30
    at walk (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/walk.js:7:16)
    at ValueParser.walk (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/dist/lib/transform.js:66:100)
    at callback (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss-calc/dist/index.js:27:32)
    at callback (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss/lib/container.es6:110:18)
    at Rule.each (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss/lib/container.es6:76:16)
    at Rule.walk (/Users/zhangpc/Projects/app-stack-portal/node_modules/postcss/lib/container.es6:107:17)
    at /Users/zhangpc/Projects/app-stack-portal/node_modules/postcss/lib/container.es6:121:24
  hash:
   { errStr:
      'Lexical error on line 1: Unrecognized text.\n\n  Erroneous area:\n1: 41.66666667%; - 15px\n^..............^',
     recoverable: false,
     text: '',
     token: null,
     line: 0,
     loc:
      { first_line: 1,
        first_column: 12,
        last_line: 1,
        last_column: 12,
        range: [Array] },
     yy:
      { parseError: undefined,
        quoteName: undefined,
        lexer: undefined,
        parser: undefined,
        pre_parse: undefined,
        post_parse: undefined,
        pre_lex: undefined,
        post_lex: undefined },
     lexer:
      { yy: {},
        __decompressed: true,
        _input: '',
        yytext: '',
        yyleng: 0,
        match: '',
        matches: false,
        _more: false,
        _backtrack: false,
        yylloc: [Object],
        _signaled_error_token: false,
        done: false,
        yylineno: 0,
        matched: '',
        conditionStack: [Array],
        __currentRuleSet__: null,
        offset: 0 },
     destroy: [Function: destructLexErrorInfo] },
  postcssNode:
   Declaration {
     raws: { before: '\n  ', between: ':' },
     type: 'decl',
     parent:
      Rule {
        raws: [Object],
        type: 'rule',
        nodes: [Array],
        parent: [Root],
        source: [Object],
        selector: '.tenantQuota___1Ei5Y .part .content .content-item .right2',
        lastEach: 9,
        indexes: [Object] },
     source: { start: [Object], input: [Input], end: [Object] },
     prop: 'width',
     value: 'calc(41.66666667%; - 15px)' } }
```

不太了解 error 中应该要打印的部分，没有提 pr，可以说明下，我来提 pr。

## 相关环境信息

- **Umi 版本**：3.1.1
- **Node 版本**：10.19.0
- **操作系统**：macOS Catalina

**Comment by xiaohuoni** [comment]
@sorrycc cc

**Comment by backlost** [comment]
我们也遇到同样问题，服务器上报错导致没办法知道是什么原因。看这个问题有段时间了，求解决

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/82534743-37a28500-9b78-11ea-9875-b5c26a1254e1.png)

修过了
