### ISSUE TITLE
umi 插件配置

### ISSUE THREAD

**Issue by Guxing0321** [umijs/umi#4514]
Hi team,

根据umi 官网教程，发现umi 配置插件始终不成功

.umirc.ts 配置代码如下

 ```
  plugins: [
     [
       'umi-plugin-react',
       {
         antd: true,
         dva: true,
      },
    ],
   ],
```

console显示 Path must be a string.

然后查资料尝试安装 umi-plugin-react
yarn add umi-plugin-react
又开始报错

```
$ umi generate tmp
api.onOptionChange is not a function
TypeError: api.onOptionChange is not a function
    at _default (d:\git_clone\reactUmi\node_modules\umi-plugin-react\lib\index.js:62:7)
    at Service.initPlugin (d:\git_clone\reactUmi\node_modules\@umijs\core\lib\Service\Service.js:405:12)
    at Service.initPresetsAndPlugins (d:\git_clone\reactUmi\node_modules\@umijs\core\lib\Service\Service.js:313:12)
    at d:\git_clone\reactUmi\node_modules\@umijs\core\lib\Service\Service.js:227:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (d:\git_clone\reactUmi\node_modules\@umijs\core\lib\Service\Service.js:106:103)
    at _next (d:\git_clone\reactUmi\node_modules\@umijs\core\lib\Service\Service.js:108:194)
    at d:\git_clone\reactUmi\node_modules\@umijs\core\lib\Service\Service.js:108:364
    at new Promise (<anonymous>)
    at d:\git_clone\reactUmi\node_modules\@umijs\core\lib\Service\Service.js:108:97
error Command failed with exit code 1.
```

请问，有没有好的办法解决，已经被搞得头大了

node: v10.20.1
yarn:  1.21.1
脚手架： @umijs/umi-app

BR
Robin

**Comment by Guxing0321** [comment]
Hi， Team，

我同事跟我说，这个是umi版本的问题，
https://umijs.org/zh-CN/docs/upgrade-to-umi-3
根据这个链接改下配置就好了

BR
Robin

**Comment by vw331** [comment]
fuck !!!  https://www.yuque.com/ant-design/course/agmsgo

**Comment by xiaohuoni** [comment]
@vw331 教程是 umi@2 的版本

**Comment by swanf** [comment]
舍弃掉 umi-plugin-react，并在 package.json 中删掉     "umi-plugin-react": "^1.15.8" 这种代码，然后升级到 @umijs/preset-react 即可。详见：https://umijs.org/zh-CN/docs/upgrade-to-umi-3#%E5%8D%87%E7%BA%A7-umi-plugin-react-%E4%B8%BA-umijspreset-react
