### ISSUE TITLE
项目启动报错， UnhandledPromiseRejectionWarning: TypeError: text.trimEnd is not a function

### ISSUE THREAD

**Issue by gitchong** [umijs/umi#4575]
## What happens?

create-umi 创建的项目  选择的ant-design-pro模板
依赖安装启动后，浏览器访问8000端口时
抛出如下错误：

 App running at:
  - Local:   http://localhost:8000 (copied to clipboard)
  - Network: http://192.168.1.4:8000
(node:12788) UnhandledPromiseRejectionWarning: TypeError: text.trimEnd is not a function
    at attachComments (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:14769:60)
    at coreFormat (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:14796:23)
    at format (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:15017:75)
    at formatWithCursor (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:15033:12)
    at args (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:50675:12)
    at Object.format (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:50695:12)
    at ~\fang\p1\react-demo3\node_modules\_@umijs_core@3.1.2@@umijs\core\lib\Html\Html.js:275:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (~\fang\p1\react-demo3\node_modules\_@umijs_core@3.1.2@@umijs\core\lib\Html\Html.js:86:103)
    at _next (~\fang\p1\react-demo3\node_modules\_@umijs_core@3.1.2@@umijs\core\lib\Html\Html.js:88:194)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:12788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (re
jection id: 1)
(node:12788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12788) UnhandledPromiseRejectionWarning: TypeError: text.trimEnd is not a function
    at attachComments (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:14769:60)
    at coreFormat (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:14796:23)
    at format (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:15017:75)
    at formatWithCursor (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:15033:12)
    at args (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:50675:12)
    at Object.format (~\fang\p1\react-demo3\node_modules\_prettier@2.0.4@prettier\index.js:50695:12)
    at ~\fang\p1\react-demo3\node_modules\_@umijs_core@3.1.2@@umijs\core\lib\Html\Html.js:275:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (~\fang\p1\react-demo3\node_modules\_@umijs_core@3.1.2@@umijs\core\lib\Html\Html.js:86:103)
    at _next (~\fang\p1\react-demo3\node_modules\_@umijs_core@3.1.2@@umijs\core\lib\Html\Html.js:88:194)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:12788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (re
jection id: 2)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by stillyu** [comment]
node版本过低
