### ISSUE TITLE
umi build error when exportStatic=true

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#463]
## .umirc.js
```js
...
exportStatic: true,
```
## use
umi 1..3.0
run  `umi build`
## reproduce
[umi-examples/context](https://github.com/umijs/umi-examples/tree/master/context)
```js
{ Error: EISDIR: illegal operation on a directory, open 'F:\umi-examples\context\dist\index.html'
    at Object.fs.openSync (fs.js:646:18)
    at fs.writeFileSync (fs.js:1291:33)
...
```
[umi-examples/routes-with-child-routes-json](https://github.com/umijs/umi-examples/tree/master/routes-with-child-routes-json)
```js
{ Error: EEXIST: file already exists, mkdir 'F:\umi-examples\routes-with-child-routes-json\dist\index.html'
    at Object.fs.mkdirSync (fs.js:885:18)
...
```

**Comment by xiaohuoni** [comment]
使用
```js
exportStatic: {
    htmlSuffix: true,
}
```
没有错误。
