### ISSUE TITLE
添加自定义区块时，我司gitlab地址不能通过umi内置判断。

### ISSUE THREAD

**Issue by ChinaLiuRixing** [umijs/umi#4649]
umi版本：2.10.6
node版本：v11.15.0

报错信息如下：
`
> umi block add http://git.companyname.com/username/reponame/file
< Parse url and args✖  error     Error: http://git.companyname.com/username/reponame/file can't match any pattern
    at /Users/bjhl/Desktop/tree/code/work/fe-channel-manage/node_modules/umi-build-dev/lib/plugins/commands/block/download.js:237:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/bjhl/Desktop/tree/code/work/fe-channel-manage/node_modules/umi-build-dev/lib/plugins/commands/block/download.js:95:103)
    at _next (/Users/bjhl/Desktop/tree/code/work/fe-channel-manage/node_modules/umi-build-dev/lib/plugins/commands/block/download.js:97:194)
`

关注第一个报错信息，然后找到他的位置
`
```
 if (isGitUrl(url)) {
      realUrl = url;
      debug('is git url');
    } else if (/^[\w]+[\w\-\/]*$/.test(url)) {
      realUrl = `${defaultGitUrl}/tree/master/${url}`;
      debug(`will use ${realUrl} as the block url`);
    } else if (/^[\.\/]|^[c-zC-Z]:/.test(url)) {
      // ^[c-zC-Z]:  目的是为了支持window下的绝对路径，比如 `C:\\Project\\umi`
      // locale path for test
      const sourcePath = (0, _path().resolve)(process.cwd(), url);
      debug(`will use ${sourcePath} as the block url`);
      return {
        isLocal: true,
        sourcePath
      };
    } else {
      throw new Error(`${url} can't match any pattern`);
    }
```
`
在最后一个else中，抛出的错误。

是因为我们的gitlab地址不能被识别为git，即isGitUrl函数作用在我司gitlab地址上时，判断失误。

我司地址格式（已脱敏）：http://git.companyname.com/username/reponame/file

联系方式：15776556165

**Comment by ChinaLiuRixing** [comment]
追究到isGitUrl函数内部，

`
const gitSiteParser = /^(https\:\/\/|http\:\/\/|git\@)((github|gitlab)[\.\w\-]+|(?:(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))(\/|\:)([\w\-]+)\/([\w\-]+)(\/tree\/([\w\.\-]+)([\w\-\/]+))?(.git)?$/;

function isGitUrl(url) {
  return gitSiteParser.test(url);
}

`


是这个正则写的不够包容

**Comment by ChinaLiuRixing** [comment]
顺便问下，umi3怎么自定义区块
