### ISSUE TITLE
npm create umi，报错

### ISSUE THREAD

**Issue by runthinker** [umijs/umi#4675]
## What happens?

运行npm create umi ,选择ant-design-pro，再选择JavaScript，错误信息如下：
> [Sylvanas] Prepare js environment...
events.js:287
      throw er; // Unhandled 'error' event
      ^

SyntaxError: unknown: Unexpected token (24:12)

  22 | };
  23 |
> 24 | export type { DefaultSettings };
     |             ^
  25 |
  26 | export default proSettings;
  27 |
    at Object.raise (D:\Lib\yarn\global\node_modules\@babel\parser\lib\index.js:6325:17)
    at Object.unexpected (D:\Lib\yarn\global\node_modules\@babel\parser\lib\index.js:7642:16)
    at Object.parseIdentifierName (D:\Lib\yarn\global\node_modules\@babel\parser\lib\index.js:9521:18)
    at Object.parseIdentifier (D:\Lib\yarn\global\node_modules\@babel\parser\lib\index.js:9499:23)
    at Object.tsParseTypeAliasDeclaration (D:\Lib\yarn\global\node_modules\@babel\parser\lib\index.js:4785:20)
    at Object.tsParseDeclaration (D:\Lib\yarn\global\node_modules\@babel\parser\lib\index.js:5102:23)
    at Object.tsTryParseExportDeclaration (D:\Lib\yarn\global\node_modules\@babel\parser\lib\index.js:5011:17)
    at Object.parseExportDeclaration (D:\Lib\yarn\global\node_modules\@babel\parser\lib\index.js:5488:26)
    at Object.maybeParseExportDeclaration (D:\Lib\yarn\global\node_modules\@babel\parser\lib\index.js:10967:31)
    at Object.parseExport (D:\Lib\yarn\global\node_modules\@babel\parser\lib\index.js:10896:29)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (D:\Lib\yarn\global\node_modules\yeoman-generator\lib\index.js:436:22)
    at processImmediate (internal/timers.js:456:21) {
  pos: 441,
  loc: Position { line: 24, column: 12 },
  code: 'BABEL_PARSE_ERROR'
}

## 相关环境信息

- **Umi 版本**：3.1.4
- **Node 版本**：12.16.3
- **操作系统**：win10 64bit

**Comment by dongsongshan** [comment]
用 yarn 或者 tyarn

**Comment by kevinzl** [comment]
yarn 也是一样的报错

**Comment by jsdocker** [comment]
我也遇到，之前用的好好的

**Comment by DusuWen** [comment]
相同问题，使用umi ui, 选择 ant-design-pro typescript

**Comment by xiaohuoni** [comment]
@chenshuai2144 是不是又切到v5了？

**Comment by qiuwenkai** [comment]
@babel\parser版本问题，需要更新`yarn\global\node_modules\`以及`yarn\global\node_modules\sylvanas`模块内的`@babel\parser`模块版本

**Comment by chenshuai2144** [comment]
清空一下全局的依赖安装吧

**Comment by mtianyan** [comment]
yarn global remove create-umi yarn global remove prisma 成功修复

**Comment by SagittariusZhu** [comment]
```
{
  "dependencies": {
    "@ant-design/codemod-v4": "^1.0.2",
    "@umijs/create-umi-app": "^3.2.7",
    "create-umi": "^0.24.1",
    "serve": "^11.3.0"
  },
  "resolutions": {
    "create-umi/yeoman-generator": "4.5.0"
  }
}
```
确保你的~/.config/yarn/global/package.json内容如上所示，否则可以执行以下命令删除低版本的模块
```
yarn global remove create-umi
```
然后直接执行以下命令即可
```
yarn create umi
```
