### ISSUE TITLE
define属性指定process.env.contextPath问题

### ISSUE THREAD

**Issue by laishuliang** [umijs/umi#47]
`  "define": {
    "process.env.contextPath": process.env.contextPath,
  }`

这样定义出错，请问这样的方式怎样指定process.env中的值？

**Comment by sorrycc** [comment]
试过可以。。

**Comment by sorrycc** [comment]
我更新了这个例子，试试运行 `contextPath=111 roadhog dev`，https://github.com/sorrycc/roadhog/tree/master/examples/dead-simple

**Comment by laishuliang** [comment]
在antd pro项目的.webpackrc中增加以下定义，可以还原此编译问题，
`  "define": {
    "process.env.contextPath": process.env.contextPath,
  },`

控制台打印编译出错信息：
`Watch handler failed, since Unexpected token p in JSON at position 148
SyntaxError: Unexpected token p in JSON at position 148
    at JSON.parse (<anonymous>)
    at getUserConfig (D:\work\lorcan\git\frontend\sinogear-frontend-blank\node_modules\af-webpack\lib\getUserConfig\index.js:118:19)
    at FSWatcher.watchConfigs.on (D:\work\lorcan\git\frontend\sinogear-frontend-blank\node_modules\af-webpack\lib\getUserConfig\index.js:191:32)
    at emitThree (events.js:135:13)
    at FSWatcher.emit (events.js:216:7)
    at FSWatcher.<anonymous> (D:\work\lorcan\git\frontend\sinogear-frontend-blank\node_modules\chokidar\index.js:197:38)
    at FSWatcher._emit (D:\work\lorcan\git\frontend\sinogear-frontend-blank\node_modules\chokidar\index.js:238:5)
    at FSWatcher.<anonymous> (D:\work\lorcan\git\frontend\sinogear-frontend-blank\node_modules\chokidar\lib\nodefs-handler.js:263:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
`

**Comment by sorrycc** [comment]
检查 JSON，多了个逗号。

**Comment by laishuliang** [comment]
检查去掉了还是同样的编译错误。

**Comment by laishuliang** [comment]
或且说，像下面运行脚本

`"dev": "cross-env DISABLE_ESLINT=true contextPath=http://localhost BROWSER=none HOST=0.0.0.0 roadhog dev",`

如何在项目代码中获取contextPath或其它变量的设值？

**Comment by laishuliang** [comment]
或且说，像下面运行脚本

`"dev": "cross-env DISABLE_ESLINT=true contextPath=http://localhost:8000 BROWSER=none HOST=0.0.0.0 roadhog dev",`

如何在项目代码中获取contextPath或其它变量的设值？

**Comment by laishuliang** [comment]
可以了。谢谢！

是要使用`.webpackrc.js`，不是`.webpackrc`的配置文件，

为什么要搞二种配置文件写法呢，应该用那种，有什么区别呢？
