### ISSUE TITLE
yarn install fail

### ISSUE THREAD

**Issue by luminous6** [umijs/umi#4749]
## What happens?
yarn install fail

yarn install 最后一步的时候出现错误
[4/4] Building fresh packages...
$ umi generate tmp
Unexpected token (101:91)
SyntaxError: Unexpected token (101:91)
    at Object._raise (F:\shangyou\syh-cms-umijs-tri\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\location.js:241:45)
    at Object.raiseWithData (F:\shangyou\syh-cms-umijs-tri\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\location.js:236:17)
    at Object.raise (F:\shangyou\syh-cms-umijs-tri\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\location.js:220:17)
    at Object.unexpected (F:\shangyou\syh-cms-umijs-tri\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\util.js:149:16)
    at Object.parseExprAtom (F:\shangyou\syh-cms-umijs-tri\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\expression.js:1144:20)
    at Object.parseExprAtom (F:\shangyou\syh-cms-umijs-tri\node_modules\@umijs\utils\node_modules\@babel\parser\src\plugins\jsx\index.js:532:22)
    at Object.parseExprSubscripts (F:\shangyou\syh-cms-umijs-tri\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\expression.js:539:23)
    at Object.parseMaybeUnary (F:\shangyou\syh-cms-umijs-tri\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\expression.js:519:21)
    at Object.parseMaybeUnary (F:\shangyou\syh-cms-umijs-tri\node_modules\@umijs\utils\node_modules\@babel\parser\src\plugins\typescript\index.js:2417:22)
    at Object.parseExprOps (F:\shangyou\syh-cms-umijs-tri\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\expression.js:311:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：12.16.1
- [**操作系统**：]win10

**Comment by xiaohuoni** [comment]
安装失败都是网络问题，你要自行排查。
