### ISSUE TITLE
config 支持依赖 src 目录中的文件

### ISSUE THREAD

**Issue by alwaysRemember** [umijs/umi#4773]
## What happens?

在config文件中引入同文件夹的routes.ts文件，routes.ts中引入了src/interface/global.ts后无法正常的执行
## Mini Showcase Repository(REQUIRED)

https://github.com/alwaysRemember/koala_background_system

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
```
{ Error: Cannot find module '@/enums/UserAuthEnum'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/tang/Documents/myProject/koala/backgorund_system/config/routes.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._compile (/Users/tang/Documents/myProject/koala/backgorund_system/node_modules/_pirates@4.0.1@pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.newLoader [as .ts] (/Users/tang/Documents/myProject/koala/backgorund_system/node_modules/_pirates@4.0.1@pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:600:32) code: 'MODULE_NOT_FOUND' }
Could not resolve "/Users/tang/Documents/myProject/koala/backgorund_system/src/interface/global" in file /Users/tang/Documents/myProject/koala/backgorund_system/config/routes.ts.
Could not resolve "/Users/tang/Documents/myProject/koala/backgorund_system/src/enums/UserAuthEnum" in file /Users/tang/Documents/myProject/koala/backgorund_system/config/routes.ts.
/Users/tang/Documents/myProject/koala/backgorund_system/src/enums/UserAuthEnum.ts:12
export enum EUserAuth {
```
使用：
```
import { IRouteData } from '@/interface/global';
import { EUserAuth } from '@/enums/UserAuthEnum';
const routers: Array<IRouteData> = [
  {
    path: '/login',
    component: './Login',
    meta: {
      auth: EUserAuth.PUBLIC,
      title: '用户登录',
    },
  },
];
```

**Expected behavior** 1. 2.

## Context

- **Umi Version**:2.9
- **Node Version**:10.15.3
- **Platform**:mac os 10.14.5

**Comment by alwaysRemember** [comment]
使用vscode快捷键是可以访问的

**Comment by xiaohuoni** [comment]
这个问题一直存在，config目录下不能引用config之外的文件

**Comment by alwaysRemember** [comment]
@xiaohuoni  那如果说要根据路由来写个菜单列表岂不是相当于要写两份类似路由配置的文件了。。

**Comment by xiaohuoni** [comment]
@sorrycc 这个看一下怎么处理比较好？

**Comment by alwaysRemember** [comment]
@xiaohuoni 我尝试使用  patchRoutes 方法动态的新增一个路由进去，发现两个问题。

1. 文档错误: 文档中写的参数是一个对象，但实际为一个数组（我当前已存在路由的数组）。
2. 按照文档写的方式直接操作routes修改，不生效，打印发现routes是已经塞入了我的login路由，但实际访问的时候未生效，不知是我代码问题还是其他问题

```
export function patchRoutes(routes: any) {
  routes = routes.concat(routerList);
}

```

路由文件:
```
const routers: Array<IRoute> = [
  {
    path: '/login',
    component: require("./pages/Login").default,
    meta: {
      title: '用户登录',
    },
  },
];

export default routers;
```

**Comment by alwaysRemember** [comment]
而且 **运行时配置** 这个文档是否不完整，有一些其他的方法比如：modifyRouteProps，这个方法并不存在，但是我确实可以用

**Comment by alwaysRemember** [comment]
@xiaohuoni 你好，我发现一个侧向可以解决这个问题的方法，既然config中无法引入src的内容，我无非就是在乎需要写两份路由表这个问题，那么可以直接在src中写一份路由文件，然后使用**patchRoutes** 方法进行动态的路由添加。但是这样的话我不确定是否会造成性能方面的问题，因为我每次路由切换的时候，都会执行 **patchRoutes**这个方法。
