### ISSUE TITLE
model.js 内包含 react 代码导致 umi dev指令退出，报错信息无帮助

### ISSUE THREAD

**Issue by shengliangli** [umijs/umi#4780]
## What happens?

umijs 3.x ，pages 目录下的一个 react 组件不小心命名为 model.js，刚好符合了 model 的命名约定，导致 umi dev 命令出错退出，报错信息无法定位。

报错信息如下：
```
cross-env PORT=8000 umi dev
Unterminated regular expression (4:19)
SyntaxError: Unexpected token, expected "</>/<=/>=" (11:10)
    at Object._raise (D:\git\cenbdp\console\sjtptb\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\location.js:241:45)
    at Object.raiseWithData (D:\git\cenbdp\console\sjtptb\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\location.js:236:17)
    at Object.raise (D:\git\cenbdp\console\sjtptb\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\location.js:220:17)
    at Object.unexpected (D:\git\cenbdp\console\sjtptb\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\util.js:149:16)
    at Object.expectRelational (D:\git\cenbdp\console\sjtptb\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\util.js:56:12)
    at Object.tsParseTypeAssertion (D:\git\cenbdp\console\sjtptb\node_modules\@umijs\utils\node_modules\@babel\parser\src\plugins\typescript\index.js:1114:12)
    at Object.parseMaybeUnary (D:\git\cenbdp\console\sjtptb\node_modules\@umijs\utils\node_modules\@babel\parser\src\plugins\typescript\index.js:2415:21) 
    at Object.parseExprOps (D:\git\cenbdp\console\sjtptb\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\expression.js:311:23)
    at Object.parseMaybeConditional (D:\git\cenbdp\console\sjtptb\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\expression.js:263:23)   
    at Object.parseMaybeAssign (D:\git\cenbdp\console\sjtptb\node_modules\@umijs\utils\node_modules\@babel\parser\src\parser\expression.js:211:21)        
Done in 4.13s.
```

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

 https://github.com/shengliangli/umi-test-for-model-js

## 复现步骤，错误日志以及相关配置

yarn 安装阶段就会出错，提示 umi general temp 失败，把 src/pages/test/model.js 改名为 modal.js后才能继续。

恢复 model.js 名称，执行 umi dev ，报错，改名为其他名称后，umi dev 正常

## 相关环境信息

- **Umi [版本**：3.x](url)
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
有些约定的文件名，尽量不要使用，然后你的 model 是怎么写的，不满足 dva model 的场景应该会被忽略才对

**Comment by shengliangli** [comment]
提这个 issue 的目的是希望提升 umi 本身的健壮性

**Comment by xiaohuoni** [comment]
@shengliangli 嗯，我是问你的 model 是怎么写的。可能有没覆盖到的场景

**Comment by shengliangli** [comment]
@xiaohuoni 见 https://github.com/shengliangli/umi-test-for-model-js

**Comment by xiaohuoni** [comment]
我的错误不同，但应该是个 bug
```
Unterminated regular expression (4:19)
SyntaxError: Unterminated regular expression (4:19)
    at Object._raise (/Users/xiaohuoni/Downloads/umi-test-for-model-js-master/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/location.js:241:45)
    at Object.raiseWithData (/Users/xiaohuoni/Downloads/umi-test-for-model-js-master/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/location.js:236:17)
    at Object.raise (/Users/xiaohuoni/Downloads/umi-test-for-model-js-master/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/location.js:220:17)
    at Object.readRegexp (/Users/xiaohuoni/Downloads/umi-test-for-model-js-master/node_modules/@umijs/utils/node_modules/@babel/parser/src/tokenizer/index.js:929:20)
    at Object.readToken_slash (/Users/xiaohuoni/Downloads/umi-test-for-model-js-master/node_modules/@umijs/utils/node_modules/@babel/parser/src/tokenizer/index.js:463:12)
    at Object.getTokenFromCode (/Users/xiaohuoni/Downloads/umi-test-for-model-js-master/node_modules/@umijs/utils/node_modules/@babel/parser/src/tokenizer/index.js:851:14)
    at Object.getTokenFromCode (/Users/xiaohuoni/Downloads/umi-test-for-model-js-master/node_modules/@umijs/utils/node_modules/@babel/parser/src/plugins/typescript/index.js:2576:22)
    at Object.nextToken (/Users/xiaohuoni/Downloads/umi-test-for-model-js-master/node_modules/@umijs/utils/node_modules/@babel/parser/src/tokenizer/index.js:239:12)
    at Object.next (/Users/xiaohuoni/Downloads/umi-test-for-model-js-master/node_modules/@umijs/utils/node_modules/@babel/parser/src/tokenizer/index.js:154:10)
    at Object.parseExprOp (/Users/xiaohuoni/Downloads/umi-test-for-model-js-master/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/expression.js:375:14)
✨  Done in 2.47s.
```

**Comment by xiaohuoni** [comment]
可以先配这个绕过，https://umijs.org/plugins/plugin-dva#skipmodelvalidate
和这个问题相同 https://github.com/umijs/umi/issues/4141 这边跟进

**Comment by q269384828** [comment]
我是想着升级到3.2 的,之前用的是 2.x, 搞了一圈发现是这个问题就不弄了, 应该不是model 的问题, 可能是其他地方的types 要重新引用了, 也不说清楚, 然后就放弃了
Unexpected token (36:75)
SyntaxError: Unexpected token (36:75)
