### ISSUE TITLE
[Feature Request]  cross-env ANALYZE=1 umi build 出现端口错误

### ISSUE THREAD

**Issue by tomgao365** [umijs/umi#4824]
## What happens?

执行 `cross-env ANALYZE=1 umi build` 出现端口的错误。如果是端口占用错误，是否可以增加环境变量 `ANALYZE_PORT` 来支持自定义端口
```bash
√ Webpack
  Compiled successfully in 28.89s

 DONE  Compiled successfully in 28892ms                                                                                                                                                       16:10:00
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 127.0.0.1:8888
    at Server.setupListenHandle [as _listen2] (net.js:1292:21)
    at listenInCluster (net.js:1357:12)
    at doListen (net.js:1496:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1336:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8888
}
```

## Mini Showcase Repository(REQUIRED)

antd pro 最新仓库
https://github.com/ant-design/ant-design-pro/tree/v5

## Context

- **Umi Version**: 3.2.3
- **Node Version**: 12.16.1
- **Platform**: windows 10 1909

**Comment by tomgao365** [comment]
可以通过修改 config/config.ts 里的 analyze 配置来重新定义端口
```js
analyze:{
	analyzerPort: 8686,
}
```
