### ISSUE TITLE
umi2.8.13升级到umi3.2.3后，npm dev后报错“Path must be a string.”

### ISSUE THREAD

**Issue by tsinglemon** [umijs/umi#4847]
Path must be a string.
TypeError: Path must be a string.
    at Function.resolveSync [as sync] (E:\sxdit_ttyy_manage_umi\node_modules\@umijs\utils\node_modules\resolve\lib\sync.js:53:15)
    at map.path (E:\sxdit_ttyy_manage_umi\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js:90:29)
    at Array.map (<anonymous>)
    at getPluginsOrPresets (E:\sxdit_ttyy_manage_umi\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js:89:99)
    at resolvePlugins (E:\sxdit_ttyy_manage_umi\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js:183:19)
    at new Service (E:\sxdit_ttyy_manage_umi\node_modules\@umijs\core\lib\Service\Service.js:183:59)
    at new Service (E:\sxdit_ttyy_manage_umi\node_modules\umi\lib\ServiceWithBuiltIn.js:50:5)
    at E:\sxdit_ttyy_manage_umi\node_modules\umi\lib\forkedDev.js:40:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\sxdit_ttyy_manage_umi\node_modules\umi\lib\forkedDev.js:31:103)
    at _next (E:\sxdit_ttyy_manage_umi\node_modules\umi\lib\forkedDev.js:33:194)
    at E:\sxdit_ttyy_manage_umi\node_modules\umi\lib\forkedDev.js:33:364
    at new Promise (<anonymous>)
    at E:\sxdit_ttyy_manage_umi\node_modules\umi\lib\forkedDev.js:33:97
    at Object.<anonymous> (E:\sxdit_ttyy_manage_umi\node_modules\umi\lib\forkedDev.js:74:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

**Comment by leftstick** [comment]
按照[文档](https://umijs.org/docs/upgrade-to-umi-3)操作了么，如果已按照文档操作，请提供可复现repo

**Comment by tsinglemon** [comment]
这个问题解决了。
是umi3把某些配置项删掉和需要把`umi-plugin-pro-block`相关的参数都改成false才行。
这点是透过报错信息里指向的代码里发现的，文档上并没有标记出把`umi-plugin-pro-block`相关的参数都改成false；
