### ISSUE TITLE
examples/ssr-with-eggjs 运行失败

### ISSUE THREAD

**Issue by appzk** [umijs/umi#4863]
## What happens?

2020-06-11 13:44:02,209 INFO 14793 [master] egg started on http://127.0.0.1:7001 (2143ms) with STICKY MODE!
{ Error: Cannot find module 'umi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/fugang/workspace/umi/examples/ssr-with-eggjs/app/web/config/config.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (/Users/fugang/.nvm/versions/node/v10.16.0/lib/node_modules/umi/node_modules/_pirates@4.0.1@pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .ts] (/Users/fugang/.nvm/versions/node/v10.16.0/lib/node_modules/umi/node_modules/_pirates@4.0.1@pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32) code: 'MODULE_NOT_FOUND' }
/Users/fugang/.nvm/versions/node/v10.16.0/lib/node_modules/umi/node_modules/_umi-build-dev@1.10.17@umi-build-dev/lib/UserConfig.js:97
      throw new Error(msg);
      ^

Error: 配置文件 "config/config.ts" 解析出错，请检查语法。

Error: Cannot find module 'umi'

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

最小可复现仓库
https://github.com/umijs/umi/tree/master/examples/ssr-with-eggjs

复现步骤，错误日志以及相关配置
cnpm i
npm run dev

解决方案：
cnpm i umi

相关环境信息
Node 版本：10.16.0
操作系统：mac osx 10.14.6

**Comment by williamnie** [comment]
yarn add umi 安装一下umi

**Comment by appzk** [comment]
> yarn add umi 安装一下umi

我知道装umi,peerDependencies未起作用。是不是应该将umi放置在dependencies里面

"peerDependencies": {
    "umi": "latest"
  },

**Comment by williamnie** [comment]
> > yarn add umi 安装一下umi
> 
> 我知道装umi,peerDependencies未起作用。是不是应该将umi放置在dependencies里面
> 
> "peerDependencies": {
> "umi": "latest"
> },

可以
