### ISSUE TITLE
使用antd-pro的布局不仅需要开启配置layout: {}还要安装@ant-design/pro-layout包

### ISSUE THREAD

**Issue by wangyuan0108** [umijs/umi#4865]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：10.16.0
- **操作系统**：macOS 10.15.5

**Comment by wangyuan0108** [comment]
umi文档说只开启配置就行了，但是我试了下，开启配置之后会报错找不到这个包
```js
{ Error: Cannot find module '@ant-design/pro-layout'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at haveProLayout (/Users/wpwl/wy/wy_admin/node_modules/@umijs/plugin-layout/lib/index.js:76:13)
    at Object.api.onGenerateFiles [as fn] (/Users/wpwl/wy/wy_admin/node_modules/@umijs/plugin-layout/lib/index.js:155:62)
    at /Users/wpwl/wy/wy_admin/node_modules/@umijs/core/lib/Service/Service.js:570:28
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/wpwl/wy/wy_admin/node_modules/@umijs/core/lib/Service/Service.js:106:103)
    at _next (/Users/wpwl/wy/wy_admin/node_modules/@umijs/core/lib/Service/Service.js:108:194)
    at /Users/wpwl/wy/wy_admin/node_modules/@umijs/core/lib/Service/Service.js:108:364
    at new Promise (<anonymous>)
    at /Users/wpwl/wy/wy_admin/node_modules/@umijs/core/lib/Service/Service.js:108:97
    at _next10 (eval at create (/Users/wpwl/wy/wy_admin/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:68:18)
    at _promise10.then._result10 (eval at create (/Users/wpwl/wy/wy_admin/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:93:1)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
@umijs/plugin-layout 需要安装 ProLayout 才可运行
```

**Comment by leftstick** [comment]
`@ant-design/pro-layout` 需要用户自己手动安装，你的文档变更 pr 很棒，指出了这个问题。

**Comment by CarsonXin** [comment]
需要手动安装 `yarn install @ant-design/pro-layout`

**Comment by wangyuan0108** [comment]
@leftstick 我觉得刚使用新版，然后说配置开启就生效，结果报错，估计很多人会和我有一样的疑惑，就提了下，不是技术问题。。。。
