### ISSUE TITLE
使用 import 进来的 routes 文件配置 layout: false 无效

### ISSUE THREAD

**Issue by GuoQichen** [umijs/umi#4867]
## What happens?

在 `.umirc.js` 或者 `config/config.ts` 中，引用单独的 routes 文件，route 配置中的 layout 无效（不使用单独的 routes 文件配置有效）

## 最小可复现仓库

使用 `yarn create @umijs/umi-app` 新建项目，把配置中的 routes 提取到单独的文件就可以复现

## 复现步骤，错误日志以及相关配置

这样配置 layout: false 有效
```js
export default defineConfig({
  layout: {},
  nodeModulesTransform: {
    type: 'none',
  },
  routes: [
    { path: '/', layout: false, component: '@/pages/index' },
  ],
});
```

这样配置 layout: false 无效
```js
// .umirc.ts
import routes from './config/routes'
export default defineConfig({
  layout: {},
  nodeModulesTransform: {
    type: 'none',
  },
  routes,
});
```
```js
// config/routes.ts
export default [
  { path: '/', layout: false, component: '@/pages/index' },
]
```

## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：12.8.1
- **操作系统**：macOS

**Comment by nhanhaloli** [comment]
I create a new folder like you
`const routes = [
  {
    path: '/',
    exact: true,
    component: '@/pages/index'
  },
  {
    path: '/login',
    exact: true,
    component: '@/pages/login'
  },
]

export default routes`

And i import all of this into .umirc.ts and appear a error like this 
`nhan@nhan-MS-7B19:/media/nhan/Công việc/Nhan_Dev_Cashbag/cashbag-dashboard$ yarn start
yarn run v1.22.4
$ umi dev
Cannot find module '@/routes'
Error: Cannot find module '@/routes'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/media/nhan/Công việc/Nhan_Dev_Cashbag/cashbag-dashboard/.umirc.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/media/nhan/Công việc/Nhan_Dev_Cashbag/cashbag-dashboard/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .ts] (/media/nhan/Công việc/Nhan_Dev_Cashbag/cashbag-dashboard/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Done in 1.54s.`

I dont know how to fix it, any idea here, thank everyone

**Comment by leftstick** [comment]
@nhanhaloli  you import `routes`  module in `.umirc.ts` via `import routes from '@/routes'`, right ?

Try use relative path instead of `@/routes`, for example: `import routes from './routes'` (relative path depends on your module position relationship)

**Comment by leftstick** [comment]
@GuoQichen  按你的方法，没法复现

**Comment by GuoQichen** [comment]
@leftstick 稍后我提供一个复现的demo

**Comment by GuoQichen** [comment]
@leftstick 新建的项目确实已经没有这个问题了， 我之前建的项目在更新依赖后也没有问题了
