### ISSUE TITLE
按照官方文档安装并开启srr后，发现只要引用umi就会报错，不开ssr没问题

### ISSUE THREAD

**Issue by kwooshung** [umijs/umi#4914]
### 相关依赖的版本
```json
"dependencies": {
    "@ant-design/pro-layout": "^5.0.12",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.2.5",
    "ahooks": "^2.0.1",
    "antd": "^4.3.5",
    "lint-staged": "^10.0.7",
    "prettier": "^2.0.5",
    "rc-animate": "^3.1.0",
    "rc-banner-anim": "^2.4.4",
    "rc-queue-anim": "^1.8.5",
    "rc-scroll-anim": "^2.7.4",
    "rc-texty": "^0.2.0",
    "rc-tween-one": "^2.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "umi": "^3.2.5",
    "yorkie": "^2.0.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^3.4.0",
    "@typescript-eslint/parser": "^3.4.0",
    "babel-eslint": "^10.1.0",
    "css-loader": "^3.6.0",
    "eslint": "^7.3.1",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-jsx-control-statements": "^2.2.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.0",
    "less": "^3.11.3",
    "less-loader": "^6.1.2",
    "node-sass": "^4.14.1",
    "postcss-loader": "^3.0.0",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.2.1",
    "stylelint": "^13.6.1",
    "stylelint-config-recommended": "^3.0.0",
    "stylelint-config-standard": "^20.0.0",
    "stylelint-order": "^4.1.0",
    "stylelint-scss": "^3.18.0",
    "typescript": "^3.9.5"
  }
```

### 如下两段代码，均有报错，且内容都一样：
```jsx
import { Link } from 'umi';

<Link to="/">测试</Link>
```

```jsx
import { Helmet } from 'umi';

<Helmet>
    <meta charSet="utf-8" />
    <title>My Title</title>
    <link rel="canonical" href="http://mysite.com/example" />
</Helmet>
```

### 如下两段代码，均有报错且内容一样，如下图：
![image](https://user-images.githubusercontent.com/3413930/85888484-3ff77b00-b81c-11ea-8d41-47d0342c3c59.png)

#### 我把第二段代码第1行改为如下，就不报错了，但是使用此种方式引入umi其他的内容，还是报错。
```jsx
import { Helmet } from "react-helmet";

<Helmet>
    <meta charSet="utf-8" />
    <title>My Title</title>
    <link rel="canonical" href="http://mysite.com/example" />
</Helmet>
```

### 以下为我的 `.umirc.ts` 配置文件
```ts
import { defineConfig } from 'umi';

export default defineConfig({
    //根目录
    base: '/',
    //使用 CDN 部署，把 publicPath 的值设为 CDN 的值就可以
    publicPath: './',
    //标题，关闭，否则没法使用Helmet
    title: false,
    //服务器渲染
    ssr: {
        forceInitial: false,
        devServerRender: true,
        mode: 'stream',
        staticMarkup: true,
    },
    antd: {},
    dva: {
        immer: true,
        hmr: true
    },
    //按需加载
    dynamicImport: {},
    //浏览器兼容
    targets: {
        ie: 9,
    },
    //浏览器前缀
    autoprefixer: {
        //移除过时的前缀
        remove: true
    },
    //配置是否让生成的文件包含 hash 后缀
    hash: true,
    //配置图片文件是否走 base64 编译的阈值。默认是 10000 字节，少于他会被编译为 base64 编码，否则会生成单独的文件
    inlineLimit: 10000,
    //为所有非三方脚本加上 crossorigin="anonymous" 属性，通常用于统计脚本错误。
    crossorigin: true,
    // layout:{
    // theme: 'PRO',
    // loading: true,
    // },
    //国际化
    // locale: { antd: true },
    nodeModulesTransform: {
        type: 'none',
    },
    // 如果不配置约定式路由，则自动根据pages生成路由
    routes: [
        { path: '/', component: '@/pages/index' },
    ],
});

```

**Comment by ycjcl868** [comment]
刚在内部项目用了，没发现这个问题，给个复现试试

**Comment by kwooshung** [comment]
> 刚在内部项目用了，没发现这个问题，给个复现试试

git不知道为什么提交不上了，暂时放到百度帮盘了，而且还发现，路由最多2层，3层就找不到了比如xxx.com/a/b/c
找不到c这个页面。

可以的话，希望你们弄一个基础版本，我看看有什么区别
链接: https://pan.baidu.com/s/178dYlC5bSACvlCrdtrjdXA 提取码: fw2b

**Comment by kwooshung** [comment]
> 刚在内部项目用了，没发现这个问题，给个复现试试

嗯，git好了，我弄了一个最小测试版本，麻烦你们看下

`git@github.com:kwooshung/umitest.git`

**Comment by CassielLee** [comment]
你node版本是多少？可能是node版本的问题，我之前是14.0也有这样的问题，后面换成10.21.0就好了～

**Comment by leftstick** [comment]
@kwooshung  你给的repo：`git@github.com:kwooshung/umitest.git` 里，报的错是：

```
lugin-model: Invoking '@@initialState' model failed: ReferenceError: window is not defined
    at _default (/Users/github/umitest/dist/umi.server.js:687:32)
    at processChild (/Users/github/umitest/dist/umi.server.js:37420:14)
    at resolve (/Users/github/umitest/dist/umi.server.js:37337:5)
    at ReactDOMServerRenderer.render (/Users/github/umitest/dist/umi.server.js:37812:22)
    at ReactDOMServerRenderer.read (/Users/github/umitest/dist/umi.server.js:37750:29)
    at Object.renderToString (/Users/github/umitest/dist/umi.server.js:38365:27)
    at _callee3$ (/Users/github/umitest/dist/umi.server.js:976:102)
    at tryCatch (/Users/github/umitest/dist/umi.server.js:68218:40)
    at Generator.invoke [as _invoke] (/Users/github/umitest/dist/umi.server.js:68447:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/github/umitest/dist/umi.server.js:68270:21)
    at asyncGeneratorStep (/Users/github/umitest/dist/umi.server.js:761:103)
    at _next (/Users/github/umitest/dist/umi.server.js:763:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

貌似和你上面描述的问题不一样。如果是这个问题的话，那是因为`@umijs/plugin-model` 目前看起来还不支持ssr，所以解决方案页简单，不要直接装`@umijs/preset-react`，需要哪个插件装哪个就好了，在你提供的repo里，只需要

```
yarn add @umijs/plugin-helmet @umijs/plugin-request @umijs/plugin-antd
```

**Comment by ycjcl868** [comment]
> git@github.com:kwooshung/umitest.git

node 14 和 node 12 都没问题，试过

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi/pull/5486/files#diff-754d395d0bf281da5b546b90bcd4da3fR18-R20

可能是 engines 的问题，试下这样改能不能运行

**Comment by ycjcl868** [comment]
还有问题吗？
