### ISSUE TITLE
umi 1.3.3 运行 umi-antd-pro 出错

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#495]
更新umi相关插件
```js
"umi": "1.3.3",
"umi-plugin-dll": "^0.2.1",
 "umi-plugin-dva": "^0.7.2",
 "umi-plugin-routes": "0.1.4"
```
执行 npm start (umi dev)
报错
```js
Compiling...

  build [==                  ] 10%
F:\umi-antd-pro\node_modules\webpack\lib\Stats.js:223                                        text += `\n @ ${current.readableIdentifier(requestShortener)}`;
                             ^
RangeError: Invalid string length
    at formatError (F:\umi-antd-pro\node_modules\webpack\lib\Stats.js:223:30)
    at Array.map (<anonymous>)
    at Stats.toJson (F:\umi-antd-pro\node_modules\webpack\lib\Stats.js:231:56)
    at Server.sockServer.on (F:\umi-antd-pro\node_modules\webpack-dev-server\lib\Server.js:607:43)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at App.emit (F:\umi-antd-pro\node_modules\sockjs\lib\sockjs.js:196:29)
    at F:\umi-antd-pro\node_modules\sockjs\lib\transport.js:111:25
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
非必现，一次不报错可以，ctrl +c 关闭之后再执行 npm start
我的电脑，最多三次，就一定会报这个错。
可重新demo ：https://github.com/xiaohuoni/umi-antd-pro  （需要更新umi相关插件版本）

**Comment by sorrycc** [comment]
mac 下不报错，估计是新增的 hard-source-webpack-plugin 在 windows 下的兼容问题，禁用他运行试试还会不会报错，

```bash
$ HARD_SOURCE=none umi dev
```

**Comment by xiaohuoni** [comment]
在pro项目，禁用之后可以启动

**Comment by 472756921** [comment]
弱弱地问一句怎么禁用 hard-source-webpack-plugin

**Comment by xiaohuoni** [comment]
现在默认是禁用的吧
