### ISSUE TITLE
Path must be a string: 在安装了auto-external-packages 之后

### ISSUE THREAD

**Issue by CrazyOctopusDan** [umijs/umi#5045]
前因：
umi打包完之后发现umi.xxxx.js这个包有2.5M这么大，于是找解决方案，解决方案中说可以安装 `umi-plugin-auto-externals`
结果：
```
npm run dev 

Path must be a string.
TypeError: Path must be a string.
    at Function.resolveSync [as sync] (/Users/zhangyi/zhangyi/giti/giklinks-portal-web/node_modules/resolve/lib/sync.js:58:15)
    at /Users/zhangyi/zhangyi/giti/giklinks-portal-web/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:90:29
    at Array.map (<anonymous>)
    at getPluginsOrPresets (/Users/zhangyi/zhangyi/giti/giklinks-portal-web/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:89:99)
```
查看了以前的issue，说是可能是 `@umijs/preset-react` 没有更新到最新，但是我查了package.json，目前用的是umi3 + 最新的`@umijs/preset-react` 

找不到解决方案，只能先卸载这个包了。

**Comment by xiaohuoni** [comment]
auto-external-packages 这个包不维护了，不要用
