### ISSUE TITLE
缺陷: Maximum call stack size exceeded  umi3.2.0 node 12.14.0 mac

### ISSUE THREAD

**Issue by shwzh** [umijs/umi#5125]
## What happens?

yarn create umi 之后    umi3.2.0  
用npm i 安装依赖，（用yarn 装依赖，yarn run i18n-remove 命令会报错）

运行 npm run i18n-remove 之后 
再次运行 npm run start 
报错： 

Popup.js:187 Uncaught RangeError: Maximum call stack size exceeded
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:187)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:194)
    at Object.mergedMotion.<computed> [as onEnterStart] (Po
## 相关环境信息

- **Umi 版本   3.2.0**：
- **Node 版本  12.14.0**：
- **操作系统   mac**：

**Comment by shwzh** [comment]
issue

**Comment by xiaohuoni** [comment]
`i18n-remove` 做了啥？

**Comment by infnan** [comment]
我也碰到了类似问题，尝试
```
rm -rf node_modules
rm -rf src/.umi
npm i
```
（把node_modules和.umi两个目录都删掉）之后貌似就好了

**Comment by xiaohuoni** [comment]
缓存问题的话，其实删除 src/.umi/.cache 就可以。

**Comment by branchesgit** [comment]
Module build failed (from ./node_modules/@umijs/preset-dumi/lib/loader/index.js):
RangeError: Maximum call stack size exceeded
    at Set.add (<anonymous>)
    at watchers.forEach.item (/home/branches/branches/code/hqcontact/packages/hqcontact/node_modules/@umijs/preset-dumi/lib/utils/watcher.js:85:16)
    at Array.forEach (<anonymous>)
    at loop (/home/branches/branches/code/hqcontact/packages/hqcontact/node_modules/@umijs/preset-dumi/lib/utils/watcher.js:83:14)
    at watchers.forEach.item (/home/branches/branches/code/hqcontact/packages/hqcontact/node_modules/@umijs/preset-dumi/lib/utils/watcher.js:88:11)
    at Array.forEach (<anonymous>)
    at loop (/home/branches/branches/code/hqcontact/packages/hqcontact/node_modules/@umijs/preset-dumi/lib/utils/watcher.js:83:14)
    at watchers.forEach.item (/home/branches/branches/code/hqcontact/packages/hqcontact/node_modules/@umijs/preset-dumi/lib/utils/watcher.js:88:11)
    at Array.forEach (<anonymous>)
    at loop (/home/branches/branches/code/hqcontact/packages/hqcontact/node_modules/@umijs/preset-dumi/lib/utils/watcher.js:83:14)
    at watchers.forEach.item (/home/branches/branches/code/hqcontact/packages/hqcontact/node_modules/@umijs/preset-dumi/lib/utils/watcher.js:88:11)
    at Array.forEach (<anonymous>)
    at loop (/home/branches/branches/code/hqcontact/packages/hqcontact/node_modules/@umijs/preset-dumi/lib/utils/watcher.js:83:14)
    at watchers.forEach.item (/home/branches/branches/code/hqcontact/packages/hqcontact/node_modules/@umijs/preset-dumi/lib/utils/watcher.js:88:11)
    at Array.forEach (<anonymous>)
    at loop (/home/branches/branches/code/hqcontact/packages/hqcontact/node_modules/@umijs/preset-dumi/lib/utils/watcher.js:83:14)

 @ ./src/.umi/core/routes.ts 28:19-44
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

**Comment by ycjcl868** [comment]
还有吗？
