### ISSUE TITLE
按照官网配置chunks 和 chainWebpack，无法运行

### ISSUE THREAD

**Issue by H-Sven** [umijs/umi#5136]
```
chunks: ['vendors', 'umi'],
  chainWebpack: function (config, { webpack }) {
    config.merge({
      optimization: {
        minimize: true,
        splitChunks: {
          chunks: 'all',
          minSize: 30000,
          minChunks: 3,
          automaticNameDelimiter: '.',
          cacheGroups: {
            vendor: {
              name: 'vendors',
              test({ resource }) {
                return /[\\/]node_modules[\\/]/.test(resource);
              },
              priority: 10,
            },
          },
        },
      }
    });
  },
```

直接复制官网配置中的这一段代码到.umirc.ts中，
之后执行yarn start，进度条一直卡在80-90%

执行，yarn build 报错，报错信息如下
```
AssertionError [ERR_ASSERTION]: chunk of vendors not found.
    at C:\Users\win10\Desktop\ad-monitoring\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (C:\Users\win10\Desktop\ad-monitoring\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:93:14)
    at C:\Users\win10\Desktop\ad-monitoring\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:186:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\win10\Desktop\ad-monitoring\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:62:103)
    at _next (C:\Users\win10\Desktop\ad-monitoring\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:64:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

**Comment by aixfox** [comment]
webpack chain 推荐这么改 `config.optimization.splitChunks()`，可能是 merge 得不对。

**Comment by zhouyi318** [comment]
umi3 删除了 routes、library、dll、hardSource、pwa、hd、fastClick、chunks，不可继续使用

**Comment by H-Sven** [comment]
@zhouyi318 那怎么办啊

**Comment by xiaohuoni** [comment]
应该是可以的，你可以参考这个看看，https://zhuanlan.zhihu.com/p/157540425 过几天我整一个通用的文章

**Comment by imal1** [comment]
删掉minimize: true，它似乎有问题

**Comment by athrunsun** [comment]
> umi3 删除了 routes、library、dll、hardSource、pwa、hd、fastClick、chunks，不可继续使用

umi3 没有删除 chunks 配置项：https://umijs.org/zh-CN/config#chunks

**Comment by DevXiaolan** [comment]
这个怎么close了？看上去没解决啊。
我把 minChunks: 3, 改为 minChunks: 2, 就可以了，这些之间什么逻辑？

**Comment by athrunsun** [comment]
@DevXiaolan 可以参考下这个地方的讨论：https://github.com/umijs/umi/issues/5425

**Comment by Tironzx** [comment]
> 这个怎么close了？看上去没解决啊。 我把 minChunks: 3, 改为 minChunks: 2, 就可以了，这些之间什么逻辑？

我改了还是不行

**Comment by wangweiwei** [comment]
minChunks: 1

**Comment by taojiangcb** [comment]
我也碰到同一个问题，包拆不出来。

AssertionError [ERR_ASSERTION]: chunk of vendors not found.
    at /Users/jiangtao/Documents/work/cost-pm/reos-app-cost-pm/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (/Users/jiangtao/Documents/work/cost-pm/reos-app-cost-pm/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
    at /Users/jiangtao/Documents/work/cost-pm/reos-app-cost-pm/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:188:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jiangtao/Documents/work/cost-pm/reos-app-cost-pm/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
    at _next (/Users/jiangtao/Documents/work/cost-pm/reos-app-cost-pm/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='

**Comment by dalang81** [comment]
![Image](https://github.com/user-attachments/assets/85bfcc2a-732e-4a34-8ecb-b930956da54d)

![Image](https://github.com/user-attachments/assets/2219d9e8-ff2b-4683-b007-c37ea40c19d9)
