### ISSUE TITLE
配置outputPath失败

### ISSUE THREAD

**Issue by yxl2628** [umijs/umi#514]
配置文件如下：
> .webpackrc.js
```
export default {
  'publicPath': '/dist/static/',
  'outputPath': 'kindergarten',
  'theme': {
    'primary-color': '#303c5f',
    'success-color': '#3d91d0',
    'error-color': '#fa5343'
  },
  'copy': [
    {
      'from': 'src/static/',
      'to': 'static'
    }
  ]
}
```
> .umirc.js
```
export default {
  plugins: ['umi-plugin-dva'],
  pages: {
    '/home': { Route: './src/routes/PrivateRoute.js' },
    '/video': { Route: './src/routes/PrivateRoute.js' },
  },
  exportStatic: {}
}

```
> pakage.json
```
{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "crypto-js": "^3.1.9-1",
    "dva": "^2.2.3",
    "echarts": "^4.1.0",
    "react-player": "^1.6.1",
    "umi": "^1.3.3",
    "umi-plugin-dva": "^0.7.1"
  },
  "devDependencies": {
    "eslint": "^4.14.0",
    "eslint-config-umi": "^0.1.1",
    "eslint-plugin-flowtype": "^2.34.1",
    "eslint-plugin-import": "^2.6.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "husky": "^0.12.0"
  }
}

```
# 报错信息：
```
> @ build E:\startimes-git\feature-project\kindergarten-portal
> umi build


E:\startimes-git\feature-project\kindergarten-portal\node_modules\af-webpack\lib\getUserConfig\index.js:51
  throw new Error(msg);
        ^
Error: Configuration item outputPath is disabled, please remove it.
    at throwError (E:\startimes-git\feature-project\kindergarten-portal\node_modules\af-webpack\lib\getUserConfig\index.js:51:9)
    at getUserConfig (E:\startimes-git\feature-project\kindergarten-portal\node_modules\af-webpack\lib\getUserConfig\index.js:165:5)
    at Service.getWebpackRCConfig (E:\startimes-git\feature-project\kindergarten-portal\node_modules\umi-build-dev\lib\Service.js:120:39)
    at Service.build (E:\startimes-git\feature-project\kindergarten-portal\node_modules\umi-build-dev\lib\Service.js:374:33)
    at Object.build [as default] (E:\startimes-git\feature-project\kindergarten-portal\node_modules\umi-build-dev\lib\build.js:14:18)
    at _default (E:\startimes-git\feature-project\kindergarten-portal\node_modules\umi\lib\build.js:19:52)
    at Object.<anonymous> (E:\startimes-git\feature-project\kindergarten-portal\node_modules\umi\lib\scripts\build.js:12:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `umi build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by xiaohuoni** [comment]
相同环境，可用。
```js
export default {
    publicPath:"/static/",
}
```

**Comment by sorrycc** [comment]
@xiaohuoni 不是 publicPath，是 outputPath

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/blob/master/packages/umi-build-dev/src/Service.js#L75
看这里这个属性被禁用的。

**Comment by amily4555** [comment]
.umirc.js 支持设置 outputPath
