### ISSUE TITLE
[BUG] Invalid config key: https

### ISSUE THREAD

**Issue by JoshOY** [umijs/umi#5201]
## What happens?

Umi outputs `Invalid config key: https` when we try applying customized cert  with`https` as a configuration item.

This is not expected according to documentation: https://umijs.org/docs/env-variables#https

## How To Reproduce

Add https configuration to `config.ts` with following context:

```typescript
export default defineConfig({
  // ...
  https: {
    key: './rootCA-key.pem',
    cert: './rootCA.pem',
  },
});
```

And start with:

```bash
umi dev
```

Will produce following error log:

```
Invalid config key: https
Error: Invalid config key: https
    at Config.getConfig (${PROJECT_PATH}/@umijs/core/lib/Config/Config.js:172:13)
    at ${PROJECT_PATH}/node_modules/@umijs/core/lib/Service/Service.js:277:44
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (${PROJECT_PATH}/node_modules/@umijs/core/lib/Service/Service.js:108:103)
    at _next (${PROJECT_PATH}/node_modules/@umijs/core/lib/Service/Service.js:110:194)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Context

- **Umi Version**: 3.2.14
- **Node Version**: v12.18.1
- **Platform**: MacOS 10.15.5

**Comment by JoshOY** [comment]
Finally realized that this config item should be wrapped inside `devServer`:

```typescript
export default defineConfig({
  // ...
  devServer: {
    https: {
      key: './rootCA-key.pem',
      cert: './rootCA.pem',
    },  
  },
});
```
