### ISSUE TITLE
effects 的代码报错无法定位

### ISSUE THREAD

**Issue by s97712** [umijs/umi#523]
```
export default {
  namespace: 'test',
  reducers: {
    test(state,nothing){
      function *yield_fun(){
        window.undefined();
      };  
      yield_fun().next();
      return state
    }   
  },  
  effects: {
    load_all({shop_id}, {call, put}){
      window.undefined();
    }   
  }
}
```
调用 dispatch({ type:"test/load_all",{}) 时报错
```
uncaught at _callee3 at _callee3 
 at _callee6 
 at takeEvery(puhuo/load_all, _callee) 
 at _callee 
 at _callee 
 Error: TypeError: window.undefined is not a function
    at load_all (http://127.0.0.1:8000/umi.js:61656:14)
    at sagaWithCatch$ (http://127.0.0.1:8000/umi.js:59401:27)
    at tryCatch (http://127.0.0.1:8000/umi.js:59673:40)
    at Generator.invoke [as _invoke] (http://127.0.0.1:8000/umi.js:59907:22)
    at Generator.prototype.(anonymous function) [as next] (http://127.0.0.1:8000/umi.js:59725:21)
    at next (http://127.0.0.1:8000/umi.js:58080:27)
    at currCb (http://127.0.0.1:8000/umi.js:58157:7)
    at http://127.0.0.1:8000/umi.js:58268:16
    at exec (http://127.0.0.1:8000/umi.js:17610:5)
    at flush (http://127.0.0.1:8000/umi.js:17651:5)
    at asap (http://127.0.0.1:8000/umi.js:17624:5)
    at Array.<anonymous> (http://127.0.0.1:8000/umi.js:5473:27)
```
没有出错的行号，已经加了source-map了。
原来认为是webpack对yield的问题，不过测试后发现并不是，在其它地方的错误是可以定位的。
只要是 effects 的里代码，包括被调用的代码，都无法定位错误，希望能解决这个问题，不然调试起来真的很难受。

**Comment by s97712** [comment]
@xiaohuoni  加了也一样的

**Comment by sorrycc** [comment]
dva 的问题，在 dvajs/dva 提吧。redux-saga 新版本有改进报错提示的，还没有时间跟进，有兴趣可以给 dva 发个 PR。
