### ISSUE TITLE
mac、Windows 都是好的，但是 Jenkins 上 build 失败

### ISSUE THREAD

**Issue by wawaPoplar** [umijs/umi#5245]
build failed
Error: build failed
    at compiler.run (/home/rd/.jenkins/workspace/prod_zhengzhi__p-web-distributor/node_modules/@umijs/bundler-webpack/lib/index.js:107:27)
    at finalCallback (/home/rd/.jenkins/workspace/prod_zhengzhi__p-web-distributor/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at runWithDependencies.err (/home/rd/.jenkins/workspace/prod_zhengzhi__p-web-distributor/node_modules/webpack/lib/MultiCompiler.js:275:14)
    at /home/rd/.jenkins/workspace/prod_zhengzhi__p-web-distributor/node_modules/neo-async/async.js:2830:7
    at done (/home/rd/.jenkins/workspace/prod_zhengzhi__p-web-distributor/node_modules/neo-async/async.js:2925:13)
    at err (/home/rd/.jenkins/workspace/prod_zhengzhi__p-web-distributor/node_modules/webpack/lib/MultiCompiler.js:186:23)
    at compiler.run (/home/rd/.jenkins/workspace/prod_zhengzhi__p-web-distributor/node_modules/webpack/lib/MultiCompiler.js:267:15)
    at finalCallback (/home/rd/.jenkins/workspace/prod_zhengzhi__p-web-distributor/node_modules/webpack/lib/Compiler.js:257:39)
    at emitAssets.err (/home/rd/.jenkins/workspace/prod_zhengzhi__p-web-distributor/node_modules/webpack/lib/Compiler.js:279:21)
    at hooks.emit.callAsync.err (/home/rd/.jenkins/workspace/prod_zhengzhi__p-web-distributor/node_modules/webpack/lib/Compiler.js:492:20)
    at _promise0.then._err0 (eval at create (/home/rd/.jenkins/workspace/prod_zhengzhi__p-web-distributor/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:53:1)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@4.1.0 build: `PROGRESS=none umi build`
npm ERR! Exit status 1

**Comment by sorrycc** [comment]
没有其他信息了？

**Comment by xiaohuoni** [comment]
看看是不是需要先执行一次 umi g tmp，不然就可能是大小写问题或者 node 版本问题。自己排查一下，你这个日志，我看不太出来是啥错误引起的。

**Comment by 104gogo** [comment]
用3.2.16版本打包，会报下面的错误，以前的版本是好的
![image](https://user-images.githubusercontent.com/8522646/90400147-a0918e80-e0ce-11ea-8754-c563f18dddb2.png)

**Comment by 104gogo** [comment]
我擦，什么时候文档改了。。
```
        dynamicImport: {
          webpackChunkName: true,
          loadingComponent: './components/Loading.js',
        },
```

**Comment by xiaohuoni** [comment]
看下你的配置

**Comment by 104gogo** [comment]
> 看下你的配置

```
dynamicImport: {
    loading: '@/components/PageLoading',
  },
```

**Comment by xiaohuoni** [comment]
是不是没有这个文件 `src/components/PageLoading` ？

**Comment by 104gogo** [comment]
有这个文件的，不过我们把`@`的配置改成了如下：
```
  alias: {
    '@': path.resolve(__dirname, '../../web'),
  },
```
另外3.2.15版本打包就是正常的，没有上面的报错，怀疑是3.2.16改了下面的代码出现的问题，空了我去验证下。。

![image](https://user-images.githubusercontent.com/8522646/90633893-71f3ef00-e259-11ea-8595-29d920873cc5.png)

**Comment by helloyoucan** [comment]
同样的问题 in     "umi": "^3.2.8",

To install it, you can run: npm install --save @/pages/componnets/ActionDialogWidget
Child
    
    ERROR in ./src/pages/componnets/actionDialog/index.tsx
    Module not found: Error: Can't resolve '@/pages/componnets/ActionDialogWidget' in '/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/src/pages/componnets/actionDialog'
     @ ./src/pages/componnets/actionDialog/index.tsx 3:0-71 31:46-64
     @ ./src/pages/componnets/actionDialog/main.ts
     @ ./src/pages/componnets/actionVideo/index.tsx
     @ ./src/pages/index.tsx
     @ ./src/.umi-production/core/routes.ts
     @ ./src/.umi-production/umi.ts
     @ multi ./src/.umi-production/umi.ts
null
build failed
Error: build failed
    at compiler.run (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/@umijs/bundler-webpack/lib/index.js:108:27)
    at finalCallback (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at runWithDependencies.err (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/webpack/lib/MultiCompiler.js:277:6)
    at done (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at err (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/webpack/lib/MultiCompiler.js:188:7)
    at compiler.run (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/webpack/lib/MultiCompiler.js:270:7)
    at finalCallback (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/webpack/lib/Compiler.js:257:39)
    at hooks.done.callAsync.err (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/webpack/lib/Compiler.js:273:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/webpack/lib/Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/data/jenkins_yum/workspace/bellcloud_english_front_BellCloudEnglishWeb/node_modules/webpack/lib/Compiler.js:678:31)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:test: `umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-20T02_37_07_870Z-debug.log
Build step 'Execute shell' marked build as failure
Email was triggered for: Failure - Still
Trigger Failure - Any was overridden by another trigger and will not send an email.
Sending email for trigger: Failure - Still
Sending email to: wangyh@bell.ai zhuanglf@bell.ai linjl@bell.ai wucanlong@bell.ai
Finished: FAILURE

**Comment by leadream** [comment]
我在 GitLab CI 中构建遇到了同样的问题。使用的是 Node 镜像，版本号是 v14.10.0。我加了 `umi g tmp` 也不行，还是会报找不到依赖的错误（主要是找不到下面这些配置了别名的依赖）。

```js
export default defineConfig({
  alias: {
    tooltip: '@/components/common/tooltip',
    select: '@/components/common/select',
    picker: '@/components/common/picker',
    dialog: '@/components/common/dialog',
    message: '@/components/common/message',
  }
}
```

错误截图：

![image](https://user-images.githubusercontent.com/12868055/93177217-0ec88000-f765-11ea-8faf-4bdca59b6537.png)

**Comment by Zero-Qi** [comment]
> 破案了，是我大小写不一致的原因。
> 
> ~我在 GitLab CI 中构建遇到了同样的问题。使用的是 Node 镜像，版本号是 v14.10.0。我加了 `umi g tmp` 也不行，还是会报找不到依赖的错误（主要是找不到下面这些配置了别名的依赖）。~
> 
> ```js
> export default defineConfig({
>   alias: {
>     tooltip: '@/components/common/tooltip',
>     select: '@/components/common/select',
>     picker: '@/components/common/picker',
>     dialog: '@/components/common/dialog',
>     message: '@/components/common/message',
>   }
> }
> ```
> 
> 错误截图：
> 
> ![image](https://user-images.githubusercontent.com/12868055/93177217-0ec88000-f765-11ea-8faf-4bdca59b6537.png)

该怎么解决呢 我也是报大小写和alias找不到
