### ISSUE TITLE
引入插件 pugin:[]  写法报错

### ISSUE THREAD

**Issue by xflihaibo** [umijs/umi#5286]
plugins: [
 [
    join(__dirname, "..", require("../package").main || "index.js"),
    {
      cdn: "aliyun", 
      publicPath: "https://static-aliyun.com.com/",
      config: {
        accessKey: "xxxxxxx",
        secretKey: "xxxxxxx",
        bucket: "xxxxxxx",
        region: "xxxxxxx",
        exclude: /\.html$/
      }
    }
  ]
]

> @ build /Users/xxx/Desktop/github/debug/debug-client
> umi build

Path must be a string.
TypeError: Path must be a string.
    at Function.resolveSync [as sync] (/Users/xxx/Desktop/github/debug/debug-client/node_modules/@umijs/utils/node_modules/resolve/lib/sync.js:53:15)
    at map.path (/Users/xxx/Desktop/github/debug/debug-client/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:90:29)
    at Array.map (<anonymous>)
    at getPluginsOrPresets (/Users/xxx/Desktop/github/debug/debug-client/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:89:99)
    at resolvePlugins (/Users/xxx/Desktop/github/debug/debug-client/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:183:19)
    at new Service (/Users/xxx/Desktop/github/debug/debug-client/node_modules/@umijs/core/lib/Service/Service.js:183:59)
    at new Service (/Users/xxx/Desktop/github/debug/debug-client/node_modules/umi/lib/ServiceWithBuiltIn.js:50:5)
    at /Users/xxx/Desktop/github/debug/debug-client/node_modules/umi/lib/cli.js:98:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/xxx/Desktop/github/debug/debug-client/node_modules/umi/lib/cli.js:53:103)

**Comment by xflihaibo** [comment]
plugins 引入插件，加参数就会报错 Path must be a string.

export default {
  plugins: [
    [
      'umi-plugin-react',
      {
        dva: true,
        antd: true,
      },
    ],
 ],
};

**Comment by sorrycc** [comment]
`plugins: [` 里的 `plugin:[` 是什么？没这个写法的。

**Comment by xflihaibo** [comment]
> `plugins: [` 里的 `plugin:[` 是什么？没这个写法的。

plugins: [
[
'umi-plugin-react',
{
dva: true,
antd: true,
},
],
],这样的写法依旧报错

**Comment by xiaohuoni** [comment]
@xflihaibo umi@2还是umi@3？

**Comment by xflihaibo** [comment]
> umi@3 的版本，那我自定义定的plugins怎么注册在umi 上呢？ 我用umi 框架直接生成了plugins ，扁平化的写法就找不到插件项目

**Comment by xiaohuoni** [comment]
这里只要写入插件名称或者插件路径就可以。配置是你在插件中定义的。和 umi@2 不同的是，插件没有 option 参数了。你可以简单的看一下任意一个 umi@3 的插件，应该就能理解了。
比如之前是 
```js
plugins: [
    [
     'umi-plugin-react',
     {
      dva: true,
      antd: true,
     },
    ],
]
```
现在是(演示的伪代码，无任何实际意义)
```js
plugins: ['umi-plugin-react'],
react: {
      dva: true,
      antd: true,
     },
```

**Comment by xflihaibo** [comment]
😯😯
