### ISSUE TITLE
umi依赖的zlib库中，有使用node-waf指令，导致install失败

### ISSUE THREAD

**Issue by gaoxianglyx** [umijs/umi#5322]
## 报错原因
zlib的包里依赖到了node-waf指令，这个指令已经被node废弃了
而Zlib也内置到了node里面

由于@umijs/preset-build-in中依赖了zlib，导致了我在服务器端npm install失败

## 报错日志
`49] Installing unquote@~1.1.1sh: node-waf: command not found
sh: node-waf: command not found
✖ Install fail! RunScriptError: Run "sh -c node-waf clean || true; node-waf configure build" error, exit code 127
RunScriptError: Run "sh -c node-waf clean || true; node-waf configure build" error, exit code 127
    at ChildProcess.<anonymous> (/data/hongsong/yinxing/node-v14.7.0-linux-x64/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)`

## 相关环境信息

- **Umi 版本**：3.2.19
- **Node 版本**：14.7
- **操作系统**：centos

**Comment by xiaohuoni** [comment]
换个node版本吧，我们还没在这么新的node版本上跑过测试，不确定还有多少问题。
