### ISSUE TITLE
ant-design-pro umi 正则表达式 运行报错

### ISSUE THREAD

**Issue by MrCx0810** [umijs/umi#5465]
## What happens?
如题

## Mini Showcase Repository(REQUIRED)

用 yarn create umi 
选取ant-design-pro 模板，
直接运行报错

## How To Reproduce

npm start

## Context

报错信息：
Invalid regular expression: /(node_modules|D:\WorkSpace\front\admin\dist\)/: Unterminated group
SyntaxError: Invalid regular expression: /(node_modules|D:\WorkSpace\front\admin\dist\)/: Unterminated group
    at new RegExp (<anonymous>)
    at Bundler.setupDevServerOpts (D:\WorkSpace\front\admin\node_modules\@umijs\bundler-webpack\lib\index.js:148:69)
    at D:\WorkSpace\front\admin\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\dev.js:269:30
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\WorkSpace\front\admin\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\dev.js:74:103)
    at _next (D:\WorkSpace\front\admin\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\dev.js:76:194)

- **Umi Version**: ^3.2.14
- **Node Version**: v12.18.4
- **Platform**: Windows10

**Comment by leshalv** [comment]
我这边也出现了，更新了umi版本后

**Comment by xiaoxiaofan123** [comment]
请问这个问题修复了吗 我更新到了umi最新的版本 还是不行

**Comment by xiaohuoni** [comment]
> 请问这个问题修复了吗 我更新到了umi最新的版本 还是不行

修复了。

**Comment by xiaoxiaofan123** [comment]
> > 请问这个问题修复了吗 我更新到了umi最新的版本 还是不行
> 
> 修复了。

是把umi升到最新版，npm start就可以了么

**Comment by xiaohuoni** [comment]
是的
