### ISSUE TITLE
document.ejs context.config.publicPath

### ISSUE THREAD

**Issue by wqjiao** [umijs/umi#5514]
## What happens?

在 document.ejs 中引入 `<link rel="icon" type="image/x-icon" href="<%= context.config.publicPath % />favicon.png" />` 报错提示：

```
Error: Could not find matching close tag for "<%=".
    at D:\cWorkshop\fe-bms\forceyu-system\node_modules\umi-build-dev\node_modules\ejs\lib\ejs.js:710:19
    at Array.forEach (<anonymous>)
    at Template.generateSource (D:\cWorkshop\fe-bms\forceyu-system\node_modules\umi-build-dev\node_modules\ejs\lib\ejs.js:695:15)
    at Template.compile (D:\cWorkshop\fe-bms\forceyu-system\node_modules\umi-build-dev\node_modules\ejs\lib\ejs.js:572:12)
    at Object.compile (D:\cWorkshop\fe-bms\forceyu-system\node_modules\umi-build-dev\node_modules\ejs\lib\ejs.js:392:16)
    at handleCache (D:\cWorkshop\fe-bms\forceyu-system\node_modules\umi-build-dev\node_modules\ejs\lib\ejs.js:215:18)
    at Object.exports.render (D:\cWorkshop\fe-bms\forceyu-system\node_modules\umi-build-dev\node_modules\ejs\lib\ejs.js:419:10)
    at HTMLGenerator.getContent (D:\cWorkshop\fe-bms\forceyu-system\node_modules\umi-build-dev\lib\html\HTMLGenerator.js:228:29)
    at HTMLGenerator.getMatchedContent (D:\cWorkshop\fe-bms\forceyu-system\node_modules\umi-build-dev\lib\html\HTMLGenerator.js:124:19)
    at sendHtml (D:\cWorkshop\fe-bms\forceyu-system\node_modules\umi-build-dev\lib\plugins\commands\dev\createRouteMiddleware.js:31:37)
    at D:\cWorkshop\fe-bms\forceyu-system\node_modules\umi-build-dev\lib\plugins\commands\dev\createRouteMiddleware.js:45:9
    at Layer.handle [as handle_request] (D:\cWorkshop\fe-bms\forceyu-system\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\cWorkshop\fe-bms\forceyu-system\node_modules\express\lib\router\index.js:317:13)
    at D:\cWorkshop\fe-bms\forceyu-system\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\cWorkshop\fe-bms\forceyu-system\node_modules\express\lib\router\index.js:335:12)
    at next (D:\cWorkshop\fe-bms\forceyu-system\node_modules\express\lib\router\index.js:275:10)
    at next (D:\cWorkshop\fe-bms\forceyu-system\node_modules\express\lib\router\route.js:127:14)
    at D:\cWorkshop\fe-bms\forceyu-system\node_modules\serve-index\index.js:135:16
    at FSReqCallback.oncomplete (fs.js:167:21)
```

## 最小可复现仓库

https://codesandbox.io/s/unruffled-breeze-q523q?file=/src/pages/document.ejs

## 复现步骤，错误日志以及相关配置

按照 [umi 配置模板](https://umijs.org/zh-CN/docs/html-template) 在 document.ejs 中增加了 `<link rel="icon" type="image/x-icon" href="<%= context.config.publicPath % />favicon.png" />` 这个之后报错

## 相关环境信息

- **Umi 版本**：2.7.7
- **Node 版本**：
- **操作系统**：

**Comment by Lpmvb** [comment]
```html
<link rel="icon" type="image/x-icon" href="<%= context.publicPath %>favicon.png" />
```
[Umi2文档](https://v2.umijs.org/zh/guide/html-template.html#%E4%BF%AE%E6%94%B9%E9%BB%98%E8%AE%A4%E6%A8%A1%E6%9D%BF)

**Comment by wqjiao** [comment]
好的，谢谢
