### ISSUE TITLE
umi build Uglify 报错

### ISSUE THREAD

**Issue by arvinxx** [umijs/umi#557]
报错信息如下
```
Skipping static resource "E:/Tech/Github/lingmao-fronten
d/dist/static/src__pages__Data___layout.6f381dd5.async.js" (9.33 MB) - max size is 2.1 MB
Skipping static resource "E:/Tech/Github/lingmao-frontend/dist/static/src__pages__Interview___layout.54a0401f.async.js" (3.7 MB) - max size is 2.1 MB
Skipping static resource "E:/Tech/Github/lingmao-frontend/dist/static/src__pages__Persona___layout.00f8d2d1.async.js" (2.29 MB) - max size is 2.1 MB
Skipping static resource "E:/Tech/Github/lingmao-frontend/dist/static/src__pages__User__Login.6b66e1e7.async.js" (2.26 MB) - max size is 2.1 MB
Skipping static resource "E:/Tech/Github/lingmao-frontend/dist/static/src__layouts__index.b86f4230.async.js" (2.27 MB) - max size is 2.1 MB
Skipping static resource "E:/Tech/Github/lingmao-frontend/dist/static/src__pages__Dashboard__index.1238dd3e.async.js" (2.25 MB) - max size is 2.1 MB
Total precache size is about 2.6 MB for 15 resources.
Build completed in 181.151s

Failed to compile.

Failed to minify the bundle. Error: src__pages__Data___layout.6f381dd5.async.
js from UglifyJs
Unexpected token operator «=», expected punc «,» [src__pages__Data___layout.6
f381dd5.async.js:10654,38]
    at doneHandler (E:\Tech\Github\lingmao-frontend\node_modules\af-webpack\l
ib\build.js:91:27)
    at emitRecords.err (E:\Tech\Github\lingmao-frontend\node_modules\webpack\
lib\Compiler.js:265:13)
    at Compiler.emitRecords (E:\Tech\Github\lingmao-frontend\node_modules\web
pack\lib\Compiler.js:371:38)
    at emitAssets.err (E:\Tech\Github\lingmao-frontend\node_modules\webpack\l
ib\Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (E:\Tech\Github\lingmao-frontend\node_mod
ules\webpack\lib\Compiler.js:364:12)
    at next (E:\Tech\Github\lingmao-frontend\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (E:\Tech\Github\lingmao-frontend\node_modules\webpack\lib\performan
ce\SizeLimitsPlugin.js:99:4)
    at next (E:\Tech\Github\lingmao-frontend\node_modules\tapable\lib\Tapable.js:220:14)
    at callback (E:\Tech\Github\lingmao-frontend\node_modules\copy-webpack-plugin\dist\index.js:126
:17)
    at Compiler.afterEmit (E:\Tech\Github\lingmao-frontend\node_modules\copy-webpack-plugin\dist\in
dex.js:220:13)
    at next (E:\Tech\Github\lingmao-frontend\node_modules\tapable\lib\Tapable.js:220:14)
    at E:\Tech\Github\lingmao-frontend\node_modules\sw-precache-webpack-plugin\lib\index.js:98:18
    at <anonymous>
Read more here: http://bit.ly/2tRViJ9
```
在 .webpackrc.js 添加 `es5ImcompatibleVersions:true` 后仍然出错。不知道啥原因了

.webpackrc.js 配置如下
```js
export default {
  theme: './src/theme.js',
  alias: {
    components: resolve(__dirname, './src/components'),
    styles: resolve(__dirname, './src/styles'),
    utils: resolve(__dirname, './src/utils'),
    services: resolve(__dirname, './src/services'),
  },
  es5ImcompatibleVersions: true,
  proxy: process.env.NO_PROXY
    ? {
        '/api': 'http://localhost:7001/',
        '/ml': 'http://localhost:9898',
      }
    : {},
};

```
也不知道自己做了什么骚操作就报错了 😢 求助

**Comment by sorrycc** [comment]
package.json 贴出来看下。

**Comment by arvinxx** [comment]
package.json 
```js
  "scripts": {
    "start":
      "cross-env NO_PROXY=true COMPILE_ON_DEMAND=none BROWSER=none HARD_SOURCE=none  ESLINT=none TS_CONFIG_PATHS_PLUGIN=none umi dev",
    "start:proxy": "cross-env BROWSER=none ESLINT=none umi dev",
    "build": "cross-env ESLINT=none umi build",
    "site": "roadhog-api-doc static && gh-pages -d dist",
    "analyze": "cross-env ANALYZE=true umi build",
    "lint:style": "stylelint \"src/**/*.less\" --syntax less",
    "lint-staged": "lint-staged",
    "precommit": "npm run lint-staged",
    "commitmsg": "commitlint -e $GIT_PARAMS",
    "test": "umi test",
    "test:watch": "umi test --watch",
    "cov": "umi test --coverage",
    "test:all": "node ./tests/run-tests.js"
  },
 "dependencies": {
    "@babel/polyfill": "^7.0.0-beta.47",
    "axios": "^0.18.0",
    "bizcharts": "^3.1.7",
    "bizcharts-plugin-slider": "^2.0.3",
    "classnames": "^2.2.5",
    "echarts": "^4.1.0",
    "echarts-for-react": "^2.0.8",
    "enquire-js": "^0.1.2",
    "fastclick": "^1.0.6",
    "highlightable": "^1.0.7",
    "immutability-helper": "^2.7.0",
    "lodash": "^4.17.5",
    "lodash-decorators": "^4.5.0",
    "ml-kmeans": "^3.1.0",
    "moment": "^2.21.0",
    "numeral": "^2.0.6",
    "omit.js": "^1.0.0",
    "path-to-regexp": "^2.2.0",
    "qs": "^6.5.2",
    "rc-drawer-menu": "^0.5.7",
    "react-beautiful-dnd": "^7.1.2",
    "react-broadcast": "^0.7.0",
    "react-container-query": "^0.9.1",
    "react-contextmenu": "^2.9.2",
    "react-dnd": "^2.6.0",
    "react-dnd-html5-backend": "^2.6.0",
    "react-document-title": "^2.0.3",
    "react-fittext": "^1.0.0",
    "react-hot-loader": "^4.2.0",
    "react-hotkeys": "^1.1.4",
    "react-reflex": "^2.2.3",
    "shortid": "^2.2.8",
    "slate": "^0.33.6",
    "slate-plain-serializer": "^0.5.12",
    "slate-react": "^0.12.6",
    "styled-components": "^3.2.2",
    "url-polyfill": "^1.0.12",
    "xlsx": "^0.12.12"
  },
  "devDependencies": {
    "@antv/data-set": "^0.8.8",
    "@commitlint/cli": "^6.2.0",
    "@types/enzyme": "^3.1.10",
    "@types/jest": "^22.2.3",
    "@types/lodash": "^4.14.108",
    "@types/mockdate": "^2.0.0",
    "@types/react": "^16.3.14",
    "@types/react-dnd": "^2.0.36",
    "@types/react-dom": "^16.0.5",
    "@types/react-redux": "^6.0.0",
    "@types/sinon": "^4.3.3",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "commitlint-config-gitmoji": "^1.0.1",
    "cross-env": "^5.1.5",
    "cross-port-killer": "^1.0.1",
    "gh-pages": "^1.0.0",
    "puppeteer": "^1.4.0",
    "husky": "^0.14.3",
    "less-vars-to-js": "^1.2.1",
    "lint-staged": "^6.0.0",
    "mockdate": "^2.0.2",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^1.12.1",
    "regenerator-runtime": "^0.11.1",
    "roadhog-api-doc": "latest",
    "sinon": "^5.0.7",
    "slate-prop-types": "^0.4.29",
    "stylelint": "^8.4.0",
    "stylelint-config-standard": "^18.0.0",
    "umi": "^1.3.3",
    "umi-plugin-dll": "^0.2.1",
    "umi-plugin-dva": "^0.7.2",
    "umi-plugin-polyfill": "^0.1.0",
    "umi-plugin-routes": "^0.1.2"
  },
  "lint-staged": {
    "**/*.{js,jsx}": ["prettier --trailing-comma all --single-quote --write"],
    "**/*.less": "stylelint --syntax less --fix"
  },
  "browserslist": ["> 1%", "last 2 versions", "not ie <= 10"]
```

**Comment by cynthiaCh** [comment]
umi  build出错：
umi.js from UglifyJs
Unexpected token: punc «)» [umi.js:34451,27]

package.json如下：
{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "test": "umi test",
    "lint": "eslint --ext .js src mock tests",
    "precommit": "lint-staged"
  },
  "dependencies": {
    "echarts": "^4.2.1",
    "echarts-for-react": "^2.0.15-beta.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "babel-eslint": "^9.0.0",
    "eslint": "^5.4.0",
    "eslint-config-umi": "^1.4.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "react-test-renderer": "^16.7.0",
    "umi": "^2.7.0",
    "umi-plugin-react": "^1.8.0"
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "eslint --fix",
      "git add"
    ]
  },
  "engines": {
    "node": ">=8.0.0"
  }
}
