### ISSUE TITLE
mac 可以正常构建，但是 jenkins 不能正常构建(jenkins 自动触发构建)

### ISSUE THREAD

**Issue by alun-430** [umijs/umi#5590]
### 问题描述
项目在本地 umi build && umi generate tmp 正常，但是在 jenkins 环境中却 build 失败。

#### 本地和线上的不同：
yarn 安装的依赖不同，线上使用的默认 yarn 镜像地址，本地使用的公司的镜像；
yarn 版本：本地版本：v1.22.4，线上版本：v1.22.5
node 版本：本地版本：v14.3.0，线上版本：v12.19.0

#### 线上 build 失败报错代码提示：

```
$ umi generate tmp
/var/lib/jenkins/workspace/admin/node_modules/marked-terminal/node_modules/chalk/source/index.js:106
	...styles,
	^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/lib/jenkins/workspace/admin/node_modules/marked-terminal/index.js:3:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Build step 'Execute shell' marked build as failure
An attempt to send an e-mail to empty list of recipients, ignored.
[Checks API] No suitable checks publisher found.
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
Finished: FAILURE
```

#### 初步原因分析：
umi 不能识别 node_modules 中的 es6 语法，所以 build 的时候需要编译 node_modules 中的 es6 语法，所以配置了一下 .umirc.ts

```
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'all',
  },
});
```

#### 修改之后查看运行结果，结果在 jenkins 中还是会有上述的问题，也尝试过增加 babel 配置，但是还是不行，求解，谢谢！！！！

**Comment by ycjcl868** [comment]
umi build 后不需要用  umi generate tmp

目测是 node 版本过低，要看运行时 node 版本，`package.json` 里的 `engines`

**Comment by gebin** [comment]
node:  v10.15.3
npm: 6.4.1

"umi": "^3.2.14"

yarn install 的时候，会执行umi generate tmp，出现同样的报错

**Comment by GSBL** [comment]
问题都没解决，问题就关了
