### ISSUE TITLE
umi create(ts)后设置forkTSChecker 报错AssertionError [ERR_ASSERTION]: chunk of umi not found.

### ISSUE THREAD

**Issue by SpiritQAQ** [umijs/umi#5605]
## What happens?

npm create umi 后 config.ts中增加`forkTSChecker:{}`。
npm run start后 htmlUtils的opts参数中chunks为空。

## 复现步骤，错误日志以及相关配置

```
(node:64720) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at /Users/zegel/Desktop/code/AntDesignProTs/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (/Users/zegel/Desktop/code/AntDesignProTs/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
    at /Users/zegel/Desktop/code/AntDesignProTs/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:186:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/zegel/Desktop/code/AntDesignProTs/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
    at _next (/Users/zegel/Desktop/code/AntDesignProTs/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:64720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:64720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

start时候通过编译的话，即使后面报ts错也是正常流程不会复现
只要start时候无法通过编译，就会报错

create umi时选择的ant-design-pro 和  v4
尝试了多个umi版本设置forkTSChecker，均有该问题。

## 相关环境信息

- **Umi 版本**：v3.2.24
- **Node 版本:**：v14.13.1
- **操作系统**：macOS

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/97983452-2f3ab100-1d8a-11eb-9841-893525f2e2d9.png)

试下安装下 typescript 

```sh
npm i typescript -D
```

**Comment by SpiritQAQ** [comment]
@ycjcl868 
在调试过程中有升级过ts。现在typescript版本4.0.5
![image](https://user-images.githubusercontent.com/20139321/98065920-8e82e900-1e90-11eb-8f85-4aaf2c8c25ea.png)

**Comment by SpiritQAQ** [comment]
![image](https://user-images.githubusercontent.com/20139321/98066671-a52a3f80-1e92-11eb-80c7-cfcb37973b42.png)
确实umi create后的package.json里没有typescript。但问题应该不是这个，我一直用的是全局的typescript。
重新install -D了typescript 版本4.0.5 依然可以复现
复现步骤:
1. 先将代码改到不正确
2. run start

**Comment by ycjcl868** [comment]
可能是全局的 ts 版本有冲突，
