### ISSUE TITLE
[Bug] 时不时会出现这个错误  umi 3.1.10

### ISSUE THREAD

**Issue by kicktech** [umijs/umi#5645]
AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at /Users/bcnetech/TongDe/nanchang/nccb-city-cockpit-ldcj-web-ui/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (/Users/bcnetech/TongDe/nanchang/nccb-city-cockpit-ldcj-web-ui/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
    at /Users/bcnetech/TongDe/nanchang/nccb-city-cockpit-ldcj-web-ui/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:186:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/bcnetech/TongDe/nanchang/nccb-city-cockpit-ldcj-web-ui/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
    at _next (/Users/bcnetech/TongDe/nanchang/nccb-city-cockpit-ldcj-web-ui/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

**Comment by xiaohuoni** [comment]
什么时候会重现？？

**Comment by ycjcl868** [comment]
来个复现

**Comment by kicktech** [comment]
就11月8号晚上，我们公司有两台电脑开发遇到过，一台是mac启动后出现一次，另一台是window出现后刷很多遍。后面什么也没改动到现在又好了，我在想会不会是我们公司网络有问题

**Comment by 2hz4917** [comment]
`(node:27900) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of base not found.
    at C:\user\Workspace\zhihuixuanpin\node_modules\_@umijs_preset-built-in@3.2.17@@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (C:\user\Workspace\zhihuixuanpin\node_modules\_@umijs_preset-built-in@3.2.17@@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:93:14)
    at C:\user\Workspace\zhihuixuanpin\node_modules\_@umijs_preset-built-in@3.2.17@@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:186:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\user\Workspace\zhihuixuanpin\node_modules\_@umijs_preset-built-in@3.2.17@@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:62:103)
    at _next (C:\user\Workspace\zhihuixuanpin\node_modules\_@umijs_preset-built-in@3.2.17@@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:64:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:27900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection 
id: 1)
(node:27900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

这个问题，我今天也碰到了，现在又回退版本了

**Comment by wangzi6224** [comment]
我也遇到了, 是什么原因呢

**Comment by kicktech** [comment]
没有啥好办法，试试回退下umi的版本

> 我也遇到了, 是什么原因呢

**Comment by 2hz4917** [comment]
我的问题解决了，是在config打包文件里把chunks的配置给注释掉

**Comment by httol** [comment]
umi版本3.5.19，dev下启动出现一下错误
1. 删除 .umi不起作用。
2. 关闭mfsu后可以暂时规避这个错误。不知道原因。。。 
![image](https://user-images.githubusercontent.com/4971746/136701613-5b88547e-7317-412d-90b5-d2b48830a405.png)

**Comment by starlikerain** [comment]
解决方案呢，为啥就 closed 了，我这边 config 里面没有配置 chunks

**Comment by shanzheng1991** [comment]
解决方案呢，为啥就 closed 了，我这边 config 里面没有配置 chunks

**Comment by DAWDAEAED01** [comment]
解决方案呢，为啥就 closed 了，我这边 config 里面没有配置 chunks

**Comment by Lee66** [comment]
(node:1836) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at /Users/robotlee/chiwu/gsk-scorecard-webapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (/Users/robotlee/chiwu/gsk-scorecard-webapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
    at /Users/robotlee/chiwu/gsk-scorecard-webapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:189:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/robotlee/chiwu/gsk-scorecard-webapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
    at _next (/Users/robotlee/chiwu/gsk-scorecard-webapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by fzhange** [comment]
所以解决方案是啥

**Comment by Embrace-future** [comment]
我笑死了，2年后有个冤种来这里找解决方案，没有···😂

**Comment by xiaohuoni** [comment]
笑死，所以问题是啥！谁给个复现。

**Comment by LBJDJW** [comment]
我也遇到了 咋搞

**Comment by iceicea** [comment]
路径匹配问题,在windows匹配  '\' , 匹配'/'的话会找不到chunk

**Comment by garmin21** [comment]
> 路径匹配问题,在windows匹配 '' , 匹配'/'的话会找不到chunk

请问哪里的路径，能给个示例吗？我跑一个项目也遇到这个问题，跑不起来

**Comment by BuyTmall** [comment]
AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at D:\xinmenheyWork\FoTangScreen\fotang-screen\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (D:\xinmenheyWork\FoTangScreen\fotang-screen\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:93:14)
    at D:\xinmenheyWork\FoTangScreen\fotang-screen\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:189:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\xinmenheyWork\FoTangScreen\fotang-screen\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:62:103)
    at _next (D:\xinmenheyWork\FoTangScreen\fotang-screen\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:64:194) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

我今天也碰到了, 之前好好的,没有动任何东西, 突然就起不来了

**Comment by joinerlz** [comment]
3年后又有个冤种来这里找解决方案，没有···😂

**Comment by httol** [comment]
垃圾框架 哈哈哈

**Comment by httol** [comment]
经验：少用这种罗圈框架减少不必要的麻烦

**Comment by xiongying1994** [comment]
啥原因啊，也是本来好好的，突然就不行了

**Comment by wangzi6224** [comment]
> 啥原因啊，也是本来好好的，突然就不行了

都6202年了，用AI吧

**Comment by xiongying1994** [comment]
> > 啥原因啊，也是本来好好的，突然就不行了
> 
> 都6202年了，用AI吧

AI就是一直让删除node_modules和.umi文件夹，没一点用

**Comment by xiongying1994** [comment]
就TM离谱，重启电脑就可以用了。。。。。。。。
