### ISSUE TITLE
[Bug] Cannot use import statement outside a module

### ISSUE THREAD

**Issue by hongmaoxiao** [umijs/umi#5649]
## What happens?
昨晚还是好好的，今天一运行yarn run start 就发现这个错误，有点莫名其妙，试着解决却不知道定位到哪里

## Mini Showcase Repository(REQUIRED)

```
yarn run v1.22.10
$ umi dev
🚀 Starting Umi UI using umi@3.2.26...
🌈 Umi UI mini Ready on port 3000.
Starting the development server...

● Webpack █████████████████████████ compiling (0%)


/Users/xhm/project/hundred-management/node_modules/antd/es/layout/style/index.js:1
import '../../style/index.less';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:992:16)
    at Module._compile (internal/modules/cjs/loader.js:1040:27)
    at Module._compile (/Users/xhm/project/hundred-management/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (/Users/xhm/project/hundred-management/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/xhm/project/hundred-management/node_modules/@ant-design/pro-layout/lib/BasicLayout.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._compile (/Users/xhm/project/hundred-management/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (/Users/xhm/project/hundred-management/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
Error: /Users/xhm/project/hundred-management/node_modules/antd/es/layout/style/index.js:1
import '../../style/index.less';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:992:16)
    at Module._compile (internal/modules/cjs/loader.js:1040:27)
    at Module._compile (/Users/xhm/project/hundred-management/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (/Users/xhm/project/hundred-management/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/xhm/project/hundred-management/node_modules/@ant-design/pro-layout/lib/BasicLayout.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._compile (/Users/xhm/project/hundred-management/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (/Users/xhm/project/hundred-management/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at /Users/xhm/project/hundred-management/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/mock/utils.js:152:13
    at Array.reduce (<anonymous>)
    at getMockConfig (/Users/xhm/project/hundred-management/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/mock/utils.js:144:16)
    at getMockData (/Users/xhm/project/hundred-management/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/mock/utils.js:132:36)
    at Object.<anonymous> (/Users/xhm/project/hundred-management/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/mock/mock.js:105:48)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/xhm/project/hundred-management/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/mock/mock.js:40:103)
    at _next (/Users/xhm/project/hundred-management/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/mock/mock.js:42:194)
    at /Users/xhm/project/hundred-management/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/mock/mock.js:42:364
    at new Promise (<anonymous>)
    at Object.fn (/Users/xhm/project/hundred-management/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/mock/mock.js:42:97)
    at /Users/xhm/project/hundred-management/node_modules/@umijs/core/lib/Service/Service.js:533:44
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/xhm/project/hundred-management/node_modules/@umijs/core/lib/Service/Service.js:108:103)
    at _next (/Users/xhm/project/hundred-management/node_modules/@umijs/core/lib/Service/Service.js:110:194)
    at /Users/xhm/project/hundred-management/node_modules/@umijs/core/lib/Service/Service.js:110:364
```

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
yarn run start

**Expected behavior** 1. 2.
正常启动
## Context

- **Umi Version**: "umi": "^3.2.14",
- **Node Version**: v14.10.0
- **Platform**: macOs Catalina 10.15.7

**Comment by hongmaoxiao** [comment]
知道是什么问题了，但是这里有个问题，写完代码以后，编译没有报错，页面也正常，还能继续开发，但是一旦重新yarn run start就开始报错了，这就有点莫名其妙，说明这个watch可能还有点问题。

**Comment by EdisonVan** [comment]
碰到了同样的问题，请问最后怎么解决的？

**Comment by sjzpengyuyan** [comment]
请问解决了吗

**Comment by sjzpengyuyan** [comment]
> 碰到了同样的问题，请问最后怎么解决的？

兄弟，你解决了吗？怎么解决的？

**Comment by sjzpengyuyan** [comment]
> 知道是什么问题了，但是这里有个问题，写完代码以后，编译没有报错，页面也正常，还能继续开发，但是一旦重新yarn run start就开始报错了，这就有点莫名其妙，说明这个watch可能还有点问题。

请问怎么解决的？
