### ISSUE TITLE
2+版本按照官网更新到最新umi3.2.27，global.less无法顺利编译

### ISSUE THREAD

**Issue by lwbweb** [umijs/umi#5699]
umi-antd-mobile
ERROR  Failed to compile with 1 errors                                                                                                                     2:25:41 ├F10: PM┤

 error  in ./src/global.less

Module build failed (from ./node_modules/@umijs/bundler-webpack/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Users/admin/Desktop/fengniaolm/alliance/node_modules/webpack/lib/NormalModule.js:469:19)
    at /Users/admin/Desktop/fengniaolm/alliance/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/admin/Desktop/fengniaolm/alliance/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/admin/Desktop/fengniaolm/alliance/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/admin/Desktop/fengniaolm/alliance/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/admin/Desktop/fengniaolm/alliance/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/admin/Desktop/fengniaolm/alliance/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/admin/Desktop/fengniaolm/alliance/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/admin/Desktop/fengniaolm/alliance/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

 @ ./src/.umi/umi.ts 12:0-25
 @ multi ./src/.umi/umi.ts
## Context

- **Umi Version**:3.2.27
- **Node Version**:12.18.2
- **Platform**:mac

**Comment by lwbweb** [comment]
global.less内有自定义字体，缺乏loader
