### ISSUE TITLE
官方文档的快速上手脚本运行失败，出现chencheng的工作目录

### ISSUE THREAD

**Issue by sunaigo** [umijs/umi#5724]
![image](https://user-images.githubusercontent.com/19339064/100059424-088e0880-2e66-11eb-96dc-7ae669a73194.png)

**Comment by sunaigo** [comment]
yarn run v1.22.10
$ umi dev
Starting the development server...

✖ Webpack
  Compiled with some errors in 427.33ms

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                       下午2:50:43

 error  in ./src/.umi/umi.ts

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/sunyulong/Codes/demo/umi_demo/src/.umi/umi.ts: Cannot find module '/Users/chencheng/Code/github.com/ant-design/babel-plugin-import/node_modules/babel-preset-umi/node_modules/@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/babel-plugin-import/lib/index.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/@babel/core/lib/config/files/index.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/@babel/core/lib/index.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/@babel/register/lib/cache.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/@babel/register/lib/node.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/@babel/register/lib/index.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/@umijs/utils/lib/BabelRegister/BabelRegister.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/@umijs/utils/lib/index.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/@umijs/core/lib/Config/Config.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/@umijs/core/lib/index.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/umi/lib/ServiceWithBuiltIn.js
- /Users/sunyulong/Codes/demo/umi_demo/node_modules/umi/lib/forkedDev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/sunyulong/Codes/demo/umi_demo/node_modules/babel-plugin-import/lib/index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._compile (/Users/sunyulong/Codes/demo/umi_demo/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (/Users/sunyulong/Codes/demo/umi_demo/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)

 @ multi ./src/.umi/umi.ts

**Comment by dddreee** [comment]
+1

**Comment by sorrycc** [comment]
已通过 dist-tag 指定版本为 1.13.1，重装依赖后再试，如果是构建平台，直接重试，现在安装到的应该是 babel-plugin-import@1.13.1。

**Comment by laixstx** [comment]
我在 jenkins 上重新编译，还是报这个错啊

**Comment by laixstx** [comment]
✖ Webpack
  Compiled with some errors in 228.47ms

 ERROR  Failed to compile with 1 errors下午3:30:23

 error  in ./src/pages/.umi-production/umi.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '/Users/chencheng/Code/github.com/ant-design/babel-plugin-import/node_modules/babel-preset-umi/node_modules/@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /var/lib/jenkins/workspace/dev_user-web/node_modules/babel-plugin-import/lib/index.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/@babel/core/lib/config/files/plugins.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/@babel/core/lib/config/files/index.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/@babel/core/lib/index.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/@babel/register/lib/cache.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/@babel/register/lib/node.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/@babel/register/lib/index.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/af-webpack/lib/registerBabel.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/af-webpack/registerBabel.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/umi-build-dev/lib/registerBabel.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/umi-build-dev/lib/getPlugins.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/umi-build-dev/lib/Service.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/umi/lib/scripts/build.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/umi/lib/cli.js
- /var/lib/jenkins/workspace/dev_user-web/node_modules/umi/bin/umi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/var/lib/jenkins/workspace/dev_user-web/node_modules/babel-plugin-import/lib/index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Module._compile (/var/lib/jenkins/workspace/dev_user-web/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Object.newLoader [as .js] (/var/lib/jenkins/workspace/dev_user-web/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireModule (/var/lib/jenkins/workspace/dev_user-web/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPlugin (/var/lib/jenkins/workspace/dev_user-web/node_modules/@babel/core/lib/config/files/plugins.js:68:17)
    at createDescriptor (/var/lib/jenkins/workspace/dev_user-web/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)

 @ multi ./node_modules/antd-dayjs-webpack-plugin/src/init-dayjs.js ./src/pages/.umi-production/umi.js

**Comment by laixstx** [comment]
能否发布一个稳定的新版本呢？这种错误真的是....

**Comment by thomasyxy** [comment]
还是一样报错

**Comment by dddreee** [comment]
> 已通过 dist-tag 指定版本为 1.13.1，重装依赖后再试，如果是构建平台，直接重试，现在安装到的应该是 babel-plugin-import@1.13.1。

还是有这个问题
```
Module build failed (from ./node_modules/_babel-loader@8.2.1@babel-loader/lib/index.js):
Error: Cannot find module '/Users/chencheng/Code/github.com/ant-design/babel-plugin-import/node_modules/babel-preset-umi/node_modules/@babel/runtime/helpers/interopRequireDefault'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
```

**Comment by laixstx** [comment]
问题没解决，能不能不要这么快着急 close 呢？
