### ISSUE TITLE
项目构建失败 error  in ./src/pages/.umi-production/umi.js

### ISSUE THREAD

**Issue by thomasyxy** [umijs/umi#5727]
$ yarn run build
yarn run v1.22.4
warning package.json: No license field
$ UMI_ENV=dev umi build
 ERROR  Failed to compile with 1 errors7:36:45 AM

 error  in ./src/pages/.umi-production/umi.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '/Users/chencheng/Code/github.com/ant-design/babel-plugin-import/node_modules/babel-preset-umi/node_modules/@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /builds/mnew/vip/node_modules/babel-plugin-import/lib/index.js
- /builds/mnew/vip/node_modules/@babel/core/lib/config/files/plugins.js
- /builds/mnew/vip/node_modules/@babel/core/lib/config/files/index.js
- /builds/mnew/vip/node_modules/@babel/core/lib/index.js
- /builds/mnew/vip/node_modules/@babel/register/lib/cache.js
- /builds/mnew/vip/node_modules/@babel/register/lib/node.js
- /builds/mnew/vip/node_modules/@babel/register/lib/index.js
- /builds/mnew/vip/node_modules/af-webpack/lib/registerBabel.js
- /builds/mnew/vip/node_modules/af-webpack/registerBabel.js
- /builds/mnew/vip/node_modules/umi-build-dev/lib/registerBabel.js
- /builds/mnew/vip/node_modules/umi-build-dev/lib/getPlugins.js
- /builds/mnew/vip/node_modules/umi-build-dev/lib/Service.js
- /builds/mnew/vip/node_modules/umi/lib/scripts/build.js
- /builds/mnew/vip/node_modules/umi/lib/cli.js
- /builds/mnew/vip/node_modules/umi/bin/umi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/builds/mnew/vip/node_modules/babel-plugin-import/lib/index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module._compile (/builds/mnew/vip/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.newLoader [as .js] (/builds/mnew/vip/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireModule (/builds/mnew/vip/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPlugin (/builds/mnew/vip/node_modules/@babel/core/lib/config/files/plugins.js:68:17)
    at createDescriptor (/builds/mnew/vip/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)

 @ multi ./src/pages/.umi-production/umi.js

**Comment by laixstx** [comment]
+1

**Comment by laixstx** [comment]
@sorrycc

**Comment by ycjcl868** [comment]
重新安装下依赖，好了

**Comment by thomasyxy** [comment]
![image](https://user-images.githubusercontent.com/15939196/100074393-a3dca900-2e79-11eb-98a7-069661b038e2.png)
@ycjcl868 刚试的，还没有解决

**Comment by liutian** [comment]
我也是，不要自动关闭issue行吗，就为了kpI!!!!!
