### ISSUE TITLE
使用umi构建失败

### ISSUE THREAD

**Issue by thomasyxy** [umijs/umi#5787]
error Couldn't find any versions for "@umijs/ast" that matches "3.3.0"
Error: Couldn't find any versions for "@umijs/babel-plugin-import-to-await-require" that matches "3.3.0"
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.4/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.4/lib/cli.js:750:123)
    at Function.<anonymous> (/opt/yarn-v1.22.4/lib/cli.js:50545:13)
    at Generator.next (<anonymous>)
    at step (/opt/yarn-v1.22.4/lib/cli.js:310:30)
    at /opt/yarn-v1.22.4/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find any versions for "@umijs/server" that matches "3.3.0"
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.4/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.4/lib/cli.js:750:123)
    at Function.<anonymous> (/opt/yarn-v1.22.4/lib/cli.js:50545:13)
    at Generator.next (<anonymous>)
    at step (/opt/yarn-v1.22.4/lib/cli.js:310:30)
    at /opt/yarn-v1.22.4/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find any versions for "@umijs/server" that matches "3.3.0"
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.4/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.4/lib/cli.js:750:123)
    at Function.<anonymous> (/opt/yarn-v1.22.4/lib/cli.js:50545:13)
    at Generator.next (<anonymous>)
    at step (/opt/yarn-v1.22.4/lib/cli.js:310:30)
    at /opt/yarn-v1.22.4/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find any versions for "@umijs/renderer-mpa" that matches "3.3.0"
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.4/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.4/lib/cli.js:750:123)
    at Function.<anonymous> (/opt/yarn-v1.22.4/lib/cli.js:50545:13)
    at Generator.next (<anonymous>)
    at step (/opt/yarn-v1.22.4/lib/cli.js:310:30)
    at /opt/yarn-v1.22.4/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find any versions for "@umijs/babel-plugin-auto-css-modules" that matches "3.3.0"
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.4/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.4/lib/cli.js:750:123)
    at Function.<anonymous> (/opt/yarn-v1.22.4/lib/cli.js:50545:13)
    at Generator.next (<anonymous>)
    at step (/opt/yarn-v1.22.4/lib/cli.js:310:30)
    at /opt/yarn-v1.22.4/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find any versions for "@umijs/bundler-webpack" that matches "3.3.0"
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.4/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.4/lib/cli.js:750:123)
    at Function.<anonymous> (/opt/yarn-v1.22.4/lib/cli.js:50545:13)
    at Generator.next (<anonymous>)
    at step (/opt/yarn-v1.22.4/lib/cli.js:310:30)
    at /opt/yarn-v1.22.4/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by dobeweb** [comment]
删掉node_module、package-lock，重新安装下

**Comment by ycjcl868** [comment]
重新安装

**Comment by thomasyxy** [comment]
@ycjcl868 是少发了几个模块吗 部署失败的时候看了一眼你们15分钟前发的3.3.0
