### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by kz739925388** [umijs/umi#5791]
在 mac pro 下使用 UMI_ENV： cross-env  UMI_ENV=dev  umi  dev 
报错：
cross-env  UMI_ENV=dev  umi  dev

Invalid config key: 0 ：配置键无效
Error: Invalid config key: 0
    at Config.getConfig (/Users/xiaokang/demo/myUmi/node_modules/@umijs/core/lib/Config/Config.js:172:13)
    at /Users/xiaokang/demo/myUmi/node_modules/@umijs/core/lib/Service/Service.js:277:44
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/xiaokang/demo/myUmi/node_modules/@umijs/core/lib/Service/Service.js:108:103)
    at _next (/Users/xiaokang/demo/myUmi/node_modules/@umijs/core/lib/Service/Service.js:110:194)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by kz739925388** [comment]
型号名称：	MacBook Pro
  型号标识符：	MacBookPro16,2
  处理器名称：	四核Intel Core i5
  处理器速度：	2 GHz
  处理器数目：	1
  核总数：	4
  L2缓存（每个核）：	512 KB
  L3缓存：	6 MB
  超线程技术：	已启用
  内存：	16 GB
  系统固件版本：	1554.50.3.0.0 (iBridge: 18.16.12561.0.0,0)
  序列号（系统）：	C02DG3S3ML7L
  硬件UUID：	32964907-62EB-5A82-9167-9DB3076D4A00
  预置UDID：	32964907-62EB-5A82-9167-9DB3076D4A00
  激活锁状态：	已启用

**Comment by chenyangyang123** [comment]
解决了么?
