### ISSUE TITLE
[Bug] npm run openapi 报错'@umijs\openapi\dist\mockGenerator.js:Unexpected token '.

### ISSUE THREAD

**Issue by birdycn** [umijs/umi#6129]
```
Unexpected token '.'
D:\node_modules\@umijs\openapi\dist\mockGenerator.js:151
                const conte = methodConfig?.tags?.join('/') ||      
                                           ^

SyntaxError: Unexpected token '.'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)      
    at Module._compile (D:\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (D:\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)    at Module.require (internal/modules/cjs/loader.js:887:19)       
    at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@5.0.0-beta.2 openapi: `umi openapi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@5.0.0-beta.2 openapi script.  
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2021-02-04T12_22_29_766Z-debug.log
```

**Comment by birdycn** [comment]
升级到14还是会报错

```
[openAPI]: 💺 将 Swagger 转化为 openAPI
[GenSDK] gen service param error: TypeError: Cannot read property 'replace' of undefined
    at Object.stripDot (D:\\node_modules\@umijs\openapi\dist\util.js:183:16)
    at D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:254:59
    at Array.map (<anonymous>)
    at D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:241:18
    at Array.map (<anonymous>)
    at ServiceGenerator.getServiceTP (D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:234:14)
    at ServiceGenerator.genFile (D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:210:14)
    at generateService (D:\\node_modules\@umijs\openapi\dist\index.js:60:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at Object.stripDot (D:\\node_modules\@umijs\openapi\dist\util.js:183:16)
    at D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:254:59
    at Array.map (<anonymous>)
    at D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:241:18
    at Array.map (<anonymous>)
    at ServiceGenerator.getServiceTP (D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:234:14)
    at ServiceGenerator.genFile (D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:210:14)
    at generateService (D:\\node_modules\@umijs\openapi\dist\index.js:60:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@5.0.0-beta.2 openapi: `umi openapi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@5.0.0-beta.2 openapi script.  
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2021-02-04T16_33_16_298Z-debug.log```

**Comment by birdycn** [comment]
升级到14还是会报错

```
[openAPI]: 💺 将 Swagger 转化为 openAPI
[GenSDK] gen service param error: TypeError: Cannot read property 'replace' of undefined
    at Object.stripDot (D:\\node_modules\@umijs\openapi\dist\util.js:183:16)
    at D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:254:59
    at Array.map (<anonymous>)
    at D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:241:18
    at Array.map (<anonymous>)
    at ServiceGenerator.getServiceTP (D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:234:14)
    at ServiceGenerator.genFile (D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:210:14)
    at generateService (D:\\node_modules\@umijs\openapi\dist\index.js:60:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at Object.stripDot (D:\\node_modules\@umijs\openapi\dist\util.js:183:16)
    at D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:254:59
    at Array.map (<anonymous>)
    at D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:241:18
    at Array.map (<anonymous>)
    at ServiceGenerator.getServiceTP (D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:234:14)
    at ServiceGenerator.genFile (D:\\node_modules\@umijs\openapi\dist\serviceGenerator.js:210:14)
    at generateService (D:\\node_modules\@umijs\openapi\dist\index.js:60:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@5.0.0-beta.2 openapi: `umi openapi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@5.0.0-beta.2 openapi script.  
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2021-02-04T16_33_16_298Z-debug.log```

**Comment by ycjcl868** [comment]
为啥要用 @umijs\openapi

**Comment by JeromeYangtao** [comment]
@ycjcl868 openApi 现在不维护了吗

> 为啥要用 @umijs/openapi

**Comment by noenif** [comment]
一定要有operationId ,经过测试,swagger   自动生成的文件,只支持以下几种
2和3都可以

1.petstore
2.simpleapi
3.iot

好像Oauth 都是没有生成相关的operationId 数据

**Comment by LanJamRom** [comment]
我使用yapi中导出的swagger json文件也是报一样的错误

**Comment by Echo365** [comment]
swag-go 同样报错。

**Comment by Echo365** [comment]
> 一定要有operationId ,经过测试,swagger 自动生成的文件,只支持以下几种
> 2和3都可以
> 
> 1.petstore
> 2.simpleapi
> 3.iot
> 
> 好像Oauth 都是没有生成相关的operationId 数据
> 这是他的底层源码
> ![image](https://user-images.githubusercontent.com/25174520/109803762-651a7400-7c5c-11eb-873c-3e7946042e78.png)
> 
> 非常支持,阿里,真的跑通前后端沟通的最后一公里....这个东西,我一开始做前端就感觉肯定会存在,Vue 有个 类似的,但是年久失修.React 来由Umi 等一系列的React组件,希望这个插件别挂了

可以使用 swagger2openapi转换一下 https://www.npmjs.com/package/swagger2openapi
