### ISSUE TITLE
debug is not a function

### ISSUE THREAD

**Issue by sfy666666** [umijs/umi#6175]
## 问题
 使用yarn start命令运行umi-examples中的eleme-demo时报错debug is not a function

## 复现步骤
1.在github下载umi-examples代码
2.进入eleme-demo
```
cd G:\UmiJsWorkSpace\umi-examples-master\eleme-demo>
```
3.安装依赖
```
yarn
```
4.运行
```
yarn start
```
5.运行结果
```
debug is not a function
TypeError: debug is not a function
    at module.exports (G:\UmiJsWorkSpace\umi-examples-master\eleme-demo\node_modules\umi-plugin-datahub\index.js:25:3)
    at G:\UmiJsWorkSpace\umi-examples-master\eleme-demo\node_modules\@umijs\core\lib\Service\Service.js:350:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (G:\UmiJsWorkSpace\umi-examples-master\eleme-demo\node_modules\@umijs\core\lib\Service\Service.js:108:103)
    at _next (G:\UmiJsWorkSpace\umi-examples-master\eleme-demo\node_modules\@umijs\core\lib\Service\Service.js:110:194)
    at G:\UmiJsWorkSpace\umi-examples-master\eleme-demo\node_modules\@umijs\core\lib\Service\Service.js:110:364
    at new Promise (<anonymous>)
    at G:\UmiJsWorkSpace\umi-examples-master\eleme-demo\node_modules\@umijs\core\lib\Service\Service.js:110:97
    at Service.applyAPI (G:\UmiJsWorkSpace\umi-examples-master\eleme-demo\node_modules\@umijs\core\lib\Service\Service.js:357:7)
    at G:\UmiJsWorkSpace\umi-examples-master\eleme-demo\node_modules\@umijs\core\lib\Service\Service.js:440:20
Done in 5.94s.
```
## 我已按照umijs官方文档修改package.json和umirs.js文件
修改后的package.json
```
{
  "dependencies": {
    "@umijs/preset-react": "^1.7.13",
    "react-sticky": "^6.0.1",
    "umi": "^3.3.9",
    "umi-plugin-datahub": "4"
  },
  "scripts": {
    "start": "umi dev",
    "start:ui": "UMI_UI=1 umi dev"
  }
}

```
修改后的umirs.js
```
const path = require('path');

export default {
  exportStatic: {
    htmlSuffix: true,
  },
 
  proxy: {
    '^/shopping': {
      hub: 'eleme-demo',
    },
    '^/bgs': {
      hub: 'eleme-demo',
    },
  },
  store: path.join(__dirname, 'data'),

};

```

## Context

- **umi@3.3.9**:
- **Node v14.15.5**:
- **Window 10 专业版**:

**Comment by sorrycc** [comment]
这个例子不是 umi 3 的。
