### ISSUE TITLE
Unexpected token, expected "</>/<=/>=" (97:8) 这个怎么解决

### ISSUE THREAD

**Issue by shxinlei** [umijs/umi#6207]
Unexpected token, expected "</>/<=/>=" (97:8)
SyntaxError: Unexpected token, expected "</>/<=/>=" (97:8)
    at Object._raise (/Users/alick.shi/Desktop/dosm-automation-web/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/error.js:60:45)
    at Object.raiseWithData (/Users/alick.shi/Desktop/dosm-automation-web/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/error.js:55:17)
    at Object.raise (/Users/alick.shi/Desktop/dosm-automation-web/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/error.js:39:17)
    at Object.unexpected (/Users/alick.shi/Desktop/dosm-automation-web/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/util.js:139:16)
    at Object.expectRelational (/Users/alick.shi/Desktop/dosm-automation-web/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/util.js:43:12)
    at Object.tsParseTypeAssertion (/Users/alick.shi/Desktop/dosm-automation-web/node_modules/@umijs/utils/node_modules/@babel/parser/src/plugins/typescript/index.js:1183:12)
    at Object.parseMaybeUnary (/Users/alick.shi/Desktop/dosm-automation-web/node_modules/@umijs/utils/node_modules/@babel/parser/src/plugins/typescript/index.js:2541:21)
    at Object.parseExprOps (/Users/alick.shi/Desktop/dosm-automation-web/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/expression.js:349:23)
    at Object.parseMaybeConditional (/Users/alick.shi/Desktop/dosm-automation-web/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/expression.js:314:23)
    at Object.parseMaybeAssign (/Users/alick.shi/Desktop/dosm-automation-web/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/expression.js:269:21)

 "dependencies": {
    "@ant-design/pro-layout": "^6.14.5",
    "@umijs/preset-react": "1.x",
    "monaco-editor": "^0.22.3",
    "umi": "^3.3.9"
  },
  "devDependencies": {
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@umijs/test": "^3.3.7",
    "lint-staged": "^10.0.7",
    "monaco-editor-webpack-plugin": "^3.0.0",
    "prettier": "^2.2.0",
    "react": "17.x",
    "react-dom": "17.x",
    "typescript": "^4.1.2",
    "yorkie": "^2.0.0"
  }

有人遇到这个问题吗

**Comment by shxinlei** [comment]
@sorrycc 已经找到问题了  是在pages 下面建立了一个 名字为 Modal.tsx 的文件 更改文件名后正常
