### ISSUE TITLE
[Bug] 3.4.0 beta 无法启用 forkTSChecker

### ISSUE THREAD

**Issue by urielvan** [umijs/umi#6230]
## What happens?

配置项启用 forkTSChecker 无法正常启用插件

## Mini Showcase Repository(REQUIRED)

https://github.com/urielvan/umi-fork-ts-bug

## How To Reproduce

执行 `npm run start` 之后控制台中输出了错误信息，src/pages/index.tsx 中参数 `foo` 为隐式 any 类型，正常情况下应该被报错

```
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'D:\Code\fork-ts\node_modules\@umijs\deps\compiled\fork-ts-checker-webpack-plugin\TypeScriptReporterRpcService.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

√ Webpack
  Compiled successfully in 3.14s

RpcIpcMessagePortClosedError: Process 3860 exited with code "1" [null]
Issues checking service aborted - probably out of memory. Check the `memoryLimit` option in the ForkTsCheckerWebpackPlugin configuration.
If increasing the memory doesn't solve the issue, it's most probably a bug in the TypeScript or EsLint.

```

## Context

- **Umi Version**: 3.4.0-beta6
- **Node Version**: 12.18.3
- **Platform**: windows 10

**Comment by ycjcl868** [comment]
@umijs/deps 没打进去

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/110437454-60d4d780-80f0-11eb-986d-4c8492af825e.png)
正常是这个报错对吧？
