### ISSUE TITLE
[Bug] UmiJS 3.4.1 webpack5 基于路由的按需编译 lazyCompilation 打开页面出错

### ISSUE THREAD

**Issue by onlyling** [umijs/umi#6256]
## What happens?

```json
{
 "dependencies": {
    "umi": "^3.4.1",
  }
}
```
```js
// .umirc.ts
{
  // 控制台会打印一些错误，打开页面没有问题
  // (node:13223) [DEP_WEBPACK_LIBRARY_TEMPLATE_PLUGIN] DeprecationWarning: webpack.LibraryTemplatePlugin is deprecated and has been replaced by compilation.outputOptions.library or compilation.addEntry + passing a library option
  // (node:13223) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin

  // 进入对应的路由打印的错误
  // [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
  webpack5: {}
}
```

```js
// .umirc.ts
{
  webpack5: {
    // 控制台打印的错误
    //  (node:14772) [DEP_WEBPACK_LIBRARY_TEMPLATE_PLUGIN] DeprecationWarning: webpack.LibraryTemplatePlugin is deprecated and has been replaced by compilation.outputOptions.library or compilation.addEntry + passing a library option
    // (node:14772) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin

    // 进入对应的路由打印的错误
    // [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)

    // 浏览器控制台打印的错误
    // EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.
    // [@umijs/runtime] load component failed Error: Problem communicating active modules to the server: undefined undefined:undefined:undefined undefined
    lazyCompilation: {}
  }
}
```

浏览器控制台打印的具体错误信息

```
EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.

devScripts.js:5836 

[@umijs/runtime] load component failed Error: Problem communicating active modules to the server: undefined undefined:undefined:undefined undefined
    at lazy-compilation-web.js:34
    at Set.forEach (<anonymous>)
    at EventSource.activeEventSource.onerror (lazy-compilation-web.js:32) 
    at LoadableComponent (http://192.168.2.144:8000/umi.js:26892:68)
    at Route
    at Switch
    at Router (http://192.168.2.144:8000/umi.js:78005:30)
    at RouterComponent (http://192.168.2.144:8000/umi.js:26106:23)
    at __WEBPACK_DEFAULT_EXPORT__ (http://192.168.2.144:8000/umi.js:20282:24)
    at FormProvider (http://192.168.2.144:8000/umi.js:45275:31)
    at LocaleProvider (http://192.168.2.144:8000/umi.js:29199:87)
    at ProviderChildren (http://192.168.2.144:8000/umi.js:28231:24)
    at LocaleReceiver (http://192.168.2.144:8000/umi.js:29069:87)
    at ConfigProvider (http://192.168.2.144:8000/umi.js:28338:13)
    at _LocaleContainer (http://192.168.2.144:8000/umi.js:20992:60)
    at __WEBPACK_DEFAULT_EXPORT__ (http://192.168.2.144:8000/umi.js:21342:23)
```

在 `3.4.0` 版本中，`lazyCompilation: {}` 并没有这个问题。

## Mini Showcase Repository(REQUIRED)

暂无。

## How To Reproduce

暂无。

## Context

- **Umi Version**: 3.4.1
- **Node Version**: v12.14.1
- **Platform**: Mac OS 10.15.7 (19H524)

**Comment by wangxingkang** [comment]
+1

**Comment by bluescurry** [comment]
(node:13223) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin

**Comment by sorrycc** [comment]
@bluescurry 这个信息不对，我们没有用到 workbox-webpack-plugin 。
