### ISSUE TITLE
[Bug] antdV5生成后运行到umi g tmp 报错[openAPIConfig].flat is not a function

### ISSUE THREAD

**Issue by wtyang** [umijs/umi#6294]
## What happens?
使用yarn create umi project-name 生成项目，antdV5生成后运行到umi g tmp 报错[openAPIConfig].flat is not a function
## How To Reproduce
终端运行 `yarn create umi project-name`,    
选择 `Select the boilerplate type ant-design-pro` , `Be the first to experience the new umi@3 ? Pro V5`
执行成功后 `cd project-name` ,执行 `yarn`,  执行到下方报错
``` 
warning " > jsdom-global@3.0.2" has unmet peer dependency "jsdom@>=10.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ umi g tmp
[openAPIConfig].flat is not a function
TypeError: [openAPIConfig].flat is not a function
    at Object.api.onGenerateFiles [as fn] (/Users/wty/git/base-admin-v3/node_modules/@umijs/plugin-openapi/lib/index.js:144:27)
    at /Users/wty/git/base-admin-v3/node_modules/@umijs/core/lib/Service/Service.js:609:28
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/wty/git/base-admin-v3/node_modules/@umijs/core/lib/Service/Service.js:108:103)
    at _next (/Users/wty/git/base-admin-v3/node_modules/@umijs/core/lib/Service/Service.js:110:194)
    at /Users/wty/git/base-admin-v3/node_modules/@umijs/core/lib/Service/Service.js:110:364
    at new Promise (<anonymous>)
    at /Users/wty/git/base-admin-v3/node_modules/@umijs/core/lib/Service/Service.js:110:97
    at _next16 (eval at create (/Users/wty/git/base-admin-v3/node_modules/@umijs/deps/compiled/tapable/index.js:1:7783), <anonymous>:17:18)
    at _promise16.then._result16 (eval at create (/Users/wty/git/base-admin-v3/node_modules/@umijs/deps/compiled/tapable/index.js:1:7783), <anonymous>:42:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
清理node_module，清理npm cache后，使用npm，cnpm，tyarn 尝试同样失败
```
> ant-design-pro@5.0.0-beta.2 postinstall /Users/wty/git/base-admin-v3
> umi g tmp

[openAPIConfig].flat is not a function
```
## Context
- Umi Version: 3.4.2
- Node Version: 10.16.3
- Platform: Mac OS 10.14.6 (18G95)

**Comment by chenshuai2144** [comment]
升级一下 node 的版本吗，最好升级到 12

**Comment by wtyang** [comment]
升级了node版本，问题已经解决
