### ISSUE TITLE
[Bug] 修改webpack output filename会报错

### ISSUE THREAD

**Issue by RIPm** [umijs/umi#6407]
设置output filename名称
```js
chainWebpack(memo: any) {
  memo.output.filename('[name].js?[contenthash]')
}
```
会报`AssertionError [ERR_ASSERTION]: chunk of umi not found`

```sh
(node:13512) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at htmlChunks.forEach (e:\polarbear-base-app-pc\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:104:27)
    at Array.forEach (<anonymous>)
    at chunksToFiles (e:\polarbear-base-app-pc\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:93:14)
    at e:\polarbear-base-app-pc\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:188:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (e:\polarbear-base-app-pc\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:62:103)
    at _next (e:\polarbear-base-app-pc\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:64:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Context

- **Umi Version**: 3.3.3
- **Node Version**:  10.23.0
- **Platform**: Windows 10

**Comment by drizzlesconsin** [comment]
```diff
+ chunks: ['vendors', 'umi'],
chainWebpack(memo) {}
```

**Comment by RIPm** [comment]
> ```diff
> + chunks: ['vendors', 'umi'],
> chainWebpack(memo) {}
> ```

如果不想划分vendors，output filename就设不了那样子的吗

**Comment by xiaohuoni** [comment]
因为 chunks 默认带有 umi，不生成这个文件就会报错。

**Comment by RIPm** [comment]
> 因为 chunks 默认带有 umi，不生成这个文件就会报错。

默认不是设了`chunks: ['umi']`吗，要改filename的话还要加多个`vendors`?
