### ISSUE TITLE
[Bug] @umijs/bundler-webpack 3.4.10打包报错

### ISSUE THREAD

**Issue by xhlwill** [umijs/umi#6446]
build 出错：

```bash
Cannot find module 'webpack/lib/ModuleFilenameHelpers'

Error: Cannot find module 'webpack/lib/ModuleFilenameHelpers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.mod._resolveFilename (/cloud/source_code/node_modules/_@umijs_bundler-webpack@3.4.10@@umijs/bundler-webpack/lib/requireHook.js:49:28)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/cloud/source_code/node_modules/_v8-compile-cache@2.3.0@v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/cloud/source_code/node_modules/_esbuild-loader@2.9.2@esbuild-loader/dist/minify-plugin.js:8:33)
    at Module._compile (/cloud/source_code/node_modules/_v8-compile-cache@2.3.0@v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._compile (/cloud/source_code/node_modules/_@umijs_deps@0.8.1@@umijs/deps/compiled/babel/bundle.js:141004:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/cloud/source_code/node_modules/_@umijs_deps@0.8.1@@umijs/deps/compiled/babel/bundle.js:141009:7)
```

今天发现，17小时前包@umijs/bundler-webpack升级了导致的。
- **Umi Version**: 3.4.10
- **Node Version**: 10.22.1
- **Platform**: mac

**Comment by wangyongsong** [comment]
```bash
annot find module 'webpack/lib/ModuleFilenameHelpers'
Require stack:
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/esbuild-loader/dist/minify-plugin.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/esbuild-loader/dist/index.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/@umijs/plugin-esbuild/lib/index.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/@umijs/core/lib/Service/Service.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/@umijs/core/lib/index.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/umi/lib/ServiceWithBuiltIn.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/umi/lib/cli.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/umi/bin/umi.js
Error: Cannot find module 'webpack/lib/ModuleFilenameHelpers'
Require stack:
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/esbuild-loader/dist/minify-plugin.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/esbuild-loader/dist/index.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/@umijs/plugin-esbuild/lib/index.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/@umijs/core/lib/Service/Service.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/@umijs/core/lib/index.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/umi/lib/ServiceWithBuiltIn.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/umi/lib/cli.js
- /Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/umi/bin/umi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.mod._resolveFilename (/Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/@umijs/bundler-webpack/lib/requireHook.js:49:28)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/esbuild-loader/dist/minify-plugin.js:8:33)
    at Module._compile (/Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._compile (/Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/@umijs/deps/compiled/babel/bundle.js:141004:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (/Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/@umijs/deps/compiled/babel/bundle.js:141009:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/esbuild-loader/dist/index.js:10:41)
    at Module._compile (/Users/wangyongsong/Documents/work/zjkj/v2/wwyc_admin_antdpro5/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```
刚刚build，同样报错了 2021年04月20日14:12:49

**Comment by Lind-pro** [comment]
同样的错误 2021年4月20日15:58
