### ISSUE TITLE
[Bug] unit test error when using useRequest

### ISSUE THREAD

**Issue by aspirantzhang** [umijs/umi#6484]
## What happens?

进行组件的单元测试，使用从umi导出的useRequest时，发生错误
When doing a unit test of the component, an error occurs when I use the `useRequest` exported from `umi`

```
    TypeError: Cannot read property 'modify' of undefined

      145 |   const requestConfig: RequestConfig = plugin.applyPlugins({
      146 |     key: 'request',
    > 147 |     type: ApplyPluginsType.modify,
          |                            ^
      148 |     initialValue: {},
      149 |   });
      150 |

      at getRequestMethod (src/.umi/plugin-request/request.ts:147:28)
      at request (src/.umi/plugin-request/request.ts:272:25)
      at finalRequestMethod (src/.umi/plugin-request/request.ts:86:16)
      at apply (node_modules/@ahooksjs/use-request/lib/index.js:144:16)
      at Fetch.apply [as service] (node_modules/@ahooksjs/use-request/lib/utils/usePersistFn.js:59:20)
…………
```

## Mini Showcase Repository(REQUIRED)

https://codesandbox.io/s/userequest-test-d12v8?file=/package.json

Open new terminal -> yarn test

## Source Code
index.tsx
```tsx
import React from "react";
import { useRequest } from "umi";

const Index = () => {
  const init = useRequest(`https://public-api-v1.aspirantzhang.com/users`);

  if (init.error) {
    return <div>failed to load</div>;
  }
  if (init.loading) {
    return <div>loading...</div>;
  }
  return <div>{JSON.stringify(init.data)}</div>;
};

export default Index;
```
index.test.tsx
```tsx
/**
 * @jest-environment jsdom
 */
import React from "react";
import { render } from "@testing-library/react";
import "@testing-library/jest-dom/extend-expect";

import Index from "./index";

test("index", () => {
  const renderer = render(<Index />);

  expect(renderer).toMatchSnapshot();
});
```

**Comment by fybchristasker** [comment]
同样的问题，有解决方案吗

**Comment by aspirantzhang** [comment]
> 同样的问题，有解决方案吗

我在 umi-plugins也发了[issue](https://github.com/umijs/umi/issues/6484)，截止目前均无人应答，暂时无解决方案 。

**Comment by Choicelin** [comment]
有更新吗

**Comment by DongDeming** [comment]
我在`setupFilesAfterEnv: ['./setup-file.tsx']` 中使用mock了 umi 来解决这个问题
```
jest.mock('umi', () => {
  const originalModule = jest.requireActual('umi');

  return {
    __esModule: true,
    ...originalModule,
    ApplyPluginsType: {
      modify: 'modify',
    },
  };
});
```
