### ISSUE TITLE
[Bug] 构建时用query的hash方式会报错

### ISSUE THREAD

**Issue by RIPm** [umijs/umi#6555]
## What happens?
现在遇到一个场景，用`qiankun`搭建一个由主应用管理其他子应用打开的项目。
当其中一个子应用有改动并重新部署后，主应用没刷新，去打开那个子应用的某个页面，就会报chunk js和css资源404的问题。
因为文件名的hash值变了，没能找回之前的文件。
所以想将`umi`默认的文件名hash作为版本号改为query string的方式，但会报编译错误。

``` js
memo.output
   .filename('[name].js?[contenthash]')
   // .filename('umi.js?[contenthash]')
   .chunkFilename('[name].async.js?[contenthash]');
```
会报AssertionError [ERR_ASSERTION]: chunk of umi not found的错误

```bash
(node:13512) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at htmlChunks.forEach (e:\polarbear-base-app-pc\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:104:27)
    at Array.forEach (<anonymous>)
    at chunksToFiles (e:\polarbear-base-app-pc\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:93:14)
    at e:\polarbear-base-app-pc\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:188:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (e:\polarbear-base-app-pc\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:62:103)
    at _next (e:\polarbear-base-app-pc\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:64:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Context

- **Umi Version**: 3.3.3
- **Node Version**: 10.23.0
- **Platform**: Windows 10

**Comment by xiaohuoni** [comment]
你这配置是无效的，你可以先配置 `chunks:[]` 来查看生成的文件。
然后看你的需求，好像可以配置 `hash:true` https://umijs.org/config#hash

**Comment by RIPm** [comment]
> 你这配置是无效的，你可以先配置 `chunks:[]` 来查看生成的文件。
> 然后看你的需求，好像可以配置 `hash:true` https://umijs.org/config#hash

就是`hash:true` 会导致出现这个问题，现在自己把hash方式改成url参数那种

**Comment by xiaohuoni** [comment]
没看明白

**Comment by RIPm** [comment]
> 没看明白

就是`hash:true`导致文件名变了，在主应用管理的子应用里再打开其他页面就会重新加载js，然后由于重新部署文件名变了，资源就找不到了

**Comment by ovenslove** [comment]
同问，有解决方案么
