### ISSUE TITLE
[Bug]启动程序报错，umi的版本为umi@3.2.28。plugin @umijs/plugin-locale is already registered by 

### ISSUE THREAD

**Issue by rggaoxin** [umijs/umi#6596]
Versions
umi:3.2.28
dumi:1.1.18
node:v12.20.2
npm:6.14.11
OS:mac 10.15.5
Browser:null

尝试更新了dumi、umi版本，无效。

log信息为：

plugin @umijs/plugin-locale is already registered by /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js, plugin from /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js register failed.
Error: plugin @umijs/plugin-locale is already registered by /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js, plugin from /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js register failed.
    at Service.registerPlugin (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:457:13)
    at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:436:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:108:103)
    at _next (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:110:194)
    at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:110:364
    at new Promise (<anonymous>)
    at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:110:97
    at Service.initPlugin (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:442:7)
    at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:317:22

**Comment by xiaohuoni** [comment]
重复安装注册了，可能是preset和package里面都安装了。删掉package里面的就可以
