### ISSUE TITLE
[Bug] umi-request 不支持服务端渲染 SSR

### ISSUE THREAD

**Issue by guanyuan** [umijs/umi#6620]
## What happens?
开启了ssr，在静态防范 getInitialProps中发送接口请求，报错：
我想问一下，是不是umi-request 不支持 node端执行？

```
_UserProfilePage.getInitialProps = (async ctx => {
  const state = ctx.store.getState();
  if (ctx.isServer) {
    const industries = await request.get('/bsp/ipo/finProjectInfo/addrs', {
      params: { page_size: 9999, type: 'REG_PROV' },
    })

    const dicts: any = _result(industries, 'data.data') || [];
    return Promise.resolve({
      data: {
        title:  JSON.stringify( dicts[0]),
      },
    });
  } else {
    return Promise.resolve({
      data: {
        title: 'Hello World' + state.auth.countryCode,
      },
    });
  }
}) as IGetInitialProps;
```

```
ReferenceError: document is not defined
[1]       at Function.newNotificationInstance [as newInstance] (/Users/guanyuan13/workspaces/node10/bsp-web-koa/dist/umi.server.js:273579:5)
[1]       at getMessageInstance (/Users/guanyuan13/workspaces/node10/bsp-web-koa/dist/umi.server.js:58700:62)
[1]       at notice (/Users/guanyuan13/workspaces/node10/bsp-web-koa/dist/umi.server.js:58723:5)
[1]       at Object.show (/Users/guanyuan13/workspaces/node10/bsp-web-koa/dist/umi.server.js:58774:16)
[1]       at errorHandler (/Users/guanyuan13/workspaces/node10/bsp-web-koa/dist/umi.server.js:317719:66)
[1]       at /Users/guanyuan13/workspaces/node10/bsp-web-koa/dist/umi.server.js:280896:26
[1]       at process._tickCallback (internal/process/next_tick.js:68:7)
```

去掉接口请求，如下面的代码，页面可以正常渲染出Hello world。加上接口请求，就会报错

```
import React from 'react';
import { IGetInitialProps } from 'umi';

const _UserProfilePage = (props: any) => {
  const { data } = props;
  return (
    <div>
     <div>{data.title}</div>
    </div>
  );
};

_UserProfilePage.getInitialProps = (async (ctx) => {
    return Promise.resolve({
      data: {
        title: 'Hello World',
      },
    });
}) as IGetInitialProps;
```

## How To Reproduce

**Steps to reproduce the behavior:**
 1. 开启ssr
 2. 页面组件添加静态方法getInitialProps
 3. getInitialProps中，使用umi-request请求接口数据

**Expected behavior** 
期望开启服务端渲染后，接口数据能够提前拿到，渲染到页面上。
当查看网页源码的时候，可以看到接口返回的api数据。

## Context

- **Umi Version**: 3.3.3
- **Node Version**: v10.16.0
- **Platform**: mac

**Comment by Jeepeng** [comment]
支持的，楼主的错误应该是reject后 antd Notification控件报的，可以看看哪里用到了这个

**Comment by guanyuan** [comment]
> 支持的，楼主的错误应该是reject后 antd Notification控件报的，可以看看哪里用到了这个

好的， 谢谢，确实不是umi-request的锅。
我使用的是 import { extend } from 'umi-request';

直接使用 import {request} from 'umi' 是没有问题的。
