### ISSUE TITLE
如何在非根目录执行 umi dev？

### ISSUE THREAD

**Issue by linesh-simplicity** [umijs/umi#675]
现在我的目录结构是这样：

```console
.(~/my/blogs/linesh-tw)
├─ package.json
└─ src
   ├─ angular
   ├─ vue
   └─ react
      ├── index.html
      └── pages
          └── index.js
```

当我在 `src/react` 目录下执行 `umi dev` 的时候，项目能够正常在 `localhost:8080` 访问到 `pages/index.js` 中的内容。不过当我想在项目根目录下面执行 `npm start` 的时候，umi 就会报如下的错误。搜了下官网的文档，似乎没找到相关的配置项，想了解下这个场景是我少配了什么东西，还是 umi 当前不支持这种做法呢？应该怎么解决呢？谢谢。

```js
{
  "scripts": {
    "start": "cd src/react && umi dev",
  },
  "dependencies": {
    "dva": "^2.3.1",
    "umi": "^1.3.12"
  }
}
```

我猜是因为在根目录下，哪怕是 cd 到了 `src/react` 下，npm 的执行路径（工作目录）依然是项目根目录，而 umi 在项目根目录下找不到 `src/pages` 或 `pages`。

```bash
{ Error: ENOENT: no such file or directory, scandir '~/my/blogs/linesh-tw/pages'
    at Error (native)
    at fs.readdirSync (fs.js:952:18)
    at getRouteConfigFromDir (~/my/blogs/linesh-tw/node_modules/umi-build-dev/lib/routes/getRouteConfigFromDir.js:29:37)
    at _default (~/my/blogs/linesh-tw/node_modules/umi-build-dev/lib/routes/getRouteConfig.js:31:49)
    at Service.initRoutes (~/my/blogs/linesh-tw/node_modules/umi-build-dev/lib/Service.js:288:49)
    at ~/my/blogs/linesh-tw/node_modules/umi-build-dev/lib/Service.js:198:13
    at next (native)
    at step (~/my/blogs/linesh-tw/node_modules/umi-build-dev/lib/Service.js:54:221)
    at _next (~/my/blogs/linesh-tw/node_modules/umi-build-dev/lib/Service.js:54:409)
    at ~/my/blogs/linesh-tw/node_modules/umi-build-dev/lib/Service.js:54:477
    at ~/my/blogs/linesh-tw/node_modules/umi-build-dev/lib/Service.js:54:97
    at Service.dev (~/my/blogs/linesh-tw/node_modules/umi-build-dev/lib/Service.js:283:7)
    at Object.dev [as default] (~/my/blogs/linesh-tw/node_modules/umi-build-dev/lib/dev.js:14:18)
    at _default (~/my/blogs/linesh-tw/node_modules/umi/lib/dev.js:23:50)
    at Object.<anonymous> (~/my/blogs/linesh-tw/node_modules/umi/lib/scripts/realDev.js:14:18)
    at Module._compile (module.js:570:32)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '~/my/blogs/linesh-tw/pages' 
}
```

**Comment by linesh-simplicity** [comment]
加上 `APP_ROOT` 以后上面的问题就修复了，不过会接着报下面的错误：

```shell
➜  linesh-tw (master) ✗ npm start

> linesh-blog@0.0.1 start ~/my/blogs/linesh-tw
> APP_ROOT=src/react umi dev

internal/modules/cjs/loader.js:550
throw err;
^

Error: Cannot find module 'webpack/lib/Chunk'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
at Function.Module._load (internal/modules/cjs/loader.js:475:25)
at Module.require (internal/modules/cjs/loader.js:598:17)
at require (internal/modules/cjs/helpers.js:11:18)
at Object.<anonymous> (~/my/blogs/linesh-tw/node_modules/extract-text-webpack-plugin/dist/index.js:17:14)
at Module._compile (internal/modules/cjs/loader.js:654:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
at Module.load (internal/modules/cjs/loader.js:566:32)
at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

我尝试过把 devDependencies 下面的依赖全部删掉，删掉 `node_modules` 再安装；尝试过 node 6, 9, 10 三个版本，也都是报同样的错误。

一个可复现的仓库在这里：https://github.com/linesh-simplicity/linesh-simplicity.github.io/tree/chore/migrate-to-dva

**Comment by sorrycc** [comment]
我试过正常，用 yarn 安装的依赖。

**Comment by linesh-simplicity** [comment]
神奇。我用 yarn 安装了一下也是正常的。看来是之前用 npm 安装导致，目测依赖没装全，我再研究研究为啥会有这个问题。

感谢。这个 issue 可关了。
