### ISSUE TITLE
[Bug] Cannot find module '@umijs/preset-react'

### ISSUE THREAD

**Issue by b1ngx** [umijs/umi#6822]
## What happens?

已安装 `@umijs/preset-react`

```
> next@ postinstall /opt/app-root/src/html
> umi generate tmp

Cannot find module '@umijs/preset-react' from '/opt/app-root'
Error: Cannot find module '@umijs/preset-react' from '/opt/app-root'
    at Function.resolveSync [as sync] (/opt/app-root/src/html/node_modules/@umijs/deps/compiled/resolve/index.js:1:11170)
    at /opt/app-root/src/html/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:94:29
    at Array.map (<anonymous>)
    at getPluginsOrPresets (/opt/app-root/src/html/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:89:99)
    at resolvePresets (/opt/app-root/src/html/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:173:23)
    at new Service (/opt/app-root/src/html/node_modules/@umijs/core/lib/Service/Service.js:183:59)
    at new Service (/opt/app-root/src/html/node_modules/umi/lib/ServiceWithBuiltIn.js:50:5)
    at /opt/app-root/src/html/node_modules/umi/lib/cli.js:119:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/opt/app-root/src/html/node_modules/umi/lib/cli.js:55:103)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next@ postinstall: `umi generate tmp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the next@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2021-06-28T06_38_43_089Z-debug.log
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": error while running runtime: exit status 1
```

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:   3.4.25
- **Node Version**: 14.17.1
- **Platform**: centos 7

**Comment by PeachScript** [comment]
请提供最小可复现仓库

**Comment by 738** [comment]
@b1ngx 

I just removed `@umijs/preset-react` from dependencies.
