### ISSUE TITLE
[Bug] 项目采用monorep管理方式(使用的lerna)并使用umi3.5开启mfsu报错

### ISSUE THREAD

**Issue by choby** [umijs/umi#6833]
## What happens?

问题简单描述如题，报错内容：
in ./src/.umi/core/routes.ts

Module build failed (from ../../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep dumi-theme-default/src/builtins/Previewer.tsx
    at getDepVersion (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/getDepVersion.js:120:27)
    at DepInfo.addTmpDep (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepInfo.js:132:56)
    at Object.onTransformDeps (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js:289:23)
    at PluginPass.CallExpression (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/babel-plugin-import-to-await-require/lib/index.js:284:139)
    at newFn (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:62022:21)
    at NodePath._call (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56841:20)
    at NodePath.call (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56828:17)
    at NodePath.visit (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56878:31)
    at TraversalContext.visitQueue (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56353:16)
    at TraversalContext.visitSingle (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56322:19)
    at TraversalContext.visit (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56381:19)
    at Function.traverse.node (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56506:17)
    at NodePath.visit (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56885:18)
    at TraversalContext.visitQueue (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56353:16)
    at TraversalContext.visitSingle (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56322:19)
    at TraversalContext.visit (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56381:19)

 error  in ./src/.umi/plugin-layout/icons.ts

Module build failed (from ../../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep @ant-design/icons/es/icons/TableOutlined
    at getDepVersion (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/getDepVersion.js:120:27)
    at DepInfo.addTmpDep (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepInfo.js:132:56)
    at Object.onTransformDeps (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js:289:23)
    at PluginPass.exit (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/babel-plugin-import-to-await-require/lib/index.js:173:140)
    at newFn (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:62022:21)
    at NodePath._call (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56841:20)
    at NodePath.call (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56828:17)
    at NodePath.visit (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56887:8)
    at TraversalContext.visitQueue (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56353:16)
    at TraversalContext.visitSingle (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56322:19)
    at TraversalContext.visit (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56381:19)
    at Function.traverse.node (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56506:17)
    at traverse (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56486:12)
    at transformFile (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:6224:29)
    at transformFile.next (<anonymous>)
    at run (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:6152:12)

 error  in ./src/.umi/plugin-locale/locale.tsx

Module build failed (from ../../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep moment/locale/zh-tw
    at getDepVersion (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/getDepVersion.js:120:27)
    at DepInfo.addTmpDep (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepInfo.js:132:56)
    at Object.onTransformDeps (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js:289:23)
    at PluginPass.exit (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/babel-plugin-import-to-await-require/lib/index.js:173:140)
    at newFn (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:62022:21)
    at NodePath._call (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56841:20)
    at NodePath.call (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56828:17)
    at NodePath.visit (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56887:8)
    at TraversalContext.visitQueue (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56353:16)
    at TraversalContext.visitSingle (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56322:19)
    at TraversalContext.visit (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56381:19)
    at Function.traverse.node (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56506:17)
    at traverse (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56486:12)
    at transformFile (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:6224:29)
    at transformFile.next (<anonymous>)
    at run (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:6152:12)

 error  in ./src/app.tsx

Module build failed (from ../../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep @ant-design/icons
    at getDepVersion (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/getDepVersion.js:120:27)
    at DepInfo.addTmpDep (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepInfo.js:132:56)
    at Object.onTransformDeps (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js:289:23)
    at PluginPass.exit (/Users/choby/Documents/bingli/management_system/node_modules/umi/node_modules/@umijs/babel-plugin-import-to-await-require/lib/index.js:173:140)
    at newFn (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:62022:21)
    at NodePath._call (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56841:20)
    at NodePath.call (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56828:17)
    at NodePath.visit (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56887:8)
    at TraversalContext.visitQueue (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56353:16)
    at TraversalContext.visitSingle (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56322:19)
    at TraversalContext.visit (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56381:19)
    at Function.traverse.node (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56506:17)
    at traverse (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:56486:12)
    at transformFile (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:6224:29)
    at transformFile.next (<anonymous>)
    at run (/Users/choby/Documents/bingli/management_system/node_modules/@umijs/deps/compiled/babel/bundle.js:6152:12)

## Mini Showcase Repository(REQUIRED)

复现仓库：https://github.com/choby/mfsu_with_monorep

## How To Reproduce

环境：macos 12 beta

特别说明，复现代码中apps目录下的ant-design-pro-5使用的ant-design-pro官方源码，未做任何改动，不放在monorep中是可以正常编译的， 一旦放入monorep后就出现上述错误

**Comment by agui2200** [comment]
<img width="443" alt="image" src="https://user-images.githubusercontent.com/6271220/124213619-7ba9dc80-db23-11eb-83a7-ce730357747a.png">
更新了对应antd-pro 的依赖以后,我就不报类似错误了,你可以试试

**Comment by choby** [comment]
> <img alt="image" width="443" src="https://user-images.githubusercontent.com/6271220/124213619-7ba9dc80-db23-11eb-83a7-ce730357747a.png">
> 
> 更新了对应antd-pro 的依赖以后,我就不报类似错误了,你可以试试

我试过没啥用, 不报这个错又会报其他很多错误, 类似:
plugin @umijs/plugin-blocks is already registered by /Users/choby/Documents/bingli/management_system/node_modules/@umijs/plugin-blocks/lib/index.js, plugin from /Users/choby/Documents/bingli/management_system/node_modules/@umijs/plugin-blocks/lib/index.js register failed.

**Comment by sorrycc** [comment]
记得删除 yarn.lock，缓存的 dumi 版本应该是老的。

**Comment by veici** [comment]
该问题在3.5.1版本修复在3.5.2版本又回退了，现版本下还没解决方案吗
