### ISSUE TITLE
build出错，dev没问题

### ISSUE THREAD

**Issue by tingli1991** [umijs/umi#684]
Failed to minify the bundle. Error: umi.34882b5a.js from UglifyJs
Invalid assignment [umi.34882b5a.js:32064,30]
    at doneHandler (C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\af-webpack\lib\build.js:91:27)
    at emitRecords.err (C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\webpack\lib\Compiler.js:265:13)
    at Compiler.emitRecords (C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\webpack\lib\Compiler.js:371:38)
    at emitAssets.err (C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\webpack\lib\Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\webpack\lib\Compiler.js:364:12)
    at next (C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at next (C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\tapable\lib\Tapable.js:220:14)
    at callback (C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\copy-webpack-plugin\dist\index.js:126:17)
    at Compiler.afterEmit (C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\copy-webpack-plugin\dist\index.js:220:13)
    at next (C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\tapable\lib\Tapable.js:220:14)
    at C:\Users\zzj\AppData\Roaming\npm\node_modules\umi\node_modules\sw-precache-webpack-plugin\lib\index.js:98:18
    at <anonymous>
Read more here: http://bit.ly/2tRViJ9

**Comment by swustzl** [comment]
请问这个问题怎么解决的啊

**Comment by MartinLongYW** [comment]
这个问题解决了么

**Comment by swustzl** [comment]
参考： https://github.com/sorrycc/blog/issues/68
.webpackrc 里配：加上 
export default {
  es5ImcompatibleVersions: true,
}
