### ISSUE TITLE
[Bug] 添加mfsu后编译不通过

### ISSUE THREAD

**Issue by fanhualei** [umijs/umi#6879]
### 错误信息

[在gitee上的源代码，可以下载后重现这个编译错误](https://gitee.com/fanhualei/wukong-doc)

```
ERROR  Failed to compile with 1 errors                                                                                                   下午9:04:52

 error  in ./src/app.ts

Module parse failed: Top-level-await is only supported in EcmaScript Modules
File was processed with these loaders:
 * ./node_modules/@umijs/deps/compiled/babel-loader/index.js
You may need an additional loader to handle the result of these loaders.
Error: Top-level-await is only supported in EcmaScript Modules
    at /home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:138806:11
    at Hook.eval (eval at create (/home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50172:10), <anonymous>:7:16)
    at JavascriptParser.walkAwaitExpression (/home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:154429:29)
    at JavascriptParser.walkExpression (/home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:154359:10)
    at JavascriptParser.walkVariableDeclaration (/home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:154213:33)
    at JavascriptParser.walkStatement (/home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:153707:10)
    at JavascriptParser.walkStatements (/home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:153568:9)
    at JavascriptParser.parse (/home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:155453:9)
    at /home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:116109:26
    at processResult (/home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115836:11)
    at /home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115900:5
    at /home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:35132:3
    at iterateNormalLoaders (/home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34958:10)
    at iterateNormalLoaders (/home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34965:10)
    at /home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34980:3
    at context.callback (/home/fan/08-web/wukong-doc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34850:13)


● Webpack █████████████████████████ done (99%)  

```

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/issues/6766
FAQ 里有。
