### ISSUE TITLE
[Bug] [MFSU] package.json not found for dep qiankun——lerna

### ISSUE THREAD

**Issue by DZ-study** [umijs/umi#6882]
## What happens?
问题描述：
新建一个lerna项目，创建main主应用和两个子应用，主应用配置qiankun，mfsu之后，启动报错，子应用可以正常运行

## Mini Showcase Repository(REQUIRED)
复现仓库地址：
https://github.com/DZ-study/umi-mfsu-demo

主应用umi配置：
`nodeModulesTransform: {
    type: 'none',
  },
  routes,
  fastRefresh: {},
  layout: {
    name: 'Test',
    locale: true,
    layout: 'side'
  },
  qiankun: {
    master: {
      apps: [
        {
          name: 'firstdemo',
          entry: '//localhost:7001'
        },
        {
          name: 'app2',
          entry: "//localhost:7002"
        }
      ]
    }
  },
  mfsu: {},
  dynamicImport: {}`

错误提示：
 ERROR  Failed to compile with 3 errors                                                                      上午7:10:12

 error  in ./src/.umi/plugin-layout/layout/layout/index.tsx

Module build failed (from ../../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep @umijs/route-utils
    at getDepVersion (D:\000-frontend_masters\lerna-repo\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\getDepVersion.js:123:27)
    at DepInfo.addTmpDep (D:\000-frontend_masters\lerna-repo\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepInfo.js:139:56)
    at Object.onTransformDeps (D:\000-frontend_masters\lerna-repo\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\mfsu.js:281:23)
    at PluginPass.exit (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\babel-plugin-import-to-await-require\lib\index.js:173:140)
    at newFn (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:62022:21)
    at NodePath._call (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56841:20)
    at NodePath.call (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56828:17)
    at NodePath.visit (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56887:8)
    at TraversalContext.visitQueue (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56353:16)
    at TraversalContext.visitSingle (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56322:19)

 error  in ./src/.umi/plugin-qiankun/MicroApp.tsx

Module build failed (from ../../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep qiankun
    at getDepVersion (D:\000-frontend_masters\lerna-repo\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\getDepVersion.js:123:27)
    at DepInfo.addTmpDep (D:\000-frontend_masters\lerna-repo\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepInfo.js:139:56)
    at Object.onTransformDeps (D:\000-frontend_masters\lerna-repo\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\mfsu.js:281:23)
    at PluginPass.exit (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\babel-plugin-import-to-await-require\lib\index.js:173:140)
    at newFn (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:62022:21)
    at NodePath._call (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56841:20)
    at NodePath.call (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56828:17)
    at NodePath.visit (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56887:8)
    at TraversalContext.visitQueue (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56353:16)
    at TraversalContext.visitSingle (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56322:19)

 error  in ./src/.umi/plugin-qiankun/masterRuntimePlugin.ts

Module build failed (from ../../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep qiankun
    at getDepVersion (D:\000-frontend_masters\lerna-repo\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\getDepVersion.js:123:27)
    at DepInfo.addTmpDep (D:\000-frontend_masters\lerna-repo\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepInfo.js:139:56)
    at Object.onTransformDeps (D:\000-frontend_masters\lerna-repo\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\mfsu.js:281:23)
    at PluginPass.exit (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\babel-plugin-import-to-await-require\lib\index.js:173:140)
    at newFn (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:62022:21)
    at NodePath._call (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56841:20)
    at NodePath.call (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56828:17)
    at NodePath.visit (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56887:8)
    at TraversalContext.visitQueue (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56353:16)
    at TraversalContext.visitSingle (D:\000-frontend_masters\lerna-repo\node_modules\@umijs\deps\compiled\babel\bundle.js:56322:19)

## Context

- **Umi Version**: 3.5.2
- **Node Version**:  v14.16.1
- **Platform**: window10

**Comment by sorrycc** [comment]
monorepo 还不支持。

**Comment by laozhu** [comment]
一样的问题，大佬早点支持 monorepo，很需要，我先关着吧。

**Comment by sorrycc** [comment]
暂不支持 monorepo，等下个 mirror 版本。

**Comment by caoxu331** [comment]
坐等支持monorepo😂

**Comment by yaohaizh** [comment]
@sorrycc msft大概什么时候支持monorepo的？有没有时间表的？谢谢~~~

**Comment by GreatAuk** [comment]
@DZ-study 问下，如果公共组件单独一个拆成一个package，其它子应用 package 引用这个 组件package，有实现吗？

**Comment by dingyc1022** [comment]
现在支持了吗

**Comment by CherishTheYouth** [comment]
还不支持嘛，有计划吗？
