### ISSUE TITLE
[Bug] 同时配置了 mfsu 和 qiankun 之后 Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by yunyouu** [umijs/umi#6904]
现有项目已经使用了 qiankun，umi 版本升级到 3.5.3 之后直接启动会出现这个错误。

```
// 配置文件
import { defineConfig } from 'umi';
import routes from './routes';

export default defineConfig({
    ...
    mfsu:{},
    qiankun: { slave: { devSourceMap: false, keepOriginalRoutes: true } },
});

```

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:721:3)
    at tryReadSync (node:fs:431:20)
    at readFileSync (node:fs:477:19)
    at /opt/project/enjoy-link_wms_web/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js:333:48
    at Layer.handle [as handle_request] (/opt/project/enjoy-link_wms_web/node_modules/@umijs/server/node_modules/@umijs/deps/compiled/express/index.js:1:56673)
    at trim_prefix (/opt/project/enjoy-link_wms_web/node_modules/@umijs/server/node_modules/@umijs/deps/compiled/express/index.js:1:53129)
    at /opt/project/enjoy-link_wms_web/node_modules/@umijs/server/node_modules/@umijs/deps/compiled/express/index.js:1:52730
    at Function.process_params (/opt/project/enjoy-link_wms_web/node_modules/@umijs/server/node_modules/@umijs/deps/compiled/express/index.js:1:53268)
    at next (/opt/project/enjoy-link_wms_web/node_modules/@umijs/server/node_modules/@umijs/deps/compiled/express/index.js:1:52631)
    at /opt/project/enjoy-link_wms_web/node_modules/@umijs/preset-built-in/lib/plugins/features/devScripts.js:56:9
    at Layer.handle [as handle_request] (/opt/project/enjoy-link_wms_web/node_modules/@umijs/server/node_modules/@umijs/deps/compiled/express/index.js:1:56673)
    at trim_prefix (/opt/project/enjoy-link_wms_web/node_modules/@umijs/server/node_modules/@umijs/deps/compiled/express/index.js:1:53129)
    at /opt/project/enjoy-link_wms_web/node_modules/@umijs/server/node_modules/@umijs/deps/compiled/express/index.js:1:52730
    at Function.process_params (/opt/project/enjoy-link_wms_web/node_modules/@umijs/server/node_modules/@umijs/deps/compiled/express/index.js:1:53268)
    at next (/opt/project/enjoy-link_wms_web/node_modules/@umijs/server/node_modules/@umijs/deps/compiled/express/index.js:1:52631)
    at next (/opt/project/enjoy-link_wms_web/node_modules/@umijs/server/node_modules/@umijs/deps/compiled/express/index.js:1:58381)
```

- **Umi Version**: 3.5.3
- **Node Version**: 16.2
- **Platform**: wsl2

**Comment by yanglwr** [comment]
> 补充：sandbox 是关闭的

**Comment by sorrycc** [comment]
需要给复现仓库。

**Comment by zsz91** [comment]
持续关注. 我也遇到了同样的问题. 
只开启了 mfsu: {},
