### ISSUE TITLE
[Bug] 开启 mfsu 和 workerLoader 情况卡 99%

### ISSUE THREAD

**Issue by SturdyCat** [umijs/umi#7011]
开启 mfsu 和 workerLoader 情况卡 99%
```
mfsu: {},
workerLoader: {},
```
不开 mfsu 都工作正常

- **Umi Version**: v3.5.13
- **Node Version**: v14.15.3
- **Platform**: macOS 10.15.7

**Comment by sorrycc** [comment]
99% 是显示问题，功能是正常的。

**Comment by SturdyCat** [comment]
使用 web worker 情况
开启 workerLoader + mfsu 就是报错误
不开启 mfsu 时都可以正常工作
```
yarn run v1.22.10
$ cross-env UMI_ENV=dev umi dev
Bundle with webpack 5...
MFSU Enabled
Starting the development server...

✖ Webpack
  Compiled with some errors in 19.60s


✖ Webpack
  

 ERROR  Failed to compile with 0 errors                                                                                                                                                                                                                                                                            上午11:34:27

(node:18278) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at /Users/Shirley/Desktop/Code/umi-wasm/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (/Users/Shirley/Desktop/Code/umi-wasm/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
    at /Users/Shirley/Desktop/Code/umi-wasm/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:189:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/Shirley/Desktop/Code/umi-wasm/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
    at _next (/Users/Shirley/Desktop/Code/umi-wasm/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18278) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18278) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by sorrycc** [comment]
需要有复现步骤。

**Comment by SturdyCat** [comment]
@sorrycc 
[源代码地址](https://github.com/SturdyCat/bug-umi-worker.git)

**Comment by 431910864** [comment]
加上webpack5: { lazyCompilation: {} } 就能跑通 但是会报其他的错

**Comment by SturdyCat** [comment]
@431910864 还是 mfsu 的兼容性问题，开启 lazyCompilation 只是启动时没有出发错这段位置，当运行到这里仍然报错

**Comment by cuijiudai** [comment]
我也遇到了
