### ISSUE TITLE
[Bug] monorepo 开启mfsu报错

### ISSUE THREAD

**Issue by sanmmm** [umijs/umi#7040]
## What happens?
monorepo项目结构下。使用--hoist将公共依赖包提取到了仓库root目录（D:\example\）下的node_modules中。然后开启子项目（D:\example\platform\frontend）umi的mfsu，会报错：

Module build failed (from ../../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep @ant-design/icons which is imported from D:\example\platform\frontend\src\app.tsx
    at getDepVersion (D:\example\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\getDepVersion.js:129:27)
    at DepInfo.addTmpDep (D:\example\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepInfo.js:141:56)
    at Object.onTransformDeps (D:\example\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\mfsu.js:300:23)
    at PluginPass.exit (D:\example\node_modules\@umijs\babel-plugin-import-to-await-require\lib\index.js:182:140)
    at newFn (D:\example\node_modules\@umijs\deps\compiled\babel\bundle.js:62022:21)
    at NodePath._call (D:\example\node_modules\@umijs\deps\compiled\babel\bundle.js:56841:20)     
    at NodePath.call (D:\example\node_modules\@umijs\deps\compiled\babel\bundle.js:56828:17)      
    at NodePath.visit (D:\example\node_modules\@umijs\deps\compiled\babel\bundle.js:56887:8)      
    at TraversalContext.visitQueue (D:\example\node_modules\@umijs\deps\compiled\babel\bundle.js:56353:16)
    at TraversalContext.visitSingle (D:\example\node_modules\@umijs\deps\compiled\babel\bundle.js:56322:19)
    at TraversalContext.visit (D:\example\node_modules\@umijs\deps\compiled\babel\bundle.js:56381:19)
    at Function.traverse.node (D:\example\node_modules\@umijs\deps\compiled\babel\bundle.js:56506:17)
    at traverse (D:\example\node_modules\@umijs\deps\compiled\babel\bundle.js:56486:12)
    at transformFile (D:\example\node_modules\@umijs\deps\compiled\babel\bundle.js:6224:29)       
    at transformFile.next (<anonymous>)
    at run (D:\example\node_modules\@umijs\deps\compiled\babel\bundle.js:6152:12)

查阅代码，应该是读取依赖package.json文件的这部分代码只考虑到cwd文件夹下的node_modules，没有考虑上游文件夹。
https://github.com/umijs/umi/blob/5b2b74ed2b97065c37e5622abdc6b21116cb2c09/packages/preset-built-in/src/plugins/features/mfsu/getDepVersion.ts#L86-L98

**Comment by sorrycc** [comment]
暂不支持 monorepo，等下个 mirror 版本。

**Comment by zoffyzhang** [comment]
如果包管理工具是 yarn v1，可以尝试 nohoist，配置 package.json

```json
  "workspaces": {
    "packages": ["packages/*"],
    "nohoist":  ["**"]
  },
```
