### ISSUE TITLE
[Bug] 配置webpack5，启动报错 

### ISSUE THREAD

**Issue by Joyeuxman** [umijs/umi#7087]
## 背景：项目是用umi脚手架进行搭建的，刚开始umi版本号是3.4.25，在此版本上添加`webpack5:{}`，启动报错
后来升级umi版本号3.5.14，配置文件中添加 `webpack5:{}`，然后启动项目依旧报错
报错如下：
```
Cannot read property 'toIdentifier' of undefined
TypeError: Cannot read property 'toIdentifier' of undefined
    at ReactRefreshPlugin.apply (/Users/work/cloud-classroom/node_modules/umi/node_modules/@umijs/preset-built-in/bundled/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:158:18)
    at WrappedPlugin.apply (/Users/work/cloud-classroom/node_modules/@umijs/deps/compiled/speed-measure-webpack-plugin/index.js:1:3333)
    at createCompiler (/Users/work/cloud-classroom/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:191641:12)
    at /Users/work/cloud-classroom/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:191611:48
    at Array.map (<anonymous>)
    at createMultiCompiler (/Users/work/cloud-classroom/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:191611:33)
    at create (/Users/work/cloud-classroom/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:191685:16)
    at Object.webpack (/Users/work/cloud-classroom/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:191718:32)
    at Bundler.setupDevServerOpts (/Users/work/cloud-classroom/node_modules/@umijs/bundler-webpack/lib/index.js:197:40)
    at /Users/work/cloud-classroom/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/dev.js:300:30
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/work/cloud-classroom/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/dev.js:74:103)
    at _next (/Users/work/cloud-classroom/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/dev.js:76:194)
```

**Comment by sorrycc** [comment]
还是给个复现仓库吧，试了下不能复现。

**Comment by furylee** [comment]
> 还是给个复现仓库吧，试了下不能复现。

今天clone 了ant pro simple JS版本,build时报warn
```
(node:11428) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favo
r of optimization.emitOnErrors
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:11428) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.pro
cessAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:11428) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to Normal
Module.getCompilationHooks(compilation).loader
```
关闭 webpack5和mfsu才不报

**Comment by Joyeuxman** [comment]
我找到原因了，我在`.env`文件中，添加了`SPEED_MEASURE=CONSOLE`，就会出现那个报错信息。我去掉之后就不会报错了。

**Comment by byan** [comment]
> 我找到原因了，我在`.env`文件中，添加了`SPEED_MEASURE=CONSOLE`，就会出现那个报错信息。我去掉之后就不会报错了。

我没添加这也出现在这个报错了~

**Comment by tvrcgo** [comment]
> > 还是给个复现仓库吧，试了下不能复现。
> 
> 今天clone 了ant pro simple JS版本,build时报warn
> 
> ```
> (node:11428) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favo
> r of optimization.emitOnErrors
> (Use `node --trace-deprecation ...` to show where the warning was created)
> (node:11428) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.pro
> cessAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
> (node:11428) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to Normal
> Module.getCompilationHooks(compilation).loader
> ```
> 
> 关闭 webpack5和mfsu才不报

打开 webpack5 也遇到这个 warning，在 chainWebpack 里面看 config.toConfig()，还是 webpack4 的写法。

![image](https://user-images.githubusercontent.com/237062/164673638-d262795e-cc72-46be-9083-cf8121d34100.png)

production mode 有，development mode 没有

**Comment by buquan** [comment]
> 我找到原因了，我在`.env`文件中，添加了`SPEED_MEASURE=CONSOLE`，就会出现那个报错信息。我去掉之后就不会报错了。

应该不是umi问题，请问不去 `SPEED_MEASURE=CONSOLE` 有办法解决吗，这个[issue](https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/149)好像还是没找到答案
