### ISSUE TITLE
build   disableDynamicImport: false 编译不成功

### ISSUE THREAD

**Issue by wangxiansheng001** [umijs/umi#711]
```
1 verbose cli   'build' ]
2 info using npm@6.1.0
3 info using node@v9.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle antd-admin@5.0.0-beta~prebuild: antd-admin@5.0.0-beta
6 info lifecycle antd-admin@5.0.0-beta~build: antd-admin@5.0.0-beta
7 verbose lifecycle antd-admin@5.0.0-beta~build: unsafe-perm in lifecycle true
8 verbose lifecycle antd-admin@5.0.0-beta~build: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\wwwww\antd-admin-2018\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\mongodb\bin;C:\Program Files\PuTTY\;C:\Users\Administrator\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\Administrator\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle antd-admin@5.0.0-beta~build: CWD: D:\wwwww\antd-admin-2018
10 silly lifecycle antd-admin@5.0.0-beta~build: Args: [ '/d /s /c', 'cross-env BABELRC=1  umi build' ]
11 silly lifecycle antd-admin@5.0.0-beta~build: Returned: code: 134  signal: null
12 info lifecycle antd-admin@5.0.0-beta~build: Failed to exec build script
13 verbose stack Error: antd-admin@5.0.0-beta build: `cross-env BABELRC=1  umi build`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid antd-admin@5.0.0-beta
```

**Comment by xiaohuoni** [comment]
@wangxiansheng001 disableDynamicImport默认就是false，配不配置都是一样的。
