### ISSUE TITLE
AssertionError [ERR_ASSERTION]: filePath not found

### ISSUE THREAD

**Issue by WLyKan** [umijs/umi#7114]
配置mfsu后，启动报错

```bash
# /node_modules/@umijs/plugin-model/lib/helpers/constant
AssertionError [ERR_ASSERTION]: filePath not found of /node_modules/@umijs/plugin-model/lib/helpers/constant
    at /node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:116:27
# 经查是后缀名不对，plugin-model/lib/helpers/constant的后缀名是 .tsx.tpl
# 加上后缀名后，提示后缀名不支持
Error: Parse file /node_modules/@umijs/plugin-model/lib/helpers/constant.tsx.tpl failed, .tpl not support!
    at /node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/getDepReExportContent.js:131:13
```

**Comment by astonishqft** [comment]
遇到了同样的错误

**Comment by xiefengnian** [comment]
plugin-model 的 helpers 经过改造已经将这些 runtime 放置到 .umi/plugin-model 下了，检查一下这个目录有没有

**Comment by sorrycc** [comment]
先确认 umi 和相关插件的依赖是否最新，是的话给复现步骤。

**Comment by WLyKan** [comment]
> 先确认 umi 和相关插件的依赖是否最新，是的话给复现步骤。

我升级了`umi`, `@umijs/preset-react`, 可能把`@umijs/preset-ant-design-pro`漏了。
把node_modules删掉重新安装了，没有报错了

**Comment by hu-tu-yi-shi** [comment]
只删 `node_modules` 没用， 得删了 src下的  `.umi`
