### ISSUE TITLE
[Bug] Cannot find module x when using Yarn PnP.

### ISSUE THREAD

**Issue by Molay** [umijs/umi#7230]
## What happens?

Yarn PnP can greatly reduce disk space and avoid  the damage to SSD caused by large number of small files.

But when using Yarn PnP for umi app project, the '@umijs/deps/compiled/resolve/index.js' file will conflict with the yarn's default PnP module require logic, so that dependent modules cannot be found.

Can you guys adapt the codes to support Yarn PnP? 

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

No need to upload the repository, use the following example directly:

```bash
mkdir test-app
cd test-app
yarn create @umijs/umi-app

# The major version of yarn must be greater than or equal to 2
yarn set version berry

# These dependency packages need to be processed as top-level packages before `yarn install`
## @umijs/utils tried to access @umijs/babel-preset-umi, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
yarn add @umijs/babel-preset-umi --dev
## @umijs/babel-preset-umi tried to access @umijs/utils, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
yarn add @umijs/utils --dev  

# The postinstall and start operation will fail with error message 'Cannot find module '@umijs/preset-react' from "test-app"'
yarn install
yarn postinstall
yarn start

```

## How To Reproduce

Follow the example above to reproduce the problem.

```bash
# This file contains the result of Yarn building a package (root-workspace-0b6124@workspace:.)
# Script name: postinstall

Cannot find module '@umijs/preset-react' from 'test-app'
Error: Cannot find module '@umijs/preset-react' from 'test-app'
    at Function.resolveSync [as sync] (test-app/.yarn/cache/@umijs-deps-npm-3.5.17-155423346d-c6049b8149.zip/node_modules/@umijs/deps/compiled/resolve/index.js:1:11170)
    at test-app/.yarn/cache/@umijs-core-npm-3.5.17-450551b11e-722018cbdf.zip/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:94:29
    at Array.map (<anonymous>)
    at getPluginsOrPresets (test-app/.yarn/cache/@umijs-core-npm-3.5.17-450551b11e-722018cbdf.zip/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:89:99)
    at resolvePresets (test-app/.yarn/cache/@umijs-core-npm-3.5.17-450551b11e-722018cbdf.zip/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:173:23)
    at new Service (test-app/.yarn/cache/@umijs-core-npm-3.5.17-450551b11e-722018cbdf.zip/node_modules/@umijs/core/lib/Service/Service.js:197:59)
    at new Service (test-app/.yarn/cache/umi-npm-3.5.17-b8e6fdb58a-47695465f9.zip/node_modules/umi/lib/ServiceWithBuiltIn.js:50:5)
    at test-app/.yarn/cache/umi-npm-3.5.17-b8e6fdb58a-47695465f9.zip/node_modules/umi/lib/cli.js:119:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (test-app/.yarn/cache/umi-npm-3.5.17-b8e6fdb58a-47695465f9.zip/node_modules/umi/lib/cli.js:55:103)
```

```bash
Error: Cannot find module '@umijs/preset-react' from 'test-app'
    at Function.resolveSync [as sync] (test-app/.yarn/cache/@umijs-deps-npm-3.5.17-155423346d-c6049b8149.zip/node_modules/@umijs/deps/compiled/resolve/index.js:1:11108)
    at test-app/.yarn/cache/@umijs-core-npm-3.5.17-450551b11e-722018cbdf.zip/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:94:29
    at Array.map (<anonymous>)
    at getPluginsOrPresets (test-app/.yarn/cache/@umijs-core-npm-3.5.17-450551b11e-722018cbdf.zip/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:89:99)
    at resolvePresets (test-app/.yarn/cache/@umijs-core-npm-3.5.17-450551b11e-722018cbdf.zip/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:173:23)
    at new Service (test-app/.yarn/cache/@umijs-core-npm-3.5.17-450551b11e-722018cbdf.zip/node_modules/@umijs/core/lib/Service/Service.js:197:59)
    at new Service (test-app/.yarn/cache/umi-npm-3.5.17-b8e6fdb58a-47695465f9.zip/node_modules/umi/lib/ServiceWithBuiltIn.js:50:5)
    at test-app/.yarn/cache/umi-npm-3.5.17-b8e6fdb58a-47695465f9.zip/node_modules/umi/lib/forkedDev.js:44:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (test-app/.yarn/cache/umi-npm-3.5.17-b8e6fdb58a-47695465f9.zip/node_modules/umi/lib/forkedDev.js:33:103)
```

## Context

- **Umi Version**: latest
- **Node Version**: 14.15.4
- **Platform**: macOS 10.15.7
- **Yarn Version**: 3.0.1

**Comment by xiaohuoni** [comment]
还没支持 yarn2 ，请关注这里的进度 https://github.com/umijs/umi/issues/6303

**Comment by gmqiyue** [comment]
官方仓库有个[umi-plugin-pnp](https://github.com/umijs/umi-plugin-pnp)插件，这个插件是废弃了么？
