### ISSUE TITLE
[Feature/Question] MFSU Support Virtual Modules

### ISSUE THREAD

**Issue by harlan-zw** [umijs/umi#7303]
Related: https://github.com/windicss/windicss-webpack-plugin/issues/92#issuecomment-912845045

The MFSU scans modules, resolving their package.json based on their path (afaik), the windicss webpack plugin uses a virtual module that does not have a package.json, leading to the error:

```
 error  in ./src/app.ts

Module build failed (from ./node_modules/@umijs/deps/compiled/babel-loader/index.js):
**AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep windi.css which is imported from @/app.ts
    at getDepVersion (/home/harlan/packages/windicss-webpack-plugin/umijs-windicss/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/getDepVersion.js:129:27)**
    at DepInfo.addTmpDep (/home/harlan/packages/windicss-webpack-plugin/umijs-windicss/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepInfo.js:141:56)
    at Object.onTransformDeps (/home/harlan/packages/windicss-webpack-plugin/umijs-windicss/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js:321:23)
    at PluginPass.exit (/home/harlan/packages/windicss-webpack-plugin/umijs-windicss/node_modules/@umijs/babel-plugin-import-to-await-require/lib/index.js:217:140)
    at newFn (/home/harlan/packages/windicss-webpack-plugin/umijs-windicss/node_modules/@umijs/deps/compiled/babel/bundle.js:62022:21)
    at NodePath._call (/home/harlan/packages/windicss-webpack-plugin/umijs-windicss/node_modules/@umijs/deps/compiled/babel/bundle.js:56841:20)
    at NodePath.call (/home/harlan/packages/windicss-webpack-plugin/umijs-windicss/node_modules/@umijs/deps/compiled/babel/bundle.js:56828:17)
    at NodePath.visit (/home/harlan/packages/windicss-webpack-plugin/umijs-windicss/node_modules/@umijs/deps/compiled/babel/bundle.js:56887:8)
    at TraversalContext.visitQueue (/home/harlan/packages/windicss-webpack-plugin/umijs-windicss/node_modules/@umijs/deps/compiled/babel/bundle.js:56353:16)
    at TraversalContext.visitSingle (/home/harlan/packages/windicss-webpack-plugin/umijs-windicss/node_modules/@umijs/deps/compiled/babel/bundle.js:56322:19)
```

Is there any way to have a module skipped by MFSU?

Thanks :)

**Comment by xiefengnian** [comment]
I'm trying to fix this problem~

**Comment by kevinpursuing** [comment]
@xiefengnian 请问问题解决了吗

**Comment by kevinpursuing** [comment]
@xiaohuoni 请问这个问题修复了吗

**Comment by soulcm** [comment]
这个问题umijs这边有人在解决吗，我这边也遇到了

**Comment by z1948296027** [comment]
这个问题umijs这边有人在解决吗，我这边也遇到了

**Comment by kevinpursuing** [comment]
请问什么时候解决呢

**Comment by chenkaixia** [comment]
这个还没有解决啊

**Comment by GrinZero** [comment]
+1

**Comment by EricWong1994** [comment]
+1，咋close了 @sorrycc

**Comment by EricWong1994** [comment]
当config中开启 webpack5: {} 配置后， windicss的text-3xl  font-semibold font-600 不生效
