### ISSUE TITLE
[Bug] 项目内编写的插件引入其他文件时报错

### ISSUE THREAD

**Issue by lostaloneesk** [umijs/umi#7380]
## What happens?

我在项目里面编写了一个插件，这个插件引入了项目内的其他文件后，启动项目就会报错
```since Cannot use import statement outside a module```

![image](https://user-images.githubusercontent.com/17976986/134762624-f42beb79-5c95-45f7-8013-4c03661afd28.png)

![image](https://user-images.githubusercontent.com/17976986/134762717-4be40f08-7950-41eb-9359-7681cc4f9ebd.png)

![image](https://user-images.githubusercontent.com/17976986/134762734-e1274c0c-3d89-4c2f-9999-99f1a6177ebd.png)

报错内容
```
$ cross-env UMI_ENV=dev umi dev
Register plugin /Users/worker/Documents/admin/plugins/access/index.ts failed, since Cannot use import statement outside a module
Error: Register plugin /Users/worker/Documents/admin/plugins/access/index.ts failed, since Cannot use import statement outside a module
    at Object.apply (/Users/worker/Documents/admin/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:163:15)
    at /Users/worker/Documents/admin/node_modules/@umijs/core/lib/Service/Service.js:364:22
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/worker/Documents/admin/node_modules/@umijs/core/lib/Service/Service.js:110:103)
    at _next (/Users/worker/Documents/admin/node_modules/@umijs/core/lib/Service/Service.js:112:194)
    at /Users/worker/Documents/admin/node_modules/@umijs/core/lib/Service/Service.js:112:364
    at new Promise (<anonymous>)
    at /Users/worker/Documents/admin/node_modules/@umijs/core/lib/Service/Service.js:112:97
    at Service.applyAPI (/Users/worker/Documents/admin/node_modules/@umijs/core/lib/Service/Service.js:371:7)
    at /Users/worker/Documents/admin/node_modules/@umijs/core/lib/Service/Service.js:454:20
✨  Done in 2.62s.
```

**Comment by lostaloneesk** [comment]
@sorrycc
