### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by wzquyin** [umijs/umi#7506]
今天出现的新问题，以前没有
今天崭新的电脑上，执行
yarn create @umijs/umi-app
然后创建出来的新项目，yarn install后 yarn start 直接报错，各种不行，，重试无数次了，是否某个依赖库更新，导致了没法用？
package.json文件如下
"dependencies": {
    "@ant-design/pro-layout": "^6.5.0",
    "react": "17.x",
    "react-dom": "17.x",
    "umi": "^3.5.19"
  },
  "devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.5.20",
    "lint-staged": "^10.0.7",
    "prettier": "^2.2.0",
    "typescript": "^4.1.2",
    "yorkie": "^2.0.0"
  }

错误如下
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports.__webpack_modules__.57442.module.exports (E:\blockChain\minner\app2\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:135907:62)
    at NormalModule._initBuildHash (E:\blockChain\minner\app2\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:109317:16)
    at handleParseError (E:\blockChain\minner\app2\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:109371:10)
    at E:\blockChain\minner\app2\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:109403:5
    at E:\blockChain\minner\app2\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:109258:12
    at E:\blockChain\minner\app2\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:61157:3
    at iterateNormalLoaders (E:\blockChain\minner\app2\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:60998:10)
    at Array.<anonymous> (E:\blockChain\minner\app2\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:60989:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by yaohwu** [comment]
https://github.com/ant-design/ant-design-pro/issues/9272

It works using node 18 in mac but failed in Linux docker. Why?
