### ISSUE TITLE
开启esbuild后打包失败，有复现

### ISSUE THREAD

**Issue by mdddj** [umijs/umi#7537]
出错版本
```bash
"umi": "^3.5.20"
@umijs/plugin-esbuild": "^1.4.1"
```

复现Github: [https://github.com/mdddj/dd_blog_react](https://github.com/mdddj/dd_blog_react)

下载项目，打开控制台
```bash
yarn
yarn build
```

(去掉`esbuild: {}`打包一切正常)
##### 报错内容 
```bash
HookWebpackError: Transform failed with 1 error:
245.js:9:50: error: Transforming for-await loops to the configured target environment is not supported yet
    at makeWebpackError (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:108568:9)
    at C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:93433:12
    at eval (eval at create (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:50186:10), <anonymous>:42:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
-- inner error --
Error: Transform failed with 1 error:
245.js:9:50: error: Transforming for-await loops to the configured target environment is not supported yet
    at failureErrorWithLog (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:1160:15)
    at C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:1026:33
    at C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:542:9
    at handleIncomingPacket (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:631:9)
    at Socket.readFromStdout (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:509:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
caused by plugins in Compilation.hooks.processAssets
Error: Transform failed with 1 error:
245.js:9:50: error: Transforming for-await loops to the configured target environment is not supported yet
    at failureErrorWithLog (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:1160:15)
    at C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:1026:33
    at C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:542:9
    at handleIncomingPacket (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:631:9)
    at Socket.readFromStdout (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:509:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
build failed
Error: build failed
    at C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\bundler-webpack\lib\index.js:172:29
    at C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114591:14
    at C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114422:12
    at C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:38249:7
    at done (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:38284:11)
    at C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:38237:7
    at C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114419:8
    at arrayEach (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:37824:9)
    at Object.each (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:38265:9)
    at nodeDone (C:\Users\eee\Documents\GitHub\dd_blog_react\node_modules\umi\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114413:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by mdddj** [comment]
大佬子们帮忙解决一下

**Comment by 24kglod** [comment]
"umi": "^3.5.0"
@umijs/plugin-esbuild": "^1.0.1"
我是这个版本，build没问题

**Comment by mdddj** [comment]
> "umi": "^3.5.0" @umijs/plugin-esbuild": "^1.0.1" 我是这个版本，build没问题

 试了 也不行

**Comment by xiaohuoni** [comment]
```
 { path: '/push-blog', component: '@/pages/markdown' },
```
你这个组件里面有的包，esbuild 不支持。

**Comment by mdddj** [comment]
> ```
>  { path: '/push-blog', component: '@/pages/markdown' },
> ```
> 
> 你这个组件里面有的包，esbuild 不支持。

好吧多谢大佬。打包后dist文件夹大约2M，第一次加载网站要40秒左右，有什么办法优化到十秒内吗

**Comment by xiaohuoni** [comment]
https://zhuanlan.zhihu.com/p/157540425 https://umijs.org/zh-CN/guide/boost-compile-speed 看看这些，有没有你要的。

**Comment by mdddj** [comment]
试过了，进行到esbuild这一步，来提了这个issue
