### ISSUE TITLE
[Bug] while loading "./file-saver" from webpack/container/reference/mf

### ISSUE THREAD

**Issue by Valar103769** [umijs/umi#7895]
开启 mfsu之后, 编译报错, 

我是这样用的,
```js
import { saveAs } from 'file-saver'

 saveAs(
      new Blob([s2ab(wbout)], {
        type: 'application/octet-stream',
      }),
      'test.xlsx',
    )
```

[@umijs/runtime] load component failed Error: Module "./file-saver" does not exist in container.
while loading "./file-saver" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:903:11 
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules_umi_node_modules_umijs_runtime_dist_index_esm_js.eb4fd323.async.js:393:68)
    at Route
    at Switch
    at Route
    at Switch
    at WithExceptionOpChildren (http://localhost:8000/.umi__plugin-layout__Layout.js:231:24)
    at main
    at Basic (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.50388db9.async.js:430:25)
    at Adapter (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.50388db9.async.js:413:66)
    at ErrorBoundary (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_antd_es__util_getDataOrAr-d82008.9e202bd5.async.js:6011:87)
    at SWRConfig$1 (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-provider_es_index_js-node_modules_ant-design_pro-utils_es-d7da91.65d0fc76.async.js:3473:23)
    at ConfigProviderWrap (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-provider_es_index_js-node_modules_ant-design_pro-utils_es-d7da91.65d0fc76.async.js:241:23)
    at WrapContent (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_antd_es__util_getDataOrAr-d82008.9e202bd5.async.js:957:21)
    at div
    at section
    at BasicLayout (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.50388db9.async.js:445:63)
    at Adapter (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.50388db9.async.js:413:66)
    at div
    at Provider (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_antd_es__util_getDataOrAr-d82008.9e202bd5.async.js:13040:31)
    at BasicLayout (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_antd_es__util_getDataOrAr-d82008.9e202bd5.async.js:383:67)
    at BasicLayout (http://localhost:8000/.umi__plugin-layout__Layout.js:710:24)
    at http://localhost:8000/.umi__plugin-layout__Layout.js:41:19
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules_umi_node_modules_umijs_runtime_dist_index_esm_js.eb4fd323.async.js:393:68)
    at Route
    at Switch
    at Router (http://localhost:8000/mf-dep_vendors-node_modules_react-router-dom_esm_react-router-dom_js.cb21f110.async.js:3229:30)
    at RouterComponent (http://localhost:8000/mf-dep_vendors-node_modules_babel_runtime_helpers_esm_objectWithoutPropertiesLoose_js-node_modules_b-7797da.075049d7.async.js:610:23)
    at AccessProvider (http://localhost:8000/umi.js:1077:24)
    at http://localhost:8000/umi.js:1720:24
    at FormProvider (http://localhost:8000/mf-dep_vendors-node_modules_rc-field-form_es_index_js.42990c0c.async.js:2425:31)
    at LocaleProvider (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js.4a981af9.async.js:905:87)
    at ProviderChildren (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js.4a981af9.async.js:735:24)
    at LocaleReceiver (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_context_js.984d0515.async.js:720:87)
    at ConfigProvider (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js.4a981af9.async.js:843:13)
    at _LocaleContainer (http://localhost:8000/umi.js:2966:31)
    at http://localhost:8000/umi.js:3552:23

**Comment by qiutian00** [comment]
`重启一下？`

**Comment by Valar103769** [comment]
> `重启一下？`

认真的?

**Comment by ascend-hgx** [comment]
之后你怎么处理的呢，我联网可以正常访问，不联网也会报这个错。我只是访问自己电脑端口为什么还会这样呢

**Comment by Valar103769** [comment]
> 

我关了mfsu
你在做文件保存,导出的功能么可以借鉴下这个代码
 [antd table 导出excel](https://github.com/Valar103769/code-snip/blob/main/ExportButton.tsx)

**Comment by xiaofuliang** [comment]
遇到同样问题，是关了mfsu就可以了吗
