### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by larntin** [umijs/umi#7913]
## What happens?

升级到mfsu之后，项目一直报错
`
AssertionError [ERR_ASSERTION]: filePath not found of camunda-bpmn-moddle/resources/camunda
    at D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:119:27   
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:64:103)
    at _next (D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:194)
    at D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:364   
    at new Promise (<anonymous>)
    at D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:97    
    at figureOutExport (D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:129:17)
    at D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:184:201
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:84:103)
    at _next (D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:86:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

## Mini Showcase Repository(REQUIRED)

我的项目分支： msfu-test
https://gitee.com/larntin/bpmn-antd-demo/tree/msfu-test/  

## How To Reproduce

执行必现，启动不了项目

## Context

- **Umi Version**:  umi@3.5.21
- **Node Version**: 14.19.0
- **Platform**: window 10

**Comment by larntin** [comment]
same to #7914

**Comment by huangjihua** [comment]
> same to #7914

清空 .umi 目录下的 .cache 目录，然后重新编译下即可。
