### ISSUE TITLE
[Bug] mfsu报错找不到文件（json）

### ISSUE THREAD

**Issue by larntin** [umijs/umi#7914]
## What happens?

升级到mfsu之后，项目一直报错
`
AssertionError [ERR_ASSERTION]: filePath not found of camunda-bpmn-moddle/resources/camunda
    at D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:119:27   
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:64:103)
    at _next (D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:194)
    at D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:364   
    at new Promise (<anonymous>)
    at D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:97    
    at figureOutExport (D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:129:17)
    at D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:184:201
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:84:103)
    at _next (D:\source\bpmn-antd-demo\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:86:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

## Mini Showcase Repository(REQUIRED)

我的项目分支： msfu-test
https://gitee.com/larntin/bpmn-antd-demo/tree/msfu-test/  

## How To Reproduce

执行必现，启动不了项目

## Context

- **Umi Version**:  umi@3.5.21
- **Node Version**: 14.19.0
- **Platform**: window 10

**Comment by huangjihua** [comment]
遇到同样的问题，只要开启了 msfu 就会有这个问题
![image](https://user-images.githubusercontent.com/3156292/164606277-420f1ab0-49a3-4f33-8673-c09421c29965.png)

**Comment by liu18776919354** [comment]
npm 8.3.2
node v16.13.0
删掉node_modules文件夹+删掉.umi文件夹，然后重新npm install，再npm run start 还是同样的错误
![2801652274586_ pic](https://user-images.githubusercontent.com/13309154/167857728-63699ae8-785d-4a4e-b489-3aec4bacde20.jpg)

**Comment by flyingmylo** [comment]
同样的问题，删掉.umi 和 node_modules 重新也不行。请问现在解决了么？
