### ISSUE TITLE
config.ts 不支持根据环境动态配置配置项？

### ISSUE THREAD

**Issue by MaelWeb** [umijs/umi#8142]
## What happens?
在 config.ts 中根据环境动态启用  MFSU 和 webpack5 报错。

config.ts 配置如下：
```ts
import { defineConfig } from 'umi';
import Routes from './routes';

const baseConfig = {
  nodeModulesTransform: {
    type: 'none',
  },
  dynamicImport: { loading: '@/components/Loading' },
  routes: Routes,
  lessLoader: {
    modifyVars: {
      hack: 'true; @import "~@/variables.less";',
    },
  },
};

if (process.env.NODE_ENV === 'development') {
  baseConfig.webpack5 = {};
  baseConfig.mfsu = {};
}

export default defineConfig(baseConfig);

```
报错信息如下：
```text
Bundle with webpack 5...
⏱️  MFSU Enabled
Starting the development server...
Cannot read property 'ModuleFederationPlugin' of undefined
TypeError: Cannot read property 'ModuleFederationPlugin' of undefined
    at Object.fn (/Users/eden/Workspace/climb-web-admin/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js:410:62)
    at /Users/eden/Workspace/climb-web-admin/node_modules/@umijs/core/lib/Service/Service.js:587:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/eden/Workspace/climb-web-admin/node_modules/@umijs/core/lib/Service/Service.js:110:103)
    at _next (/Users/eden/Workspace/climb-web-admin/node_modules/@umijs/core/lib/Service/Service.js:112:194)
    at /Users/eden/Workspace/climb-web-admin/node_modules/@umijs/core/lib/Service/Service.js:112:364
    at new Promise (<anonymous>)
    at /Users/eden/Workspace/climb-web-admin/node_modules/@umijs/core/lib/Service/Service.js:112:97
    at /Users/eden/Workspace/climb-web-admin/node_modules/@umijs/core/lib/Service/Service.js:591:32
    at _next2 (eval at create (/Users/eden/Workspace/climb-web-admin/node_modules/@umijs/deps/compiled/tapable/index.js:1:7783), <anonymous>:17:17)
    at eval (eval at create (/Users/eden/Workspace/climb-web-admin/node_modules/@umijs/deps/compiled/tapable/index.js:1:7783), <anonymous>:42:1)
```

## Context

- **Umi Version**: 3.5.23
- **Node Version**: v14.15.0
- **Platform**: mac

**Comment by walker27** [comment]
+1

**Comment by chiaweilee** [comment]
试试 umirc.dev.js

https://umijs.org/zh-CN/docs/config#%E5%A4%9A%E7%8E%AF%E5%A2%83%E5%A4%9A%E4%BB%BD%E9%85%8D%E7%BD%AE

**Comment by MaelWeb** [comment]
> 试试 `umirc.dev.js` 或者 `config/config.dev.js`
> 
> https://umijs.org/zh-CN/docs/config#%E5%A4%9A%E7%8E%AF%E5%A2%83%E5%A4%9A%E4%BB%BD%E9%85%8D%E7%BD%AE

mfsu 必须在 config.ts 里面配置，否则也会报这个错

**Comment by zjfresh** [comment]
你这个错误是webpack5的问题吧

webpack5: {}

框架会直接读文件扫描内容（字符串） webpack5: 来判断, node_modules/.pnpm/umi@3.5.20/node_modules/umi/lib/initWebpack.js

webpack5 的判断 在 umi dev 脚本一开始运行时就会触发到(node_modules/.pnpm/umi@3.5.20/node_modules/umi/lib/forkedDev.js initWebpack() )，所以通过读文件来提前嗅探
