### ISSUE TITLE
[Bug] build时,public里的内容被esbuild处理报错

### ISSUE THREAD

**Issue by zhfish** [umijs/umi#8158]
## What happens?
我在public下放了一些静态文件，其中包括几个json格式js后缀，在build时，因为js后缀被报错
请问如何可以不让esbuild处理public里的内容
```
caused by plugins in Compilation.hooks.processAssets
Error: Transform failed with 1 error:
static/vditor/dist/js/mathjax/sre/mathmaps/fr.js:2:25: error: Expected ";" but found ":"
    at failureErrorWithLog (/Users/zhfish/dianke/ylf_frontend/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1160:15)
    at /Users/zhfish/dianke/ylf_frontend/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1026:33
    at /Users/zhfish/dianke/ylf_frontend/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:542:9
    at handleIncomingPacket (/Users/zhfish/dianke/ylf_frontend/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:631:9)
    at Socket.readFromStdout (/Users/zhfish/dianke/ylf_frontend/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:509:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

## How To Reproduce
yarn build
## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by zhfish** [comment]
#7373
找到一个同样问题，不知为何close了？

**Comment by zjfresh** [comment]
懒得看哪里把 public 丢给 esbuild，直接改 @umijs/plugin-esbuild 的 esbuild-loader options 配置更快点

![image](https://user-images.githubusercontent.com/28496323/173757992-bd58b987-4b9d-45ca-928c-71277f53c182.png)

紧急/本地随便解决：直接按上图改node_modules里的 plugin-esbuild

永久：clone @umijs/plugin-esbuild 下来改成可配置 exclude（最好是可配置 options），然后发 npm 包，卸载原包，引入新包

**Comment by zhfish** [comment]
谢谢

**Comment by zhfish** [comment]
> 可以先用这个暂时patch一下 https://www.npmjs.com/package/patch-package

竟然还有如此神器

**Comment by HengCC** [comment]
我好像也遇到这个问题了. build报错. 贼无语. 这刚来看就遇到这个帖子. 
大概报错内容`478.3f971fea.async.js:8:407582: error: Transforming for-await loops to the configured target environment is not supported yet` 看起来似乎也是esbuild的问题.

**Comment by HengCC** [comment]
> #7373 找到一个同样问题，不过这个问题使用的是terser,现在是esbuild 不知为何close了？



> ## What happens?
> 我在public下放了一些静态文件，其中包括几个json格式js后缀，在build时，因为js后缀被报错 请问如何可以不让esbuild处理public里的内容？
> 
> ```
> caused by plugins in Compilation.hooks.processAssets
> Error: Transform failed with 1 error:
> static/vditor/dist/js/mathjax/sre/mathmaps/fr.js:2:25: error: Expected ";" but found ":"
>     at failureErrorWithLog (/Users/zhfish/dianke/ylf_frontend/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1160:15)
>     at /Users/zhfish/dianke/ylf_frontend/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1026:33
>     at /Users/zhfish/dianke/ylf_frontend/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:542:9
>     at handleIncomingPacket (/Users/zhfish/dianke/ylf_frontend/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:631:9)
>     at Socket.readFromStdout (/Users/zhfish/dianke/ylf_frontend/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:509:7)
>     at Socket.emit (events.js:400:28)
>     at addChunk (internal/streams/readable.js:293:12)
>     at readableAddChunk (internal/streams/readable.js:267:9)
>     at Socket.Readable.push (internal/streams/readable.js:206:10)
>     at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
> ```

@sorrycc 有配置能忽略掉public目录中的文件吗?
