### ISSUE TITLE
Error: Register plugin @umijs/preset-umi/dist/features/ssr/ssr.js failed

### ISSUE THREAD

**Issue by cuibty** [umijs/umi#8202]
pnpm dlx create-umi

`
> umi setup

fatal - Error: Register plugin C:/Users/cuibty/Desktop/antdpro04/node_modules/.pnpm/@umijs+preset-umi@4.0.1/node_modules/@umijs/preset-umi/dist/features/ssr/ssr.js failed, since Cannot find module '../parcel-css.win32-ia32-msvc.node'
Require stack:
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@parcel+css@1.9.0\node_modules\@parcel\css\node\index.js
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@umijs+bundler-webpack@4.0.1\node_modules\@umijs\bundler-webpack\dist\index.js
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@umijs+preset-umi@4.0.1\node_modules\@umijs\preset-umi\dist\features\ssr\builder\css-loader.js
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@umijs+preset-umi@4.0.1\node_modules\@umijs\preset-umi\dist\features\ssr\builder\assets-loader.js
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@umijs+preset-umi@4.0.1\node_modules\@umijs\preset-umi\dist\features\ssr\builder\builder.js
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@umijs+preset-umi@4.0.1\node_modules\@umijs\preset-umi\dist\features\ssr\ssr.js
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@umijs+core@4.0.1\node_modules\@umijs\core\dist\service\plugin.js
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@umijs+core@4.0.1\node_modules\@umijs\core\dist\service\pluginAPI.js
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@umijs+core@4.0.1\node_modules\@umijs\core\dist\index.js
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\umi@4.0.1_typescript@4.7.4\node_modules\umi\dist\service\service.js
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\umi@4.0.1_typescript@4.7.4\node_modules\umi\dist\cli\cli.js
- C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\umi@4.0.1_typescript@4.7.4\node_modules\umi\bin\umi.js
    at Plugin.apply (C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@umijs+core@4.0.1\node_modules\@umijs\core\dist\service\plugin.js:49:23)
    at Service.initPlugin (C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@umijs+core@4.0.1\node_modules\@umijs\core\dist\service\service.js:371:37)
    at Service.run (C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\@umijs+core@4.0.1\node_modules\@umijs\core\dist\service\service.js:217:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Service.run2 (C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\umi@4.0.1_typescript@4.7.4\node_modules\umi\dist\service\service.js:36:16)
    at async Object.run (C:\Users\cuibty\Desktop\antdpro04\node_modules\.pnpm\umi@4.0.1_typescript@4.7.4\node_modules\umi\dist\cli\cli.js:37:13)
fatal - A complete log of this run can be found in:
fatal - C:\Users\cuibty\Desktop\antdpro04\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi-next/issues
 ELIFECYCLE  Command failed with exit code 1
`

**Comment by caprimoon** [comment]
同样遇到该问题，等一个解决方法
