### ISSUE TITLE
umi4 怎么结合qiankun 有demo吗？看文档上的出不来

### ISSUE THREAD

**Issue by zhishunwen** [umijs/umi#8219]

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/umi/tree/master/examples/ 的 max 和 qiankun-slave，前者是主应用，后者是子应用。

**Comment by PhilipDing** [comment]
> 参考 https://github.com/umijs/umi/tree/master/examples/ 的 max 和 qiankun-slave，前者是主应用，后者是子应用。

示例运行不起来，页面会提示：
```
Cannot read properties of undefined (reading 'displayName')
```


异常信息：
```
Uncaught Error: Element type is invalid. Received a promise that resolves to: undefined. Lazy element type must resolve to a class or function.
    at mountLazyComponent (mf-va_remoteEntry.js:17862:19)
    at beginWork (mf-va_remoteEntry.js:18840:24)
    at HTMLUnknownElement.callCallback2 (mf-va_remoteEntry.js:6602:25)
    at Object.invokeGuardedCallbackDev (mf-va_remoteEntry.js:6627:26)
    at invokeGuardedCallback (mf-va_remoteEntry.js:6661:41)
    at beginWork$1 (mf-va_remoteEntry.js:22138:17)
    at performUnitOfWork (mf-va_remoteEntry.js:21574:23)
    at workLoopSync (mf-va_remoteEntry.js:21513:15)
    at renderRootSync (mf-va_remoteEntry.js:21492:17)
    at recoverFromConcurrentError (mf-va_remoteEntry.js:21114:30)
    at performConcurrentWorkOnRoot (mf-va_remoteEntry.js:21062:32)
    at workLoop (mf-va_remoteEntry.js:3348:44)
    at flushWork (mf-va_remoteEntry.js:3327:24)
    at MessagePort.performWorkUntilDeadline (mf-va_remoteEntry.js:3535:31)

```

**Comment by fz6m** [comment]
↑ 拉取一下最新的主分支代码，该问题已修复。

**Comment by tc9011** [comment]
Sloved By `@umijs/max: 4.0.8`

**Comment by dryqiao** [comment]
```
// config.ts
qiankun: {
     slave: {},
},
安装plugin-qiankun，写入以上配置会报错：

Invalid config keys: qiankun
```
作为子应用只想安装个qiankun插件，一定要安装整个max吗？

**Comment by fz6m** [comment]
单独使用 qiankun ：

```bash
  pnpm add @umijs/plugins
```

```ts
// .umirc.ts

export default {
  plugins: ['@umijs/plugins/dist/qiankun'],
  qiankun: {}
}
```

**Comment by BaoXiaoShuai** [comment]
> 
单独使用qiankun后，一直报错。，
2loader.js:229 Uncaught (in promise) Error: [qiankun]: You need to export lifecycle functions in fourApp entry
    at getLifecyclesFromExports (loader.js:229:1)
    at _callee17$ (loader.js:393:1)
    at tryCatch (regeneratorRuntime.js:86:1)
    at Generator._invoke (regeneratorRuntime.js:66:1)
    at Generator.next (regeneratorRuntime.js:117:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)

但是在app.ts 中有写

export const qiankun = {
  // 应用加载之前
  async bootstrap(props: any) {
    console.log('app1 bootstrap', props)

  },
  // 应用 render 之前触发
  async mount(props: any) {
    console.log('app1 mount', props)
  },
  // 应用卸载之后触发
  async unmount(props: any) {
    console.log('app1 unmount', props)
  },
}

请问是怎么回事呢

**Comment by fz6m** [comment]
给一个复现看看
