### ISSUE TITLE
windows 下 .umirc.js registerBabel 失败

### ISSUE THREAD

**Issue by liuyangc3** [umijs/umi#825]
umi version: 2.0.0.beta7
OS: windows 10

.umirc.js
```
export default {
  plugins: [
    ['umi-plugin-react', {
      antd: true
    }],
  ],
};
```

when run umi dev
```
$ umi dev
C:\Users\LY\Projects\umi\.umirc.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (C:\Users\LY\Projects\umi\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (C:\Users\LY\Projects\umi\node_modules\pirates\lib\index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
C:\Users\LY\Projects\umi\node_modules\umi-build-dev\lib\UserConfig.js:175
      this.printError(msg);
           ^

TypeError: Cannot read property 'printError' of undefined
    at onError (C:\Users\LY\Projects\umi\node_modules\umi-build-dev\lib\UserConfig.js:175:12)
    at requireFile (C:\Users\LY\Projects\umi\node_modules\umi-build-dev\lib\UserConfig.js:93:12)
    at UserConfig.getConfig (C:\Users\LY\Projects\umi\node_modules\umi-build-dev\lib\UserConfig.js:179:63)
    at Service.init (C:\Users\LY\Projects\umi\node_modules\umi-build-dev\lib\Service.js:231:31)
    at Service.run (C:\Users\LY\Projects\umi\node_modules\umi-build-dev\lib\Service.js:245:10)
    at Object.<anonymous> (C:\Users\LY\Projects\umi\node_modules\umi\lib\scripts\realDev.js:26:47)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
error Command failed with exit code 1.
```

**Comment by Nokecy** [comment]
export default {} 换成 exports.default = {}
