### ISSUE TITLE
[Bug] umi3.5.26引入umi-plugin-keep-alive后报错

### ISSUE THREAD

**Issue by xiaoyierle** [umijs/umi#8262]
## What happens?

> umi3.5.26引入umi-plugin-keep-alive后报错
具体报错信息

```
 ERROR  Failed to compile with 1 errors                      下午4:55:55

 error  in ./src/.umi/umi.ts

Module build failed (from ./node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel-loader/index.js):
Error: [BABEL] /Users/wangzhengyi/workspace/work/umi-test/src/.umi/umi.ts: .0 is not a valid Plugin property
    at /Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:4191:42
    at Array.forEach (<anonymous>)
    at validatePluginObject (/Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:4180:20)
    at /Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:2687:55
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:4293:3)
    at Generator.next (<anonymous>)
    at step (/Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:121035:32)
    at evaluateAsync (/Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:121065:5)
    at Function.errback (/Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:120887:7)

 @ multi ./node_modules/_@umijs_preset-built-in@3.5.26@@umijs/preset-built-in/bundled/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./src/.umi/umi.ts
```
初步排查下来是 ./node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel-loader/index.js

```
function validatePluginObject(obj) {
  const rootPath = {
    type: "root",
    source: "plugin"
  };
// obj  [
  '/Users/wangzhengyi/workspace/work/umi-test/node_modules/_react-activation@0.11.2@react-activation/babel.js'
]
  Object.keys(obj).forEach(key => {
    const validator = VALIDATORS[key];
    if (validator) {
      const optLoc = {
        type: "option",
        name: key,
        parent: rootPath
      };
      validator(optLoc, obj[key]);
    } else {
      const invalidPluginPropertyError = new Error(`.${key} is not a valid Plugin property`);
      invalidPluginPropertyError.code = "BABEL_UNKNOWN_PLUGIN_PROPERTY";
      throw invalidPluginPropertyError;
    }
  });
  return obj;
}
```

这里的obj应该是对象，但拿到的是个数组，所以报错了

> 最小复现仓库地址 https://github.com/xiaoyierle/umi-keepalive.git

## 复现操作

- cnpm i
- npm start

运行就会报错

> 相关依赖

- **Umi Version**: v3.5.26
- **Node Version**:v14.17.3
- **Platform**: MAC OS 12.3.1

**Comment by NJimmi** [comment]
请问怎么解决的

**Comment by xinlanlan** [comment]
卧槽，我也刚遇到，之前还是好的，刚才发现突然不行了，果断去掉不用了。 🐶

**Comment by xiaohuoni** [comment]
发新包了，支持 umi@4 的版本

**Comment by cangsnage** [comment]
> 发新包了，支持 umi@4 的版本，中间版本有问题，安装最新版可解决

我i想问下umijs@3的版本现在不支持这个插件了么
