### ISSUE TITLE
jenkins打包报错，本地打包没问题

### ISSUE THREAD

**Issue by zxc6881553** [umijs/umi#8290]
Erroneous area:
1: 0.75 / $activity-indicator-spinner-count * ($i - 1)
^.........^
    at /wwwroot/umi.88bd2fdb.css:1651:3
    at Object.parseError (/wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1060336)
    at Object.lexer_parseError [as parseError] (/wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1067523)
    at Object.lexer_next [as next] (/wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1077684)
    at Object.lexer_fastLex [as fastLex] (/wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1078466)
    at fastLex (/wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1063127)
    at Parser.parse (/wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1063649)
    at /wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1053275
    at walk (/wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1142146)
    at ValueParser.walk (/wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1137452)
    at transformValue (/wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1053157)
    at _default (/wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1053730)
    at callback (/wwwroot/node_modules/@umijs/deps/compiled/optimize-css-assets-webpack-plugin/index.js:1:1046407)
    at callback (/wwwroot/node_modules/postcss/lib/container.es6:110:18)
    at Rule.each (/wwwroot/node_modules/postcss/lib/container.es6:76:16)
    at Rule.walk (/wwwroot/node_modules/postcss/lib/container.es6:107:17)
    at /wwwroot/node_modules/postcss/lib/container.es6:121:24 {
  hash: {
    errStr: 'Lexical error on line 1: Unrecognized text.\n' +
      '\n' +
      '  Erroneous area:\n' +
      '1: 0.75 / $activity-indicator-spinner-count * ($i - 1)\n' +
      '^.........^',
    recoverable: false,
    text: '',
    token: null,
    line: 0,
    loc: {
      first_line: 1,
      first_column: 7,
      last_line: 1,
      last_column: 7,
      range: [Array]
    },
    yy: {
      parseError: undefined,
      quoteName: undefined,
      lexer: undefined,
      parser: undefined,
      pre_parse: undefined,
      post_parse: undefined,
      pre_lex: undefined,
      post_lex: undefined
    },
    lexer: {
      yy: {},
      __decompressed: true,
      _input: '',
      yytext: '',
      yyleng: 0,
      match: '',
      matches: false,
      _more: false,
      _backtrack: false,
      yylloc: [Object],
      _signaled_error_token: false,
      done: false,
      yylineno: 0,
      matched: '',
      conditionStack: [Array],
      __currentRuleSet__: null,
      offset: 0
    },
    destroy: [Function: destructLexErrorInfo]
  },
  postcssNode: Declaration {
    raws: { before: '\n  ', between: ':' },
    type: 'decl',
    parent: Rule {
      raws: [Object],
      type: 'rule',
      nodes: [Array],
      parent: [Root],
      source: [Object],
      selector: '.za-activity-indicator--spinner div:nth-of-type(1)',
      lastEach: 9,
      indexes: [Object]
    },
    source: { start: [Object], input: [Input], end: [Object] },
    prop: 'opacity',
    value: '1-calc(0.75 / $activity-indicator-spinner-count * ($i - 1))'
  }
}
build failed
Error: build failed
    at /wwwroot/node_modules/@umijs/bundler-webpack/lib/index.js:172:29
    at finalCallback (/wwwroot/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108196:12)
    at /wwwroot/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108217:14
    at /wwwroot/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:67111:7
    at done (/wwwroot/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:67206:13)
    at /wwwroot/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108128:23
    at /wwwroot/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108209:15
    at finalCallback (/wwwroot/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:98589:39)
    at onCompiled (/wwwroot/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:98597:20)
    at /wwwroot/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:99008:23
    at /wwwroot/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:97408:14
    at eval (eval at create (/wwwroot/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:147581:10), <anonymous>:37:1)
error Command failed with exit code 1.

**Comment by zxc6881553** [comment]
node:12.14.1-alpine3.11

**Comment by zxc6881553** [comment]
版本：3.5.15

**Comment by sorrycc** [comment]
这是压缩报错了吧，没复现步骤请自行排查。
