### ISSUE TITLE
[Bug] 不兼容ie

### ISSUE THREAD

**Issue by cjdxhjj** [umijs/umi#8494]
## What happens?

使用向导创建一个最简单的应用。无法在ie上运行
![image](https://user-images.githubusercontent.com/5616997/178296515-b702eca6-2f45-4309-a278-d0a568418e35.png)
![image](https://user-images.githubusercontent.com/5616997/178296725-7ae6159f-6a3b-4d3a-9057-a2a6b0dcda66.png)
edge浏览器正常
![image](https://user-images.githubusercontent.com/5616997/178296633-4e4667a9-5462-42cd-95fb-94954827289c.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.6
- **Node Version**:
- **Platform**: win 10 64

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/178297239-48a829d7-1049-4dc4-8458-46a40b4fd3ba.png)

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/178297324-a4ac884b-21b9-4de9-b40c-5bf05e7add50.png)

**Comment by jounzhang** [comment]
PS D:\workspace\project\axinfu\stream_web> pnpm run build

> ant-design-pro@6.0.0-beta.1 build D:\workspace\project\axinfu\stream_web
> max build

Hello PRO
info  - Umi v4.0.12
error - jsMinifier: esbuild is not supported when there is ie in the targets, you can use jsMinifier: 'terser'
fatal - Error: IE is not supported
    at getEsBuildTarget (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+bundler-webpack@4.0.12_xnp4kzegbjokq62cajex2ovgkm\node_modules\@umijs\bundler-webpack\dist\utils\getEsBuildTarget.js:31:11)
    at addCompressPlugin (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+bundler-webpack@4.0.12_xnp4kzegbjokq62cajex2ovgkm\node_modules\@umijs\bundler-webpack\dist\config\compressPlugin.js:55:70)
    at getConfig (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+bundler-webpack@4.0.12_xnp4kzegbjokq62cajex2ovgkm\node_modules\@umijs\bundler-webpack\dist\config\config.js:140:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Proxy.build (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+bundler-webpack@4.0.12_xnp4kzegbjokq62cajex2ovgkm\node_modules\@umijs\bundler-webpack\dist\build.js:52:25)
    at async Command.fn (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+preset-umi@4.0.12_kbunkbeezhexeikqzjunp6h7bq\node_modules\@umijs\preset-umi\dist\commands\build.js:144:17)
    at async Service.run (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+core@4.0.12\node_modules\@umijs\core\dist\service\service.js:270:15)
    at async Service.run2 (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\umi@4.0.12_llqjcapggugs3ytnsdohj4a7a4\node_modules\umi\dist\service\service.js:74:12)
    at async run (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\umi@4.0.12_llqjcapggugs3ytnsdohj4a7a4\node_modules\umi\dist\cli\cli.js:55:7)
fatal - A complete log of this run can be found in:
fatal - D:\workspace\project\axinfu\stream_web\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
 ELIFECYCLE  Command failed with exit code 1.

**Comment by drizzlesconsin** [comment]
IE 兼容性问题 https://github.com/umijs/umi/issues/8930#issuecomment-1210281662

**Comment by xiaohuoni** [comment]
低浏览器相关的兼容，可以使用配置 [legacy](https://umijs.org/docs/api/config#legacy) 
有其他异常欢迎新开 issues 讨论
