### ISSUE TITLE
umijs 4.0.7版本 umi build阶段报错 Invalid config keys: locale

### ISSUE THREAD

**Issue by shpilu** [umijs/umi#8554]
config.ts配置:
export default {
  plugins: [],
  locale: {
    antd: false, // 如果项目依赖中包含 `antd`，则默认为 true
    baseNavigator: true,
    baseSeparator: '-',
    default: 'zh-CN',
    title: false,
    useLocalStorage: true,
  },
  npmClient: 'npm',
  routes: pageRoutes,
};
报错：
> build
> umi build

fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: locale
    at Function.validateConfig (/usr/local/lib/node_modules/umi/node_modules/@umijs/core/dist/config/config.js:159:30)
    at Config.getConfig (/usr/local/lib/node_modules/umi/node_modules/@umijs/core/dist/config/config.js:38:16)
    at Service.resolveConfig (/usr/local/lib/node_modules/umi/node_modules/@umijs/core/dist/service/service.js:301:38)
    at Service.run (/usr/local/lib/node_modules/umi/node_modules/@umijs/core/dist/service/service.js:233:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Service.run2 (/usr/local/lib/node_modules/umi/dist/service/service.js:36:16)
    at async Object.run (/usr/local/lib/node_modules/umi/dist/cli/cli.js:37:13) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by shpilu** [comment]
我是参考官网 https://umijs.org/docs/max/i18n 开发的

**Comment by xierenyuan** [comment]
如果使用的是 @umijs/max 的话 命令需要修改成  `max build`

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
