### ISSUE TITLE
request 数组参数

### ISSUE THREAD

**Issue by wangchangkang** [umijs/umi#8698]
数组日期请求错误，希望将数组符号去除
HTTP Status 400 – Bad Request
http://127.0.0.1:8020/store/customers?current=1&pageSize=20&insertTime[]=2022-07-01&insertTime[]=2022-07-31

```tsx
 <ProTable
                actionRef={actionRef}
                rowKey="id"
                headerTitle="查询表格"
                columns={columns}
                request={(params => customers(params))}
            />

```

```js


export async function customers(params: any) {
    return request<any>('/store/customers', {params})
        .then((res: any) => {
            return {data: res.content, total: res.totalElements}
        });
}
```

```java

java.lang.IllegalArgumentException: Invalid character found in the request target [/store/customers?current=1&pageSize=20&insertTime[]=2022-07-25&insertTime[]=2022-07-25 ]. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:494) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) [tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.63.jar:9.0.63]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_301]

```

**Comment by wangchangkang** [comment]
```js
export async function customers(params: any) {
    return request<any>(
        '/store/customers',
        {
            params,
            paramsSerializer: (params) => QueryString.stringify(params,{arrayFormat:'repeat'})
        })
        .then((res: any) => {
            return {data: res.content, total: res.totalElements}
        });
}

```

**Comment by wangxingkang** [comment]
这个通过   plugin-request 可以自己设置吧
