### ISSUE TITLE
Umi4 SSR doesn't work?

### ISSUE THREAD

**Issue by skitsanos** [umijs/umi#8753]
Hi,

Couldn't make SSR working while migrating from Umi3 to Umi4 (`4.0.8`), if I added the `ssr` key into config (`.umirc.js`) this way:

```js
export default {
    svgr: {},

    ssr: {
        serverBuildPath: './dist/umi.server.js'
    }
};
```

No change if I put it in a basic way:

```js
export default {
    svgr: {},

    ssr: {}
};
```

`umi dev` and `umi setup` throw an error

```
> umi-ssr@2.0.0 run
> umi dev

fatal - Error: Parse error @:26:41
    at parse (/Projects/umi/umi-ssr/node_modules/@umijs/bundler-utils/compiled/es-module-lexer/index.js:1:511)
    at parseModuleSync (/Projects/umi/umi-ssr/node_modules/@umijs/bundler-utils/dist/index.js:46:43)
    at parseModule (/Projects/umi/umi-ssr/node_modules/@umijs/bundler-utils/dist/index.js:36:10)
    at async getModuleExports (/Projects/umi/umi-ssr/node_modules/@umijs/preset-umi/dist/features/tmpFiles/getModuleExports.js:29:24)
    at async getRoutes (/Projects/umi/umi-ssr/node_modules/@umijs/preset-umi/dist/features/tmpFiles/routes.js:107:78)
    at async Hook.fn (/Projects/umi/umi-ssr/node_modules/@umijs/preset-umi/dist/features/appData/appData.js:37:19)
    at async /Projects/umi/umi-ssr/node_modules/@umijs/core/dist/service/service.js:114:25 {
  idx: 569
}
```

my `package.json` is like this:

```json
{
  "name": "umi-ssr",
  "version": "2.0.0",
  "main": "index.js",
  "license": "MIT",
  "private": true,
  "scripts": {
    "postinstall": "umi setup",
    "run": "umi dev",
    "build": "umi build --clean"
  },
  "dependencies": {
    "ahooks": "^3.6.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "umi": "^4.0.8",
    "unirest": "^0.6.0"
  },
  "devDependencies": {
    "@umijs/plugins": "^4.0.8",
    "express": "^4.18.1"
  }
}
```

Is `ssr` still a part of UmiJs, or it was removed? Because I don't see it listed on https://umijs.org/docs/api/config either...

**Comment by shanhuaji** [comment]
@sorrycc

**Comment by sorrycc** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). @skitsanos

**Comment by sorrycc** [comment]
请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 并单独提 issue， @shanhuaji

**Comment by skitsanos** [comment]
@sorrycc, here is the demo branch with an issue https://github.com/skitsanos/umi-ssr/tree/umi4
