### ISSUE TITLE
[Bug] Umi4使用脚本生成测试文件后，运行测试报错`Invalid config keys: antd` 

### ISSUE THREAD

**Issue by hackers267** [umijs/umi#8758]
## Mini Showcase Repository(REQUIRED)

https://github.com/hackers267/test_error.git

## How To Reproduce
下载仓库，然后执行下面的命令即可复现。
```
pnpm install
pnpm test
````

报错：
```
Error: Jest: Failed to parse the TypeScript config file jest.config.ts
  AssertionError [ERR_ASSERTION]: Invalid config keys: antd, access, model, initialState, request, layout
    at readConfigFileAndSetRootDir (node_modules/jest/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:136:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async readConfig (node_modules/jest/node_modules/jest-config/build/index.js:233:18)
    at async readConfigs (node_modules/jest/node_modules/jest-config/build/index.js:420:26)
    at async runCLI (node_modules/@jest/core/build/cli/index.js:132:59)
    at async Object.run (node_modules/jest/node_modules/jest-cli/build/cli/index.js:155:37)
 ELIFECYCLE  Test failed. See above for more details.
```

## Context

- **Umi Version**: umi@4.0.9
- **Node Version**: v14.19.3
- **Platform**: Linux

一个临时的解决方案是可以在使用测试的时候自定义环境变量：`UMI_PRESETS=<rootDir>/node_modules/@umijs/max/dist/preset.js`;

是不是可以在UMI为添加`test`命令，因为在使用UMI命令的时候，可以自动设置`UMI_PRESETS`环境变量。

**Comment by Echo-minn** [comment]
我执行`npm start`也报同样的错

**Comment by ihavecoke** [comment]
使用 @umijs/plugins 在 config.ts 中配置 {antd:{}}

**Comment by fz6m** [comment]
将 `jest.config.ts` 中的导入换为 max ：

```diff
// jest.config.ts

-import { ... } from 'umi/test'
+import { ... } from '@umijs/max/test'
```

**Comment by hackers267** [comment]
> 将 `jest.config.ts` 中的导入换为 max ：
> 
> ```diff
> // jest.config.ts
> 
> -import { ... } from 'umi/test'
> +import { ... } from '@umijs/max/test'
> ```

这个可以解决问题。希望可以在自动生成`jest.config.ts`的时候，自动使用这个方案。

**Comment by fz6m** [comment]
你使用的是什么生成的？max 的生成器是：

```bash
  pnpm max g jest
```

**Comment by hackers267** [comment]
> 

使用的是umi生成器：
```
pnpm umi g jest
```
居然也可以使用，但生成的是错误的代码片段。

**Comment by zhangxinyong12** [comment]
解决了吗？我也遇到了同样的问题。我没看懂，应该怎么解决。help
