### ISSUE TITLE
Program Files (x86) 目录下运行出错

### ISSUE THREAD

**Issue by linqiang007** [umijs/umi#890]
OS: windows server 2012R2 
1. 有考虑是jenkins的问题；但直接在项目目录下，重新npm i 运行,也是不行的。
2. 然后项目拷到非 Program Files (x86) 目录下，运行是正常的。
3. 运行的是本地目录的umi

```
>  cross-env HOST=0.0.0.0 umi build 

C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\.umirc.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Module._compile (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:654:10)
    at Object.newLoader [as .js] (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at requireFile (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi-build-dev\lib\UserConfig.js:93:20)
    at Function.getConfig (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi-build-dev\lib\UserConfig.js:110:48)
    at Service.initPlugins (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi-build-dev\lib\Service.js:273:40)
    at Service.build (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi-build-dev\lib\Service.js:380:10)
    at Object.build [as default] (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi-build-dev\lib\build.js:14:18)

C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi-build-dev\lib\UserConfig.js:171
      throw new Error(msg);

Error: 閰嶇疆鏂囦欢 "C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\.umirc.js" 瑙ｆ瀽鍑洪敊锛岃妫�鏌ヨ娉曘��

SyntaxError: Unexpected token export
    at onError (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi-build-dev\lib\UserConfig.js:171:13)
    at requireFile (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi-build-dev\lib\UserConfig.js:97:12)
    at UserConfig.getConfig (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi-build-dev\lib\UserConfig.js:177:63)
    at Service.build (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi-build-dev\lib\Service.js:382:30)
    at Object.build [as default] (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi-build-dev\lib\build.js:14:18)
    at _default (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi\lib\build.js:19:52)
    at Object.<anonymous> (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modules\umi\lib\scripts\build.js:12:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

```
> umi dev
C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\.umirc.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Module._compile (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admi
n-test\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:584:10)
    at Object.newLoader [as .js] (C:\Program Files (x86)\Jenkins\workspace\jhw-m
obile-admin-test\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at requireFile (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-te
st\node_modules\umi-build-dev\lib\UserConfig.js:93:20)
    at Function.getConfig (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-a
dmin-test\node_modules\umi-build-dev\lib\UserConfig.js:110:48)
    at Service.initPlugins (C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-
admin-test\node_modules\umi-build-dev\lib\Service.js:273:40)
    at C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\node_modul
es\umi-build-dev\lib\Service.js:130:13
    at Generator.next (<anonymous>)
配置文件 "C:\Program Files (x86)\Jenkins\workspace\jhw-mobile-admin-test\.umirc.
js" 解析出错，请检查语法。

SyntaxError: Unexpected token export
```

**Comment by okoala** [comment]
提供可复现的仓库吧

**Comment by linqiang007** [comment]
@okoala  刚试过，这个项目也是一样的错 https://github.com/umijs/umi-dva-user-dashboard.git

**Comment by sorrycc** [comment]
是 babel 的问题，我猜是因为目录带 `(x86)`，然后 babel 在把路径转为正则时没有处理好。

两个方案：

1. 不要放在这个目录下
2. 在 `.umirc.js` 里把 `export default {}` 改成 `module.exports = {}`

**Comment by okoala** [comment]
按理说数据之类不应该放在 `Program Files` 中，哪天把软件一删，数据不都没了~
