### ISSUE TITLE
umi start

### ISSUE THREAD

**Issue by shanzufeng** [umijs/umi#8904]
在控制台输入umi start的时候报错了
fatal - AssertionError [ERR_ASSERTION]: Invalid command start, it's not registered.
    at Service.run (/Users/mac/.config/yarn/global/node_modules/@umijs/core/dist/service/service.js:225:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Service.run2 (/Users/mac/.config/yarn/global/node_modules/umi/dist/service/service.js:74:12)
    at async Object.run (/Users/mac/.config/yarn/global/node_modules/umi/dist/cli/cli.js:55:7) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
fatal - A complete log of this run can be found in:
fatal - /usr/local/lib/node_modules/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

**Comment by fz6m** [comment]
由于缺乏足够的信息，请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 的 demo 帮助排查问题。

**Comment by sorrycc** [comment]
没有 start 这个命令，只有 umi dev。
