### ISSUE TITLE
1.x 升级 2.0-beta 配置 antd 出错

### ISSUE THREAD

**Issue by arvinxx** [umijs/umi#892]
根据升级指南,将`.umi.js`配置如下
```js
export default {
  alias: {
  //...
}
  plugins: [
    [
      'umi-plugin-react',
      {
        antd: true,
        dva: true,
      },
    ],
  ],
};

```

后报错如下
```
icedembp:digital-currency-calc ice$ npm start

> dc-calculator@1.0.0 start /Users/ice/CodeProjects/digital-currency-calc
> cross-env BROWSER=none umi dev

Plugin apply failed: Cannot read property 'resolve' of undefined
/Users/ice/CodeProjects/digital-currency-calc/node_modules/umi-build-dev/lib/Service.js:186
        throw e;
        ^

TypeError: Cannot read property 'resolve' of undefined
    at api.register (/Users/ice/CodeProjects/digital-currency-calc/node_modules/umi-plugin-react/lib/plugins/antd.js:33:19)
    at reduce (/Users/ice/CodeProjects/digital-currency-calc/node_modules/umi-build-dev/lib/Service.js:180:16)
    at Array.reduce (<anonymous>)
    at Service.applyPlugins (/Users/ice/CodeProjects/digital-currency-calc/node_modules/umi-build-dev/lib/Service.js:176:42)
    at Object.afWebpackOpts.chainConfig.webpackConfig [as chainConfig] (/Users/ice/CodeProjects/digital-currency-calc/node_modules/umi-build-dev/lib/getWebpackConfig.js:24:13)
    at _default (/Users/ice/CodeProjects/digital-currency-calc/node_modules/af-webpack/lib/getConfig/index.js:222:10)
    at Object._default [as default] (/Users/ice/CodeProjects/digital-currency-calc/node_modules/umi-build-dev/lib/getWebpackConfig.js:35:33)
    at Service.run (/Users/ice/CodeProjects/digital-currency-calc/node_modules/umi-build-dev/lib/Service.js:297:65)
    at Object.<anonymous> (/Users/ice/CodeProjects/digital-currency-calc/node_modules/umi/lib/scripts/realDev.js:32:47)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
```

package.json 依赖如下
```js
"dependencies": {
    "dva": "^2.3.0",
    "react-intl": "^2.4.0"
  },
  "devDependencies": {
    "@commitlint/cli": "^6.2.0",
    "@types/enzyme": "^3.1.10",
    "@types/jest": "^22.2.3",
    "@types/node": "^8.0.56",
    "@types/react": "^16.0.27",
    "@types/react-intl": "^2.3.8",
    "@types/react-redux": "^6.0.0",
    "commitlint-config-gitmoji": "*",
    "cross-env": "*",
    "husky": "^0.14.3",
    "lint-staged": "*",
    "prettier": "*",
    "sinon": "^6.1.5",
    "stylelint": "^9.4.0",
    "ts-jest-babel-7": "^22.0.4",
    "umi": "^2.0.0-beta.17",
    "umi-plugin-react": "^1.0.0-beta.1"
  },

```

如注释掉 `antd:true`则能正常编译，但是 CSS 样式全部丢失

**Comment by sorrycc** [comment]
`umi -v --verbose` 看下？

**Comment by huangzj0520** [comment]
删除node_modules重新安装就可以了

**Comment by okoala** [comment]
`umi -v --verbose` 一下，看看各个模块的版本号和路径

**Comment by kayikay** [comment]
$ umi -v --verbose
umi@2.0.0-beta.17
win32 x64
node@v8.9.4
umi-build-dev@1.0.0-beta.17
af-webpack@1.0.0-beta.17
babel-preset-umi@1.0.0-beta.17
umi-test@1.0.0-beta.17
react@16.4.2 (C:\Users\null\AppData\Local\Yarn\Data\global\node_modules\react)
react-dom@16.4.2 (C:\Users\null\AppData\Local\Yarn\Data\global\node_modules\react-dom)
react-router@4.3.1 (C:\Users\null\AppData\Local\Yarn\Data\global\node_modules\react-router)
react-router-dom@4.3.1 (C:\Users\null\AppData\Local\Yarn\Data\global\node_modules\react-router-dom)
dva@2.4.0 (F:\web-ui\web-ui\node_modules\dva)
dva-loading@2.0.5
dva-immer@0.2.3
path-to-regexp@1.7.0

**Comment by arvinxx** [comment]
@sorrycc @okoala 
```bash
$ umi -v --verbose

umi@2.0.0-beta.17
darwin x64
node@v8.11.3
umi-build-dev@1.0.0-beta.17
af-webpack@1.0.0-beta.17
babel-preset-umi@1.0.0-beta.17
umi-test@1.0.0-beta.17
react@16.4.2 (/Users/ice/CodeProjects/digital-currency-calc/node_modules/react)
react-dom@16.4.2 (/Users/ice/CodeProjects/digital-currency-calc/node_modules/react-dom)
react-router@4.3.1 (/Users/ice/CodeProjects/digital-currency-calc/node_modules/react-router)
react-router-dom@4.3.1 (/Users/ice/CodeProjects/digital-currency-calc/node_modules/react-router-dom)
dva@2.3.2 (/Users/ice/CodeProjects/digital-currency-calc/node_modules/dva)
dva-loading@2.0.5
dva-immer@0.2.3
path-to-regexp@1.7.0

```

**Comment by okoala** [comment]
发个能复现的仓库

**Comment by arvinxx** [comment]
刚才删掉 node_modules 后复制一份再安装，就又可以了…可能是之前没有安装正确吧。感谢
