### ISSUE TITLE
Error: Invalid plugin umi-presets-pro, can not be resolved.[Bug] say something

### ISSUE THREAD

**Issue by Darcula666** [umijs/umi#8928]
fatal - Error: Invalid plugin umi-presets-pro, can not be resolved.
    at /Users/tiankun/reactProjects/antd-pro/.yarn/cache/@umijs-core-npm-4.0.11-1b493b995b-7c96ea79d5.zip/node_modules/@umijs/core/dist/service/plugin.js:127:17
    at Array.map (<anonymous>)
    at get (/Users/tiankun/reactProjects/antd-pro/.yarn/cache/@umijs-core-npm-4.0.11-1b493b995b-7c96ea79d5.zip/node_modules/@umijs/core/dist/service/plugin.js:118:9)
    at Function.getPluginsAndPresets (/Users/tiankun/reactProjects/antd-pro/.yarn/cache/@umijs-core-npm-4.0.11-1b493b995b-7c96ea79d5.zip/node_modules/@umijs/core/dist/service/plugin.js:137:16)
    at Service.run (/Users/tiankun/reactProjects/antd-pro/.yarn/cache/@umijs-core-npm-4.0.11-1b493b995b-7c96ea79d5.zip/node_modules/@umijs/core/dist/service/service.js:202:55)
    at Service.run2 (/Users/tiankun/reactProjects/antd-pro/.yarn/cache/umi-npm-4.0.11-7c6e69c7f3-c4588fa0a3.zip/node_modules/umi/dist/service/service.js:74:23)
    at /Users/tiankun/reactProjects/antd-pro/.yarn/cache/umi-npm-4.0.11-7c6e69c7f3-c4588fa0a3.zip/node_modules/umi/dist/cli/forkedDev.js:24:19
    at Object.<anonymous> (/Users/tiankun/reactProjects/antd-pro/.yarn/cache/umi-npm-4.0.11-7c6e69c7f3-c4588fa0a3.zip/node_modules/umi/dist/cli/forkedDev.js:37:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
fatal - A complete log of this run can be found in:
fatal - /Users/tiankun/reactProjects/antd-pro/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

**Comment by xierenyuan** [comment]
需要提供[最小重现](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by Longder** [comment]
应该是使用yarn 3构建时候会出现的错误，切换撑yarn 1.22.19就正常
