### ISSUE TITLE
基于非max创建的umi项目如何使用umi插件？

### ISSUE THREAD

**Issue by zxq08** [umijs/umi#9045]
根据文档通过非max形式创建的项目，无法引入dva等插件？

.umirc.ts:
export default {
  npmClient: 'pnpm',
  dva: {}
};

报错信息：
fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: dva

"umi": "^4.0.12"

**Comment by fz6m** [comment]
```bash
  pnpm add @umijs/plugins
```

```ts
// .umirc.ts

export default {
  plugins: ['@umijs/plugins/dist/dva'],
  dva: {}
}
```

**Comment by shl07** [comment]
D:\work\reactsjsdemo>node -v
v16.17.0

D:\work\reactsjsdemo>umi -v
info  - [你知道吗？] 如果想点击组件跳转至编辑器源码位置，可尝试新出的 clickToComponent 配置项，详见 https://umijs.org/docs/api/config#clicktocomponent
umi@4.0.21
config.js  
export default {
    dva: {}
}

package.json 
{
  "name": "reactsjsdemo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@umijs/preset-react": "^2.1.6",
    "umi": "^4.0.21"
  }
}

执行：umi dev 出现异常
fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: dva
    at Function.validateConfig (C:\Users\css\AppData\Local\Yarn\Data\global\node_modules\@umijs\core\dist\config\config.js:179:31)
    at Config.getConfig (C:\Users\css\AppData\Local\Yarn\Data\global\node_modules\@umijs\core\dist\config\config.js:60:12)
    at Service.resolveConfig (C:\Users\css\AppData\Local\Yarn\Data\global\node_modules\@umijs\core\dist\service\service.js:280:97)
    at Service.run (C:\Users\css\AppData\Local\Yarn\Data\global\node_modules\@umijs\core\dist\service\service.js:237:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Service.run2 (C:\Users\css\AppData\Local\Yarn\Data\global\node_modules\umi\dist\service\service.js:58:12)
    at async C:\Users\css\AppData\Local\Yarn\Data\global\node_modules\umi\dist\cli\forkedDev.js:24:5 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,

**Comment by sanshuiwang** [comment]
> 根据文档通过非max形式创建的项目，无法引入dva等插件？
> 
> .umirc.ts: export default { npmClient: 'pnpm', dva: {} };
> 
> 报错信息： fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: dva
> 
> "umi": "^4.0.12"

你后来怎么处理的？
