### ISSUE TITLE
[Bug] 4.0.14 npm run start 报错 AssertionError [ERR_ASSERTION]: dev, prod, test config files will be auto loaded by env, Do not configure process.env.umi_ENV with these values

### ISSUE THREAD

**Issue by dxhuii** [umijs/umi#9104]
## 报错

yarn start
yarn run v1.22.18
$ cross-env UMI_ENV=dev max dev
fatal - AssertionError [ERR_ASSERTION]: dev, prod, test config files will be auto loaded by env, Do not configure process.env.umi_ENV with these values
    at Service.run (~/node_modules/umi/node_modules/@umijs/core/dist/service/service.js:189:31)
    at Service.run2 (~/node_modules/umi/dist/service/service.js:74:23)
    at ~/node_modules/umi/dist/cli/forkedDev.js:24:19
    at Object.<anonymous> (~/node_modules/umi/dist/cli/forkedDev.js:37:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
fatal - A complete log of this run can be found in:
fatal -~/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
✨  Done in 3.02s.

## Mini Showcase Repository(REQUIRED)
 [v6.0.0-beta.1](https://github.com/ant-design/ant-design-pro/releases/tag/v6.0.0-beta.1) 官方模板，把umijs/max 升级到4.0.14

## Context

- **Umi Version**: 4.0.14
- **Node Version**: 16.14.2
- **Platform**: chrome 104 mac os 12.5

**Comment by drizzlesconsin** [comment]
移除 `UMI_ENV=dev` 就能解决问题
<img width="571" alt="image" src="https://user-images.githubusercontent.com/69514654/186723518-de8f52bc-d7f0-4c0a-8c34-b8cc4ccae2dd.png">

**Comment by sorrycc** [comment]
Resolved via #9105
