### ISSUE TITLE
Error: Invalid plugin @umijs/plugins/dist/initial-state, can not be resolved.

### ISSUE THREAD

**Issue by ihamlet** [umijs/umi#9125]
Error: Invalid plugin @umijs/plugins/dist/initial-state, can not be resolved.
```
fatal - Error: Invalid plugin @umijs/plugins/dist/initial-state, can not be resolved.
    at C:\Users\--\AppData\Local\pnpm\global\5\.pnpm\@umijs+core@4.0.15\node_modules\@umijs\core\dist\service\plugin.js:127:17
    at Array.map (<anonymous>)
    at get (C:\Users\--\AppData\Local\pnpm\global\5\.pnpm\@umijs+core@4.0.15\node_modules\@umijs\core\dist\service\plugin.js:118:9)
    at Function.getPluginsAndPresets (C:\Users\--\AppData\Local\pnpm\global\5\.pnpm\@umijs+core@4.0.15\node_modules\@umijs\core\dist\service\plugin.js:138:16)
    at Service.run (C:\Users\--\AppData\Local\pnpm\global\5\.pnpm\@umijs+core@4.0.15\node_modules\@umijs\core\dist\service\service.js:203:55)
    at Service.run2 (C:\Users\--\AppData\Local\pnpm\global\5\.pnpm\umi@4.0.15\node_modules\umi\dist\service\service.js:74:23)
    at C:\Users\--\AppData\Local\pnpm\global\5\.pnpm\umi@4.0.15\node_modules\umi\dist\cli\forkedDev.js:24:19
    at Object.<anonymous> (C:\Users\--\AppData\Local\pnpm\global\5\.pnpm\umi@4.0.15\node_modules\umi\dist\cli\forkedDev.js:37:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
fatal - A complete log of this run can be found in:
fatal - E:\BLOG\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues`
```

**Comment by fz6m** [comment]
```bash
  pnpm add @umijs/plugins
```

**Comment by ihamlet** [comment]
```  
plugins: [
    '@umijs/plugins/dist/initial-state',
    '@umijs/plugins/dist/model',
  ]
```

 "@umijs/plugins": "^4.0.7"

**Comment by ihamlet** [comment]
The Issues still exists

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
