### ISSUE TITLE
[Bug] MFSU chainWebpack使用unocss webpack插件报错

### ISSUE THREAD

**Issue by wkeylin** [umijs/umi#9311]
## What happens?
unocss cli最新版本目前有点问题，想要切换到[webpack plugin](https://github.com/unocss/unocss/tree/main/packages/webpack)的方式，但是在开启mfsu会报错，关掉mfsu没问题
```
error - AssertionError [ERR_ASSERTION]: filePath not found of uno.css
    at Dep.buildExposeContent (/Users/kirin/Documents/scm/test/node_modules/@umijs/mfsu/dist/dep/dep.js:70:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DepBuilder.writeMFFiles (/Users/kirin/Documents/scm/test/node_modules/@umijs/mfsu/dist/depBuilder/depBuilder.js:154:23)
    at async DepBuilder.build (/Users/kirin/Documents/scm/test/node_modules/@umijs/mfsu/dist/depBuilder/depBuilder.js:132:7)
    at async MFSU.buildDeps (/Users/kirin/Documents/scm/test/node_modules/@umijs/mfsu/dist/mfsu/mfsu.js:200:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}
```
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

[demo](https://github.com/wkeylin/umi-unocss-webpack-plugin)

## Context

- **Umi Version**: 4.0.20
- **Node Version**: v16.17.0
- **Platform**: mac

**Comment by wkeylin** [comment]
解决了：mfsu: { exclude: ['uno.csss']}
