### ISSUE TITLE
[Bug] umi4 SSR 不工作，不兼容 svg

### ISSUE THREAD

**Issue by SturdyCat** [umijs/umi#9392]
## What happens?
### config.ts 配置文件
```
ssr: {}
```
### 不兼容 svg
```
sandbox@sse-sandbox-uh6ny5:/sandbox$ yarn start
yarn run v1.22.19
warning package.json: No license field
$ umi dev
warn  - [plugin: ./node_modules/@umijs/plugins/dist/locale] antd is not installed. <SelecLang /> unavailable
info  - [你知道吗？] dev 模式下访问 /__umi 路由，可以发现很多有用的内部信息。
warn  - SSR feature is in beta, may be unstable
info  - Umi v4.0.21
wait  - [SSR] Compiling...
fatal - Error: Build failed with 1 error:
src/pages/index.tsx:1:46: ERROR: Do not know how to load path: svgAssets:/sandbox/src/pages/@/assets/images/404.svg
    at failureErrorWithLog (/sandbox/node_modules/esbuild/lib/main.js:1605:15)
    at /sandbox/node_modules/esbuild/lib/main.js:1251:28
    at runOnEndCallbacks (/sandbox/node_modules/esbuild/lib/main.js:1034:63)
    at buildResponseToResult (/sandbox/node_modules/esbuild/lib/main.js:1249:7)
    at /sandbox/node_modules/esbuild/lib/main.js:1358:14
    at /sandbox/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/sandbox/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/sandbox/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Do not know how to load path: svgAssets:/sandbox/src/pages/@/assets/images/404.svg'
    }
  ],
  warnings: []
}
```
## Mini Showcase Repository(REQUIRED)
[minimal reproduction](https://github.com/SturdyCat/umi4-bug/blob/main/README.md)
[![minimal reproduction](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/umi4-bug-uh6ny5?file=/src/pages/index.tsx)

## How To Reproduce
 点击 codesandbox 右下 terminal 区域回车
 输入  yarn start

## Context

- **Umi Version**: 4.0.21
- **Node Version**: v14.19.2
- **Platform**: mac m1 12.5.1

**Comment by ShinChven** [comment]
我猜 UmiJS4 的 SSR 还没装备好。我用的时候也有不少毛病。退回了3。

**Comment by hinego** [comment]
> 我猜 UmiJS4 的 SSR 还没装备好。我用的时候也有不少毛病。退回了3。

UMI4 根本就不完善（LowImport 也不能用。。）

主要是官网都写支持了

还写了怎么用

结果根本没做好  。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by hocgin** [comment]
我也退回了 umi3 了，ssr umi4 的 model 这块也有问题。。

**Comment by fz6m** [comment]
最新版本 `4.0.46` 支持 svg 了。

**Comment by laeni** [comment]
目前版本（`4.0.52`）还是无法在开启 SSR 情况下使用 SVG，即使在本 Issues 的最小复现项目上将版本升级到`4.0.46`也不行。
复现项目: <https://github.com/laeni/umi4-bug>

会有如下提示
```
laeni@LaenideiMac umi4-bug % yarn dev
yarn run v1.22.19
$ umi dev
warn  - [plugin: ./node_modules/@umijs/plugins/dist/locale] antd is not installed. <SelecLang /> unavailable
info  - [你知道吗？] 如果你需要增加 Git 提交消息校验和自动代码格式化, umi g precommit 就可以一键完成配置，详见 https://umijs.org/docs/guides/generator#precommit-配置生成器
warn  - SSR feature is in beta, may be unstable
info  - Umi v4.0.46
wait  - [SSR] Compiling...
fatal - Error: Build failed with 1 error:
src/pages/index.tsx:1:46: ERROR: Do not know how to load path: svgAssets:/Users/laeni/Documents/Workspace/demo/umi4-bug/src/pages/@/assets/react.svg
    at failureErrorWithLog (/Users/laeni/Documents/Workspace/demo/umi4-bug/node_modules/esbuild/lib/main.js:1604:15)
    at /Users/laeni/Documents/Workspace/demo/umi4-bug/node_modules/esbuild/lib/main.js:1056:28
    at runOnEndCallbacks (/Users/laeni/Documents/Workspace/demo/umi4-bug/node_modules/esbuild/lib/main.js:1476:61)
    at buildResponseToResult (/Users/laeni/Documents/Workspace/demo/umi4-bug/node_modules/esbuild/lib/main.js:1054:7)
    at /Users/laeni/Documents/Workspace/demo/umi4-bug/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/Users/laeni/Documents/Workspace/demo/umi4-bug/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/Users/laeni/Documents/Workspace/demo/umi4-bug/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/Users/laeni/Documents/Workspace/demo/umi4-bug/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Do not know how to load path: svgAssets:/Users/laeni/Documents/Workspace/demo/umi4-bug/src/pages/@/assets/react.svg'
    }
  ],
  warnings: [
    {
      detail: undefined,
      id: 'empty-import-meta',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: '"import.meta" is not available with the "cjs" output format and will be empty'
    },
    {
      detail: undefined,
      id: 'empty-import-meta',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: '"import.meta" is not available with the "cjs" output format and will be empty'
    },
    {
      detail: undefined,
      id: 'empty-import-meta',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: '"import.meta" is not available with the "cjs" output format and will be empty'
    },
    {
      detail: undefined,
      id: 'empty-import-meta',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: '"import.meta" is not available with the "cjs" output format and will be empty'
    }
  ]
}
```
