### ISSUE TITLE
umi-test 报  TypeError: Cannot read property 'createElement' of undefined 错误

### ISSUE THREAD

**Issue by arvinxx** [umijs/umi#964]
测试文件 `UnitSelector.test.tsx` 如下
``` jsx
import React from 'react';
import { shallow } from 'enzyme';
import App from '../App';

const wrapper = shallow(<App  />);


it('render', () => {
  expect(wrapper.find('.container').length).toEqual(1);
});
```
报错如下
```
components/__test__/UnitSelector.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'createElement' of undefined

      3 | import App from '../UnitSelector';
      4 | 
    > 5 | const wrapper = shallow(<App changeUnit={() => {}} />);
        |                         ^
      6 | 
      7 | // const { wrapper, props } = setup();
      8 | 

      at Object.<anonymous> (components/__test__/UnitSelector.test.tsx:5:25)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        5.179s
Ran all test suites.
(node:3706) UnhandledPromiseRejectionWarning: Error: Jest failed
    at _jest.default.runCLI.then.result (/Users/ice/CodeProjects/digital-currency-calc/node_modules/umi-test/lib/index.js:65:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:3706) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3706) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

自行配置了一下 `jest.config.js`如下
```js
module.exports = {
  moduleNameMapper: {
    '\\.(css|less|sass|scss)$': require.resolve('identity-obj-proxy'),
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/fileMock.js',
    '@/(.*)$': '<rootDir>/$1',
  },
};

```

相关依赖版本如下
```
icedeMacBook-Pro:111 ice$ npx umi -v --verbose
umi@2.0.0-beta.21
darwin x64
node@v8.11.3
umi-build-dev@1.0.0-beta.21
af-webpack@1.0.0-beta.21
babel-preset-umi@1.0.0-beta.21
umi-test@1.0.0-beta.21
react@16.4.2 (/Users/ice/CodeProjects/111/node_modules/react)
react-dom@16.4.2 (/Users/ice/CodeProjects/111/node_modules/react-dom)
react-router@4.3.1 (/Users/ice/CodeProjects/111/node_modules/react-router)
react-router-dom@4.3.1 (/Users/ice/CodeProjects/111/node_modules/react-router-dom)
dva@2.4.0 (/Users/ice/CodeProjects/111/node_modules/dva)
dva-loading@2.0.5
dva-immer@0.2.3
path-to-regexp@1.7.0

```

请问是什么原因？

PS：可复现 repo : https://github.com/arvinxx/umi-test-problem

**Comment by dilidili** [comment]
tsconfig.json 中使用 ```esModuleInterop: true``` 替代 ```allowSyntheticDefaultImports: true```
Ref: https://github.com/kulshekhar/ts-jest/issues/632

**Comment by sorrycc** [comment]
试试楼上的方法，有问题再 reopen 。

**Comment by wanghaomayu** [comment]
@sorrycc 亲测有用

**Comment by Ma63d** [comment]
项目中也遇到同样问题，记录一下避免大家踩坑。项目前端运行可以通过 allowSyntheticDefaultImports 来避免硬书写 import * as React 的写法，但是 ts-jest 从 v23 起不支持 allowSyntheticDefaultImports, 只支持用 esModuleInterop 来解决同样问题: [kulshekhar/ts-jest#632](https://github.com/kulshekhar/ts-jest/issues/632)，所以需要楼上 esModuleInterop: true 的配置。

**Comment by ycjcl868** [comment]
+1
