### ISSUE TITLE
【Bug】语法错误的代码导致 MFSU 退出

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#9678]
复现步骤：

1. 删除 `node_modules/.cache`

2. 添加 `src/app.ts` ，注意数字开头再加英文 ：
    
    ```ts
    // app.ts
    
    3222eeeeee
    ```

3. 启动服务：
    
    ```bash
      pnpm dev
    ```

_Originally posted by @fz6m in https://github.com/umijs/umi/discussions/9601#discussioncomment-4024608_
    

相关问题：

 - https://github.com/umijs/umi/discussions/9601

 - https://github.com/umijs/umi/issues/9667

**Comment by stormslowly** [comment]
这样的情况 关了mfsu  dev 也起不来吧。

**Comment by stormslowly** [comment]
app.ts  作为项目的运行时配置文件 在项目启动时需要解析来决定生成文件；如果 app.ts 有语法错误，无法解析，关闭 dev server 符合预期；类似 .umirc.ts 有错误项目也起不来。

**Comment by fz6m** [comment]
当关闭 `mfsu: false` 时，`app.ts` 按照如上错误的写法，是可以启动项目的，但不会退出进程。

当打开 `mfsu` 时，`app.ts` 错误的语法会导致进程退出，个人感觉鲁棒性不够。

有可能一边启动项目一边进行 `app.ts` 的编码，这样就启动失败了。

**Comment by stormslowly** [comment]
没有复现出来 [暗中观察]

```bash
echo -e '\n--- .umirc.ts --- \n'; grep mfsu .umirc.ts ; echo -e '\n--- app.tsx --- \n' ;  cat src/app.tsx ; npm run dev

--- .umirc.ts ---

  mfsu: false,
  // mfsu: {
   // mfsu: { strategy: "normal" },
  //mfsu:{

--- app.tsx ---

console.log('1')
42XD

> dev
> max  dev

info  - @local

/project/umi-playground/src/app.tsx:
  1 | console.log('1')
> 2 | 42XD
    |  ^ Syntax error "X"
  3 |

error - transform /project/umi-playground/src/app.tsx failed
fatal - Error: Transform failed with 1 error:
<stdin>:2:2: ERROR: Syntax error "X"
    at failureErrorWithLog (/project/umi-next/node_modules/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib/main.js:1605:15)
    at /project/umi-next/node_modules/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib/main.js:1394:29
    at /project/umi-next/node_modules/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/project/umi-next/node_modules/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/project/umi-next/node_modules/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Syntax error "X"'
    }
  ],
  warnings: []
}
fatal - A complete log of this run can be found in:
fatal - /project/umi-playground/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
```

**Comment by fz6m** [comment]
看了一下，如果是 `app.tsx` 的话，两者行为一致，都会报错中断。

如果是 `app.ts` 的话，关闭 mfsu 可以启动项目。。。

**Comment by stormslowly** [comment]
开启 mfsu eager 的情况下，语法分析报错，如果分析不出来依赖，后面也没法正确编译；
如果需要在有语法错误的情况下分析，暂时没有好的解法。

如果一定需要 dev 能起来，可以通过    mfsu:{    strategy:'normal'  }  绕开
