### ISSUE TITLE
[Bug] umijs 4.x  ssr  build-manifest.json 文件路径报错

### ISSUE THREAD

**Issue by rfw** [umijs/umi#9720]
## What happens?
ssr模式报错
```
(node:16580) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'E:dev_project_testdisuild-manifest.json'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.getManifest [as manifest] (E:\dev_project\_test\src\.umi\server\umi.server.js:47416:35)
    at E:\dev_project\_test\src\.umi\server\umi.server.js:47174:70
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.<anonymous> (E:\dev_project\_test\src\.umi\server\umi.server.js:47223:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). T
o terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 17)
```
![image](https://user-images.githubusercontent.com/10648685/200464583-4ab7ef6f-6efa-46b3-9508-8eff96a1f606.png)
实际目录：
```
E:\dev_project\_test\
```
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

yarn create umi --no-git // 初始化项目后，
 ssr: {},  // 仅配置ssr 后 yarn dev 出现报错

## How To Reproduce

yarn create umi --no-git // 初始化项目后，
 ssr: {},  // 仅配置ssr 后 yarn dev 出现报错

## Context

- **Umi Version**: "^4.0.29
- **Node Version**: v14.17.6
- **Platform**:  Windows 10 专业版

**Comment by rfw** [comment]
@fz6m
