### ISSUE TITLE
[Bug] 4.0版本，.umirc.ts文件中开启dynamicImport: {}报错

### ISSUE THREAD

**Issue by Yuri-Zhou** [umijs/umi#9756]
dynamicImport在3.5上配置，工作正常。
同样的方式，搬到umdynamicImport在3.5上配置，工作正常。
同样的方式，搬到umi@4.0.29上，启动报错。

**error info：**
AssertionError [ERR_ASSERTION]: Invalid config keys: dynamicImport
    at Function.validateConfig (D:\code\npmproject\umi\node_modules\@umijs\core\dist\config\config.js:182:31)
    at Config.getConfig (D:\code\npmproject\umi\node_modules\@umijs\core\dist\config\config.js:60:12)
    at FSWatcher.<anonymous> (D:\code\npmproject\umi\node_modules\@umijs\core\dist\config\config.js:80:47)
    at invokeFunc (D:\code\npmproject\umi\node_modules\@umijs\utils\compiled\lodash\index.js:9:61298)
    at trailingEdge (D:\code\npmproject\umi\node_modules\@umijs\utils\compiled\lodash\index.js:9:61694)
    at Timeout.timerExpired [as _onTimeout] (D:\code\npmproject\umi\node_modules\@umijs\utils\compiled\lodash\index.js:9:61597)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by fz6m** [comment]
umi 4 没有 `dynamicImport` 了，默认按页拆包，和 `dynamicImport` 一样。

**Comment by GKLL** [comment]
我在src/下面配置了laoding.tsx,好像不生效呢

**Comment by merabtenei** [comment]
> I configured laoding.tsx under src/, but it doesn’t seem to take effect.

True when getInitialState is asyncronous and takes time to return data, a blank page is displayed and not the loading.tsx.
