### ISSUE TITLE
[Bug] yarn test Error 

### ISSUE THREAD

**Issue by f2egxz** [umijs/umi#9843]
## What happens?

执行 test  报错
```base
yarn run v1.22.10
warning ../../package.json: No license field
$ jest
Error: Jest: Failed to parse the TypeScript config file /Users/gxz/Desktop/umi4test/jest.config.ts
  AssertionError [ERR_ASSERTION]: Invalid config keys: antd, access, model, initialState, request, layout
    at readConfigFileAndSetRootDir (/Users/gxz/Desktop/umi4test/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:136:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async readConfig (/Users/gxz/Desktop/umi4test/node_modules/jest-config/build/index.js:233:18)
    at async readConfigs (/Users/gxz/Desktop/umi4test/node_modules/jest-config/build/index.js:420:26)
    at async runCLI (/Users/gxz/Desktop/umi4test/node_modules/@jest/core/build/cli/index.js:132:59)
    at async Object.run (/Users/gxz/Desktop/umi4test/node_modules/jest-cli/build/cli/index.js:155:37)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

[review code](https://github.com/f2egxz/umi4test.git)

## How To Reproduce

下载代码，
```base
yarn 
yarn test
```

**Steps to reproduce the behavior:** 
1.  按照[官方文档](https://umijs.org/docs/tutorials/getting-started) 初始化新项目 

```base
➜  umi4test yarn create umi
yarn create v1.22.10
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-umi@4.0.32" with binaries:
      - create-umi
[#####################################################################] 254/254?
✔ Pick Umi App Template › Ant Design Pro
✔ Pick Npm Client › yarn
✔ Pick Npm Registry › taobao
...
```

3. 紧接着
```base
npx umi g jest

info  - [你知道吗？] umi g tsconfig 可一键完成项目的 TypeScript 配置。
✔ Will you use @testing-library/react for UI testing?! … yes
info  - Update package.json for devDependencies
info  - Update package.json for scripts
info  - Write jest-setup.ts
info  - Write jest.config.ts
yarn install v1.22.10
```
添加 jest 测试

4. 执行测试命令，报错

**Expected behavior** 
1. 可以正常运行 测试

## Context

- **Umi Version**:  "@umijs/max": "^4.0.32",
- **Node Version**:  v16.18.1
- **Platform**: mac

**Comment by fz6m** [comment]
max 项目使用微生成器时，需要使用 `max g *` ，故需要做如下调整：

```diff
// jest.config.ts
-import { Config, configUmiAlias, createConfig } from 'umi/test';
+import { Config, configUmiAlias, createConfig } from '@umijs/max/test';
```

**Comment by Yyunfan** [comment]
@fz6m 改成max/test 也还是会报 Error: Jest: Failed to parse the TypeScript config file

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现。
