### ISSUE TITLE
[Bug] build error（Transform failed with 1 error( Terser plugin )）

### ISSUE THREAD

**Issue by enzozyx** [umijs/umi#9931]
## What happens?
build app error. the error log is:
umi.js:250294:1: ERROR: Transforming async generator functions to the configured target environment ("chrome80", "es2015") is not supported yet
Error: Transform failed with 1 error:
umi.js:250294:1: ERROR: Transforming async generator functions to the configured target environment ("chrome80", "es2015") is not supported yet
    at failureErrorWithLog (E:\workspaces\max-cesium-platform\node_modules\esbuild\lib\main.js:1566:15)
    at E:\workspaces\max-cesium-platform\node_modules\esbuild\lib\main.js:805:29
    at responseCallbacks.<computed> (E:\workspaces\max-cesium-platform\node_modules\esbuild\lib\main.js:671:9)
    at handleIncomingPacket (E:\workspaces\max-cesium-platform\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (E:\workspaces\max-cesium-platform\node_modules\esbuild\lib\main.js:647:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

`
umi.js:250294:1: ERROR: Transforming async generator functions to the configured target environment ("chrome80", "es2015") is not supported yet
Error: Transform failed with 1 error:
umi.js:250294:1: ERROR: Transforming async generator functions to the configured target environment ("chrome80", "es2015") is not supported yet
    at failureErrorWithLog (E:\workspaces\max-cesium-platform\node_modules\esbuild\lib\main.js:1566:15)
    at E:\workspaces\max-cesium-platform\node_modules\esbuild\lib\main.js:805:29
    at responseCallbacks.<computed> (E:\workspaces\max-cesium-platform\node_modules\esbuild\lib\main.js:671:9)
    at handleIncomingPacket (E:\workspaces\max-cesium-platform\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (E:\workspaces\max-cesium-platform\node_modules\esbuild\lib\main.js:647:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
`

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
Transforming async generator functions to the configured target environment ("chrome80", "es2015")

**Comment by KrishnaPG** [comment]
Getting the same error even with chrome 108. How to configure it to use `esNext` and not `es2015`? It seems to have been hardcoded in the code https://github.com/umijs/umi/blob/c2326c104141c00ca99db0a6d60d70069323550d/packages/bundler-webpack/src/config/compressPlugin.ts#L39-L41

**Comment by fz6m** [comment]
We don't know what code throw the error

Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub.

**Comment by stormslowly** [comment]
@enzozyx 

could you plz try these steps to identify which npm package cause the build problem。

use this config
```
  jsMinifier: 'esbuild', 
  codeSplitting: {
    jsStrategy: 'depPerChunk',
  },
```
then run the build `npx bigfish build`

the problematic package name will appear in the error log.

the last step is to add the package to `extraBabelIncludes` 

```
     extraBabelIncludes: ["@zip.js/zip.js"],
```

**Comment by choi2k** [comment]
I am using ant design pro and getting the same error with `nats.ws` package.

**Comment by fz6m** [comment]
See https://umijs.org/blog/legacy-browser 。

You can try ：

```ts
// .umirc.ts
 
export default {
  jsMinifier: 'terser',
  cssMinifier: 'cssnano'
}
```

**Comment by choi2k** [comment]
> 

it works. Thanks. (y)

**Comment by Jim523424zf** [comment]
使用这个可以试下jsMinifier: 'terser',我是这样解决的
