### ISSUE TITLE
使用npm workspace ，开启mfsu加速特性，会导致某些包找不到

### ISSUE THREAD

**Issue by soeasyjx** [umijs/umi#9936]
## What happens?

使用npm workspace 组织项目
1. 在`config/config.ts`中开启`mfsu`属性
2. 执行启动命令 `npm run start`

**项目报错**
>部分错误如下
```
ERROR in ./src/components/Footer/index.tsx
Module build failed (from ../../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep @ant-design/icons which is imported from @/components/Footer/index.tsx
    at getDepVersion (/Users/jiangxin/project_git/chiyou/examples/slave-systemnotice-index-app/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/getDepVersion.js:129:27)
    at DepInfo.addTmpDep (/Users/jiangxin/project_git/chiyou/examples/slave-systemnotice-index-app/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepInfo.js:141:56)
    at Object.onTransformDeps (/Users/jiangxin/project_git/chiyou/examples/slave-systemnotice-index-app/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js:327:23)
    at PluginPass.exit (/Users/jiangxin/project_git/chiyou/node_modules/@umijs/babel-plugin-import-to-await-require/lib/index.js:217:140)
```

## 目录结构如下：
```tree
chiyou
├── examples
│   ├── slave-bjs-makenew-app
│   ├── slave-systemnotice-index-app
│   ├── slave-tianjishuo-search-app
│   └── template-app
├── lerna.json
├── package-lock.json
├── package.json
├── yarn-error.log
└── yarn.lock
```

关闭`mfsu`加速特性，可正常启动并运行项目

## Context

- **Umi Version**:3.5.0
- **Node Version**:16.17.0
- **Platform**:moc    mocOS Monterey 12.5.1

**Comment by git-dingyc** [comment]
@soeasyjx 解决了吗 我也出现了同样的问题啊
